### ISSUE TITLE
Can't select PHP versions when on /websites/modifyWebsite

### ISSUE THREAD

**Issue by lotkao** [litespeedtech/cyberpanel#100]
I have a fresh installed cyberpanel on CentOS 7.
Current Version 1.8
Build 4
I am using the free (non-Enterprise) version.

I am trying to select/change the PHP version, but get an error message:

**Cannot modify website. Error message: 'packForWeb'**

![Selection_0280](https://user-images.githubusercontent.com/12074418/59963457-5853fc00-951d-11e9-9c05-0afa5a823be2.jpg)

There is nothing added to the CYBERPANEL MAIN LOG FILE when this happens.

**Comment by usmannasir** [comment]
Did you select the package before clicking modify website?
