### ISSUE TITLE
[doubt] Is project Chatwoot compatible with CyberPanel?

### ISSUE THREAD

**Issue by willph** [litespeedtech/cyberpanel#1000]
Hi, how are you?

I installed the chatwoot app on docker, and using a proxy on the cyberpanel vhost, but the screen loads blank, as if some configuration was missing incorrect.

project [Chatwoot](https://github.com/chatwoot/chatwoot).

I would like to know if the right thing is to get in touch with the owners of the Chatwoot project?
Or is it here?

**_curiosity_**

`/super_admin/sign_in` works only 

`app/accounts/1/dashboard` doesn't working

the screen below was supposed to appear
![image](https://user-images.githubusercontent.com/17226802/203682113-952a7b76-4316-4ef8-a20e-9772cd7440ba.png)

with nginx it works
but I would like to use it on cyberpanel

**nginx user config**

```
location / {
    proxy_pass_header Authorization;
    proxy_pass http://$upstream;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Ssl on; # Optional

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_buffering off;

    client_max_body_size 0;
    proxy_read_timeout 36000s;
    proxy_redirect off;
  }
```
_**would have similar configuration on vhost?**_

**thank you very much in advance.
and sorry if i posted in the wrong place**

**Comment by usmannasir** [comment]
The best and easy way to do this is to use reverse proxy as explained here -> https://www.youtube.com/watch?v=SvnlMxgp-rM

You can use Docker container for Chatwoot, I've gone through their docs, its a bit complex, you can set the container up from command line and then use reverse proxy to route the traffic from domain.

I will close this issue here as it is not related to any CyberPanel bug.

**Comment by willph** [comment]
Thanks a lot for the help
