### ISSUE TITLE
[BUG] Databases created with WordPress Installer is not mapped to website in UI

### ISSUE THREAD

**Issue by rahuldevlab** [litespeedtech/cyberpanel#1001]
**Describe the bug**
When WordPress is installed on a website, the database is created in the background and configured to work with the the created WordPress site, but when we go to list database and select the site name then that created database is not visible.

Hence if a user deletes the files in the File manager and reinstalls the WordPress the earlier one remains, new gets created, and earlier one becomes orphan with no link to any site hence affects size.

**To Reproduce**
What steps did you take when the issue occurred? 
1. Go to "List Websites" tab.
2. Click "Manage" against your webite.
3. Install wordpress.
4. Check in wp-config.php for the db name.
5. Now goto list database, select the website name.
6. The database created by wp installer will not be visible.

**Expected behavior**
The database name should be visible so that the user can clean-up the database if not required.

**Comment by usmannasir** [comment]
<img width="1440" alt="Screenshot 2022-12-09 at 4 15 15 PM" src="https://user-images.githubusercontent.com/17538454/206690520-55cdf96d-a6d3-4f62-a137-a75d8b64d710.png">

Works for me, please reach out to our support if this is one-off case.
