### ISSUE TITLE
Upgrade for new version and SNAPPYMAIL dont work

### ISSUE THREAD

**Issue by iqbalhasandev** [litespeedtech/cyberpanel#1004]
Upgrade for new version and SNAPPYMAIL dont work
[https://serverTLD:8090/snappymail/index.php 2](https://servertld:8090/snappymail/index.php)

Just work in:
[https://serverTLD:8090/rainloop/ 1](https://servertld:8090/rainloop/)

and admin here: /rainloop/?admin

Please Solve this Problem as soon as possible

**Comment by usmannasir** [comment]
Please contact our support, this could be a one-off case.

Can't reproduce on my end.

thanks
