### ISSUE TITLE
[BUG] Terminal Vanished from Latest version

### ISSUE THREAD

**Issue by abhranil26** [litespeedtech/cyberpanel#1006]
Hi, 

I am using the latest version of Cyberpanel on Ubuntu 20.04. I updated it nearly after 2 years. Today I see that the web terminal option has disappeared and if go directly to the URL /Terminal getting "connection closed" error.

![image](https://user-images.githubusercontent.com/30792751/206855754-6060f0c7-a39a-44c9-a7b8-d50a3410ab44.png)
![image](https://user-images.githubusercontent.com/30792751/206855763-b7281a96-312a-47d9-8767-7e210a70c283.png)

**Comment by usmannasir** [comment]
Please note that we've discontinued this feature.

**Comment by psevdokounian** [comment]
> Please note that we've discontinued this feature.

if future is discontinued, why it still in panel?

**Comment by clebersleite** [comment]
really a very useful resource, it's a shame it was discontinued =/

**Comment by Noway94** [comment]
if it discontinued so it  means not longer possible now to run nodejs on cyberpanel as i need the terminal to installl npm depencies?

**Comment by Noway94** [comment]
> Please note that we've discontinued this feature.
If it has been discontinued, does this mean it is no longer possible to run Node.js on CyberPanel? or how else i can achieve that please?

**Comment by lohh2h** [comment]
> > Observe que descontinuamos esse recurso. 
> > Se ele foi descontinuado, isso significa que não é mais possível executar Node.js no CyberPanel? Ou de que outra forma eu posso fazer isso, por favor?

aapanel

**Comment by master3395** [comment]
@usmannasir I do think this should be restarted, because i just started having issues connecting to my VPS using SSH and SFTP.
But i can still log into CyberPanel.
And that way, i could have fixed my issue :/
Now i have to either revert, or have another server root terminal fix my firewall or something.
