### ISSUE TITLE
[BUG] Container view redirecting to dashboard

### ISSUE THREAD

**Issue by Javierko** [litespeedtech/cyberpanel#1007]
**The bug**
Unable to get to the created docker container using `Launch` button. I'm getting redirected to base page.

**To Reproduce**
1. Pull the latest version of `sinusbot/docker`
2. Create container with these parameters:
- port 8087 to 8087
- `env` GID group_id (group id, because you can't run this app as a root)
- `env` UID user_id (same as GID)
3. Also specify the volumes
- `/opt/sinusbot/scripts` to `/home/sinusbot/scripts`
- `/opt/sinusbot/data` to `/home/sinusbot/scripts`
4. Create the container and start, after start you will be unable to get back to the container view

**Expected behavior**
To get to the container view.

**Operating system:**
Ubuntu 22.04.1 LTS

**CyberPanel version:**
Current Version:  2.3
Build:  2
Current Commit:  d9b74886233ec78a1582eded07a26187c6f42ee1

**Comment by usmannasir** [comment]
Can you reproduce this on `Ubuntu 20.04` or `Alma Linux` ?

**Comment by Javierko** [comment]
Not sure about `Alma Linux` but `Ubuntu 20.04` has same problem as `Ubuntu 22.04`.

**Comment by tobsowo** [comment]
I am also having this same issue.

**Comment by michaeldeblok** [comment]
I have the same issue:

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

**Comment by usmannasir** [comment]
Let me check guys
