### ISSUE TITLE
[BUG] Custom SSH port "no route to host" after install cyberpanel

### ISSUE THREAD

**Issue by xdnroot** [litespeedtech/cyberpanel#1012]
Cyberpanel: 2.3.2
OS: Centos 7

If we changed the ssh port to a port other than 22 (e.g.  4040) before install cyberpanel from this script: [https://cyberpanel.net/install.sh](https://cyberpanel.net/install.sh).
That script will creates iptables rules that allow SSH port. However, the script doesn't adjust the SSH port to configured port on /etc/ssh/sshd_config (i.e. 4040) . The iptables rules stiil using default port (i.e. 22).
```
Chain IN_public_allow (1 references)
 pkts bytes target     prot opt in     out     source               destination         
...
   0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22 ctstate NEW,UNTRACKED
...
```

On the other hand, configuration on /etc/ssh/sshd_config defined port 4040 as SSH port.
This will cause the server to be inaccessible via SSH using either port 4040 or 22.

**Comment by usmannasir** [comment]
resolved, check commit above.
