### ISSUE TITLE
SSL does not renew/issue: webroot is wrong

### ISSUE THREAD

**Issue by jcn50** [litespeedtech/cyberpanel#1013]
**Describe the bug**
The problem comes from the wrong webroot path `/usr/local/lsws/Example/html`
in the command ran:
`/root/.acme.sh/acme.sh --issue -d $domain -d www.$domain --cert-file /etc/letsencrypt/live/$domain/cert.pem --key-file /etc/letsencrypt/live/$domain/privkey.pem --fullchain-file /etc/letsencrypt/live/$domain/fullchain.pem -w /usr/local/lsws/Example/html -k ec-256 --force --server letsencrypt`
by this this file:
https://github.com/usmannasir/cyberpanel/blob/stable/plogical/sslUtilities.py

However it is doing this because it is missing some lines of codes just prior to lines 292+293:
```
        URLFetchPathWWW = f'http://www.{virtualHostName}/.well-known/acme-challenge/{virtualHostName}'
        URLFetchPathNONWWW = f'http://{virtualHostName}/.well-known/acme-challenge/{virtualHostName}'
```
These missing lines should be added:
```
        CustomVerificationFileDomain = f'/home/{virtualHostName}/public_html/.well-known/acme-challenge/{virtualHostName}'
        command = f'touch {CustomVerificationFileDomain}'
        ProcessUtilities.normalExecutioner(command)
```

**Manual fixes**
`{virtualHostName}` is your domain.

Option 1: 
Run the touch command manually before SSL issuance:
`touch /home/{virtualHostName}/public_html/.well-known/acme-challenge/{virtualHostName}`

Option 2:
Create an empty file there using the File Manager: 
`/public_html/.well-known/acme-challenge/{virtualHostName}`

**Operating system:**
CentOS 7

**CyberPanel version:**
2.2.3 4de1040637951e1771e159a5d1a35cba1bc04dff

**Additional context**
The domain is also the hostname of the server.

**Comment by usmannasir** [comment]
Please note that webroot for getting ssls is `/usr/local/lsws/Example/html` in new versions.

So kindly add this as context in your vhost conf.
