### ISSUE TITLE
CyberPanel Installation Error

### ISSUE THREAD

**Issue by vpsinghbaghel** [litespeedtech/cyberpanel#1014]
Hypervisor: Proxmox 7.3
OS: Ubuntu 20.04
![cyberpanel-install-error](https://user-images.githubusercontent.com/55743857/210163050-13fb019b-6c00-44ea-b75a-130d2b9ff6d9.jpg)

Getting above error in installation.
Name resolution works fine upto the time this error occurs and then SSH access is gone.
Console access to the server remain continue and shows above error in screenshot.
Network is lost from server which restores only after a reboot.

Thank You.
Ved.

**Comment by usmannasir** [comment]
As discussed in FB group and helpdesk, we can not reproduce this issue on our end.
