### ISSUE TITLE
how can i create Domain Aliases using API or CLI? is there any way to do this or any other way so i can create domain aliases programmitacally?

### ISSUE THREAD

**Issue by irohirsoni** [litespeedtech/cyberpanel#1015]
how can i create Domain Aliases using API or CLI? is there any way to do this or any other way so i can create domain aliases programmitacally?

**Comment by qtwrk** [comment]
e.g  

`cyberpanel createWebsite --package Default --owner admin --domainName domain.com --email admin@domain.com --php 8.1 --ssl 1`

ref: https://community.cyberpanel.net/t/cyberpanel-command-line-interface/30683

**Comment by Nilbertocs** [comment]
Is there any way to set the directory for it?
