### ISSUE TITLE
[BUG] Creating an email list is not working

### ISSUE THREAD

**Issue by eng-alhawary** [litespeedtech/cyberpanel#1018]
Hello All,

I was trying to create an e-mail list for one of our websites by uploading .txt and .csv file containing multiple e-mail addresses to the base directory, but it keeps fail with following error:

`cat: /home/cyberpanel/2481: No such file or directory`

And found in some report here that this feature is discontinued [https://github.com/usmannasir/cyberpanel/issues/988#issuecomment-1312926664](url)

So, how can I make this work now as **I need it to send announcements internally for our employees**, or, a mail list for each department. Is there something like that ?

I need an internal solution like be using in some control panels, not Mailgun, Mailchimp, ..... etc.

**Comment by eng-alhawary** [comment]
@usmannasir reminder plz

**Comment by usmannasir** [comment]
To avoid spamming on servers we've removed this feature.
