### ISSUE TITLE
[BUG] Mail server SSL fail update

### ISSUE THREAD

**Issue by Dreamer41** [litespeedtech/cyberpanel#1019]
Mail server SSL fail even try manually issue new certificate successfully 
Please see old bug [report](https://github.com/usmannasir/cyberpanel/issues/971)  and community [Post](https://community.cyberpanel.net/t/cannot-send-emails-as-via-gmail-ssl-certificate-mismatch/39446/6?u=dreamer) problem need fix every 90day by running email debugger. 
Community support member josephgodwinke might have some knowledge of this issue.

**Comment by usmannasir** [comment]
Added a commit.

**Comment by Dreamer41** [comment]
@usmannasir This problem is still occurring its pretty easy to fix with debugger but very annoying to run debugger every time when certificate renews.

**Comment by tecfay** [comment]
i have the same problem. please can you solve the issue and fix it automatically.  
this is the first time i face problem. after i upgraded the cyberpanel last version.

**Comment by Dreamer41** [comment]
@tecfay If you can open new issue and link this one in there might get some attention. Since my last comment on this nothing happen.

**Comment by mazhargilani** [comment]
I have exactly same issue, even after Admin UI showing successfully renewed the mail SSL certificate, the certificate is still self signed and no trusted. So can't establish secure email.

Someone mentioned the fix  “you can find acme.sh and purge all the ecc keys and certificates for mail subdomain, and then reissue new ecc certificates the manual way.". anyone knows where can I find that acme.sh? and how can I successfully renew mail ssl cert?

I've upgraded cyberpanel to Current Version:  2.3
Build:  4Current Commit:  f41f07d8f241b6a9086b8d94e1db39fcf8816537
