### ISSUE TITLE
Path to child domain created by CLI or API

### ISSUE THREAD

**Issue by Nilbertocs** [litespeedtech/cyberpanel#1020]
Is there any way to define the path that will be directed to the child domain via API or CLI?

**Comment by usmannasir** [comment]
Please check this guide, it gives you can option of path https://documenter.getpostman.com/view/2s8Yt1s9Pf?version=latest#b73475f4-2fd5-4f09-8177-012052421d2f

**Comment by Nilbertocs** [comment]
Hi, thanks for the reply, I noticed this was added to the API when I updated my dashboard, but in the meantime I created a pull request with this little CLI modification!
[https://github.com/usmannasir/cyberpanel/pull/1023](https://github.com/usmannasir/cyberpanel/pull/1023)
