### ISSUE TITLE
FileManager archive functions have realpath issue

### ISSUE THREAD

**Issue by BurakBoz** [litespeedtech/cyberpanel#103]
Steps to produce
1. Go FileManager on any host
2. Zip a folder and download
3. Extract archive on its location
You just extracted a realpath home/somedomain.com/public_html/yourzippedfolder
results:
(folder of downloads) -> test.zip
(folder of downloads) -> home/somedomain.com/public_html/yourzippedfolder

I didn't tested tar.gz format but both of these archiving results should be like

Expected result :
(folder of downloads) -> test.zip
(folder of downloads) -> yourzippedfolder

**Comment by jetchirag** [comment]
https://github.com/usmannasir/cyberpanel/blob/26153007e681dc731cc3f9374ceba87d5f04d188/filemanager/filemanager.py#L329-L330

zip is using full path to directory, so either `-j` option can be used:

```
-j (--junk-paths)
Store just the name of a saved file (junk the path), and do not store directory names. By default, zip will store the full path (relative to the current directory).
```

or change directory before zipping.
