### ISSUE TITLE
MANAGE POWERDNS

### ISSUE THREAD

**Issue by sonnylloyd** [litespeedtech/cyberpanel#104]
OK so I recently updated my version of cyberpanel. It went smoothly and everything is running fine. (expect for needing to re-issue hostname certs I will raise another ticket for this) 

I was just taking a look around and noticed an error message on one of the pages (not sure if its effected anything but thought I would report) . 

If you go to 

**Manage Services > Manage PowerDNS**

The error message

`Error message: (1054, "Unknown column 'masterServer' in 'field list'")
`
Displays at the bottom. 

As this is a new feature I assume the update is missing an alter statement.

**Comment by MohamedMohsenX2** [comment]
The same error message with me after the upgrade.

**Comment by usmannasir** [comment]
Fixed.
