### ISSUE TITLE
[FEATURE] Email Notification when Cyberpanel attempts to get a new SSL Cert and fails/falls back to Self Signed Cert

### ISSUE THREAD

**Issue by packetdog** [litespeedtech/cyberpanel#1045]
Is there a way to force CyberPanel to issue a notification if a self-signed certificate is EVER issued? I'd much rather get an email for this issue before my client notices that their site is having an issue.

This request stemmed from this issue: https://github.com/usmannasir/cyberpanel/issues/1044

Thank you so much for your work on a great product.

**Comment by usmannasir** [comment]
Yes, possible as you can see here

```
/usr/local/CyberCP/emailDebug

If you want logs in /home/cyberpanel/error-logs.txt to be emailed to you, please run touch /usr/local/CyberCP/emailDebug, you will get logs in your email. (Email of admin account will be used to send these notifications). This also includes notification if CyberPanel fails to obtain SSL for any domain.
```
