### ISSUE TITLE
Hostname ssl certs need re-issue after update

### ISSUE THREAD

**Issue by sonnylloyd** [litespeedtech/cyberpanel#105]
I have recently updated cyberpanel. this is the second update iv done. For some reason tho everytime I do it I have to re-issue the hostname certs manually.

**Comment by usmannasir** [comment]
Fixed.

**Comment by franciscopaniskaseker** [comment]
The problem is happening with my customer.

I updated CP to last version. Even manually issuing the ssl it does not renew.

Where I can find logs about what is happening?

I upgraded CP with this command:
```bash
[root@centos-2gb-hel1-1 logs]# sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh)
```
