### ISSUE TITLE
[REQUEST] Add PiluX Support for Cyberpanel (Ubuntu 22.04 based Distro)

### ISSUE THREAD

**Issue by hasanmerkit** [litespeedtech/cyberpanel#1053]
More details here: https://community.cyberpanel.net/t/please-add-pilux-os-support/42209/

**Comment by usmannasir** [comment]
Why add PiluX when its Ubuntu 22 under the hood?

**Comment by hasanmerkit** [comment]
> Why add PiluX when its Ubuntu 22 under the hood?

Here is /etc/lsb-release file
```
DISTRIB_ID=PiluX
DISTRIB_RELEASE=v1.0
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="PiluX v1.0"
DISTRIB_PILUXBASED=true
```

Installation returns distro not supported.

**Comment by usmannasir** [comment]
You did not answer my question above?

**Comment by hasanmerkit** [comment]
Could it be a little more descriptive? My English is bad.

-> PiluX is a modified Ubuntu 22.04 distro and compatible with Ubuntu 22.04 applications
-> Installation script thinks OS is not Ubuntu 22.04 and returns error while checking /etc/lsb-release

**Comment by usmannasir** [comment]
I was asking, why do you need Pilux support when essentially it is ubuntu on back end?

**Comment by hasanmerkit** [comment]
The software probably already supports PiluX.  It's just that the auto-install script doesn't realize it's an Ubuntu because the /etc/lsb-release file doesn't have the word Ubuntu.

**Comment by usmannasir** [comment]
I am sorry, we won't be adding that.

**Comment by hasanmerkit** [comment]
No problem, i found alternatives.
