### ISSUE TITLE
[BUG] UnboundLocalError at /websites/CreateNewDomain

### ISSUE THREAD

**Issue by rodrigobg** [litespeedtech/cyberpanel#1057]
Request Method: | GET
-- | --
https://my_ip/websites/CreateNewDomain
3.1.3
UnboundLocalError
local variable 'test_domain_status' referenced before assignment
/usr/local/CyberCP/websiteFunctions/website.py, line 710, in CreateNewDomain
/usr/local/CyberCP/bin/python
3.10.6
['',  '/usr/local/CyberCP/bin',  '/usr/local/CyberCP',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/usr/local/CyberCP/lib/python3.10/site-packages',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP']
Wed, 26 Apr 2023 20:18:38 +0000

**Operating system:**
Please enter your answer here (e.g. Ubuntu 22.04 LTS)

**CyberPanel version:**
Please enter your answer here (e.g. 2.3. 

**Additional context**
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by shbs9** [comment]
Hello,

Sorry that may be you are getting response late but this issue is resolved and you just need to update your cyberpanel
