### ISSUE TITLE
Inconsistent Email Password Encryption Corrupting User Passwords

### ISSUE THREAD

**Issue by hifihedgehog** [litespeedtech/cyberpanel#107]
1.8.5 and prior did not use any email encryption whatsoever. Due to some oversight, the encryption was switched to CRYPT (from what I can see in phpMyAdmin) for new accounts and MD5 for old accounts. I was able to fix this with a simple line adjustment in Dovecot but the upgrade migration code did not account for this. Now, with 1.8.7, all passwords were switched to CRYPT and the MD5 migrated passwords no longer work. Please fix this for the sake of my users.

**Comment by usmannasir** [comment]
We will use CRYPT style from now on.
