### ISSUE TITLE
[BUG] Tune PHP-FPM Settings + Switching back to Pure OLS not working

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1070]
When clicking Tune, you get this error:
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/70430794-9dae-4908-8a5f-0d5dc4db0131)
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/6cf04b9f-03fc-4d89-b6c0-710a2e4200fc)

Switching back to PureOLS, you get an error:
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/056311bc-2c83-4f54-abda-115c835f8e86)

**Comment by usmannasir** [comment]
Please create ticket with server access: https://platform.cyberpersons.com/

Could be a bug, need to check on your server.

**Comment by usmannasir** [comment]
Resolved
