### ISSUE TITLE
[BUG] Delete Website from CyberPanel UI Removes Content Only, Websites Remain in Lists in CyberPanel UI

### ISSUE THREAD

**Issue by packetdog** [litespeedtech/cyberpanel#1073]
Hello, I went to Delete Website, and selected the site, deleted it. I received the green modal that it deleted successfully on disk. /home/[site] is completely removed. This is also removed from List Wordpress (after rescan) which is great.

Unfortunately this remains in List Websites, and I can still open/manage it. Also it appears in the list of websites in other panels, for example Issue SSL or List Databases pages. I thought about manually deleting these from the Cyberpanel database with PHPMyAdmin, but I didn't want to break anything. Please advise on how to fully remove these.

**To Reproduce** 
1. Go to Websites > Delete Website
2. Select Site from List > Click Delete Website > Click "Are you sure?"
3. Receive Green Modal Showing Site has been Deleted.

**Expected behavior**
All site content on disk is removed, and also the site is removed from the sites list in the database.

**Version**
We're running CyberPanel 2.3.4 (updated 2023/05/21) on Ubuntu 22.04 LTS

**Comment by usmannasir** [comment]
I've deleted a site, it take few seconds after that but it is also removed from the list and file system.

Can you create ticket with us to reproduce.
