### ISSUE TITLE
[BUG] Error Backing up to Google Drive, Empty Folder is Created Daily, No Backup Data Inside

### ISSUE THREAD

**Issue by packetdog** [litespeedtech/cyberpanel#1074]
Hello,

In some recent troubleshooting I discovered that my Google Drive backups were not working properly. When I went to retrieve a backup from Google Drive, I went to the day, and opened the folder, and it was empty. When I 'View Logs" on the backup page, it shows: _[ERROR] Backup failed for MYDOMAIN.com, error: Backup process killed. moving on.._ and it shows this for all of the websites I have scheduled for daily backup.

Since that log isn't very meaningful, please let me know where I'm going wrong.

I started looking into Backup V2, but it looks like for each website I need to define the Google Account 'repo' before I can back up? Is that correct that I have to do them one by one for each site? Feels time consuming considering they'll all be linked to the same Google Account.

**Version**
We're running CyberPanel 2.3.4 (updated 2023/05/21) on Ubuntu 22.04 LTS

**Comment by ahmadrusli** [comment]
It happened with me too.
I just realise yesterday (20 may 2023).
the last backup on 18 may 2023. 
so there are 2 days (19 and 20 may) not working.

the website too not working.
i do not have time to investigate where the problem.
so i move the website on other vps. and the website run again.

**Comment by usmannasir** [comment]
Do you have anything related in CyberPanel main log file? does the normal backup creation works from the GUI?
