### ISSUE TITLE
Improper Server Setup

### ISSUE THREAD

**Issue by Lvl4Sword** [litespeedtech/cyberpanel#1075]
I sent an e-mail on May 2nd at 7:19PM EST in regards to a server connected with CyberPanel infrastructure and that server is improperly setup.

Is there a preferred method of contact that someone should use for these things?

When going to `support` on https://cyberpanel.net/ at the bottom of the page, this just forwards someone to https://platform.cyberpersons.com/ , which asks for a login. This is useless if someone doesn't have nor wants an account for whatever this is for. Normally an e-mail ( PGP or not ), some kind of easy-to-use contact form, or some other method of communication is used for these things.

I'd prefer to not provide any additional information via Github, and would like to keep this private with individuals connected to cyberpersons.com

Thanks!

**Comment by usmannasir** [comment]
Right now support is only possible through this platform: https://platform.cyberpersons.com/

**Comment by Lvl4Sword** [comment]
@usmannasir 
When going to that page ( https://platform.cyberpersons.com  ), the privacy policy ( https://cyberpanel.net/privacy-policy/ ) is 404. Because of this, I'd prefer to ***not*** sign up for whatever that is.

Just to verify, there's no other way to report security issues or the like for the project or infrastructure?
