### ISSUE TITLE
[BUG] REMTOE BACKUPS (REMOTE TRANSFER)

### ISSUE THREAD

**Issue by mrEckendonk** [litespeedtech/cyberpanel#1077]
**Describe the bug**
Missing FTP account passwords after backup

**To Reproduce**
Remote Backups => Enter IP address & Password
Select sites. Start Transfers

Selected sites are being backed, nice

Not working: 
Password transferred FTP accounts.

**Expected behavior**

**Operating system:**
Ubuntu 22.04 LTS)

**CyberPanel version:**
2.3.4
Current Commit:  5a7eb5133d02bf9ac9c5d1a31ede8ab3f21dd409

**Comment by usmannasir** [comment]
?

**Comment by mrEckendonk** [comment]
All domains where fetched, only content transfered. Missed FTP users and more things .

**Comment by usmannasir** [comment]
FTP Accounts are not transferred in this backup feature.
