### ISSUE TITLE
Cannot change email passwords via Rainloop anymore

### ISSUE THREAD

**Issue by hifihedgehog** [litespeedtech/cyberpanel#108]
I am the author of the tutorial "Allow Users to Change Email Passwords" on the CyberPanel forum. 

The old SQL statement I used was this:

`UPDATE :table SET password = :newpass WHERE emailOwner_id = :domain AND email = :email AND password = :oldpass`

What exact SQL function are you using and with what parameters to encrypt passwords? This needs to be clearly documented or at least responded to so I and other CyberPanel users can continue to allow our users to continue to be able to change their email passwords from Rainloop. Thanks!

For reference, see the forum tutorial thread:
https://forums.cyberpanel.net/discussion/1079/allow-users-to-change-email-passwords

**Comment by hifihedgehog** [comment]
Done and done. I also initiated a pull request. So hopefully, it should be added very soon to the official RainLoop project. If this meets your approval team CyberPanel, please let the RainLoop team know that they can go ahead and add it:

https://github.com/hifihedgehog/rainloop-webmail/tree/master/plugins/change-password-cyberpanel
https://github.com/RainLoop/rainloop-webmail/pull/1888

**Comment by usmannasir** [comment]
Alright thank you, I will close the issue now.

**Comment by hifihedgehog** [comment]
Just as a note, this plugin was successfully pulled into RainLoop's official codebase:
https://github.com/RainLoop/rainloop-webmail/pull/1888
https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/change-password-cyberpanel

For those who prefer a standalone download, this plugin is also available at this repo:
https://github.com/hifihedgehog/change-password-cyberpanel/releases
