### ISSUE TITLE
[BUG] Unable to Switch back to Pure LiteSpeed & Redis not working with Apache as a Reverse proxy

### ISSUE THREAD

**Issue by TheMukeshPatel** [litespeedtech/cyberpanel#1080]
**Describe the bug**
1. Unable to switch back to pure OepnLiteSpeed from Apache as a Reverse proxy. When we hit the "Switch to pure OpenLiteSpeed" button in the website manager, it shows "Operation Failed! undefined"
2. Redis is not working if we enable Apache as a Reverse proxy. It shows Redis Extension: Disabled in LiteSpeed Cache.

**Screenshots**
1. https://snipboard.io/lhi5RE.jpg
2. https://snipboard.io/mJnkB8.jpg

**Operating system:**
Ubuntu 20.04 LTS

**CyberPanel version:**
Version 2.3.4

**Comment by TheMukeshPatel** [comment]
Redis is working fine when Apache is enabled as a reverse proxy with the official Redis plugin(but showing "our site does not meet the requirements for the Pro version: The PhpRedis extension is not installed."

**Comment by usmannasir** [comment]
To use redis with apache you need to install redis php extension for PHP-FPM, which you can find in the doc/video here: [https://community.cyberpanel.net/t/how-to-use-apache-as-reverse-proxy/42940](https://t.co/NEybzu5g3x)

For converting to OpenLiteSpeed, please send a ticket to our platform with server login details.

**Comment by usmannasir** [comment]
I will close as no response received.

**Comment by TheMukeshPatel** [comment]
Still, there is a problem, After switching to Apache as a Reverse proxy, the LiteSpeed crawler is disabled.

**Comment by usmannasir** [comment]
LS crawler may not work with Apache, but this problem is not related to this issue.

**Comment by TheMukeshPatel** [comment]
Ok

**Comment by TheMukeshPatel** [comment]
Okay
