### ISSUE TITLE
[BUG] Child Domains Not Showing Up

### ISSUE THREAD

**Issue by jaychow87** [litespeedtech/cyberpanel#1081]
**Describe the bug**
After updating to the latest build, the 'list domains' seems not working as usual. It is now blank with nothing showing up, but once enter some keyword on the search bar such as 'mail' then all the mail child domains will show up. Delete the keyword in the search bar will prompt (Operation Failed 'pattern added').

Even the website manage page > list domains is not working as well.

**To Reproduce**
1. Ex.: Click on the "Websites" tab.
2. Ex.: Click on "List Domains".
3. Ex.: Nothing showing up
4. Ex.: Enter 'Mail' in the search bar, and start showing up some websites
5. Ex.: Delete the 'Mail' in the search bar, and the error shows up.

**Screenshots**
![image](https://github.com/usmannasir/cyberpanel/assets/96230788/6bc5822b-1f8e-4729-b068-0cec058d1f02)

![image](https://github.com/usmannasir/cyberpanel/assets/96230788/16de9fa4-6817-41ab-a462-c5ee7dd29144)

![image](https://github.com/usmannasir/cyberpanel/assets/96230788/d87035ae-08ca-4ef2-8c19-51a898fccfa2)

![image](https://github.com/usmannasir/cyberpanel/assets/96230788/e930d1d9-2be9-4757-84fd-e8d78f879f5f)

**Operating system:**
Ubuntu 22.04 LTS

**CyberPanel version:**
Current Version:  2.3
Build:  4
Current Commit:  5d478e281bbd288c0f1ffbef83fbde215775c24b

**Comment by shbs9** [comment]
Hello,

Just checked this and seem this is an issue we are checking this and soon we will update you about this.

**Comment by usmannasir** [comment]
Please note mail child domains will now not show up (this is intentional, many people were getting confused because of them)
