### ISSUE TITLE
issue creating a website after installation on aws centos instance

### ISSUE THREAD

**Issue by BigGod12** [litespeedtech/cyberpanel#1083]
Error message: [“[Errno 2] No such file or directory: ‘/etc/opt/remi/php81/php-fpm.d/damonmee.xyz.conf’ [404]”]
checking the dir of /etc/opt/ seems empty

**Comment by usmannasir** [comment]
Centos 7 ?

**Comment by usmannasir** [comment]
Closing because of no response.

**Comment by colevr1** [comment]
yes, centos 7, just came on the same bug, creating a subdomain
![image](https://github.com/usmannasir/cyberpanel/assets/34273028/ee4c4169-eb3b-4313-a2b4-a25f6e773a58)
