### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Code-Egg** [litespeedtech/cyberpanel#1084]
The script that has an issue: 
https://github.com/usmannasir/cyberpanel/blob/stable/cyberpanel_utility.sh

Error Log:
```
/usr/bin/cyberpanel_utility: line 31: Debug_Log2: command not found
```

Possible fix method: 
Either remove the Debug_log2 command or add the Debug_log2 function 

Additional requirement: 
Please renew the OS version of the check_OS function.

**Comment by qtwrk** [comment]
https://github.com/usmannasir/cyberpanel/pull/1085

**Comment by usmannasir** [comment]
merged
