### ISSUE TITLE
[BUG] Unable to open Docker Container manager for installed containers

### ISSUE THREAD

**Issue by mohalmah** [litespeedtech/cyberpanel#1087]
When I open container manager after installing container, it just redirect me to the main cyberpanel dasboard

When opening this url: https://[CYBERPANEL]:8090/docker/view/[Container_NAME]
It redirects me to this: URL: https://[CYBERPANEL]:8090/base

Version:
Current Version:  2.3
Build:  4
Current Commit:  2b7c8104b47669c609a28e468bbd435ec2192827
Latest Version:  2.3
Latest Build:  4
Latest Commit:  151c07c5653fbd1ef1d1e67d4755031487b0b04e

**Comment by usmannasir** [comment]
can you upgrade to latest commit and then try?

**Comment by mohalmah** [comment]
It was upgrading when I am filing the issue, I think its fixed now in the latest commit

Thanks Usman
