### ISSUE TITLE
LiteSpeed Crawler disabled when use Apache as a reverproxy

### ISSUE THREAD

**Issue by TheMukeshPatel** [litespeedtech/cyberpanel#1088]
**Describe the bug**
When we switch to Apache as Reverse Proxy, LiteSpeed Crawler is disabled. After switching back to pure LiteSpeed, it works again.

**Operating system:**
Ubuntu 22.04 LTS

**CyberPanel version:**
2.3.4

**Comment by usmannasir** [comment]
As I said in privious issue, this is not related to our implementation. I believe lscrawler may not even work with apache in the backend.
