### ISSUE TITLE
CyberPanel Notification Email Address Keeps Changing?

### ISSUE THREAD

**Issue by burhanaksendir** [litespeedtech/cyberpanel#1090]
Is there a place to set the email address that CyberPanel sends out notification emails with?

> Current disk usage at “/” is 77 percent. We recommend clearing log directory by running
> 
> rm -rf /usr/local/lsws/logs/*.
> 
> When disk usage go above 80 percent we will automatically run this command.

Why is it changing and how do I set it to a permanent email address?

**Comment by usmannasir** [comment]
Using this: https://community.cyberpanel.net/t/configure-mail-for-cyberpanel-notifications/153

**Comment by burhanaksendir** [comment]
@usmannasir Thank you. I want to completely disable these notifications because I receive emails every day. Is there a setting for this?
