### ISSUE TITLE
[BUG] Bug sftp path

### ISSUE THREAD

**Issue by techwiz37** [litespeedtech/cyberpanel#1094]
after login sftp bug can see system folder
![7e281861-1110-4c23-97f7-bc943c3e4727](https://github.com/usmannasir/cyberpanel/assets/73012169/6d2bf4b8-52d1-4cab-a526-94cb4692218f)

**Comment by shbs9** [comment]
Created a new sftp account for my domain and used that to login using FileZilla and i found that i can edit and work only and the sftp account directory 
Status:	Directory listing of "/home/ab.solveddoc.com" successful
Status:	Retrieving directory listing of "/home"...
Command:	cd "/home"
Error:	Directory /home: permission denied
Error:	Failed to retrieve directory listing

**Comment by jcn50** [comment]
@amiruldev20 are you using the `root` user to login? Which version of CyberPanel are you running and on which OS?
