### ISSUE TITLE
[BUG] Apache Proxy php change Almalinux 8.8

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1095]
When configuring the php values on Apache settings, it does not restart, even if you click restart php.
For me even if it says Apache in the URL, it only allows you to edit the normal php settings.

![image](https://github.com/usmannasir/cyberpanel/assets/4199669/06e30c18-7de6-4103-a6cf-10d6b1d3373c)

![image](https://github.com/usmannasir/cyberpanel/assets/4199669/36df0d24-5756-42c6-8f91-09626a67819b)

The PHP info file after the change still shows 20, I did change the PHP version, but the values are still the default.
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/978cc03e-3b76-4fa7-a255-ee945d1dd571)

**Comment by usmannasir** [comment]
I've installed a fresh Alma 8 server on aws and can not reproduce this, please upgrade, values are updating fine. Update from 2 to 20 here: http://cpcp.cyberpanel.net/info.php

**Comment by master3395** [comment]
For some reason, when making a new site or sub site with OLS+Apache, i get a white page, with no content?`

Example url below, i haven't added any htaccess as default, i only made the subdomain as a normal domain with apache addon.
I don't know if it's related back to this Ticket `#ZQZHM9CRV`?, but this domain has no files other than the standard index.html.
I have restarted OLS gracefully, i have done so with SSH also, no luck on showing the page.
For all i can see, there should not be any issues with the permission of the domain, since i made it from CyberPanel.

[cptest.newstargeted.com](https://cptest.newstargeted.com/)

**Comment by shbs9** [comment]
Hello @master3395 i tried to reproduce your issue my os is Alma and I created a site [check.solveddoc.com](http://check.solveddoc.com/) with Apache as a reverse proxy and tested on a simple index.html working fine then installed wp o top of it and it is working totally fine even http and https on both versions.
