### ISSUE TITLE
Scheduled remote backups are not working 

### ISSUE THREAD

**Issue by BurakBoz** [litespeedtech/cyberpanel#110]
Hi,
I have a storage server 1TB and a hosting server.
on my storage server debian installed and nothing else no cyberpanel no other panels.
Also on my hosting server CyberPanel latest version installed with centos.
I added destination to storage server and checked connection is ok it just works.
After this I scheduled backup on daily frequency (destination: my storage server ip). 
After a month I checked my storage server backups and I saw an empty /home/backup folder on my storage server.
Its just not working. I wonder why? I like to fix this.

Also we can create a site backup on home folder manually but we don't have any option to backup directly to remote backup destination this is a missing feature.

One more thing: we can't select custom folder on remote backup destination also this can be considered as a feature

**Comment by MyBlood** [comment]
Последнее обновление не решило проблему?

**Comment by BurakBoz** [comment]
I have latest version v1.8.8 so no

**Comment by usmannasir** [comment]
Fixed, for earlier installations follow -> https://forums.cyberpanel.net/discussion/comment/5595/#Comment_5595
