### ISSUE TITLE
[UX improvement] Backup+Restore buttons should be disabled after pressing on it

### ISSUE THREAD

**Issue by jcn50** [litespeedtech/cyberpanel#1100]
Buttons to:
-Backup `$URL:8090/backup/backupSite`
-Restore `$URL:8090/backup/restoreSite`
should be disabled for 5 seconds once pressed on it to avoid duplicate/parallel execution.

```
$("#myButton").attr("temp_disable", "disabled");
window.setTimeout(function() { $("#myButton").attr("temp_disable", ""); }, 5000);
```

**Comment by usmannasir** [comment]
@hassanhashmey  can you take care of this ?

**Comment by hassanhashmey** [comment]
Okay

**Comment by jcn50** [comment]
Thanks Guys//

**Comment by usmannasir** [comment]
Fixed with this commit: https://github.com/usmannasir/cyberpanel/commit/26d2fbf5bfa4d59523d49583119d6ab08e4bdaf0
