### ISSUE TITLE
[BUG] Upgrade on Ubuntu 22 awaits prompt from user

### ISSUE THREAD

**Issue by jcn50** [litespeedtech/cyberpanel#1105]
**Describe the bug**
When the upgrade is triggered, the process needs an answer to this:
```
Setting up ct-preset-deb (11-15.01) ...

Configuration file '/etc/systemd/system/ct-preset-deb.timer'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** ct-preset-deb.timer (Y/I/N/O/D/Z) [default=N] ?
```

**To Reproduce**
1. on an Ubuntu 22 OS: install an prior version of CyberPanel on Ubuntu (for example Current Version:  2.3 Build:  4 Current Commit:  a2a2bd93a3957bcae0af42e8c5fbf1184cf847cc)
2. trigger the update

**Expected behavior**
Upgrades should be conducted without prompting any user action (especially true for unattended/automatic update).

**Suggested solution**
Modify the apt options in [https://github.com/usmannasir/cyberpanel/blob/stable/cyberpanel_upgrade.sh](https://github.com/usmannasir/cyberpanel/blob/stable/cyberpanel_upgrade.sh) on line 426:
```
export DEBIAN_FRONTEND=noninteractive ; apt-get -o Dpkg::Options::="--force-confold" upgrade -y
```

**Operating system:**
Ubuntu 22

**CyberPanel version:**
Current Version:  2.3 Build:  4 Current Commit:  a2a2bd93a3957bcae0af42e8c5fbf1184cf847cc

**Additional context**
Thanks Guys!

**Comment by usmannasir** [comment]
Created internal ticket, will check and revert.

**Comment by shbs9** [comment]
@jcn50 can you please have your server access at https://platform.cyberpersons.com/

**Comment by usmannasir** [comment]
@qtwrk

**Comment by jcn50** [comment]
> @jcn50 can you please have your server access at https://platform.cyberpersons.com/

@shbs9 OK I have just added my server in there~

**Comment by meramsey** [comment]
Also this might be useful to prevent new prompts to reload services which can hang things
https://askubuntu.com/questions/1367139/apt-get-upgrade-auto-restart-services

**Comment by usmannasir** [comment]
@shbs9  is there any update to this ?

**Comment by shbs9** [comment]
i tried to reproduce on own servers but cant get this error but @jcn50 can you please open a ticket or give me email need to do on your server

**Comment by usmannasir** [comment]
add on the said line, resolved.

**Comment by jcn50** [comment]
@usmannasir there is a typo [in your code](https://github.com/usmannasir/cyberpanel/blob/stable/cyberpanel_upgrade.sh) lines 429+432:
`DEBIAN_FRONTEND=noninteractive`
instead of your:
`DEBIAN_FRONTEND=noninteracitve`

**Comment by jcn50** [comment]
@shbs9 debugging in progress in ticket #NGPBT0JQZ

**Comment by jcn50** [comment]
The typos are still there in the code~ and the ticket led to nowhere so I do not think I will report any new/other bug///~~
