### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Neustradamus** [litespeedtech/cyberpanel#1106]
Dear @usmannasir,

It is possible to create new release?

Last one is very very old:
- https://github.com/usmannasir/cyberpanel/releases

v1.9.1 (2019-10-15)

Thanks in advance.

**Comment by usmannasir** [comment]
Not possible, because CyberPanel can't be installed from git using download..

**Comment by Neustradamus** [comment]
@usmannasir: You have not understood me, please reopen this ticket.

You must to create all tags on master (or stable branch), and add download packages on all tags like all!
- https://github.com/usmannasir/cyberpanel/releases
- https://github.com/usmannasir/cyberpanel/tags

Thanks in advance.

**Comment by master3395** [comment]
It would look cleaner if we did use the release page instead of just branches.
I can help you add both releases and tags if you wish @usmannasir ?

**Comment by usmannasir** [comment]
@master3395 

If we start relying on releases, then currently our version manager uses git/commits to manage updates.

Also the whole update system is based on git.

And right now if someone is behind just a one commit they can know inside CyberPanel that they are behind few commits.

So it would be hard to get this sort of flexibility with that.

**Comment by Neustradamus** [comment]
@usmannasir: It is possible to clean branches and tag release commit like all other projects in the World?
- https://github.com/usmannasir/cyberpanel/tags with the main/master branch?

It is easy to have one master/main branch and if you want a branch for security fixes.

Example:
- master/main (0.3.x)
- 0.2.x
- 0.1.x

Note that a lot of projects have only one branch.

**Comment by Neustradamus** [comment]
@usmannasir: Can you reopen this unsolved ticket too?

Thanks in advance.
