### ISSUE TITLE
Cannot save Rewrite Rules

### ISSUE THREAD

**Issue by bugrakoc** [litespeedtech/cyberpanel#111]
Hello. I am getting the following error when I try to force http -> https using rewrite rules and save it. Fresh install on Centos 7 Minimal running on OpenVZ 7 with 2GB RAM.

Could not save rewrite rules. Error message: Traceback (most recent call last):
  File "/usr/local/CyberCP/plogical/virtualHostUtilities.py", line 25, in <module>
    from vhost import vhost
  File "/usr/local/CyberCP/plogical/vhost.py", line 23, in <module>
    from managePHP.phpManager import PHPManager
  File "/usr/local/CyberCP/managePHP/phpManager.py", line 6, in <module>
    from .models import *
  File "/usr/local/CyberCP/managePHP/models.py", line 9, in <module>
    class PHP(models.Model):
  File "/usr/local/CyberCP/managePHP/models.py", line 10, in PHP
    phpVers = models.CharField(max_length=5,unique=True)
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py", line 1057, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py", line 172, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/usr/lib64/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib64/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib64/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named settings

**Comment by meramsey** [comment]
can you provide the htacces rules that are not working and whether you are using openlitespeed or Litespeed Enterprise?

If you are using Litespeed Enterprise it should work with your standard .htaccess rewrites like
`RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301,NE] `

If you are using openlitespeed it may require using different rules. See this:
https://openlitespeed.org/kb/migrate-apache-rewrite-rules-to-openlitespeed/

**Comment by Succubussix** [comment]
same

**Comment by Succubussix** [comment]
https://github.com/usmannasir/cyberpanel/issues/145

**Comment by spirogg** [comment]
Fresh install of cyberpanel Litespeed enterprise edition
Current Version
1.9
Build
1
I am also having this error above.
 I can't  save rewrite rules from the cyberpanel dropdown, i had to create .htaccess file on public html folder then save and it seems its working, but from the dropdown its not working ?



[ EDIT 10/25/2019 20:51]
installed cyberpanel version 1.9.1 CentOS 7 VPS

I was having lots of issues not being able to save save rewrite rules, not being able to send emails or receive emails after cyberpanel and installing CSF and spamassasin. 

- So I started from scratch again> upcloud.com created a vps 2 cpu 4gb ram after cloud was spun up I went to my vps > [Network] in upcloud.com panel and I set my Reverse DNS Name to my hostname (example) hostname.mydomain.com 

Then I logged into ssh and ran this code>  update yum 

 then I started to install cyberpanel.
once finished I logged in from https:// ip:8090 

then i went to cyberpanel > DNS > CONFIGURE DEFAULT NAMESERVER
added ns1.mydomain.com ns2.mydomain.com and clicked SAVE
then went to DNS> CREATE NAMESERVER
enter my domain.com
ns1.domain.com IP address of my server
 ns2.domain.com SAME IP of my server clicked SAVE.

Then I went to websites > Create New Website> added > hostame.mydomain.com  
selected all Additional Features
SSL yes
DKIM Support yes
open_basedir Protection yes
click SAVE

then I went again to websites > Create New Website> added > domain.com without the www
selected all Additional Features
SSL yes
DKIM Support yes
open_basedir Protection yes
clicked SAVE.

then I went to SSL > Hostname SSL > ISSUE SSL FOR HOSTNAME
select from the dropdown your hostname.domain.com 
click Issue SSL

then go to SSL>Manage SSL > Click dropdown select yourdomain.com Issue SSL

then go to Email > Create Email> select your domain in dropdown and add your email account(s) you want.

after creating all your  email(s) 
go back to SSL>MailServer SSL >ISSUE SSL FOR MAILSERVER select your domain.com in dropdown and click Issue SSL.

- Now go to email > access webmail and login to your Webmail and send away.. should work to send and receive. 
- NOTE: some providers block port 25 so check with your hosting provider to see if they will open port 25 for you if its blocked and if you cant send or receive emails. then it should work.

- also if you go to Websites>List Websites> find your domain and click on manage link
- now scroll down and click on rewrite rules and  select the drop down to add the template rewrite rules, then click save and should save and be correctly setup.

- I wrote down my steps I took to install cyberpanel and make sure it worked for me, not sure if you need to follow them in the same order, one after the other but, my first install was a mess, so I tried again and this one worked. 

- Note: I do not have Spamassasin or CSF installed, first install I had installed CSF and Spamassasin so not sure if one of those was the culprit for not sending or receiving emails or not being able to setup rewrite rules in cyberpanel.
I guess I can test and update here again. :)
regards,
Spiro
