### ISSUE TITLE
[BUG] minor detail needs to be reverted/removed

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1111]
Someone left a big F in the domain panel.
It was no real change of code, just a new letter.

> ![Screenshot_2023-08-11-01-27-59-26_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/usmannasir/cyberpanel/assets/4199669/1cf389b0-8ea8-4604-ba4b-ec28f5b465ba)

https://github.com/usmannasir/cyberpanel/commit/ae7ad841d1f1fe189aab6d4b6bd3310e514ab5d2

**Comment by usmannasir** [comment]
resolved.
