### ISSUE TITLE
[BUG] opendkim Permission denied

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1123]
This error came in a clean install of CP
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/67438bad-14ed-4df4-b22f-e8b92f214cf0)

/etc/opendkim/keys/newstargeted.com/default.txt

![image](https://github.com/usmannasir/cyberpanel/assets/4199669/86c77f94-993d-4f0a-87f7-9dad60fe4f8a)

**Comment by shbs9** [comment]
is this presist after upgrade as well?

**Comment by master3395** [comment]
I have not seen this error after upgrade.

**Comment by master3395** [comment]
Seems that i was a bit too fast to close this.
It still happens.
I can send emails, but DKIM does not work, even if I have the right DKIM from the DKIM Manager in CyberPanel.
I got these in the Main error log:
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/9eaa6c68-2938-4a8c-ac9e-5ad162e83258)

**Comment by shbs9** [comment]
Where dns are managed?

**Comment by master3395** [comment]
CloudFlare

**Comment by master3395** [comment]
Latest test:
https://www.mail-tester.com/test-ucnkqudib

**Comment by master3395** [comment]
It has been an issue since 3.3 for me, on all new OS installs (Centos 6,7 and Almalinux 8.6, 8.7, and 8.8)
Here is an old open case.
https://platform.cyberpersons.com/support/MMJQ0VQBH/

**Comment by master3395** [comment]
I just tried DKIM with
https://mxtoolbox.com/SuperTool.aspx

It is showing that DKIM works.
BUT the mail-tester still says DKIM is invalid.
Same does Outlook say.
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/2e4f7bae-eea1-494c-993e-57decc859097)

https://www.mail-tester.com/test-tbwu7ws1b
![image](https://cdn.discordapp.com/attachments/250027425327480834/1148686490403082270/image.png)

**Comment by master3395** [comment]
This was the solution for now.
https://community.cyberpanel.net/t/bug-dkim-signature-verification-failed/40770/16?u=master3395
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/21575d4b-9592-453e-852e-de13fe97a16d)

**Comment by usmannasir** [comment]
i am checking this now

**Comment by usmannasir** [comment]
I've made some commits to `v2.3.5-dev` branch which makes dkim valid https://www.mail-tester.com/test-r19thvwep
