### ISSUE TITLE
[ Security ] Insecure password generation

### ISSUE THREAD

**Issue by Lvl4Sword** [litespeedtech/cyberpanel#1126]
https://github.com/usmannasir/cyberpanel/blob/stable/plogical/randomPassword.py uses `random`, which the documentation ( https://docs.python.org/3/library/random.html ) specifically states not to do so for this purpose:

> Warning
> 
> The pseudo-random generators of this module should not be used for security purposes. For security or cryptographic uses, see the [secrets](https://docs.python.org/3/library/secrets.html#module-secrets) module.

The fix here would be something like:

```py
import secrets

alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
the_password = [secrets.choice(alphabet) for x in range(14)]
print(''.join(the_password))
```

**Comment by usmannasir** [comment]
I will go through this.

**Comment by usmannasir** [comment]
Fixed.
