### ISSUE TITLE
Security Contact

### ISSUE THREAD

**Issue by limerencee** [litespeedtech/cyberpanel#1131]
Hi team,

I would like to suggest adding a point-of-contact for security related bug reports as there are currently no avenues to do so.

**Comment by Lvl4Sword** [comment]
https://github.com/usmannasir/cyberpanel/issues/1075 attempted to get in contact with someone for security, and that still has yet to happen.

**Comment by usmannasir** [comment]
https://platform.cyberpersons.com

Please contact us here.
