### ISSUE TITLE
Cpanel import domain not allowed Rainloop

### ISSUE THREAD

**Issue by hennaboy** [litespeedtech/cyberpanel#115]
When using the cPanel Importer the website is created and email accounts created but the domain and email accounts are not added to rainloop. Verified in the rainloop admin console domain is not listed in the domains section.

Therefore, you are unable to login to rainloop using any email address. Resetting the password through Cyberpanel for any email address created in this manner does not add the domain either.

**Comment by usmannasir** [comment]
This was fixed. https://github.com/usmannasir/cyberpanel/commit/991469296417d5e5e3e8aaf9b8d8eb1eb467c1b2. You can upgrade to v1.9.0

**Comment by hennaboy** [comment]
Upgraded to 1.9 retried the cPanel import. Domain not added to the list of domains in Rainloop admin and therefore generates the response when trying to login 

Domain is not allowed

**Comment by hennaboy** [comment]
Also worth noting it doesnt work in reverse either. Deleting a website does not remove the domain from Rainloop

**Comment by usmannasir** [comment]
Try to upgrade again, and rerun cPanel imported. Make sure to read the cPanel Importer guide as I've changed the python path.

**Comment by hennaboy** [comment]
Upgrade was successful to 1.9

Just to note that after this upgrade initial login attempts to access https://domain.com:8090/base which produces a 404 not found and you have to click back on the browser to get the panel to load.

I have, however, ran the upgrade again.

/usr/local/CyberCP/bin/python2 /usr/local/CyberCP/plogical/cPanelImporter.py –path /path/to/file

Is the command being used as per the guide August 2019.

No errors are reported and no log file of any error generated.

domain is not added to the Rainloop admin.

**Comment by usmannasir** [comment]
Please create ticket here -> https://platform.cyberpanel.net/

You will need to provide CyberPanel and SSH logins on ticket.

Then mention ticket id here.

**Comment by hennaboy** [comment]
Ticket #6SWJZ9
