### ISSUE TITLE
[BUG] Not installing pure-ftpd and powerdns

### ISSUE THREAD

**Issue by mimsadAlef** [litespeedtech/cyberpanel#1152]
**Screenshots**
![image](https://github.com/usmannasir/cyberpanel/assets/70805659/db0d7639-f80b-4a74-9b74-0070145bf815)

**Operating system:**
CentOS 7

**CyberPanel version:**
Please enter your answer here (e.g. 2.1.1). 

Hello
I installed cyberpanel but due to embargo in my country powerdns and pureftpd were not installed now I was able to bypass this problem
Is there a way to activate these two services without reinstalling CyberPanel?

**Comment by mimsadAlef** [comment]
@usmannasir

**Comment by usmannasir** [comment]
Installation is not possible if you have installed without these features.
