### ISSUE TITLE
Cyberpanel Features are not working for all websites like  delete file, copy file, taking backup of website, etc

### ISSUE THREAD

**Issue by TayCyb** [litespeedtech/cyberpanel#1153]
Cyberpanel Main Log:
Cyberpanel Email server setting was saved as smtp then error log was
(452, b'Temporarily Deferred')
(452, b'Temporarily Deferred')
(452, b'Temporarily Deferred')
(452, b'Temporarily Deferred')
(452, b'Temporarily Deferred')
(452, b'Temporarily Deferred')
maximum recursion depth exceeded while calling a Python object
SMTP AUTH extension not supported by server 

then i changed cyberpanel server mail setting to default and rebooted then errors log was
[Errno 99] Cannot assign requested address
[Errno 99] Cannot assign requested address
[Errno 99] Cannot assign requested address
[Errno 99] Cannot assign requested address
[Errno 99] Cannot assign requested address
[Errno 99] Cannot assign requested address
[Errno 99] Cannot assign requested address
[Errno 99] Cannot assign requested address
[Errno 99] Cannot assign requested address
maximum recursion depth exceeded while calling a Python object

* Today suddenly delete file of one website using cyberpanel was not working but permission and ownership was fine so i deleted file using terminal.
* then i found above errors on main log "cyberCPMainLogFile" from cyber panel. I tried to disable postfix and rebooted but still cyberpanel features was not working. Then I tried to use features of other website and found that on all website delete file, copy file, backup website etc was not working.
* I have not done anything like cyberpanel or linux updating, upgrading, etc cyber panel features issues was shown today because yesterday I was able to delete few images file from same website using cyber panel.
* Also today I noticed cyberpanel version management page is not working. I have not checked version management page from many days.

Why All this issue happened when I have not upgraded my cyberpanel.  @usmannasir

**Comment by TayCyb** [comment]
@usmannasir

**Comment by TayCyb** [comment]
After checking, I deleted /usr/local/CyberCP/emailDebug file and rebooted.

Everything was working correctly again like before even version management page was also showing. 

=>/usr/local/CyberCP/emailDebug file is not found by default, I use touch /usr/local/CyberCP/emailDebug to enable email logging.

Why everything working fine just after deleting /usr/local/CyberCP/emailDebug and then rebooting? I think it might be any cyberpanel cache issues or limitations because I found free ram, free cpu, and free disk available in server. 

If anyone knows the reason please comment so it can help others who are facing the same issue. Thanks

**Comment by usmannasir** [comment]
`/usr/local/CyberCP/emailDebug` Will try to email you all notifications, something might have gone with your email settings due to which the problem started happening. 

https://community.cyberpanel.net/t/configure-mail-for-cyberpanel-notifications/153
