### ISSUE TITLE
[BUG] CyberPanel forums are unavailable

### ISSUE THREAD

**Issue by Lvl4Sword** [litespeedtech/cyberpanel#1154]
**Describe the bug**
All links to the forum ( https://community.cyberpanel.net/ ) lead to a login page ( https://community.cyberpanel.net/login ) with no ability to register. I don't wish to register for the forum, and see the forced login page as a bug.

**To Reproduce**
What steps did you take when the issue occurred? 
1. Go to https://community.cyberpanel.net/t/cyberpanel-command-line-interface/30683
2. See you get redirected to https://community.cyberpanel.net/login

**Expected behavior**
I don't get redirected to https://community.cyberpanel.net/login

**Comment by zaaakher** [comment]
And also the google auth isn't working due to a missing project ID

**Comment by TayCyb** [comment]
Yes, for a few days, we have been facing other issues like the version management page in the cyber panel showing errors. it might be a security issue so may be thats reason they locked and force redirected to login to prevent access until they fix security issue.

**Comment by TayCyb** [comment]
community.cyberpanel.net is working now like before.

**Comment by Lvl4Sword** [comment]
Looks to be working now. Closing this.
