### ISSUE TITLE
Restore by backup 

### ISSUE THREAD

**Issue by hennaboy** [litespeedtech/cyberpanel#116]
Restoring a site from a backup created by Cyberpanel produces the following issues

Issuing SSL throws an acme error but installs the certificate for the hostname which is then flagged invalid in any browser.

Openlitespeed does not recognize any file and shows a 404 error page.

Restoring the same site from a cPanel backup does not throw any of the problems above.

**Comment by usmannasir** [comment]
When creating a backup, your site had a valid SSL?

**Comment by hennaboy** [comment]
Yes it would have had a valid SSL. Domain was already pointed to the nameservers etc so it should not have thrown any error.

**Comment by usmannasir** [comment]
Fixed https://github.com/usmannasir/cyberpanel/commit/2405746166505ca036f5b87158cbf72ee3abfcdf
