### ISSUE TITLE
[BUG] Trying to install WPCache + WordPress gives Installation Error

### ISSUE THREAD

**Issue by Lvl4Sword** [litespeedtech/cyberpanel#1162]
**Describe the bug**
When installing WPCache + WordPress, an installation error is given.
`Installation failed. Error message: ["can only concatenate str (not \"NoneType\") to str [404]"]`

**To Reproduce**
1. In Main > Websites, click `Create Website`.
2. Create the website, wait for it to finish
3. Go to Main > List Websites > click "Manage" next to the website you just made
4. Scroll down to `Application Installer` and select `WP + LSCache"
5. Fill in `Blog Title`, `Login User`, `Login Password`, `Email`
6. Press `Install Now`
7. Watch as it fails at `Setting up Paths`

**Expected behavior**
For it to not fail and actually setup WP + LSCache

**Operating system:**
Ubuntu 20.04 LTS

**CyberPanel version:**
Version 2.3 / Build 4 / Commit 36c0d62e786508b028f5757c64933412d3cd596b 

**Additional context**
This was attempted on 2 unrelated boxes, and looks to be a CyberPanel issue.

**Comment by Lvl4Sword** [comment]
So, this is interesting. Looks like the following gets saved in the main CyberPanel log:
https://github.com/usmannasir/cyberpanel/blob/ab19aba61d7d33bb965da3b18e1e430e5ed38a5a/ApachController/ApacheVhosts.py#L531 , which is `Config path: /etc/apache2/sites-enabled/EXAMPLE.COM.conf` , `EXAMPLE.COM` replaced with whatever the site you're trying to setup with WP + LSCache.

Which looks wrong to me, considering Apache shouldn't even be getting setup.
After a short look at this, this is probably where the `None` is coming from? Not 100% on that, but it's a nice starting point for anyone else looking at this.

**Comment by usmannasir** [comment]
this is now fixed, just do upgrade.
