### ISSUE TITLE
New install 1.9.0 Spamassassin config not writing to postfix

### ISSUE THREAD

**Issue by hennaboy** [litespeedtech/cyberpanel#117]
Spamassassin installs with code 200 but the following error message is displayed

Installation failed. Failed to install SpamAssassin configurations.

Postfix config file is not updated.

**Comment by usmannasir** [comment]
Fixed https://github.com/usmannasir/cyberpanel/commit/bc2a05b5f5a58dc57cf4146d1802df1b12e01110
