### ISSUE TITLE
[BUG] Backup Weekly (old v1) not working anymore (Daily backups works fine)

### ISSUE THREAD

**Issue by morphinestyle** [litespeedtech/cyberpanel#1170]
Weekly backups made with old Backup (v1) no longer work for a long time (/usr/local/CyberCP/bin/python /usr/local/CyberCP/IncBackups/IncScheduler.py Weekly).

The last weekly backup carried out correctly dates back to September, in the meantime I made the upgrades to Cyberpanel and now I have discovered that it has no longer worked since September.

Daily backups work fine.

Operating system:
**Ubuntu 20.04 LTS** Server1
**Ubuntu 22.04 LTS** Server2
Same issue on both

My Cyberpanel version is:
```
Current Version:  2.3
Build:  4
Current Commit:  c8da443334b8815ec250a0fba606e75355f641cd
```

**Comment by usmannasir** [comment]
fixed.
