### ISSUE TITLE
Wordpress SMTP is not working. 

### ISSUE THREAD

**Issue by developershohel** [litespeedtech/cyberpanel#1177]
Versions:
WordPress: 6.4.2
WordPress MS: No
PHP: 8.0.30
WP Mail SMTP: 3.11.0

Params:
Mailer: smtp
Constants: No
ErrorInfo: SMTP Error: Could not connect to SMTP host. Connection failed. stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failedSMTP server error: QUIT command failed Detail: ��A��M�Z�,�i�aԕ�#��5 �Ǽ�s!m����p��Y��e2��֪��=?�5�v'4޻!��G0E!�e�u%z���
�O4�^3Ug��_(�;R,ɓ f��X,&:-jw�ټ��Zp�� ��i
Host: mail.itblogger.dev
Port: 587
SMTPSecure: tls
SMTPAutoTLS: bool(true)
SMTPAuth: bool(true)

Server:
OpenSSL: OpenSSL 1.0.2k 26 Jan 2017
Apache.mod_security: No

Debug:
Email Source: WP Mail SMTP
Mailer: Other SMTP
SMTP Error: Could not connect to SMTP host. Failed to connect to serverSMTP server error: Failed to connect to server

SMTP Debug:
2024-01-09 22:03:15 Connection: opening to mail.itblogger.dev:587, timeout=300, options=array()

2024-01-09 22:03:15 Connection: opened

2024-01-09 22:03:15 SERVER -> CLIENT: 220 itblogger.dev ESMTP Postfix

2024-01-09 22:03:15 CLIENT -> SERVER: EHLO itblogger.dev

2024-01-09 22:03:15 SERVER -> CLIENT: 250-itblogger.dev250-PIPELINING250-SIZE 30720000250-ETRN250-STARTTLS250-ENHANCEDSTATUSCODES250-8BITMIME250-DSN250 CHUNKING

2024-01-09 22:03:15 CLIENT -> SERVER: STARTTLS

2024-01-09 22:03:15 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS

2024-01-09 22:03:15 Connection failed. Error #2: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed [/home/itblogger.dev/public_html/wp-includes/PHPMailer/SMTP.php line 476]

SMTP Error: Could not connect to SMTP host. Connection failed. stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

2024-01-09 22:03:15 CLIENT -> SERVER: QUIT

2024-01-09 22:03:15

2024-01-09 22:03:15

2024-01-09 22:03:15 Connection: closed

SMTP Error: Could not connect to SMTP host. Connection failed. stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

**Comment by usmannasir** [comment]
You have created an email account and using the same in WP Mail SMTP?

Or just using system mail ?

**Comment by developershohel** [comment]
I setup everything checked the video
https://www.awesomescreenshot.com/video/23920840?key=d2af22cf42ebcbf3d5c985cd8773d6a9

**Comment by developershohel** [comment]
Could you check the video? I setup everything. This has not worked for a long time for all websites.
https://drive.google.com/file/d/1zjgE2Ngjo-jnMF2ihhXx5Jukfy-MNobU/view?usp=sharing

**Comment by usmannasir** [comment]
Your rDNS seems to point to : dev.community as you can see here: https://mxtoolbox.com/SuperTool.aspx?action=ptr%3a191.101.15.102&run=toolpage

But you have issued mail server for other domain. 

Can you set everything according to this video please: https://www.youtube.com/watch?v=LkjN5DCWb0o

**Comment by developershohel** [comment]
I removed the rdns/ptr records and followed all guides. But still not workingPlease contact me my Whatsapp number +8801303767370

|   |  | SHOHEL HOSSAIN
Professional web developer
| 

***@***.***

 |
| 
developershohel.com
 |
| Maheshpur, Jhenaidha,Khulna, Bangladesh |


|  |  |  |  |  |

 |


 

    On Thursday, January 11, 2024 at 11:29:58 AM GMT+6, Usman Nasir ***@***.***> wrote:  
 
 


Your rDNS seems to point to : dev.community as you can see here: https://mxtoolbox.com/SuperTool.aspx?action=ptr%3a191.101.15.102&run=toolpage

But you have issued mail server for other domain.

Can you set everything according to this video please: https://www.youtube.com/watch?v=LkjN5DCWb0o

**Comment by usmannasir** [comment]
It does not look like a bug and I can also see that you have removed PTR record.

Please contact our support [here](https://platform.cyberpersons.com/).

**Comment by developershohel** [comment]
The problem didn't solve.
This is happening for invalid SSL
Verify that the host's SSL certificate is valid.
I issued Mailserver SSL for my codepen.shop website but you can check the video.
But it's now working.
I follow all the details and setup all DNS records but not working.
This is your system bug.
I am also a PHP and Django developer. 
Everything is fine on my site.
So, check my linux by ssh.
But I can't give my SSH access here
Please give me your email or any other contact details

**Comment by usmannasir** [comment]
Please just contact our support so we can check your server for any bug/misconfigurations.    ---- On Fri, 12 Jan 2024 13:55:58 +0500  SHOHEL ***@***.***> wrote ----  
The problem didn't solve. 
This is happening for invalid SSL 
Verify that the host's SSL certificate is valid. 
I issued Mailserver SSL for my codepen.shop website but you can check the video. 
But it's now working. 
I follow all the details and setup all DNS records but not working. 
This is your system bug. 
I am also a PHP and Django developer. 
Everything is fine on my site. 
So, check my linux by ssh. 
But I can't give my SSH access here 
Please give me your email or any other contact details

**Comment by developershohel** [comment]
How can i  contact your support so you can check my server for any bugs/misconfigurations?

**Comment by developershohel** [comment]
Please give me a zoom link to fix the issues

**Comment by usmannasir** [comment]
You can conatact us here: https://platform.cyberpersons.com/

We don't provide support via zoom/google meet sorry.
