### ISSUE TITLE
Apache php-fpm extensions getting removed

### ISSUE THREAD

**Issue by eakteam** [litespeedtech/cyberpanel#1180]
Everytime that we create a new website or subdomain we have to reinstall php-fpm memcache and redis extensions because they being removed and litespeed wordpress plugin cannot connect to redis server.

Maybe something wrongs while cyberpanel starts to configure apache as reverse proxy everytime.

**Comment by usmannasir** [comment]
Fixed.

**Comment by eakteam** [comment]
@usmannasir Do you have any ETA when 2.3.5 will be ready to upgrade and we can include all the fixes in our server?

**Comment by usmannasir** [comment]
Mainly waiting for front-end guy to complete new UI/UX. 

Mean while you can still get `v2.3.5-dev` using this guide: https://community.cyberpanel.net/t/02-upgrading-cyberpanel/81

**Comment by eakteam** [comment]
> Mainly waiting for front-end guy to complete new UI/UX.
> 
> Mean while you can still get `v2.3.5-dev` using this guide: https://community.cyberpanel.net/t/02-upgrading-cyberpanel/81

I just tried that, it started the installation but after finishing i am still on 2.3.4 branch...

**Comment by usmannasir** [comment]
```
root@cyberpanel:~# cd /usr/local/CyberCP/
root@cyberpanel:/usr/local/CyberCP# git branch
  stable
  v2.3.4
* v2.3.5-dev
root@cyberpanel:/usr/local/CyberCP# ```
run these two command and see output

also how exactly did you upgrade?
