### ISSUE TITLE
Duplicate entries on DNS Records

### ISSUE THREAD

**Issue by eakteam** [litespeedtech/cyberpanel#1182]
When adding subdomain DNS entries in TXT duplicate for the main domain.
If we add 2 or more subdomains it also duplicate them more.

**Comment by usmannasir** [comment]
Can you show me a screen shot of duplicate records?

**Comment by usmannasir** [comment]
![Screenshot 2024-01-14 at 14-11-55 Add_Modify DNS Records - CyberPanel](https://github.com/usmannasir/cyberpanel/assets/17538454/3b512e5e-4c5f-4717-935b-810ba56f470f)

I don't see any duplicate records.

**Comment by eakteam** [comment]
> ![Screenshot 2024-01-14 at 14-11-55 Add_Modify DNS Records - CyberPanel](https://private-user-images.githubusercontent.com/17538454/296540015-3b512e5e-4c5f-4717-935b-810ba56f470f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODE0MDAsIm5iZiI6MTcwNTI4MTEwMCwicGF0aCI6Ii8xNzUzODQ1NC8yOTY1NDAwMTUtM2I1MTJlNWUtNGM1Zi00NzE3LTkzNWItODEwYmE1NmY0NzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDAxMTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NThkMGFjZjkwYTIwODExYjdiMGQzZmMyZTVjOTNhZWQ1M2JlMGZiYTVlYTQyMWYwYzlmNDZjZDk4MWY1ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._u-7susogds84rctAjnIl7VAEuFl10ld0apnKu7e3Qw)
> 
> I don't see any duplicate records.

I have deleted the duplicates manually and can't provide screenshot at the moment but it is easy to reproduce. Just create a subdomain for wpmautic.net and after creation is successful you will see that the system will generate duplicate dns.

**Comment by usmannasir** [comment]
As you can see in the image above, I already created sub-domain, and no duplicate records created.
