### ISSUE TITLE
Snappy Mail need update

### ISSUE THREAD

**Issue by eakteam** [litespeedtech/cyberpanel#1183]
The bundled in CP is version 2.28.1. There have been a lot of improvements since that version. The official version of Snappy Mail is: 2.32.0

**Comment by usmannasir** [comment]
fixed

**Comment by master3395** [comment]
v2.33.0 was just released.

**Comment by eakteam** [comment]
> v2.33.0 was just released.

And there is maybe one important fix that have caused problems in Cyber Panel sometimes... Maybe this is the right fix for it.

![Screenshot_20240124_203151_Chrome](https://github.com/usmannasir/cyberpanel/assets/8820741/25e4b3a3-0e3b-4299-b30b-c53463ea0b8c)
