### ISSUE TITLE
Feature Request: BackupV2 Configure Backup Destination at Local Folder

### ISSUE THREAD

**Issue by eakteam** [litespeedtech/cyberpanel#1184]
There is no option to store backups locally, only SFTP and Google Drive

**Comment by usmannasir** [comment]
Backups v2 use rustic which in turn use rclone as backend. 

You can configure any backend supported by rclone, as I've explained in this video starting from here: https://youtu.be/7dI1013xvUc?t=409

PS: rclone back-end doc: https://rclone.org/commands/rclone_backend/

**Comment by eakteam** [comment]
> Backups v2 use rustic which in turn use rclone as backend.
> 
> You can configure any backend supported by rclone, as I've explained in this video starting from here: https://youtu.be/7dI1013xvUc?t=409
> 
> PS: rclone back-end doc: https://rclone.org/commands/rclone_backend/

But this need to configure each website one by one. I have 17+ websites.

**Comment by usmannasir** [comment]
You are right because rclone work inside users which is secure but tedious to set up for all users.

Maybe on the front-end we can add option to sync backend to all sites?

**Comment by eakteam** [comment]
> You are right because rclone work inside users which is secure but tedious to set up for all users.
> 
> Maybe on the front-end we can add option to sync backend to all sites?

But if you configure all site one by one by hand there is currently the option to add them to the list to make automated backup. But i mean is very hard work to make by hand one by one all backends for each site, there should be a way to configure like one backend for all, e.x generate a zip file for all somewhere and after upload via scp,rsync,ftp etc to somewhere..

**Comment by usmannasir** [comment]
sorry could not follow you?

**Comment by eakteam** [comment]
> sorry could not follow you?

hahaha, sometimes i speak like i think :D....
I mean:

Maybe is better to generate a full backup for all websites firstly (e.x .zip file) and after the file is generated, rsync can take the order to upload it somewhere.

Maybe this is easier because at the moment we need to configure rsync for every website one by one. But if you generate a full backup file locally firstly, than  we need only one time to configure rsync. Do you get it?

**Comment by usmannasir** [comment]
v1 are full backups v2 are incremental and use rustic.

In v2 can't self-use rsync or anything as based on rustic (incremental backups)
