### ISSUE TITLE
[BUG] DISK MONITORING SHOULD CHANGE

### ISSUE THREAD

**Issue by salmankavanur** [litespeedtech/cyberpanel#1188]
**Disk Space Monitoring is not as needed**
In CyberPanel dashboard, the disk space monitoring is not in a proper way. It shows the /root partition. actually the CyberPanel uses the /home directory to host files of websites, etc. There's two possibility you can do that, you can set /home directory. then the user can understand how much disk space we used and how much space remaining and available to host. Another way is to set total disk space monitoring. that's also possible. The most suitable way is to set /home partition as monitoring disk. That will be better. I think so.

**Screenshots**
https://snipboard.io/KCDVvA.jpg

Total size of Disk   : 1134.0 GB (54.4 GB Used)
Total amount of Mem  : 31874 MB (1216 MB Used)
Total amount of Swap : 10239 MB (0 MB Used)
/home : 751.74GB (5.27GB Used - 1%) 708.21GB available to host websites
/ : 48.91GB (15.91GB Used - 35%) 30.49GB space available. but that can't use as hosting space.
--------------------------------------------------------------
but in CyberPanel Dashboard, it shows that 34% Disk Usage (/). Actually the user needs to know how much hosting space available in disk. otherwise you should set total disk space. 

**Operating system:**
Ubuntu 22.04.3 LTS

**CyberPanel version:**
2.3

**Comment by salmankavanur** [comment]
![Screenshot 2024-01-21 151854](https://github.com/usmannasir/cyberpanel/assets/26223477/c4b6b577-a0df-4d63-a5ee-36fb7e420833)

**Comment by usmannasir** [comment]
This is not a possible because the reason is home only contains the website data but you have my SQL data which is outside home(/var/lib/mysql) then you have LiteSpeed data which is outside home as well so if you set home as the as the way to detect the usage it would be a wrong representation so it is better because root contains everything and gives an overall picture

**Comment by salmankavanur** [comment]
/root partition never show the overall picture. how it works? if the /root gives overall picture then how my disk space shows as 33% as in image. it should include overall disk. you can change the /root partition to full disk space (full hard disk)

**Comment by salmankavanur** [comment]
I agree with what you said about the mySQL data and LiteSpeed data. but that's not the proper way. you can use the whole disk as monitoring. Why you closed this without making any discussion?

**Comment by usmannasir** [comment]
```
root@ubuntu-default-mariadb-install-check:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           794M  1.1M  793M   1% /run
/dev/sda1        88G  7.6G   80G   9% /
tmpfs           3.9G  916K  3.9G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  6.1M   99M   6% /boot/efi
tmpfs           794M  4.0K  794M   1% /run/user/0
root@ubuntu-default-mariadb-install-check:~# 
```

![Screenshot 2024-01-21 at 15-24-25 Home - CyberPanel](https://github.com/usmannasir/cyberpanel/assets/17538454/569a40a9-522a-4482-8c60-c4b77cb5ec08)

**Comment by salmankavanur** [comment]
![image](https://github.com/usmannasir/cyberpanel/assets/26223477/305cea23-4a14-4d46-9667-fda457e40a73)

**Comment by salmankavanur** [comment]
![image](https://github.com/usmannasir/cyberpanel/assets/26223477/d930b00b-c6c5-4f23-a1ed-84298e353285)

What about this?

**Comment by usmannasir** [comment]
Your root mount point showing 33 percent?So what is CyberPanel suppose to say?    ---- On Sun, 21 Jan 2024 15:45:50 +0500  Salman ***@***.***> wrote ----  
image.png (view on web) 
What about this?

**Comment by salmankavanur** [comment]
You said that when you're setting /root partition, that shows overall picture. if the fact is as you said, then what overall picture you're getting from my /root? I'm not getting overall picture from /root. If you use the whole disk. then you can say that the monitoring gives you overall picture.

**Comment by usmannasir** [comment]
You mounted /home separately. which is a special case.

**Comment by salmankavanur** [comment]
yeah, but in this case too need correct monitoring. the whole disk monitoring not possible?

**Comment by usmannasir** [comment]
seprate mount point accounting is not possible in CyberPanel.

**Comment by salmankavanur** [comment]
I'm not telling the partition list monitoring, I mean to change the existing / to full hard disk. do you get what I meant?
