### ISSUE TITLE
CyberPanel version mismatch

### ISSUE THREAD

**Issue by eakteam** [litespeedtech/cyberpanel#1189]
Trying to run on terminal `cyberpanel version` and it outputs **2.3.1**
Trying to run `cat /usr/local/CyberCP/version.txt` and it outputs: **{"version":"2.3","build":1}**

But in the frontend -> Version Management it shows:

```
Current Version:  2.3
Build:  4Current Commit:  8e97f4f61d350c39818e55de0c6330edb68328f5
Latest Version:  2.3
Latest Build:  4Latest Commit:  8e97f4f61d350c39818e55de0c6330edb68328f5
```

So this is just a small bug/mistake that not showing the version correctly on terminal or it may affect upgrades later since it may take the wrong version from `cat /usr/local/CyberCP/version.txt` and not performing the right upgrade proccess?

**Comment by usmannasir** [comment]
fixed.
