### ISSUE TITLE
Cpanel Import DNS

### ISSUE THREAD

**Issue by hennaboy** [litespeedtech/cyberpanel#119]
When importing a domain using the cPanel import the domain is initially created with the nameservers set on the server which is how it should be.

However, as the process runs those records are deleted and the dns records from the cPanel server used instead. This means in order to get the domain working you have to manually remove all the cPanel records.

Should the importer be also adding legacy cPanel A records and TXT records too?

**Comment by usmannasir** [comment]
For cPanel importer it is recommended to restore cPanel records but with new server ips (which is what happens now). 

Which records do you think we can skip while importing? We already skim DKIM records.

**Comment by hennaboy** [comment]
Yes, but surely you should be keeping the new cyberpanel NS records?

what happens at the moment is initially the cyberpanel nameserver records for example

ns1.domain.com
ns2.domain.com

are added but then they are removed and replaced with the nameserver records from the cPanel server you are importing from. Which would mean that the domain will not resolve to the cyberpanel server until you add the NS records back.

Same applies to the SPF txt record. It is created initially but then removed. This just leaves the cPanel txt record which does not contain the new servers IP address making the SPF record invalid for the new server.

All the A records relating to cpanel services such as

webdisk
whm
cpcalendars
cpcontacts
webmail

**Comment by usmannasir** [comment]
We can not keep the default template created by CyberPanel for cPanel imported domains. But yes I can skip some records you mentioned above.

**Comment by hennaboy** [comment]
Perhaps a routine at the end of the script then to re-add the cyberpanel server NS records?

**Comment by usmannasir** [comment]
Yes, that is also possible.
