### ISSUE TITLE
Restoring full backups - Problem with Emails, DNS and others.

### ISSUE THREAD

**Issue by eakteam** [litespeedtech/cyberpanel#1190]
Tried to restore a domain and everything went OK. 
But it didn't automatically created the mail subdomain and also DKIM was not correct. 

Also when go to Email -> DKIM Manager and select the domain it says that `Keys not available for this domain. Generate Now`
But when i click generate now it fails with this error: 

`[Errno 13] Permission denied: '/usr/local/CyberCP/lib/python3.10/site-packages/tldextract/.suffix_cache/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock'`

**Comment by eakteam** [comment]
After executing this command and restarting the server it seems to fixed and every domain display the DKIM values but when sending mail to test it says DKIM is signed but not valid, maybe it should replace it automatically old DKIM with new one on Cloudflare?
```
sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh)
```

**Comment by eakteam** [comment]
@usmannasir it a lot buggy bro. Please do something as we have completely lost the line because of bugs and don't remember a lot of fixes that we had applied before, so choosing to do a fresh install but again things happening like below. 
I will do again a fresh install, but this things below, needs to be fixed firstly since i have a lot of websites to host and cannot just manually do everything by hand man.

Summary on backup resore:

**Issue Section**
1) It doesn't create mail subdomain automatically
2) Sometimes it creates duplicate DNS entries(especially for domains with subdomains) and we have to delete them manually. But why it should create DNS entries? Should it just copy them from the backup file and just add them to DNS and not trying to create them from the start?
3) Doesn't replace DKIM values automatically to Cloudflare and also it creates duplicate DKIM records locally if you go to DKIM manager to generate new one.
4) SSL certificates on mail subdomains which was not created automatically don't work and we have to generate them one by one since it doesn't create mail subdomain.

**Optionally (It can be skipped)**
1) Many websites are depending on custom configurations of OLS, it would be very nice to have an option to do a general configuration backup for it like -> Server Configurations -> General, Tuning, Security, External App, Script Handler, App Server and Modules.
2) Backup of MariaDb config file since there are a lot of custom optimizations (`/etc/mysql/my.cnf`)
3) Backup of Postfix config file (`/etc/postfix/main.cf`) since a lot of users have issues to recreate a working mail server from the scratch. So if the mail server worked before backup/restore it should be backed up when restoring websites on system fresh install.

It is very important to solve the **Issue Section** as soon as it would be possible since it is a pain on ass and it evolve too many things to do manually and possibly messing things up especially when you have a lot of websites to configure, like in my case 17+.

**How to reproduce issues?**
Make a clean install of Cyber Panel to a new server and try to restore a full backup from `/home/backup` directory.

**Comment by usmannasir** [comment]
Today I am working on an issue side-by-side, give me time to go through in details.

**Comment by eakteam** [comment]
> Today I am working on an issue side-by-side, give me time to go through in details.

I can also help you about that by taking tests on my server side if you want since i f*** up everything and i can do tests as many times as i want before going live to production again.

**Comment by usmannasir** [comment]
Few questions.

1. Did you restore the site on same server?
2. Before creating backup for the site, main domain and mail domain both had valid SSL ?
3. if you restored site on different server, where is currently the dns pointed?

**Comment by eakteam** [comment]
> Few questions.
> 
> 1. Did you restore the site on same server?
> 2. Before creating backup for the site, main domain and mail domain both had valid SSL ?
> 3. if you restored site on different server, where is currently the dns pointed?

1) Yes in the same server by fresh installing Ubuntu from the start
2) Yes of course and after restoring the websites are working fine and the ssl recognized but the problem is here: https://github.com/usmannasir/cyberpanel/issues/1190#issuecomment-1905338811

**Comment by eakteam** [comment]
@usmannasir Something else.

In cloudflare sync maybe is better to add and option to sync only specific entry and not everything as bulk from local? 
In this case it may only need to sync DKIM record and not everything. 
There are some local entries that we don't want to sync with cloudflare like cptest(A), www.mail.example.com(CNAME), ftp(A) etc. and because it sync with cloudflare everything,  all the records are displayed there again and we have to manually delete one by one from cloudflare side, which is really fustrating.

So it would be handy to control which records we want to sync and also in the case of restore process it should not try to recreate DNS entries from the start but just copy them from the backup and maybe sync only the new DKIM signature by making sure not to duplicate it.

**Comment by usmannasir** [comment]
OK. I am trying to reproduce

**Comment by eakteam** [comment]
> OK. I am trying to reproduce

Make sure to test with website including subdomains too. In this case happens the second issue mentioned here which duplicates the DNS entries -> https://github.com/usmannasir/cyberpanel/issues/1190#issuecomment-1905338811

**Comment by usmannasir** [comment]
I've pushed one commit to initially avoid duplicate dns records. Checking the backup issue

**Comment by eakteam** [comment]
> I've pushed one commit to initially avoid duplicate dns records. Checking the backup issue

Please take a look at this before creating/importing DNS records -> https://github.com/usmannasir/cyberpanel/issues/1191#issue-2095331015

**Comment by usmannasir** [comment]
I've pushed some more commits for:

1. When site is restored on new server the DKIM key is generated in new server and that key is reflected in the DNS records (not from the backup file)
2. Duplicate DNS records should be fixed.
3. I've created and restored a backup, I don't see duplicate records in this case.
4. Added check to create mail domain upon restore.

Notes: 
```
Sometimes it creates duplicate DNS entries(especially for domains with subdomains) and we have to delete them manually. But why it should create DNS entries? Should it just copy them from the backup file and just add them to DNS and not trying to create them from the start?
```
When domain is restored on new server new A records does not point to old server but to new one including the new dkim key as I mentioned above.

**Comment by eakteam** [comment]
> I've pushed some more commits for:
> 
> 1. When site is restored on new server the DKIM key is generated in new server and that key is reflected in the DNS records (not from the backup file)
> 2. Duplicate DNS records should be fixed.
> 3. I've created and restored a backup, I don't see duplicate records in this case.
> 4. Added check to create mail domain upon restore.
> 
> Notes:
> 
> ```
> Sometimes it creates duplicate DNS entries(especially for domains with subdomains) and we have to delete them manually. But why it should create DNS entries? Should it just copy them from the backup file and just add them to DNS and not trying to create them from the start?
> ```
> 
> When domain is restored on new server new A records does not point to old server but to new one including the new dkim key as I mentioned above.

@usmannasir  Just installed **2.3.5-dev** on different VPS for testing restore process...

Mail domain is created successfully and DNS records seems OK, but when i go to **Snappy Mail Admin Panel** and go to **Domains**, selecting the main domain it shows this at the **IMAP** tab like in the first screenshot:

https://nextcloud.eakteam.com/s/3xeoSAkNERYWYWR

Shouldn't it be instead like this other one below:?

https://nextcloud.eakteam.com/s/xPdJ37sEd9SjkJ7

Reference: 

> IMAP ports
> By default IMAP works on two ports like: 143 – this is the default port which **does not provide any encryption**. Port 993 is the **secure port for IMAP and it works over TLS/SSL encryption**.
>

**Comment by usmannasir** [comment]
Upgrade and recreate website, then see

**Comment by eakteam** [comment]
> Upgrade and recreate website, then see

Just did it, the port changed to 993 but Secure stayed at STARTTLS, should be SSL/TLS or it is fine?

**Comment by usmannasir** [comment]
> > Upgrade and recreate website, then see
> 
> Just did it, the port changed to 993 but Secure stayed at STARTTLS, should be SSL/TLS or it is fine?

Question: can you login to mail client on port 993 via imap?

**Comment by usmannasir** [comment]
Let me konw if we need to address anything in this task, else we can close.

**Comment by eakteam** [comment]
> > > Upgrade and recreate website, then see
> > 
> > 
> > Just did it, the port changed to 993 but Secure stayed at STARTTLS, should be SSL/TLS or it is fine?
> 
> Question: can you login to mail client on port 993 via imap?

Yes  i can connect and i think that we should connect only in this encrypted way.



> Let me konw if we need to address anything in this task, else we can close.

For the moment you can close it. Thanks
