### ISSUE TITLE
[BUG] Create Backup don't show custom local destination

### ISSUE THREAD

**Issue by eakteam** [litespeedtech/cyberpanel#1192]
1) Create a destination by going to Backup -> Add/Delete Destination e.x `/home/webackup` and also create the corresponding directory at `/home/webackup`
2) Go to Backup -> Create Backup -> Select Website -> Select Destination (**In this selection menu our custom destination that we created in the first step is not displaying, it is only shows Home**)

This is important too since there are much cases when all the websites backups should be in the same folder to be ready to upload them in custom servers/locations.

**Note:** Custom destinations  works fine with `Backup->Schedule Backup` and all the backups are going there, but with this options there is no way to trigger it manually in any time we want and the only way is to wait for tommorow???

**Comment by eakteam** [comment]
@usmannasir since with the schedule option it works fine, is there any way to trigger it to start the process manually any time we want manually and not waiting for it to automatically do the job next day? It is important since i have a lot of sites and can't just go one by one copy the backup in their specific directories...

It can be faster to help you with other bugs too since for every reinstallation of the server i need to make backups, just in case.

**Comment by usmannasir** [comment]
The destinations you add from `Backup -> Add/Delete Destination` will not appear on `Backup -> Create Backup -> Select Website` as they are created for `Backup->Schedule Backup` only.

If you wan't to run them forcefully at any time

Daily
```
/usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/IncScheduler.py Daily
```

Weekly
```
/usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/IncScheduler.py Weekly
```
