### ISSUE TITLE
[BUG] DNS Recors being added no matter what.

### ISSUE THREAD

**Issue by eakteam** [litespeedtech/cyberpanel#1194]
When creating a website/subdomain without selecting the option for mail domain it still creates it and also adds dns recors to cname, mx and txt.

Also the option for DKIM support i think should be removed from there since it should be the default option everytime no matter what when you need to use emails.

**Comment by usmannasir** [comment]
let me check

**Comment by usmannasir** [comment]
What if user also wants email on sub domain ?

**Comment by eakteam** [comment]
> What if user also wants email on sub domain ?

They can check Mail Support + DKIM options if they want, but it create records regardless if you don't choose those options.

**Comment by usmannasir** [comment]
Honestly I am not convinced. You can search on the forums that most of the people don't even know they want this record and then they complain about emails not working.

There needs to be another solid reason for it, not everyone have a deep knowledge of how this work.

And I've seen many people using emails on subdomain, what about them? do we just ignore that usecase?

**Comment by eakteam** [comment]
> Honestly I am not convinced. You can search on the forums that most of the people don't even know they want this record and then they complain about emails not working.
> 
> There needs to be another solid reason for it, not everyone have a deep knowledge of how this work.
> 
> And I've seen many people using emails on subdomain, what about them? do we just ignore that usecase?

I see, but not saying to remove that feature but to dissable creating those records if the domain/subdomain are not for email purposes.

If we create a domain/subdomain by checking only SSL + openbase_dir **and without email,apache,dkim support,** it still creates records for the things that we don't want.

But if you want them, you can activate by just checking them on creation.

**Comment by usmannasir** [comment]
```if the domain/subdomain are not for email purposes```
That is what I was saying above that people don't know that what they are creating is for email or not. Let me explain further, some people will not check this thing, and they may not even create an email account.

But then they try to send emails from WP and it does not work.

So there is no sure shot way to say that they don't want. And yet again some people wont check the box and later create emails and complains that emails don't work.

Trust me its not that easy to decide

**Comment by eakteam** [comment]
> `if the domain/subdomain are not for email purposes` That is what I was saying above that people don't know that what they are creating is for email or not. Let me explain further, some people will not check this thing, and they may not even create an email account.
> 
> But then they try to send emails from WP and it does not work.
> 
> So there is no sure shot way to say that they don't want. And yet again some people wont check the box and later create emails and complains that emails don't work.
> 
> Trust me its not that easy to decide

I understand, the same things happen often with my clients for mobile apps.

Ok then, we will remove unnecessary things manually 😊
