### ISSUE TITLE
[Feature-Required] Backup don't include other folders/files under website directory

### ISSUE THREAD

**Issue by eakteam** [litespeedtech/cyberpanel#1196]
Backup doesn't work with custom folders/files under website directory e.x `/home/example.com`

How to reproduce:

1) Install e.x NextCloud to `/home/example.com/public_html` directory
2) Configure data directory of NextCloud to be inside `/home/example.com/data` folder **(Not under public_html)**
3) Create an backup of the website
4) Restore it

The NextCloud will not work anymore and all data are deleted since it doesn't backup custom folder `data ` under `/home/example.com ` directory.

**Comment by usmannasir** [comment]
BTW This is not bug, we only backup `public_html`. 

Let me think of this.

**Comment by usmannasir** [comment]
added.
