### ISSUE TITLE
[BUG] It does not work with PHP 7.4 / PHP 8.0 / PHP 8.1 / PHP 8.2 / PHP 8.3...

### ISSUE THREAD

**Issue by Neustradamus** [litespeedtech/cyberpanel#1197]
Dear @usmannasir,

1.9.1 (2019-10-15), the latest release build does not work with PHP 7.4 (and previous, I think) / PHP 8.0 / PHP 8.1 / PHP 8.2 / PHP 8.3...
- https://github.com/usmannasir/cyberpanel/releases
- https://github.com/usmannasir/cyberpanel/releases/tag/v1.9.1
- https://github.com/usmannasir/cyberpanel/tags

It is possible to create a new release build?

Thanks in advance.

Linked to:
- https://github.com/usmannasir/cyberpanel/issues/1106

**Comment by master3395** [comment]
This is a really old version, why not just use the latest version (2.3.5) or 2.3.4?

2.3.4 supports:
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/7e50288d-3ed6-4b3e-b6b4-1f41cefe54e2)

**Comment by Neustradamus** [comment]
The latest is 1.9.1 (2019-10-15):
- Look at right here: https://github.com/usmannasir/cyberpanel
- Here: https://github.com/usmannasir/cyberpanel/releases
- Here: https://github.com/usmannasir/cyberpanel/tags

**Comment by master3395** [comment]
CyberPanel doesn't use the releases or tags option.
Since we have to use sh to install it.
It uses the branches tab.
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/8a781a44-7828-47d6-b171-ea1e1d0f6120)

**Comment by usmannasir** [comment]
thanks @master3395 i will close it then.

**Comment by Neustradamus** [comment]
@usmannasir: No no no! the problem is always here: The latest is 1.9.1 (2019-10-15):
- Look at right here: https://github.com/usmannasir/cyberpanel
- Here: https://github.com/usmannasir/cyberpanel/releases
- Here: https://github.com/usmannasir/cyberpanel/tags

**Comment by Neustradamus** [comment]
@usmannasir: Can you reopen this ticket, it is not solved.

It is not good to close unsolved ticket.

**Comment by Neustradamus** [comment]
@usmannasir: I have done 3 screenshots to show you:
- GitHub Project Homepage: https://i.ibb.co/yR4pGxT/cyberpanel-github-main-page.png
- GitHub Project Releases: https://i.ibb.co/KLtTC01/cyberpanel-github-releases-page.png
- GitHub Project Tags: https://i.ibb.co/sPSsyBV/cyberpanel-github-tags-page.png

**Comment by master3395** [comment]
Closed because it is also pointed out here: https://github.com/usmannasir/cyberpanel/issues/1106#issuecomment-1901768545
