### ISSUE TITLE
[BUG] Dockersite Server Error (500)

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1198]
When clicking the "Create Docker Site", you instantly get error 500, if it's the first time you check out the docker setup.
Same happens if you click "Create Docker App" from /websites/ListDockerSites.

Trying to go to:
/websites/AssignPackage
Changes the theme to the default theme and gives this error, even if i just made an package.
Package:
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/64da214c-787d-4d04-93af-e8a16288b23e)

Error at /websites/AssignPackage:
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/c8669d37-1c14-4ba2-82f0-ca6db8c44990)

OS information:
Almalinux 8.8
Host: Contabo VPS (Custom installed CyberPanel, upgraded from 2.3.4).

CyberPanel information:
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/2e750d78-5f3a-4fc7-93f7-f2cdeeb6f462)

**Comment by usmannasir** [comment]
fixed.
