### ISSUE TITLE
[BUG] Snappymail needs update

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1199]
There's a big bug in the Snappymail version installed in 2.3.5
We should put the installer at 2.33.0 instead, it will fix reading emails.
Since the current version installed does not let you read emails.

**Comment by usmannasir** [comment]
source?

**Comment by master3395** [comment]
I tried with the CyberPanel version, not sure what that was, since I upgraded it to 2.33.0 just to make reading and sending work.
There was also a bug with sent messages not being posted in the "Sent" folder.

https://github.com/the-djmaze/snappymail/releases

![image](https://github.com/usmannasir/cyberpanel/assets/4199669/d73102e4-71b7-4d97-96d4-5cdcac934d00)

**Comment by master3395** [comment]
This is what it looks like in 2.3.5 when you can't click the messages, nothing happens.
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/e30b8aca-425f-475e-b4bb-132cc029093a)

Snappymail: 2.32.0

How it looks when I upgrade Snappymail to 2.33.0:
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/dd81b5c5-1837-4d18-9724-ebb9c5cfae6e)

**Comment by usmannasir** [comment]
upgraded to 2.33.0

thank you
