### ISSUE TITLE
I would like to ask how to compile lscpd, is there any source code?

### ISSUE THREAD

**Issue by killjin** [litespeedtech/cyberpanel#120]
I would like to ask how to compile lscpd, is there any source code?

**Comment by usmannasir** [comment]
No, it is only available in binary.

**Comment by Ancyker** [comment]
> No, it is only available in binary.

`lscpd` is OpenLiteSpeed, which is GPLed, so why are you distributing a binary of it and not making the source code available?

```
# /usr/local/lscp/bin/lscpd -v
LiteSpeed/0.3.1 Open (TOBEREPLACEDWITHCURRENTDATE)
```
