### ISSUE TITLE
[BUG] Problem with Disk Usage and Bandwidth Usage

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1205]
These two, do not show anything anymore.
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/0515ccc4-7929-4c6e-823e-c43b949b6430)

**Comment by usmannasir** [comment]
let me check

**Comment by usmannasir** [comment]
![Uploading Screenshot 2024-02-03 at 18-36-08 usman.wpmautic.net - CyberPanel.png…]()

**Comment by usmannasir** [comment]
![Screenshot 2024-02-03 at 18-36-08 usman wpmautic net - CyberPanel](https://github.com/usmannasir/cyberpanel/assets/17538454/324b6046-1fc1-4531-b8cd-c11c7cffac7c)

**Comment by master3395** [comment]
My bad, seems that putting it to 0 makes it not show at all.
Earlier versions of CyberPanel would show the total amount on the VPS itself.
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/4d2cf8bd-da70-4ce5-baab-34aff9545c4e)
