### ISSUE TITLE
[BUG] Manual Backup Failed

### ISSUE THREAD

**Issue by eakteam** [litespeedtech/cyberpanel#1207]
Trying to generate a backup using `/usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/IncScheduler.py Weekly` from ssh terminal, but it fails with below message:

```
[02.05.2024_15-01-58] [Errno 2] No such file or directory: '/home/cyberpanel/git'. [IncScheduler.git:90]
[02.05.2024_15-02-01] Creating website result....{'status': 0, 'createWebSiteStatus': 0, 'error_message': 'Invalid domain.'}
[02.05.2024_15-02-01] 'tempStatusPath'. [Cron.CheckHostName]
```

**Comment by usmannasir** [comment]
do you have latest commit and btw which backups (v2 or normal one?)

**Comment by eakteam** [comment]
> do you have latest commit and btw which backups (v2 or normal one?)


Yes i have the very latest commit 2.3.5 and using normal backup

**Comment by usmannasir** [comment]
Google drive or sftp ?

**Comment by usmannasir** [comment]
OK. I checked it is just a warning from back-end and from another function which is not related to backup.

Both Google Drive and sftp backups are going through, you can also double check.

**Comment by eakteam** [comment]
> Google drive or sftp ?

Local, and is not working in my case...

**Comment by usmannasir** [comment]
ah local, let me test the local.

**Comment by usmannasir** [comment]
```
root@dockertesting:~# ls -la /home/kolkaripath/02.08.2024_10-26-39/
total 16
drwxr-xr-x 2 root      root      4096 Feb  8 10:26 .
drwxr-xr-x 3 root      root      4096 Feb  8 10:26 ..
-rw------- 1 wpmau1322 wpmau1322 6060 Feb  8 10:26 backup-wpmautic.net-02.08.2024_10-26-39.tar.gz
root@dockertesting:~#
```

local working too.

**Comment by usmannasir** [comment]
Can you go here and check logs of local backup ```8090/backup/scheduleBackup```

**Comment by eakteam** [comment]
> Can you go here and check logs of local backup `8090/backup/scheduleBackup`

There is no log there but here is the output of terminal after trying to run the backup:

```
root@server ~ # /usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/IncScheduler.py Weekly
Disk Usage of info@xxxxx.com is 621
Disk Usage of reservation@xxxxx.com is 1
497,1.6566666666666667
Disk Usage of eval@xxxxx.com is 38
194,0.6466666666666667
6426,21.42
du: cannot access '/home/vmail/xxxxx.com/info': No such file or directory
Disk Usage of info@xxxxx.com is 0MB
918,3.06
Disk Usage of aa@xxxxx.com is 32
Disk Usage of bb@xxxxx.com is 13
Disk Usage of reservation@xxxxx.com is 1
67,0.22333333333333336
622,2.0733333333333333
Disk Usage of info@xxxxx.com is 819
9,0.030000000000000002
85,0.2833333333333333
Disk Usage of info@xxxxx.com is 1
73,0.24333333333333335
62,0.2066666666666667
Disk Usage of info@xxxxx.com is 1750
92,0.3066666666666667
Disk Usage of info@xxxxx.com is 1
379,1.2633333333333334
17,0.05666666666666667
Disk Usage of info@xxxxx.com is 94
629,2.0966666666666667
Disk Usage of book@xxxxx.com is 1
572,1.9066666666666667
[02.09.2024_13-35-46] [Errno 2] No such file or directory: '/home/cyberpanel/git'. [IncScheduler.git:90]
Hostname is already set, the same hostname is also used with mail service and rDNS. Let see if valid SSL also exists for this hostname..,10
[02.09.2024_13-35-49] Hostname is already set, the same hostname is also used with mail service and rDNS. Let see if valid SSL also exists for this hostname..,10
It looks like your current hostname is already the mail server hostname and rDNS is also set and there is a valid SSL, nothing needed to do.
[02.09.2024_13-35-50] It looks like your current hostname is already the mail server hostname and rDNS is also set and there is a valid SSL, nothing needed to do.
```

**Comment by usmannasir** [comment]
Can I get access to your server via ticket ?

**Comment by eakteam** [comment]
> Can I get access to your server via ticket ?

Sure, here it is: https://platform.cyberpersons.com/support/KFHU3GJMB/

**Comment by usmannasir** [comment]
![Screenshot 2024-02-10 at 14-18-59 Schedule Backup - CyberPanel](https://github.com/usmannasir/cyberpanel/assets/17538454/768ccbf9-cbc5-4625-a269-5f908ae7371b)

I see that you have added no sites to the schedule and 'Selected sites` were selected. I've added one site now, can you try

**Comment by eakteam** [comment]
> ![Screenshot 2024-02-10 at 14-18-59 Schedule Backup - CyberPanel](https://private-user-images.githubusercontent.com/17538454/303826793-768ccbf9-cbc5-4625-a269-5f908ae7371b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTcwOTgsIm5iZiI6MTcwNzU1Njc5OCwicGF0aCI6Ii8xNzUzODQ1NC8zMDM4MjY3OTMtNzY4Y2NiZjktY2JjNS00NjI1LWEyNjktNWY5MDhhZTczNzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA5MTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMWQxOTJhMDY1NWY2YzRiZmZiMDFmYWU2ZmE3ZWI5ZjZiYmNjNjIzOGQ2NzYyMTQwMjg5ZjBlYTRjODVkNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vpLCJasLvkd8UfCGju-uiCFiRR0KpPpIvwCOCDz-SDw)
> 
> I see that you have added no sites to the schedule and 'Selected sites` were selected. I've added one site now, can you try

It doesn't work even with one site or adding all of them. Do you want a screen recording?

**Comment by eakteam** [comment]
![cyberrrrr](https://github.com/usmannasir/cyberpanel/assets/8820741/3067d19f-8bfb-4f19-8a84-ae0e6dc53d11)

**Comment by usmannasir** [comment]
If you see Frequency column it says NEVER, It was a minor issue now I set the frequency to Weekly via dropdown and its going through, backup job is running.
