### ISSUE TITLE
1 Bug, 1 Typo

### ISSUE THREAD

**Issue by msburgess3200** [litespeedtech/cyberpanel#121]
Version: https://i.imgur.com/e1hzqOJ.png

Typo: Still shows 1.8 instead of 1.9.
https://i.imgur.com/yS7Uc4H.png

Bug: 404 on login... https://i.imgur.com/0cbQhaE.png
Removing /base will take you to the panel.

**Comment by usmannasir** [comment]
To fix the 404 bug, you can upgrade and clear browser cache.
