### ISSUE TITLE
[BUG] Cannot add SFTP Backup Destination

### ISSUE THREAD

**Issue by eakteam** [litespeedtech/cyberpanel#1210]
SFTP destination cannot be added to both normal and V2 Backups

Error:

```
Host uXXXXXX.your-storagebox.de not found in /root/.ssh/known_hosts
End Of File (EOF). Exception style platform.

command: /usr/bin/ssh
args: ['/usr/bin/ssh', '-o', 'StrictHostKeyChecking=no', '-p', '22', 'uXXXXXX@u388560.your-storagebox.de', 'mkdir ~/.ssh || rm -f ~/.ssh/temp && rm -f ~/.ssh/authorized_temp && cp ~/.ssh/authorized_keys ~/.ssh/temp || chmod 700 ~/.ssh || chmod g-w ~']
buffer (last 100 chars): b''
before (last 100 chars): b'ssh: connect to host uXXXXXX.your-storagebox.de port 22: Cannot assign requested address\r\r\n'
after:
```

**Comment by usmannasir** [comment]
this problem on same server? can you provide sftp login ?

**Comment by eakteam** [comment]
> this problem on same server? can you provide sftp login ?

Yes, in the same server. I have sent the SFTP login at the same ticket as before.

**Comment by usmannasir** [comment]
i will close this issue, as it seems a problem with your sftp access (mentioned on ticket)

**Comment by usmannasir** [comment]
![Screenshot 2024-02-11 at 11-01-51 Hetzner Online GmbH - Robot](https://github.com/usmannasir/cyberpanel/assets/17538454/7ccfbc42-0525-491b-b3dc-a617588df33d)

you have this enabled ? SSH Support

**Comment by eakteam** [comment]
> ![Screenshot 2024-02-11 at 11-01-51 Hetzner Online GmbH - Robot](https://private-user-images.githubusercontent.com/17538454/303901256-7ccfbc42-0525-491b-b3dc-a617588df33d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NDk1ODcsIm5iZiI6MTcwNzY0OTI4NywicGF0aCI6Ii8xNzUzODQ1NC8zMDM5MDEyNTYtN2NjZmJjNDItMDUyNS00OTFiLWIzZGMtYTYxNzU4OGRmMzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDExMDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmM2Y1ZDlhNGI1MzUwYTBmNDI3ZDA4YjNjYzU0YTllYzAwYTAyYmFhNjBjMTVjY2JkNGQ2ZDBiYjU0YjBjZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yeU5azs-dj6IoqtfqDU3ycQyFwSQ26DnmuN1fnbaxnw)
> 
> you have this enabled ? SSH Support

I can connect through other apps, but not from CyberPanel.

**Comment by usmannasir** [comment]
Yes because CyberPanel must need SSH access enabled.

**Comment by eakteam** [comment]
> Yes because CyberPanel must need SSH access enabled.

So what we should do to solve that?

**Comment by usmannasir** [comment]
enable SSH acces, update CyberPanel and try again.
