### ISSUE TITLE
[BUG] rDNA 404

### ISSUE THREAD

**Issue by fm407** [litespeedtech/cyberpanel#1211]
i get this message when i try to start the wizard: Domain that you have provided is not configured as rDNS for your server IP. [404]

if i try an nslookup from the server it resolves okay, i have changed nothing, i also have upgraded with cyberpanel_utility
 option 1

am i missing something?

**Comment by usmannasir** [comment]
Please use forum for such discussions. https://community.cyberpanel.net/

**Comment by fredroo** [comment]
@fm407 when you create a new domain the NS records, are like ns1.newwebsite.com ns2.newwebsite.com? default NAMESERVER NOT WORKING?

**Comment by fm407** [comment]
> @fm407 when you create a new domain the NS records, are like ns1.newwebsite.com ns2.newwebsite.com? default NAMESERVER NOT WORKING?

i resolved it, thanks

**Comment by fredroo** [comment]
@fm407 how do you fix this?

**Comment by fm407** [comment]
> @fm407 how do you fix this?

getting rid of cyberpanel and using a well supported solution.
