### ISSUE TITLE
[BUG] SSL issue on subdomains

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1213]
I just got a problem in 2.3.5, all subdomains get invalid/expired SSL's.
I have tried SSLV2, it just said "Already got an SSL"

Example of API that should have had let's encrypt SSL.

https://api.newstargeted.com/roblox/users/v2/user.php?username=Master3395

```
Current Version:  2.3
Build:  5
Current Commit:  24b10a3440438ac78ffbe68eb50986d96b1600ba
Latest Version:  2.3
Latest Build:  5
Latest Commit:  24b10a3440438ac78ffbe68eb50986d96b1600ba
```

And i tried SSL, it says issued.
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/8de38844-eb5a-4a2a-bd70-ab9006e10501)
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/7898d304-c77b-496c-bcdb-cae997a7577a)
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/223723c0-6039-4d02-9f9c-89eb6a97ffcb)

**Comment by master3395** [comment]
Had to revert back to 2.3.4, in order to get the Let's encrypt working for my subdomains again.

**Comment by fm407** [comment]
i have the same issue, but i reverted to 2.3.4 and i still cant get the cert for my main domain, do you mind sharing your dns settings?

**Comment by master3395** [comment]
> i have the same issue, but i reverted to 2.3.4 and i still can't get the cert for my main domain, do you mind sharing your dns settings?

I use Cloudflare for my subdomains, it's only a few subdomains I don't use Cloudflare for.
And for www.sub.domain.com 
The subdomains I don't use Cloudflare for should have gotten SSL from Let's Encrypt.
But my subdomain https://api.newstargeted.com/roblox/users/v2/user.php?username=Master3395
Does use CloudFlare, so I am not sure if there's an issue with the Cloudflare and SSL setup in 2.3.5 @usmannasir 
Because this subdomain uses CloudFlare.
![image](https://github.com/usmannasir/cyberpanel/assets/4199669/54d2aae9-85cc-42af-9f26-5fd014c160e4)

**Comment by usmannasir** [comment]
I am checking.

**Comment by usmannasir** [comment]
I have found the issue, I am correcting and pushing after some more testing.

**Comment by usmannasir** [comment]
Fixed and pushed.
