### ISSUE TITLE
[BUG updating via cyberpanel_utility AlmaLinux release 8.9 (Midnight Oncilla)

### ISSUE THREAD

**Issue by e-promo** [litespeedtech/cyberpanel#1216]
**Describe the bug**
ERROR: Could not find a version that satisfies the requirement boto3==1.34.39

**To Reproduce**
What steps did you take when the issue occurred? 
1. in console trying to update via cyberpanel-utility after notice in webpanel Note: Latest commit does not match, please upgrade CyberPanel.

**Expected behavior**
stopped 
![Schermafbeelding 2024-02-11 170954](https://github.com/usmannasir/cyberpanel/assets/80221584/d65b0f35-ee21-4448-ab8d-3dca5c40287b)

**Screenshots**

**Operating system:**
Please enter your answer here (e.g. Ubuntu 20.04 LTS)

**CyberPanel version:**
Please enter your answer here (e.g. 2.1.1). 

**Additional context**
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by lucasfurlan2** [comment]
I was going to report this problem now, thank you very much, I will be following up.

**Comment by usmannasir** [comment]
fixed yesterday night. thanks
