### ISSUE TITLE
Can not access "Access Log"

### ISSUE THREAD

**Issue by minhazulOO7** [litespeedtech/cyberpanel#122]
Edit 1: Login page still shows **V 1.8** instead of _V 1.9_
Edit: Talking about per domain **Access Log**
Clicking it says, `Could not connect to server. Please refresh this page.` Can access **Error Logs**.

**Comment by meramsey** [comment]
Can confirm this issue with login page showing v 1.8 when on V 1.9

![image](https://user-images.githubusercontent.com/1596188/65888240-2f89a100-e36d-11e9-8680-32e4f2f45d65.png)

![image](https://user-images.githubusercontent.com/1596188/65888250-36b0af00-e36d-11e9-9dda-55481edf5ebe.png)

And the Accesslogs not being accessible on Main or domain level it says it loaded it but did not show anything even after visiting site many times.

Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-64-generic x86_64)

![image](https://user-images.githubusercontent.com/1596188/65888668-e8e87680-e36d-11e9-8486-04cd9539f9ff.png)

![image](https://user-images.githubusercontent.com/1596188/65888680-ef76ee00-e36d-11e9-85b0-ce08c0bc51be.png)

Checked 3 of my cyberpanel servers all 3(2 are Centos and 1 Ubuntu) have 0 access logs and looks like it has been that way for a long time. They have same perms as the error log which works fine without issue. So this is kinda odd.

root@ols:~# stat /usr/local/lsws/logs/access.log
  File: /usr/local/lsws/logs/access.log
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: fd00h/64768d	Inode: 2362714     Links: 1
Access: (0644/-rw-r--r--)  Uid: (65534/  nobody)   Gid: ( 5001/  nobody)
Access: 2019-09-30 10:31:56.449994869 -0400
Modify: 2019-07-30 08:55:04.496345373 -0400
Change: 2019-07-30 08:55:04.496345373 -0400
 Birth: -
root@ols:~# cd /usr/local/lsws/logs/
root@ols:/usr/local/lsws/logs# ls
access.log       error.log             error.log.2019_09_30  stderr.log
auditmodsec.log  error.log.2019_09_29  lsrestart.log
root@ols:/usr/local/lsws/logs# stat error.log
  File: error.log
  Size: 41195     	Blocks: 96         IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 2359357     Links: 1
Access: (0644/-rw-r--r--)  Uid: (65534/  nobody)   Gid: ( 5001/  nobody)
Access: 2019-09-30 10:35:03.589808829 -0400
Modify: 2019-09-30 10:40:51.010391742 -0400
Change: 2019-09-30 10:40:51.010391742 -0400
 Birth: -
root@ols:/usr/local/lsws/logs# 

root@rst:~# stat /usr/local/lsws/logs/access.log
  File: /usr/local/lsws/logs/access.log
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 801h/2049d	Inode: 279114      Links: 1
Access: (0644/-rw-r--r--)  Uid: (65534/  nobody)   Gid: ( 5002/  nobody)
Access: 2019-08-10 21:26:40.397917793 -0400
Modify: 2019-08-10 21:26:40.397917793 -0400
Change: 2019-08-10 21:26:40.397917793 -0400
 Birth: -
root@rst:~# cat /usr/local/lsws/logs/
access.log            error.log             error.log.2019_09_10  lsrestart.log
auditmodsec.log       error.log.2019_08_28  error.log.2019_09_24  stderr.log
root@rst:~#

[root@wcloud:~]# stat /usr/local/lsws/logs/access.log
  File: ‘/usr/local/lsws/logs/access.log’
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: fd01h/64769d	Inode: 1284144     Links: 1
Access: (0644/-rw-r--r--)  Uid: (   99/  nobody)   Gid: (   99/  nobody)
Access: 2019-09-26 08:53:12.436325120 -0400
Modify: 2019-09-26 08:53:43.323467789 -0400
Change: 2019-09-26 08:53:43.323467789 -0400
 Birth: -
[root@wcloud:~]# cat /usr/local/lsws/logs/
Display all 1590 possibilities? (y or n)
access.log                error.log.2019_09_13.52   error.log.2019_09_19.12   error.log.2019_09_24.27
auditmodsec.log           error.log.2019_09_13.53   error.log.2019_09_19.13   error.log.2019_09_24.28
error.log

**Comment by meramsey** [comment]
This is fascinating looks like its not been working for awhile not sure why though as it looks like the vhosts are setup to properly log to their respective access.logs but no hits are generated in a long time. 

Error from the one that does have an access.log with content
`Could not fetch logs, see the logs file through command line. Error message: Not able to fetch logs, see CyberPanel main log file!`


```
root@rst:/usr/local/lsws/conf# grep -r access.log .
./httpd.conf:CustomLog "/usr/local/lsws/logs/access.log" combined
./httpd_config.xml.bak:            <fileName>$SERVER_ROOT/logs/access.log</fileName>
./httpd_config.xml:      <fileName>$SERVER_ROOT/logs/access.log</fileName>
./templates/rails.xml:        <fileName>$SERVER_ROOT/logs/$VH_NAME.access.log</fileName>
./templates/ccl.xml:        <fileName>$SERVER_ROOT/logs/$VH_NAME.access.log</fileName>
./templates/phpsuexec.xml:        <fileName>$SERVER_ROOT/logs/$VH_NAME.access.log</fileName>
./vhosts/example.com/vhost.conf:    CustomLog /home/example.com/logs/example.com.access_log combined
./vhosts/example.com/vhost.conf:    CustomLog /home/example.com/logs/example.com.access_log combined
root@rst:/usr/local/lsws/conf# stat /home/example.com/logs/example.com.access_log  File: /home/example.com/logs/example.com.access_log
  Size: 1249736   	Blocks: 2456       IO Block: 4096   regular file
Device: 801h/2049d	Inode: 275185      Links: 1
Access: (0644/-rw-r--r--)  Uid: (65534/  nobody)   Gid: ( 1002/ rstrams)
Access: 2019-09-29 11:00:01.862790641 -0400
Modify: 2019-08-10 21:18:49.067629589 -0400
Change: 2019-08-10 21:26:46.153798963 -0400
 Birth: -
root@rst:/usr/local/lsws/conf# 
```


Last logs are old
```
root@rst:/usr/local/lsws/conf# tail /home/example.com/logs/example.com.access_log"example.com 144.202.38.159 - - [11/Aug/2019:01:17:21 +0000] "GET /images/clippy.png HTTP/1.1" 200 3108"
"example.com IP - - [11/Aug/2019:01:17:21 +0000] "GET /favicon.ico HTTP/1.1" 200 318"
"example.com IP - - [11/Aug/2019:01:18:25 +0000] "GET /.well-known/acme-challenge/jdfXnNKspsIV9q7sMUNUeUYMJ8YVX6OXScwI1Dt9Q6w HTTP/1.1" 301 672"
"example.com IP - - [11/Aug/2019:01:18:25 +0000] "GET /.well-known/acme-challenge/jdfXnNKspsIV9q7sMUNUeUYMJ8YVX6OXScwI1Dt9Q6w HTTP/1.1" 301 672"
"example.com IP - - [11/Aug/2019:01:18:25 +0000] "GET /.well-known/acme-challenge/jdfXnNKspsIV9q7sMUNUeUYMJ8YVX6OXScwI1Dt9Q6w HTTP/1.1" 301 672"
"example.com IP - - [11/Aug/2019:01:18:25 +0000] "GET /.well-known/acme-challenge/jdfXnNKspsIV9q7sMUNUeUYMJ8YVX6OXScwI1Dt9Q6w HTTP/1.1" 301 672"
"example.com IP - - [11/Aug/2019:01:18:48 +0000] "GET /.well-known/acme-challenge/-LcSCFmPT3OBAjerV5Dr-nSj4q0K4JI7aNoACI_WOjc HTTP/1.1" 301 672"
"example.com IP - - [11/Aug/2019:01:18:48 +0000] "GET /.well-known/acme-challenge/-LcSCFmPT3OBAjerV5Dr-nSj4q0K4JI7aNoACI_WOjc HTTP/1.1" 301 672"
"example.com IP - - [11/Aug/2019:01:18:48 +0000] "GET /.well-known/acme-challenge/-LcSCFmPT3OBAjerV5Dr-nSj4q0K4JI7aNoACI_WOjc HTTP/1.1" 301 672"
"example.com IP - - [11/Aug/2019:01:18:48 +0000] "GET /.well-known/acme-challenge/-LcSCFmPT3OBAjerV5Dr-nSj4q0K4JI7aNoACI_WOjc HTTP/1.1" 301 672"
root@rst:/usr/local/lsws/conf#
```

Other server is same way except the access.logs are empty.
```
[root@wcloud:/usr/local/lsws/logs]# stat /usr/local/lsws/logs/error.log
  File: ‘/usr/local/lsws/logs/error.log’
  Size: 5335063   	Blocks: 10424      IO Block: 4096   regular file
Device: fd01h/64769d	Inode: 1283798     Links: 1
Access: (0644/-rw-r--r--)  Uid: (   99/  nobody)   Gid: (   99/  nobody)
Access: 2019-09-30 10:14:59.099683447 -0400
Modify: 2019-09-30 10:42:38.028677569 -0400
Change: 2019-09-30 10:42:38.028677569 -0400
 Birth: -
[root@wcloud:/usr/local/lsws/logs]# grep -r access.log /usr/local/lsws/conf/
/usr/local/lsws/conf/httpd_config.xml:      <fileName>$SERVER_ROOT/logs/access.log</fileName>
/usr/local/lsws/conf/httpd_config.xml.bak:            <fileName>$SERVER_ROOT/logs/access.log</fileName>
/usr/local/lsws/conf/vhosts/wcloud.example2.com/vhost.conf:    CustomLog /home/wcloud.example2.com/logs/wcloud.example2.com.access_log combined
/usr/local/lsws/conf/vhosts/wcloud.example2.com/vhost.conf:    CustomLog /home/wcloud.example2.com/logs/wcloud.example2.com.access_log combined
/usr/local/lsws/conf/vhosts/example2.com/vhost.conf:    CustomLog /home/example2.com/logs/example2.com.access_log combined
/usr/local/lsws/conf/vhosts/example2.com/vhost.conf:    CustomLog /home/example2.com/logs/example2.com.access_log combined
/usr/local/lsws/conf/vhosts/my.example2.com/vhost.conf:    CustomLog /home/example2.com/logs/example2.com.access_log combined
/usr/local/lsws/conf/vhosts/my.example2.com/vhost.conf:    CustomLog /home/my.example2.com/logs/my.example2.com.access_log combined
/usr/local/lsws/conf/templates/phpsuexec.xml:        <fileName>$SERVER_ROOT/logs/$VH_NAME.access.log</fileName>
/usr/local/lsws/conf/templates/ccl.xml:        <fileName>$SERVER_ROOT/logs/$VH_NAME.access.log</fileName>
/usr/local/lsws/conf/templates/rails.xml:        <fileName>$SERVER_ROOT/logs/$VH_NAME.access.log</fileName>
/usr/local/lsws/conf/httpd.conf:CustomLog "/usr/local/lsws/logs/access.log" combined
[root@wcloud:/usr/local/lsws/logs]# stat /home/example2.com/logs/example2.com.access_log
  File: ‘/home/example2.com/logs/example2.com.access_log’
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: fd01h/64769d	Inode: 517825      Links: 1
Access: (0644/-rw-r--r--)  Uid: (   99/  nobody)   Gid: ( 5002/ whatthe)
Access: 2019-09-29 22:00:01.546777220 -0400
Modify: 2019-08-21 08:13:38.819095556 -0400
Change: 2019-08-21 13:13:33.102011280 -0400
 Birth: -
[root@wcloud:/usr/local/lsws/logs]#
```

**Comment by meramsey** [comment]
So after a ton of debugging, I found the fix to this.

Bad ownership on the logs folder for the domain "lscpd:lscpd"
stat /home/example.com/logs/
  File: ‘/home/example.com/logs/’
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: fd01h/64769d	Inode: 517823      Links: 2
Access: (0750/drwxr-x---)  Uid: ( 5001/   lscpd)   Gid: ( 5001/   lscpd)
Access: 2019-09-30 10:37:25.472986904 -0400
Modify: 2019-08-21 09:00:01.390848467 -0400
Change: 2019-08-21 13:13:32.739009641 -0400
 Birth: -

Replace "user" with your username and "domain" with your domain and this should fix it right up. 
chown nobody:user /home/domain/logs/

Should look like this but with your domains user
stat /home/example.com/logs/example.com.access_log
  File: ‘/home/example.com/logs/example.com.access_log’
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: fd01h/64769d	Inode: 517825      Links: 1
Access: (0644/-rw-r--r--)  Uid: (   99/  nobody)   Gid: ( 5002/ user)
Access: 2019-09-30 12:42:00.144470061 -0400
Modify: 2019-08-21 08:13:38.819095556 -0400
Change: 2019-09-30 12:38:12.638314034 -0400
 Birth: -

Then tail the log while browsing the site to verify its working
tail -f /home/example.com/logs/example.com.access_log

I also Noticed the child domains log is broken for 443 vhosts as well sets a logfile path that does not exist. 

Before
```
cat vhost.conf 
<VirtualHost *:80>

    ServerName my.example.com
    ServerAlias www.my.example.com
    ServerAdmin webmaster@example.com
    SuexecUserGroup user user
    DocumentRoot /home/example.com/public_html/my.example.com
    CustomLog /home/example.com/logs/example.com.access_log combined
    AddHandler application/x-httpd-php73 .php
    <IfModule LiteSpeed>
        CacheRoot lscache
    </IfModule>

</VirtualHost>
<VirtualHost *:443>

    ServerName my.example.com
    ServerAlias www.my.example.com
    ServerAdmin usman@cyberpersons.com
    SuexecUserGroup user user
    DocumentRoot /home/example.com/public_html/my.example.com
    CustomLog /home/my.example.com/logs/my.example.com.access_log combined   <<<<<< this path does not exist
    <IfModule LiteSpeed>
        CacheRoot lscache
    </IfModule>
    SSLEngine on
    SSLVerifyClient none
    SSLCertificateFile /etc/letsencrypt/live/my.example.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/my.example.com/privkey.pem
    AddHandler application/x-httpd-php73 .php
</VirtualHost>
```


After:
```
<VirtualHost *:80>

    ServerName my.example.com
    ServerAlias www.my.example.com
    ServerAdmin webmaster@example.com
    SuexecUserGroup user user
    DocumentRoot /home/example.com/public_html/my.example.com
    CustomLog /home/example.com/logs/my.example.com.access_log combined
    AddHandler application/x-httpd-php73 .php
    <IfModule LiteSpeed>
        CacheRoot lscache
    </IfModule>

</VirtualHost>
<VirtualHost *:443>

    ServerName my.example.com
    ServerAlias www.my.example.com
    ServerAdmin usman@cyberpersons.com
    SuexecUserGroup user user
    DocumentRoot /home/example.com/public_html/my.example.com
    CustomLog /home/example.com/logs/my.example.com.access_log combined
    <IfModule LiteSpeed>
        CacheRoot lscache
    </IfModule>
    SSLEngine on
    SSLVerifyClient none
    SSLCertificateFile /etc/letsencrypt/live/my.example.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/my.example.com/privkey.pem
    AddHandler application/x-httpd-php73 .php
</VirtualHost>
```
@usmannasir this should probably be looked into with possibly a post upgrade hook to ensure users logs paths are have proper nobody:user and proper permissions

sadly im to tired atm to code a script to fix this but at least we know what the issue is at least on my servers with this issue.

**Comment by meramsey** [comment]
BTW @minhazulOO7 submitted this commit which I believe should fix the hardcoded version on the login page.

https://github.com/usmannasir/cyberpanel/pull/132

**Comment by minhazulOO7** [comment]
@spyngamerman yeah checked your commit, it should fix the version issue.

**Comment by cagivacode** [comment]
I just found this issue today.....Domains added in July all had this issue. Domains added later were fine.

I only noticed when checking traffic on little used domains that I moved to the Cyberpanel server first (in July).

**Comment by istiak101** [comment]
This is fixed. Please close @usmannasir @aonsyed
