### ISSUE TITLE
[BUG] Add add-on domain no longer works correctly and assigns the domain to the first site in the list

### ISSUE THREAD

**Issue by morphinestyle** [litespeedtech/cyberpanel#1221]
By adding an addon domain I can no longer choose which account to insert it into, but it places it at the first domain in my list rather than the one from which I am creating/inserting it.

It worked until a couple of weeks ago, after a few updates it gives this problem.

**Comment by usmannasir** [comment]
Hi,

I've explained this situation here: https://cyberpanel.net/KnowledgeBase/home/create-sub-addon-domain/

thanks.

**Comment by morphinestyle** [comment]
Okay!
How do you change the default cyber panel site?
Because the one Cyberpanel uses in ADDON DOMAIN is not the correct one that I want.
