### ISSUE TITLE
Mautic javascript errors

### ISSUE THREAD

**Issue by inovve** [litespeedtech/cyberpanel#1226]
![image](https://github.com/usmannasir/cyberpanel/assets/3105659/0d63d738-5a6f-4f25-93f1-a99c2ae894d0)

Cyberpanel on latest commit, Mautic fresh install, the menus highlighted at red don't work, seems like some javasctipt problem.

**Comment by usmannasir** [comment]
I can not reproduce this on Ubuntu 22 on my end. Can you check if `node` and `npm` are installed on your system?

If not please install and try to install mautic again (even though CyberPanel install npm for you, but this could be special case)

**Comment by usmannasir** [comment]
It was only an issue with AlmaLinux. `npm` and `node` versions were not compatible with Mautic.

So I've fetched and installed latest versions from `npm` and `node`, this should not happen any more. If you already have npm and node installed please remove them so CyberPanel can install required versions for you.

**Comment by shmaltz** [comment]
@usmannasir I'm having the same issue on 2.3.5 latest build.
I checked my server and did't have npm or node installed. I tried upgrading Cyberpanel to the latest build, but it still didn't install. I installed NPM and Node but it still doesn't work.
