### ISSUE TITLE
[BUG] Creating domain and or sub-domain should auto add default htaccess file in root

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1230]
When you create a new domain or sub-domain with Apache setup, it should create a "default" or "dummy" htaccess file in the root, in order for the user to know if they got it enabled, and perhaps fix any minor hiccups, such as an internal error 503 would happen.

**Comment by usmannasir** [comment]
what should be default content of that ? i mean how would an empty file help user?

**Comment by master3395** [comment]
> what should be default content of that ? i mean how would an empty file help user?

By that I mean, as a reference to help the user see how the htaccess file could look, or add a readme file, that explains how htaccess should be when using the apache setup?

**Comment by usmannasir** [comment]
.htaccess file looks pretty much same weather its Apache, OLS, LSWS Ent. I believe we should not create it, it will confuse users. 

Because when ever they will install WordPress .htaccess file is found to come, so I don't feel the need for it.
