### ISSUE TITLE
[BUG] Empy saving Vhost should not be allowed

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1231]
I just tried clearing out the vhost, to see what would happen, if I tried.
And sadly it allows me to save when the input box is empty.
Leaving just an error message if I try to click the Vhost button again.
Even if i change the rewrite rules, PHP, and open_basedir, it still does not make a working vhost i can edit.

![image](https://github.com/usmannasir/cyberpanel/assets/4199669/3a1f8287-3d54-4e43-b369-6554dd7093f8)

**Comment by usmannasir** [comment]
fixed.
