### ISSUE TITLE
[Feature] Allow DNS type SVCB (and HTTPS etc.) records

### ISSUE THREAD

**Issue by dev-polymer** [litespeedtech/cyberpanel#1233]
Hello friends! New freshest DNS record stypes need to be configured in my case, but not allowed in record type list in CyberPanel DNS yet...

Reference: More record types: [wiki/List_of_DNS_record_types](https://en.wikipedia.org/wiki/List_of_DNS_record_types)

Now specifically need HTTPS record ([RFC9460](https://datatracker.ietf.org/doc/rfc9460/?include_text=1))

Can we allow this record type? This is [supported by PowerDNS](https://doc.powerdns.com/authoritative/guides/svcb.html) now!

_P.S. Thanks for awesome CyberPanel to all team!_

**Comment by Yiivgeny** [comment]
+1

**Comment by usmannasir** [comment]
related pull request merged.
