### ISSUE TITLE
[BUG] Enabling CSF with customized Cyberpanel PORT

### ISSUE THREAD

**Issue by psycmos** [litespeedtech/cyberpanel#1235]
If i change the cyberpanel port from default to 2083, for example, and after that try enabling the CSF, it will be enabled with default port 8090 and will not use my customized port inserted with Cyberpanel UI at port config.

It will prevent the access do server.
I need to change SSH to server, disable CSF, edit the default rules of TCP IN/OUT with my port, save it and start CSF again.

So during the enable process of CSF it needs to check what real port of cyberpanel are in use the user

**Comment by usmannasir** [comment]
let me check

**Comment by usmannasir** [comment]
fixed.
