### ISSUE TITLE
phpMyAdmin fails to export over 32MB

### ISSUE THREAD

**Issue by SaJeTek-Developer** [litespeedtech/cyberpanel#1237]
# Environment

CentOS 7/Almalinux 8
Last OpenLiteSpeed 1.7.19
Last CyberPanel stable 2.3.5

**Please note that this is a duplicate of https://github.com/usmannasir/cyberpanel/issues/568 which was closed without being address due to what I believe was a misunderstanding of the last comment before closure which actually proved that the problem was still unsolved.**

# The Problem
When exporting a database larger than 32MB (e.g., +100MB) in phpMyAdmin, the download stops after reaching 32MB of the SQL file. The last line of the SQL file contains the following message:

`The dynamic response body size is over the limit, the response will be truncated by the web server. The limit is set in the key 'maxDynRespSize' located in the tuning section of the server configuration, and labeled 'max dynamic response body size'`

I have verified that the maxDynRespSize limit is set to the maximum value (2047MB). Testing with other limits (less than 2047MB) did not resolve the issue.

I am unsure if this problem is exclusive to OpenLiteSpeed (OLS) or if it is related to the phpMyAdmin + CyberPanel integration. Further testing is required.

# How to Test

1. Create a database with a size of 100MB.
2. Attempt to export the database using the quick action (without compression).
3. Wait for the download to complete.
4. Check the last line of the exported SQL file.

# What I Expect
I expect to receive a complete SQL dump of the database. While I understand that compressing the SQL dump can reduce its size below 32MB, it is sometimes impractical to compress large databases to meet this size limit.

**Comment by usmannasir** [comment]
let me check.

**Comment by usmannasir** [comment]
I can reproduce this, will revert to you.

**Comment by usmannasir** [comment]
If you install v3.0.0 ? see if this fixes your problem.

**Comment by SaJeTek-Developer** [comment]
**CentOs 7 running as root.**
Tried to upgrade to 3.0.0 from 2.3.5 but it keeps failing. The upgrade script is removing `/usr/local/lscp/bin/lscpd ` but not replacing it.

Reverted to 2.3.5 which works.

Manually downloaded lscpd 4.0.1 and put in `/usr/local/lscp/bin/lscpd `.

Error:
```
./lscpd: /usr/lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./lscpd)
[ERROR] Failed to start lscpd!
```
Im guessing v3.0.0 does not support Centos 7

**Almalinux 8 running as root.**
Tried to upgrade to 3.0.0 from 2.3.5 but it keeps failing. The upgrade script is removing `/usr/local/lscp/bin/lscpd ` but not replacing it.

Manually downloaded lscpd 4.0.1 and put in `/usr/local/lscp/bin/lscpd `.
Version of Cyberpanel is still v2.3.5

Tested issue and it's fixed as i was able to download a table exceeding 250MB.

1. Checked the contents of the file and it's valid.
2. Tested by reimporting into a test table successfully.

**Comment by usmannasir** [comment]
Please note we dont support Centos 7 anymore, for almalinux the isssue is resolved.
