### ISSUE TITLE
[BUG] Issue with Mautic JavaScript Loading via CyberPanel App Installer

### ISSUE THREAD

**Issue by abouzia** [litespeedtech/cyberpanel#1238]
## Description
I installed Mautic using the App installer in CyberPanel, but it's not loading JavaScript correctly. However, when I install the same version of Mautic locally, it works fine. This leads me to believe that the issue lies with the CyberPanel's installation process of Mautic that leads to Mautic not loading JavaScript correctly.

## Steps to Reproduce
1. Install Mautic using the App installer in CyberPanel.
2. Try to access the Mautic dashboard.

## Expected Behavior
The Mautic dashboard should load correctly, including all JavaScript, after installation via CyberPanel.

## Actual Behavior
The Mautic dashboard is not loading JavaScript correctly after installation via CyberPanel.

## Environment
CyberPanel version: 2.3.5
Mautic version: 5.0.3
PHP version: 8.0, 8.1
Ubuntu version: 20.04.6
Node version: 10.19.0
NPM version: 6.14.4

![Screenshot 2024-03-23 022400](https://github.com/usmannasir/cyberpanel/assets/2650972/fe653dce-b819-4816-90ad-3fb090bb3ade)
![Screenshot 2024-03-23 024244](https://github.com/usmannasir/cyberpanel/assets/2650972/690fa3cb-e8a4-4fa4-9e52-bd00e003742a)

**Comment by usmannasir** [comment]
Please check: https://github.com/usmannasir/cyberpanel/issues/1226
