### ISSUE TITLE
[BUG] Merge stable into 2.3.5?

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1239]
Perhaps it's a good idea to move the stable changes into 2.3.5?

![Skjermbilde 2024-03-26 094209](https://github.com/usmannasir/cyberpanel/assets/4199669/5aecb38f-9a62-438d-ba67-2fc772927440)
![bilde](https://github.com/usmannasir/cyberpanel/assets/4199669/075ed1b1-46f0-44be-807c-d596fde97160)

**Comment by usmannasir** [comment]
its done.
