### ISSUE TITLE
[BUG] Problem during update

### ISSUE THREAD

**Issue by lucasfurlan2** [litespeedtech/cyberpanel#1241]
An error occurs during the CP update on my VPS, shown in the screenshot below.
![Sem título](https://github.com/usmannasir/cyberpanel/assets/39227017/85c15c6f-6c5c-4206-98b5-0b927ea7e63b)

Version I'm currently using
![version](https://github.com/usmannasir/cyberpanel/assets/39227017/a7b5b496-e095-4dd4-a4f7-f07c0e9abdc3)

[root@XXXXXX ~]# cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.9 (Midnight Oncilla)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.9 (Midnight Oncilla)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"

Could you please check?

**Comment by shbs9** [comment]
let me reproduce this

**Comment by shbs9** [comment]
please run this
yum install mariadb-connector-c-devel

and then update

**Comment by usmannasir** [comment]
fixed at the code level, thanks

**Comment by lucasfurlan2** [comment]
The bug has been fixed, thank you very much!
