### ISSUE TITLE
fix the documentation broken links

### ISSUE THREAD

**Issue by ghost** [litespeedtech/cyberpanel#1243]
even for me that I am blind, i can see these brooken links of documentation in panel.
cyberpanel.net/docs are killed at all.
this is an urgent fix, we want to have a full documentation quickly and stable

**Comment by aerdemsenturk** [comment]
Throughout the interface, there are dozens of broken links.

The address https://go.cyberpanel.net/ no longer seems to be working. Now, there is https://community.cyberpanel.net/.

This address appears in 25 different template files. Why did it take so long to manually check and replace each one with the correct address? Is everyone expecting someone else to do this?

https://github.com/search?q=repo%3Ausmannasir%2Fcyberpanel%20https%3A%2F%2Fgo.cyberpanel.net&type=code

Overall, there is a knowledge base problem in CyberPanel. Everything is chaotic, links are broken, I'm constantly being redirected elsewhere, and mostly I encounter a page that won't load.

I'm a new CyberPanel user and trying to explore it. I don't know how aware the CyberPanel developers are of this, but despite seeming simple, this issue undermines its reliability.

**Comment by usmannasir** [comment]
this has been fixed. thanks for brining up.
