### ISSUE TITLE
[BUG]We are not able to run curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup

### ISSUE THREAD

**Issue by WaReZoR-UA** [litespeedtech/cyberpanel#1245]
If you try to go to the link https://downloads.mariadb.com/MariaDB/mariadb_repo_setup, you will get 500 - Internal Server Error.

this is the problem with the installation at the moment, the database distribution is simply not available to download

**Comment by usmannasir** [comment]
which OS?

**Comment by WaReZoR-UA** [comment]
Ubuntu 22.04
On 20.04 it works well.
I think everything is working now and it was a temporary problem.

**Comment by usmannasir** [comment]
Alright, i will close it now.
