### ISSUE TITLE
[BUG] Facing Installation error on Ubuntu 22.4 and 20 tested on 3 server and e rror is same 

### ISSUE THREAD

**Issue by Redowan-Ahmed** [litespeedtech/cyberpanel#1248]
**Important**
Error : [ERROR] We are not able to run curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash -s -- --mariadb-server-version=10.11 return code: 2.  Fatal error, see /var/log/installLogs.txt for full details.

**Describe the bug**
I tried that on 3 servers and on all servers, I faced the same issue. The system tried 3 times on each server and all failed. I tried to check the file URL https://downloads.mariadb.com/MariaDB/mariadb_repo_setup and got a 500 error page.

Please help me to figure it out.
Thanks 

**Operating system:**
Ubuntu , 22.0.4, 20.04 LTS

**CyberPanel version:**
v2.3.5

**Comment by usmannasir** [comment]
Who is your hosting provider?

**Comment by Redowan-Ahmed** [comment]
AWS

**Comment by usmannasir** [comment]
light sail or ec2

**Comment by usmannasir** [comment]
I confirmed lightsail works, on ec2 which OS image you are using, can you share link of it?

**Comment by usmannasir** [comment]
ec2 also worked with amazon provided ubuntu 22 image.
