### ISSUE TITLE
[BUG] Cloudflare DNS API Error

### ISSUE THREAD

**Issue by Coolspotcreative** [litespeedtech/cyberpanel#1252]
**Describe the bug**
When setting up the Zone DNS with the cloudflare api and with the option sync local to cloudflare disabled. When trying to fetch the dns records I get the following error: 

`Cannot fetch records. Error message: module 'CloudFlare' has no attribute 'CloudFlareAPIError'`

**To Reproduce**
What steps did you take when the issue occurred? 
1. go to cloudflare submenu in DNS
2. Enter cloudflare registered email and token and set sync local to disabled
3. Save
4. go to manage dns 
5.Select domain in the drop down

**Expected behavior**
Expectation is that it would fetch the current dns records from cloudflare

**Operating system:**
Ubuntu server 22.04.4

**CyberPanel version:**
2.3

**Comment by usmannasir** [comment]
let me check

**Comment by usmannasir** [comment]
I can see records are being fetched for me fine, maybe you have not entered the correct key.
