### ISSUE TITLE
Please add support for Debian systems, thank you.

### ISSUE THREAD

**Issue by olisc3567** [litespeedtech/cyberpanel#1253]
Hi there,

I hope this message finds you well. I am a user interested in using CyberPanel on Debian-based distributions. I kindly request adding support for Debian in the CyberPanel project. This would greatly benefit users like me who prefer Debian systems. Thank you for considering this enhancement.

I'm sorry, my English is very poor, so I have to rely on GPT for support. Have a great day!

**Comment by usmannasir** [comment]
Hi,

Yes I do understand that many people like Debian, we already have support for Ubuntu which you may not like but as of now we don't plan to add Debian support because it then becomes hard to support multiple os and release fixes for all if something goes wrong.

Sorry for inconvenience.
