### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by osmanfc** [litespeedtech/cyberpanel#1256]
No module named 'pysftp'<
Request Method: | GET
-- | --
https://spshahintelecom.com:8090/filemanager/originaltelecombd.com
3.1.3
ModuleNotFoundError
No module named 'pysftp'
/usr/local/CyberCP/plogical/backupUtilities.py, line 14, in <module>
/usr/local/CyberCP/bin/python
3.6.8
['',  '/usr/local/CyberCP/bin',  '/usr/local/CyberCP',  '/usr/local/CyberCP/lib64/python36.zip',  '/usr/local/CyberCP/lib64/python3.6',  '/usr/local/CyberCP/lib64/python3.6/lib-dynload',  '/usr/lib64/python3.6',  '/usr/lib/python3.6',  '/usr/local/CyberCP/lib/python3.6/site-packages',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP',  '/usr/local/CyberCP']
Wed, 01 May 2024 06:28:52 +0000

**Comment by usmannasir** [comment]
Closing due to no proper method used to explain problem.
