### ISSUE TITLE
Aliyun Centos 8.5 fresh installation failed clAPVersion.split NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by snsnsjsn** [litespeedtech/cyberpanel#1270]
Hi, I am installing cyberpanel to centos 8.5 
uname -a
Linux Ali2C4G 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

[root@Ali2C4G cyberpanelinstall]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
[root@Ali2C4G cyberpanelinstall]# 

after installation there is error

`[05.26.2024_19-30-23] #########################################################################

[05.26.2024_19-30-23] Successfully ran: /usr/local/lsws/bin/lswsctrl restart.

[05.26.2024_19-30-23] #########################################################################

Traceback (most recent call last):
  File "install.py", line 2626, in <module>
    main()
  File "install.py", line 2507, in main
    mysqlhost, mysqldb, mysqluser, mysqlpassword, mysqlport)
  File "/root/cyberpanelinstall/cyberpanel/install/installCyberPanel.py", line 806, in Main
    installer.installMySQL(mysql)
  File "/root/cyberpanelinstall/cyberpanel/install/installCyberPanel.py", line 369, in installMySQL
    type = clAPVersion.split('-')[0]
AttributeError: 'NoneType' object has no attribute 'split'
Oops, something went wrong...`

**Comment by usmannasir** [comment]
Centos series is not supported anymore.

**Comment by Cerg1102** [comment]
Hi Usman, 

I have the same problem in Almalinux 8.9. 

<img width="682" alt="Captura de pantalla 2024-06-03 a las 12 47 30" src="https://github.com/usmannasir/cyberpanel/assets/63961798/9c28b1f3-5555-487b-b659-7d8e838ca990">

Regards

**Comment by fueledbybits** [comment]
Why this issue has been closed?
I am having same issue on Rocky Linux 8 and Alma Linux 9.
