### ISSUE TITLE
[BUG] python pygpgme is deprecated; should be removed from requirments.txt

### ISSUE THREAD

**Issue by micfogas** [litespeedtech/cyberpanel#1273]
**Describe the bug**
The `pygpgme` package for python has been deprecated for quite a few years and is no longer available to most OS's. It has been pulled from the PIP repo. 

AlmaLinux has never used pygpgme:
```

$ docker run -i -t almalinux:7 rpm -qa '*pygpgme*'
Unable to find image 'almalinux:7' locally
docker: Error response from daemon: manifest for almalinux:7 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
$ docker run -i -t almalinux:8 rpm -qa '*pygpgme*'
$ 
```

Rocky Linux has never used it:

```
$ docker run -i -t rockylinux:7 rpm -qa '*pygpgme*'
Unable to find image 'rockylinux:7' locally
docker: Error response from daemon: manifest for rockylinux:7 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
$ docker run -i -t rockylinux:8 rpm -qa '*pygpgme*'
$
```

CentOS hasn't used it since 7
```
$ docker run -i -t centos:7 rpm -qa '*pygpgme*'
pygpgme-0.3-9.el7.x86_64
$ docker run -i -t centos:8 rpm -qa '*pygpgme*'
$ 
```

To quote Stephan Guilloux from [this thread on GitLab](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/37366):

`Regarding RH-based distros, PYGPGME was used longtime back as a dependency for YUM (RH package manager), but is no more used, for a couple of years (see below for more info).`

**To Reproduce**
What steps did you take when the issue occurred? 
1. Run the install script. When the script downloads and processes `requirments.txt`, it fails on any EL-linux beyond CentOS 7 due to the requirement for the `pygpgme` package

**Expected behavior**
This can be resolved by removing the package `pygpgme` from the install script and possibly doing an:
```
echo "pygpgme" >> requirements.txt
``` 
For OSes that need it, or using sed to remove the line immediately following the downloading of requirments.txt for ($SERVER_OS == "CentOS8")

**Operating system:**
All that identify as SERVER_OS=="CentOS8"

**CyberPanel version:**
all

**Comment by usmannasir** [comment]
completed.
