### ISSUE TITLE
[BUG] Big SSL issue on 2.3.5

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1275]
Hello, on V2.3.5, Cloudflare SSL's aren't issued to the domains at all.
So all SSL's expire.
I am reverting back to 2.3.4, to see if the same issue happens there also.

![image](https://github.com/usmannasir/cyberpanel/assets/4199669/05e96a46-b0dc-42fd-a1cb-ccac1d08da47)

**Comment by master3395** [comment]
@usmannasir Any suggestions?
I have now tried downgrading to 2.3.4, but now I'm stuck with no SSL added at all.
Not Cloudflare not let's encrypt.

![image](https://github.com/usmannasir/cyberpanel/assets/4199669/df354815-41c0-4dfa-98c6-b6baf03ae3c2)

**Comment by master3395** [comment]
I just tried installing CyberPanel using Almalinux 9
I got this when i tried making a subdomain.

Error message: ["local variable 'finalConfPath' referenced before assignment. [404]"]

No SSL was added from cloudflare there either.
https://[test.newstargeted.com](https://test.newstargeted.com/)/

**Comment by shbs9** [comment]
Can you please do one thing disable Cloudflare SSL then issue SSL form the cyberpanel after clearing cache and enable the SSL again and let me know.

**Comment by master3395** [comment]
Sadly, disabling Cloudflare SSL didn't do anything.
I disabled it for both
[https://newstargeted.com](https://newstargeted.com/)/
and
https://webhook.newstargeted.com/

**Comment by master3395** [comment]
SSL issue is solved, thanks to @shbs9 :)
