### ISSUE TITLE
PHP switch version does not work.

### ISSUE THREAD

**Issue by hennaboy** [litespeedtech/cyberpanel#128]
Upon install cyberpanel and lsws appears to default to php 7.1

whilst the options are there to select php 5.x through to 7.3 it does not actually change the websites running php version. This is due to lsws requiring a server config external app only for the default 7.1

According to

https://openlitespeed.org/kb/setup-ols-with-more-than-one-php-build/

An external app is required for each php version that you would like to use.

I tested this by selecting php7.3 for my website and it remained at 7.1

I then created an external app in lsws admin for 7.3 and then went back to cyberpanel and changed the php version for the website to 7.3 and it changed php version.

**Comment by usmannasir** [comment]
https://forums.cyberpanel.net/discussion/1926/php-changes-has-no-effect-on-site-php

**Comment by usmannasir** [comment]
Fixed https://github.com/usmannasir/cyberpanel/commit/8582dfa6c266d0bfb7ff7c4a7ebbfa18ff687536
