### ISSUE TITLE
[BUG] Upgrade error - ModuleNotFoundError: No module named 'sleep'

### ISSUE THREAD

**Issue by SaJeTek-Developer** [litespeedtech/cyberpanel#1283]
**Describe the bug**
When running the CyberPanel upgrade script, the upgrade fails with *ModuleNotFoundError: No module named 'sleep'*
file: /root/cyberpanel_upgrade_tmp/upgrade.py
This is also found in cyberpanel/plogical/upgrade.py

**Expected behavior**
The line *import sleep" should be changed to "from time import sleep"

**Operating system:**
Almalinux 9
Python 3.9

**CyberPanel version:**
2.3.5

**Workaround**
A workaround for now is to manually edit /root/cyberpanel_upgrade_tmp/upgrade.py and change the line then make the file immutable and rerun the upgrade script.

**Comment by shbs9** [comment]
I just updated on Alama 9 server with a normal upgrade script all going well no issues at all.
![image](https://github.com/user-attachments/assets/1fb7524e-83f3-4470-96de-53c0456aa834)

**Comment by shbs9** [comment]
can you share more detials or open a ticket at the platform so we can check your server

**Comment by SaJeTek-Developer** [comment]
Hi,

I wasn't able to reproduce after trying the script again.
