### ISSUE TITLE
[REQUEST] Increase Character length

### ISSUE THREAD

**Issue by SaJeTek-Developer** [litespeedtech/cyberpanel#1285]
Can we have the image field of cyberpanel.dockerManager_containers increased to 64 from 50 since the name would include "docker.io/my-very-long-username/my-very-long-image-name".

50 would have been fine without the "docker.io" part

**Comment by usmannasir** [comment]
ok let me check

**Comment by usmannasir** [comment]
i change to 150 just in case.
