### ISSUE TITLE
[BUG] Docker Manager does not work in Cyberpanel on Almalinux 9

### ISSUE THREAD

**Issue by SaJeTek-Developer** [litespeedtech/cyberpanel#1287]
**Describe the bug**
On Almalinux 9, docker is now podman-docker which is headless. Cyberpanel docker manager is completely broken and only asks to install docker even if docker is already installed.

**Operating system:**
Almalinux 9

**CyberPanel version:**
2.3.5

Please note that since older php versions are not available in Almalinux 9, this feature is crucial when migrating from CentOS 7

**Comment by usmannasir** [comment]
checking

**Comment by usmannasir** [comment]
More stuff has also changed, i am working on this.

**Comment by usmannasir** [comment]
fixed.
