### ISSUE TITLE
[BUG] Bug during update.

### ISSUE THREAD

**Issue by lucasfurlan2** [litespeedtech/cyberpanel#1289]
After checking the new updates, I went to update my vps using the standard command

sudo su - -c "sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh)"

During update, it displays the following error
![Captura de tela 2024-07-20 021734](https://github.com/user-attachments/assets/58ab22bf-e019-4e85-9e76-391ed11c6fde)

Then the cyberpanel went offline.
Internal Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.10 (Cerulean Leopard)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.10 (Cerulean Leopard)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
SUPPORT_END=2029-06-01

**Comment by usmannasir** [comment]
I am closing it as this looks like a specific issue, please contact our support.
