### ISSUE TITLE
[BUG] almalinux 9 issues July 2024

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1290]
When installing Almalinux 9 CyberPanel, you get a warning about 

`./cyberpanel.sh: line 843: subscription-manager: command not found`

![Skjermbilde 2024-07-21 231756](https://github.com/user-attachments/assets/faf5e90e-ce80-427f-b677-df3edc2e39fb)

When creating sub-sites on a clean Almalinux 9 CyberPanel setup, it makes the sub.newstargeted.com
But then it gives an error on the CP creation page.
![Skjermbilde 2024-07-22 012215](https://github.com/user-attachments/assets/e4b2edd6-026c-450e-b034-e71cbc93a368)
Also in the open lite speed admin panel, it does not make the sub-sites under "Virtual Hosts" at all.

`/etc/os-release`
-bash: /etc/os-release: Permission denied

OS Release is Blocked on Almalinux 9.4

**Comment by shbs9** [comment]
I did the installation last day i didn't face any issue like this but let me reproduce and I will update here

**Comment by master3395** [comment]
Make sure to try with Cloudflare DNS enabled.
I forgot to try without it enabled.

**Comment by usmannasir** [comment]
@shbs9 can you reproduce this as I recently fixed some issues?

**Comment by shbs9** [comment]
installation on fresh Alama 9 is fine we.
creation of subdomain with and without proxy tested both are fine 
![image](https://github.com/user-attachments/assets/e8a04083-65e6-46bc-8c95-9c9ea955db7b)

**Comment by usmannasir** [comment]
I will close this issue as we can not reproduce.
