### ISSUE TITLE
[BUG] Apache PHP missing for Almalinux 9.x

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1294]
After i installed Almalinux9

```
NAME="AlmaLinux"
VERSION="9.4 (Seafoam Ocelot)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.4 (Seafoam Ocelot)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
SUPPORT_END=2032-06-01
```

https://IP:Port/managephp/editPHPConfigs?apache=apache
You see these two images:
![image](https://github.com/user-attachments/assets/6e0aa898-35b4-4d30-9f25-a2beea9326a4)
![image](https://github.com/user-attachments/assets/bb995f64-4f9f-418b-ad49-4c0171bd6280)

Also not sure why i can't use this command in Almalinux 9.
`/etc/os-release`
You get this error:
`-bash: /etc/os-release: Permission denied`

**Comment by master3395** [comment]
The remi isn't getting created.
![image](https://github.com/user-attachments/assets/8083da9e-430d-4d37-91b0-b052b7d61aac)

**Comment by master3395** [comment]
Normal php from Php 7.4 - 8.3 works, but Apache PHP extensions are not installed for some reason.

**Comment by master3395** [comment]
If i try to use the EmailDebugger in both Almalinux 8 and 9 it works fine the first time.
But if i try to go into the debugger a second time after it's done, i simply get an internal error 500.
It seems like it can only be done once.

**Comment by usmannasir** [comment]
https://rpms.remirepo.net/enterprise/9/safe/x86_64/repoview/

I think remi for Al8 have versions above 7.4 only.

**Comment by usmannasir** [comment]
Also `/etc/os-release` is file, you can't execute it, it should be `cat /etc/os-release`

**Comment by usmannasir** [comment]
I've fixed couple of bugs in branch `v2.3.5-alma9`. I don't see the issues reported by you there, please upgrade to that branch and check.

**Comment by master3395** [comment]
> I've fixed a couple of bugs in branch `v2.3.5-alma9`. I don't see the issues reported by you there, please upgrade to that branch and check.

Cool, i will try when I get home from work :)
Also correct, Almalinux 9 only has PHP 7.4 and up.
That is why PHP 8.0 is set as the core PHP in CyberPanel also.

**Comment by master3395** [comment]
A new issue came in `2.3.5-alma9`
I can't edit the user details of the admin account.

![image](https://github.com/user-attachments/assets/ec69b298-22f9-4a70-a767-e2b8d9c1319a)

Apache php files are not there either, i went to "Install PHP extensions", the apache extensions are not installed.
![image](https://github.com/user-attachments/assets/ea97b027-9caf-4ee1-8ac7-a143f67ac542)

**Comment by usmannasir** [comment]
upgrade and. try.

**Comment by usmannasir** [comment]
upgrade to same bracnh again and try please.

**Comment by master3395** [comment]
> upgrade to same bracnh again and try please.

Same error message after upgrade.

**Comment by master3395** [comment]
Also for some reason, when i install CyberPanel on the same IP, it doesn't detect "Premium".
Shoaib Khan fixed it once before, but the issue returned after i re-installed the server.
https://platform.cyberpersons.com/support/H9E6BR3EO/

![image](https://github.com/user-attachments/assets/8967f933-3f8e-4378-a7f1-b23becaa70b4)

**Comment by usmannasir** [comment]
pyotp is resolved for me, can you double check. I just confirmed.

**Comment by master3395** [comment]
> pyotp is resolved for me, can you double check. I just confirmed.

Same thing still :/
I cleared cookies, i tried in incognito mode after the upgrade also.
![image](https://github.com/user-attachments/assets/9ecbe469-e98c-4d7d-bff2-3e708beb2360)

**Comment by usmannasir** [comment]
Are you sure you are upgrading to v2.3.5-alma9 ?

**Comment by master3395** [comment]
Yeah.

I tried with both
[](sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh))

and the one below, but that one gave me an error.

[](bash <(curl https://cyberpanel.sh/new_upgrade.sh) -b 2.3.5-alma9)
![image](https://github.com/user-attachments/assets/f2d6abdb-e8f6-4718-bcdd-1d3afadf209c)

I also tried the internal upgrade, but that seems to give me an indication of being outdated.
![image](https://github.com/user-attachments/assets/e3446d3f-bcac-4e32-9635-ae27515b882e)

**Comment by usmannasir** [comment]
```
wget https://raw.githubusercontent.com/usmannasir/cyberpanel/v2.3.5-alma9/cyberpanel_upgrade.sh
chmod +x cyberpanel_upgrade.sh
./cyberpanel_upgrade.sh
```
input version when asked.

**Comment by master3395** [comment]
> ```
> wget https://raw.githubusercontent.com/usmannasir/cyberpanel/v2.3.5-alma9/cyberpanel_upgrade.sh
> chmod +x cyberpanel_upgrade.sh
> ./cyberpanel_upgrade.sh
> ```
> 
> input version when asked.

Now it is showing the modify user.

![image](https://github.com/user-attachments/assets/b8f04f4c-609e-4c6e-8c83-2f37a7a31320)
![image](https://github.com/user-attachments/assets/75da8180-0dfa-4e74-991b-0610f68a7abf)

```
Current Version:  2.3
Build:  5Current Commit:  b16953e29431877ac02a2d533d325dd3d62b146b
Latest Version:  2.3
Latest Build:  5Latest Commit:  f5008094520cce6524435c867f452de3915c993e
```

**Comment by usmannasir** [comment]
great

**Comment by usmannasir** [comment]
i will close this now.
