### ISSUE TITLE
[BUG] Wordpress Manager

### ISSUE THREAD

**Issue by Dimpappas1984** [litespeedtech/cyberpanel#1295]
Ubuntu 22.04
Cyberpanel v2.3.5

The wordpress manager says this error when the website has php8.3 :
Operation Failed!
local variable 'php' referenced before assignment

![microhost gr](https://github.com/user-attachments/assets/7abac28b-f419-4e0d-af85-8deba929263d)

**Comment by shbs9** [comment]
I am checking this for ubuntu 22 can you please share your server access with me on our support platform as well?

**Comment by Dimpappas1984** [comment]
Of course you can access to my server.
You can replicate this problem on any cyberpanel setup. Make a dummy site
and use php8.3 and you will see this on the wordpress manager addon.

Στις Κυρ 4 Αυγ 2024, 14:19 ο χρήστης Shoaib khan khattak <
***@***.***> έγραψε:

**Comment by shbs9** [comment]
Yes just reproduced this and checking more on it

**Comment by Dimpappas1984** [comment]
> Yes just reproduced this and checking more on it

Hi. Did you check this? Its not good to have php8.3 working great but the paid plugin failed.
Do you need something else to help you with this?

**Comment by shbs9** [comment]
We already checked this and soon it will be resolved.
