### ISSUE TITLE
[BUG] /dataBases/fetchDetailsPHPMYAdmin jump

### ISSUE THREAD

**Issue by hlshell** [litespeedtech/cyberpanel#1296]
The Chinese network uses cyberpanel phpmyadmin to execute /dataBases/fetchDetailsPHPMYAdmin jump. This
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
 is included in the jump, resulting in the inability to load and enter normally. phpmyadmin. It is recommended to use the server's local built-in rather than using external links.

**Comment by usmannasir** [comment]
@qtwrk can you check

**Comment by hlshell** [comment]
NEW [Issues](https://github.com/usmannasir/cyberpanel/issues/1326)
