### ISSUE TITLE
[BUG]AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsFramework' above command failed...

### ISSUE THREAD

**Issue by benyezza** [litespeedtech/cyberpanel#1301]
root@vmi1078111:~# cyberpanel_utility

Checking root privileges...

You are running as root...

Checking Cyberpanel Utility update...
/usr/local/CyberPanel/cyberpanel_utility.sh: No such file or directory
chmod: cannot access '/usr/local/CyberPanel/cyberpanel_utility.sh': No such file or directory
md5sum: /usr/local/CyberPanel/cyberpanel_utility.sh: No such file or directory
head: cannot open '/usr/local/CyberPanel/cyberpanel_utility.sh' for reading: No such file or directory

Failed to fetch server file...

Keep using local script...
System: Ubuntu 20 detected...

		CyberPanel Utility Tools (beta)

  1. Upgrade CyberPanel.

  2. Addons.

  3. WatchDog (beta)

  4. Frequently Asked Question (FAQ)

  5. Exit.

  
  Please enter the number[1-5]: 1

Checking server...
CyberPanel upgrading...

Fetching latest data from CyberPanel server...

This may take few seconds...

Checking root privileges...

You are running as root...

Checking server location...

System: Ubuntu 20 detected...

Press the Enter key to continue with latest version, or enter specific version such as: 1.9.4 , 1.9.5 ...etc

If nothing is input in 10 seconds, script will proceed with the latest stable version. 

Please press the Enter key or specify a version number, or wait for 10 seconds: 
Branch name set to v2.3.5
Hit:1 http://asi-fs-d.contabo.net/ubuntu focal InRelease
Hit:2 http://asi-fs-d.contabo.net/ubuntu focal-updates InRelease               
Hit:3 http://asi-fs-d.contabo.net/ubuntu focal-backports InRelease             
Hit:4 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease               
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease               
Ign:6 http://rpms.litespeedtech.com/debian focal InRelease                     
Hit:7 http://rpms.litespeedtech.com/debian focal Release
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  python3-appdirs python3-distlib python3-filelock python3-importlib-metadata
  python3-more-itertools python3-zipp
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
htop is already the newest version (2.2.0-2build1).
libattr1 is already the newest version (1:2.4.48-5).
libattr1-dev is already the newest version (1:2.4.48-5).
libpsl-dev is already the newest version (0.21.0-1ubuntu1).
librtmp-dev is already the newest version (2.4+20151223.gitfa8646d.1-2build1).
telnet is already the newest version (0.17-41.2build1).
git is already the newest version (1:2.25.1-1ubuntu3.13).
libcomerr2 is already the newest version (1.45.5-2ubuntu1.1).
libcurl4-gnutls-dev is already the newest version (7.68.0-1ubuntu2.23).
libgcrypt20-dev is already the newest version (1.8.5-5ubuntu1.1).
libgnutls28-dev is already the newest version (3.6.13-2ubuntu1.11).
libgpgme-dev is already the newest version (1.13.1-7ubuntu2.2).
libgssapi-krb5-2 is already the newest version (1.17-6ubuntu4.4).
libk5crypto3 is already the newest version (1.17-6ubuntu4.4).
libkrb5-dev is already the newest version (1.17-6ubuntu4.4).
libldap2-dev is already the newest version (2.4.49+dfsg-2ubuntu1.10).
liblzma-dev is already the newest version (5.2.4-1ubuntu1.1).
libnghttp2-dev is already the newest version (1.40.0-1ubuntu0.3).
libssl-dev is already the newest version (1.1.1f-1ubuntu2.23).
nettle-dev is already the newest version (3.5.1+really3.5.1-2ubuntu0.2).
dnsutils is already the newest version (1:9.18.28-0ubuntu0.20.04.1).
libmariadbclient-dev is already the newest version (1:10.3.39-0ubuntu0.20.04.2).
nghttp2 is already the newest version (1.40.0-1ubuntu0.3).
idn2 is already the newest version (2.3.0-1+ubuntu20.04.1+deb.sury.org+2).
libidn2-0-dev is already the newest version (2.3.0-1+ubuntu20.04.1+deb.sury.org+2).
libidn2-dev is already the newest version (2.3.0-1+ubuntu20.04.1+deb.sury.org+2).
The following additional packages will be installed:
  python3-virtualenv
The following NEW packages will be installed:
  python3-virtualenv virtualenv
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 64.8 kB of archives.
After this operation, 387 kB of additional disk space will be used.
Get:1 http://asi-fs-d.contabo.net/ubuntu focal-updates/universe amd64 python3-virtualenv all 20.0.17-1ubuntu0.4 [62.7 kB]
Get:2 http://asi-fs-d.contabo.net/ubuntu focal-updates/universe amd64 virtualenv all 20.0.17-1ubuntu0.4 [2,144 B]
Fetched 64.8 kB in 0s (3,211 kB/s)
debconf: unable to initialize frontend: Noninteracitve
debconf: (Can't locate Debconf/FrontEnd/Noninteracitve.pm in @INC (you may need to install the Debconf::FrontEnd::Noninteracitve module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at (eval 19) line 2, <> line 2.)
debconf: falling back to frontend: Noninteractive
Selecting previously unselected package python3-virtualenv.
(Reading database ... 157687 files and directories currently installed.)
Preparing to unpack .../python3-virtualenv_20.0.17-1ubuntu0.4_all.deb ...
Unpacking python3-virtualenv (20.0.17-1ubuntu0.4) ...
Selecting previously unselected package virtualenv.
Preparing to unpack .../virtualenv_20.0.17-1ubuntu0.4_all.deb ...
Unpacking virtualenv (20.0.17-1ubuntu0.4) ...
Setting up python3-virtualenv (20.0.17-1ubuntu0.4) ...
Setting up virtualenv (20.0.17-1ubuntu0.4) ...
Processing triggers for man-db (2.9.1-1) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi-dev is already the newest version (3.3-4).
python3-dev is already the newest version (3.8.2-0ubuntu2).
build-essential is already the newest version (12.8ubuntu1.1).
libssl-dev is already the newest version (1.1.1f-1ubuntu2.23).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-venv is already the newest version (3.8.2-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit:1 http://asi-fs-d.contabo.net/ubuntu focal InRelease
Hit:2 http://asi-fs-d.contabo.net/ubuntu focal-updates InRelease               
Hit:3 http://asi-fs-d.contabo.net/ubuntu focal-backports InRelease             
Hit:4 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease               
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease               
Ign:6 http://rpms.litespeedtech.com/debian focal InRelease                     
Hit:7 http://rpms.litespeedtech.com/debian focal Release
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
Get more security updates through Ubuntu Pro with 'esm-apps' enabled:
  libmagickcore-6.q16-6-extra node-hosted-git-info libopenexr-dev
  python2.7-minimal libmagickwand-6.q16-6 python2.7 libmagickwand-6-headers
  redis node-tar libmagickcore-6-headers redis-tools
  libmagickcore-6-arch-config libmagickwand-6.q16-dev node-ip libopenexr24
  libmagickcore-6.q16-6 libpython2.7-minimal libmagickwand-dev
  libpython2.7-stdlib redis-server libmagickcore-6.q16-dev
  imagemagick-6-common
Learn more about Ubuntu Pro at https://ubuntu.com/pro
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already up-to-date: virtualenv in /usr/local/lib/python3.8/dist-packages (20.26.3)
Requirement already satisfied, skipping upgrade: distlib<1,>=0.3.7 in /usr/local/lib/python3.8/dist-packages (from virtualenv) (0.3.8)
Requirement already satisfied, skipping upgrade: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.8/dist-packages (from virtualenv) (4.2.2)
Requirement already satisfied, skipping upgrade: filelock<4,>=3.12.2 in /usr/local/lib/python3.8/dist-packages (from virtualenv) (3.15.4)

Nothing found, need fresh setup...

AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsFramework'
above command failed...

**Comment by irfanMiral** [comment]
Temporary solution is using older version:

```shell
pip uninstall virtualenv
pip install virtualenv==20.23.0
```

**Comment by usmannasir** [comment]
```
wget https://raw.githubusercontent.com/usmannasir/cyberpanel/v2.3.5-alma9/cyberpanel_upgrade.sh
chmod +x cyberpanel_upgrade.sh
./cyberpanel_upgrade.sh
```
see if this resolves your issue?

**Comment by usmannasir** [comment]
Resolved with new update.
