### ISSUE TITLE
[BUG] Creating backup with Cyberpanel CLI

### ISSUE THREAD

**Issue by MrDariusz** [litespeedtech/cyberpanel#1311]
**Describe the bug**
When I create a backup using the Cyberpanel CLI - cyberpanel createBackup --domain "DOMAIN" - I get several errors:
```
/usr/local/CyberCP/lib/python3.10/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/usr/local/CyberCP/lib/python3.10/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
Backup logs to be generated in /usr/local/lscp/logs/backup_log.08.20.2024_03-00-44
```
Despite these errors, the backup is created correctly, but it would be good to fix this.

Additionally, the following errors appear:
```
[08.20.2024_03-00-44] 'NoneType' object is not iterable. [158:prepMeta]
[08.20.2024_03-00-44] Domains matching query does not exist.. [179:prepMeta]
```

This error occurs for every domain except the primary domain (the first one added as Create Website with DNS ZONE and MailServer). For generating a backup of the xyz.com domain, the problem does not occur, but for the subdomain.xyz.com, it occurs repeatedly, every time. Despite these errors, the backup is still created corretly, which is strange.

**To Reproduce**
What steps did you take when the issue occurred? 

cyberpanel createBackup --domain "xyz.com" (only TripleDES errors)
or
cyberpanel createBackup --domain "subdomain.xyz.com" (TripleDES  with prepMeta errors)

**Expected behavior**
I don't want to see these messages error.

**Screenshots**
Screenshots won't be needed, I think I've explained everything.

**Operating system:**
Ubuntu 22.04.4 LTS (Jammy Jellyfish)

**CyberPanel version:**
Cyberpanel v.2.3.6 (latest stable release) 

**Additional context**
https://github.com/paramiko/paramiko/issues/2426
https://community.cyberpanel.net/t/manual-backups-broken-after-first-scheduled-backup/36981

**Comment by usmannasir** [comment]
Fixed.
