### ISSUE TITLE
[BUG] Docker manager url regex mismatch

### ISSUE THREAD

**Issue by SaJeTek-Developer** [litespeedtech/cyberpanel#1312]
**Describe the bug**
In docker manager using the latest commit of 2.3.5 or 2.3.6 we are encountering a "Not Found" page when creating a container from an image. The issue is that when you reach the page to setup the container, we get a 404 Not Found error

**To Reproduce**
What steps did you take when the issue occurred? 
1. Ex.: Click on the "Docker Manager" which expands the dropdown and then click "Create New Container".
2. Ex.: Select the tag of the image you will be creating the container for and click "Create".
3. Ex.: This will take you to a url in the format of: https://localhost:8090/docker/runContainer/?image=imagename&tag=latest
3. Ex.: That page gives a Not Found error.

**Expected behavior**
We should be presented with the page which allows us to setup the container.

**Operating system:**
Almalinux 9.4

**CyberPanel version:**
2.3.5

**Additional context**
The issue seems to be due to the file: /usr/local/CyberCP/dockerManager/urls.py
`re_path(r'^runContainer$', views.runContainer, name='runContainer'),`

The line restricts the url path to regex "runContainer$" which does not match https://localhost:8090/docker/runContainer/?image=imagename&tag=latest

**Comment by usmannasir** [comment]
This issue is resolved now. thanks
