### ISSUE TITLE
[BUG] module 're' has no attribute 'Pattern'

### ISSUE THREAD

**Issue by sonmezcem** [litespeedtech/cyberpanel#1316]
**Describe the bug**
Clean installation does not run at all. I have tried upgrade several times but no chance to work it all. 

**To Reproduce**
What steps did you take when the issue occurred? 
1. Installed the CyberPanel as described.
2. Loaded the CyberPanel by a browser
3. Received "Internal Server Error" --- "The server encountered an unexpected condition which prevented it from fulfilling the request."

**Expected behavior**
Load the control panel's login page

**Screenshots**
![image](https://github.com/user-attachments/assets/e2c9008a-4841-44f8-960f-691dde7816b8)

**Operating system:**
AlmaLinux release 8.10 (Cerulean Leopard)

**CyberPanel version:**
2.3.6

**Additional information**
CyberPanel works on behind the HAProxy. There are other 2 CyberPanel installation behind the HAProxy which work without issue.

**Comment by usmannasir** [comment]
I can not reproduce on alma8. If you have some custom settings please contact our support.

**Comment by shbs9** [comment]
I just installed and then also tested after upgrade I can't reproduce this issue as well.
