### ISSUE TITLE
[BUG] API: PHP version cannot be set in createWebsite

### ISSUE THREAD

**Issue by iqqmuT** [litespeedtech/cyberpanel#1329]
**Describe the bug**
PHP version cannot be defined in the `createWebsite` API request.

**To Reproduce**
1. Use `/api/createWebsite` API endpoint
2. Website is created with default PHP version

**Expected behavior**
I want to configure PHP version for the new website in my request.

**Operating system:**
Ubuntu 22.04 LTS

**CyberPanel version:**
2.3

**Additional context**
`PHP 7.4` is hard-coded: https://github.com/usmannasir/cyberpanel/blob/stable/websiteFunctions/website.py#L4553

**Comment by usmannasir** [comment]
fixed
