### ISSUE TITLE
[BUG] Unable to create new sites

### ISSUE THREAD

**Issue by aljailane** [litespeedtech/cyberpanel#1330]
I cannot create new domains or websites, especially after the update that restores the csf. Since I updated the branch, I have not been able to create any new website. There are also those who talked about it, and there is no fix yet. For your information, it also caused the disappearance of the SSL certificate identification.

[https://www.facebook.com/share/p/7qp2w74bwbfexSEK/](url)
Cyberpanel Ver:  2.3.7
Os:  22.04 Ubuntu 
![FB_IMG_1728061725694](https://github.com/user-attachments/assets/a7874381-a124-40c2-a259-fe63c464ac2a)
![FB_IMG_1728061719090](https://github.com/user-attachments/assets/de5be3da-1d56-42d8-b5ff-02e08da6cee7)

**Comment by usmannasir** [comment]
Please write to our support regarding this at : help@cyberpanel.net
