### ISSUE TITLE
[BUG] Almalinux 9 php 8.4 not working

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1333]
When i try to choose 8.4 for the main domain and sub domains, all i get is PHP 7.4-8.4 on Almalinux 9
![image](https://github.com/user-attachments/assets/c5c7f20e-7c42-4d52-97c0-639fe2a84983)

**Comment by usmannasir** [comment]
I didn't understand?

**Comment by master3395** [comment]
The php extension is installed.
But the domain and sub domain PHP changer only show PHP 8.3
The same when you create a new domain or sub-domain, it will only show 8.3

**Comment by Akrobs** [comment]
> The php extension is installed. But the domain and sub domain PHP changer only show PHP 8.3 The same when you create a new domain or sub-domain, it will only show 8.3

Cyberpanel uses lsphp and openlitespeed, and this is lsphp, there are no compiled PHP8.4 packages in the OLS repositories.
It's not a bug of Cyberpanel.

**Comment by usmannasir** [comment]
True @Akrobs 

And if you use Apache Manager, and convert your site from OLS to Apache you can see PHP 8.4.
