### ISSUE TITLE
[BUG] Almalinux 9 mail domain creation on domain creation

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1334]
When creating "newstargeted.com" i clicked "Create Mail Domain".
But it didn't create the mail domain in the domain itself as a subdomain or in the list website page.
But if i now try to create mail.newstargeted.com as a sub-domain it tells me that it already exists.
It did indeed make the Cloudflare DNS and the folder "mail.newstargeted.com" within the domain, but it refuses to show up on the subdomain list.

Also because it was created with the domain, i cannot delete it, and create the subdomain myself.
Because now it will say `Error message: ["This domain already exists as a child domain. [404]"]`

![image](https://github.com/user-attachments/assets/721579a5-ee78-4b8c-805f-a7a4f693323e)

But it isn't on the domain list.

![image](https://github.com/user-attachments/assets/9bc988f1-4076-4b14-854f-903682e5e545)

**Comment by usmannasir** [comment]
Looong time ago this mail was hidden as it was confusing users but it is created in the backend.

Also: now you can also login to mail client using the main domain (from new version for newly created domains).
