### ISSUE TITLE
[BUG] Risk of deletion of all sites when admin user is deleted

### ISSUE THREAD

**Issue by iqqmuT** [litespeedtech/cyberpanel#1337]
**Describe the bug**
Looking at the source, it seems that when admin user is deleted, there is a risk that all websites are deleted as well (when `force` is enabled).

**To Reproduce**
1. Create a new user with admin ACL
1. Delete user with admin ACL

**Expected behavior**
Not all sites are deleted.

**Operating system:**
Ubuntu 22.04 LTS

**CyberPanel version:**
2.3

**Additional context**
Related to #1336 

`submitUserDeletion()` gets list of websites to be deleted by calling `ACLManager.findAllSites()`. If `userInQuestion` is admin, all websites are returned. However, this code is executed only when `force` is enabled. In which case `force` is enabled?

https://github.com/usmannasir/cyberpanel/blob/b63d30af650eadad70929f49ac10360f5f2ca454/userManagment/views.py#L459-L467

**Comment by usmannasir** [comment]
Value of force is for you to decide? https://github.com/usmannasir/cyberpanel/blob/b63d30af650eadad70929f49ac10360f5f2ca454/userManagment/views.py#L447

**Comment by usmannasir** [comment]
Will close for no answer.
