### ISSUE TITLE
Cyberpanel not installing on Ubuntu 22.04- unknown host - network is down issue

### ISSUE THREAD

**Issue by charliezxy** [litespeedtech/cyberpanel#1338]
Hello,

I am trying to install cyberpanel on my new dedicated server. I've tried many times and followed the guidelines as closely as possible but unfortunately everytime it ends with the same error.

The error is same everytime: **"Unknown host, network is down"**

Cloning into 'cyberpanel'...
remote: Enumerating objects: 35087, done.
remote: Counting objects: 100% (484/484), done.
remote: Compressing objects: 100% (244/244), done.
remote: Total 35087 (delta 287), reused 391 (delta 223), pack-reused 34603 (from 1)
Receiving objects: 100% (35087/35087), 449.12 MiB | 15.75 MiB/s, done.
Resolving deltas: 100% (23306/23306), done.
Updating files: 100% (4456/4456), done.

CyberPanel source code downloaded...

Branch 'v2.3.7' set up to track remote branch 'v2.3.7' from 'origin'.
Switched to a new branch 'v2.3.7'
/root
ping: unknown host

The network is down.. :(

![errors](https://github.com/user-attachments/assets/5990dccc-3bb7-45cc-95e3-2c989a8b4cad)

Could you please advice, Thanks!

**Comment by usmannasir** [comment]
This must be temporarily only, just installed on Ubuntu 22 and Alma9.

**Comment by charliezxy** [comment]
No, It's not working for some reason. I have been trying this for 3-4 days. For some reason, cyberpanel.sh is not able to detect my server IP on line number 204.  Because error log said - _Can not detect IP. [404]_

So I hardcoded my server IP there and removed that curl command to fetch IP on line 204 - Check_Server_IP() function.

After that, the installation went get past that unknown host - network down error. And after 20 minutes it indeed said successful.

But now after the installation, when I visit port 8090 of my server, it says 503 error. 

It's still a progress. but I am clueless. Errors log suggest that there is some problem in virtual hosts, but I am not sure what exactly. 

Secondly, is it mandatory to add A or TXT records to a domain and connect that domain to my server for cyberpanel to install and work perfectly? As of now, I just have a root server from netcup and there is only IP address. I am not thinking to add my domain yet. I was thinking first to install cyberpanel and then add domains from there.
