### ISSUE TITLE
[BUG] PHPMyadmin error message

### ISSUE THREAD

**Issue by Sharp35** [litespeedtech/cyberpanel#1351]
PHPMyadmin not opening
{"error_message": "Error: Expecting value: line 1 column 1 (char 0)", "errorMessage": "Error: Expecting value: line 1 column 1 (char 0)"}

**Operating system:**
Ubuntu 22.04 LTS

**CyberPanel version:**
2.3.8 ba0831f6266538cfd0112db79c3f0d81bcc2301a

**Comment by nurissetiabudi** [comment]
I also experienced the same thing

**Comment by Sharp35** [comment]
Fixed in commit 2041deae130d26d7aeab6e1c94ec32e752b0b138 thanks
