### ISSUE TITLE
[BUG] Schedule Backup Fails on CyberPanel 2.3.8 - AlmaLinux 9

### ISSUE THREAD

**Issue by nurissetiabudi** [litespeedtech/cyberpanel#1352]
**Describe the bug**
I’ve been experiencing an issue with the Schedule Backup feature in CyberPanel for over a week. The daily backup, which previously worked without issues, now fails consistently. The error log shows “backup failed” without further details.

**Environment**
Operating System: AlmaLinux 9
CyberPanel Version: 2.3.8

**To Reproduce**
1. Set up a scheduled daily backup task on CyberPanel 2.3.8.
2. Wait for the scheduled time to pass.
3. Check the backup logs for error messages.

**Expected behavior**
The scheduled backup should complete successfully without errors, as it did previously.

**Actual Behavior**
The backup consistently fails with the error "backup failed" in the logs.

**Additional Information**
The backup functionality was working fine until about a week ago. There have been no changes made to the system setup or configuration since then. Please let me know if any further information is required for troubleshooting.

**Screenshots**
![Screenshot 2024-11-03 081308](https://github.com/user-attachments/assets/3ff69380-4de3-40c9-af0d-be03f7966d96)

**Comment by diaa-q-tech** [comment]
a similar issue was reported here 
https://community.cyberpanel.net/t/automatic-backup-not-working-after-cyberpanel-update/56365

@usmannasir could you please help?

**Comment by shbs9** [comment]
@diaa-q-tech @nurissetiabudi i checked the backups now and I cant see any issue in this if you can provide me access or details I can check for you.

**Comment by diaa-q-tech** [comment]
Thanks @shbs9 
after I upgraded to the latest changes yesterday, the issue was resolved.

**Comment by nurissetiabudi** [comment]
ok thank you very much, my scheduled backup problem is solved.

Maybe there is a small BUG in the cyberpanel BACKUP SCHEDULE, namely I can't click ADD ALL to input all websites at once, when I click it nothing happens and none of the websites I own are inputted in the BACKUP SCHEDULE, so I have to ADD them one by one
