### ISSUE TITLE
[BUG] CSF config file resets to default on cyberpanel upgrade

### ISSUE THREAD

**Issue by ImLuke954** [litespeedtech/cyberpanel#1353]
**Describe the bug**
/etc/csf/csf.conf file resets to default on upgrading cyberpanel. Any modification we make to the config file gets erased. For example if we block port 7080, 8090 and run the cyberpanel upgrade, it automatically opens port 7080, 8090. If we add an IP to csf allow list, after upgrade it gets deleted from allow list.

**To Reproduce**
What steps did you take when the issue occurred? 
1. Remove port 7080, 8090 from open ports in etc/csf/csf.conf. 
2. Add any IP to etc/csf/csf.allow list
3. Run Cyberpanel upgrade
4. The ports get opened again. 
5. CSF allow list gets blank again.

**Expected behavior**
CSF config files should not be modified on cyberpanel upgrade.

**Operating system:**
 Ubuntu 22.04 LTS

**CyberPanel version:**
2.3.8

**Comment by vpsinghbaghel** [comment]
Yes, this is true. After upgrade it's not preserving the configuration file. 
After upgrade the config file by default doesn't allow 465 port in TCP_OUT
So, we faced websites not able to send mails using SMTP where 465 port is configured.
We had to manually allow the port in TCP_OUT.

**Comment by ImLuke954** [comment]
All modifications in config file gets wiped out. We have to re-do all modifications after every upgrade.

**Comment by Wanabo** [comment]
Same here! All customized settings where gone! I customized the firewall to allow only myself as the one and only user.  Result was that a user/pass was for the grab for everyone. (Changed password of course)
To prevent this from happening again I did a chattr +i on these files. (They where all defaulted by the upgrade)
![image](https://github.com/user-attachments/assets/faa3731e-168a-40e2-b5ec-ac7baf03e854)

**Comment by n0i2** [comment]
> Same here! All customized settings where gone! I customized the firewall to allow only myself as the one and only user. Result was that a user/pass was for the grab for everyone. (Changed password of course) To prevent this from happening again I did a chattr +i on these files. (They where all defaulted by the upgrade) ![image](https://private-user-images.githubusercontent.com/13087022/386577012-faa3731e-168a-40e2-b5ec-ac7baf03e854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzE1MDMsIm5iZiI6MTczMTY3MTIwMywicGF0aCI6Ii8xMzA4NzAyMi8zODY1NzcwMTItZmFhMzczMWUtMTY4YS00MGUyLWI1ZWMtYWM3YmFmMDNlODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDExNDY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMGQzNzg1MDk0Y2UwZDU3MWNkMWE2MDhjZjlkMWMwNjg3MTQ2OThjMWM3NWU3ZWVlZmRhNGYwNDJjOWVkM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qmRISuB7NTpdMu3KVtss2104wjh0Po2BnatUv-9kUhk)

Thank you for this workaround! In case someone can't use `chattr` you can keep your config files somewhere safe and copy them back to `/etc/csf` after each update until the issue is fixed.

**Comment by Wanabo** [comment]
Also modsecurity is removed. (Actually not sure about that.)
But why are my other servers (with an other panel) using OWASP CRS ver.4.5.0 and Cyberpanel is using OWASP ModSecurity Core Rule Set ver.3.3.2?

**Comment by pfncl** [comment]
Can someone from Cyberpanel comment on this? @usmannasir

**Comment by usmannasir** [comment]
This problem started happening after we upgraded our Django version. CSF have not updated the code we had to made some hacks which resets the custom configurations.

**Comment by netzencatura** [comment]
> This problem started happening after we upgraded our Django version. CSF have not updated the code we had to made some hacks which resets the custom configurations.

Maybe an option to backup and restore CFS settings could be added to the upgrade script? Possibly other files as well? In my case, and I'm not alone, if I use Cloudflare, I always need to also edit "/usr/local/CyberCP/secMiddleware.py" So I made a small script for my own backup.

nano /root/cyberpanel_upgrade.sh

#!/bin/bash

# Directory for backups
BACKUP_DIR="/root/csf_backups"
mkdir -p "$BACKUP_DIR"

# List of files to backup/restore
FILES=(
    "/etc/csf/csf.allow"
    "/etc/csf/csf.deny"
    "/etc/csf/csf.conf"
    "/etc/csf/csf.ignore"
    "/etc/csf/csf.rignore"
    "/etc/csf/csf.blocklists"
    "/etc/csf/csf.dyndns"
    "/usr/local/CyberCP/CyberCP/secMiddleware.py"
)

# Backup function
do_backup() {
    echo "Starting backup..."
    for file in "${FILES[@]}"; do
        if [ -f "$file" ]; then
            cp "$file" "$BACKUP_DIR/$(basename "$file")"
            echo "Backed up: $file"
        else
            echo "File does not exist: $file"
        fi
    done
    echo "Backup completed to: $BACKUP_DIR"
}

# Restore function
do_restore() {
    echo "Starting restore..."
    for file in "${FILES[@]}"; do
        backup_file="$BACKUP_DIR/$(basename "$file")"
        if [ -f "$backup_file" ]; then
            cp "$backup_file" "$file"
            echo "Restored: $file"
        else
            echo "Backup does not exist: $backup_file"
        fi
    done
    
    echo "Restarting CSF..."
    csf -r
    
    echo "Restarting LSCPD..."
    systemctl restart lscpd
    
    echo "Restore completed"
}

# Main process
echo "=== Starting CyberPanel upgrade process ==="

# 1. Backup
echo "Step 1: Backing up configuration files"
do_backup

# 2. Start upgrade
echo "Step 2: Starting CyberPanel upgrade"
sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh) > /var/log/cyberpanel_upgrade.log 2>&1 &
UPGRADE_PID=$!

# 3. Wait for upgrade completion
echo "Step 3: Waiting for upgrade to complete..."
echo "Upgrade is running in background. You can check progress with: tail -f /var/log/cyberpanel_upgrade.log"

while ps -p $UPGRADE_PID > /dev/null || pgrep -f "cyberpanel.*upgrade" > /dev/null; do
    if ! ps -p $UPGRADE_PID > /dev/null && [ $? -ne 0 ]; then
        echo "Warning: Main upgrade process ended, checking for child processes..."
    fi
    echo "Upgrade still running... checking again in 60 seconds"
    sleep 60
done

# Check if upgrade completed successfully
if grep -i "error\|failed" /var/log/cyberpanel_upgrade.log; then
    echo "WARNING: Possible errors found in upgrade log. Please check /var/log/cyberpanel_upgrade.log"
    read -p "Do you want to continue with restore? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborting restore. Please check logs and run restore manually if needed."
        exit 1
    fi
fi

# 4. Restore
echo "Step 4: Upgrade complete, restoring configuration"
sleep 10  # Wait additional 10 seconds just to be safe
do_restore

echo "=== CyberPanel upgrade process completed ==="

chmod +x /root/cyberpanel_upgrade.sh

./cyberpanel_upgrade.sh

@usmannasir

**Comment by usmannasir** [comment]
this is patched.

**Comment by Wanabo** [comment]
Please add csf.dyndns to # List of files to backup. 
I have a dynamic ip at home and need the csf.dyndns to have SSH root access, because I don't allow SSH access other than my home ip in the firewall.
Don't know if other people use a similar setup, but it kept my servers free from SSH attacks for 25 years now.

**Comment by usmannasir** [comment]
added

**Comment by Wanabo** [comment]
@usmannasir 
Upgrading today did not go well on AlmaLinux 9. For your information:
```shell
Traceback (most recent call last):
  File "/root/cyberpanel_upgrade_tmp/upgrade.py", line 3983, in <module>
    main()
  File "/root/cyberpanel_upgrade_tmp/upgrade.py", line 3979, in main
    Upgrade.upgrade(args.branch)
  File "/root/cyberpanel_upgrade_tmp/upgrade.py", line 3500, in upgrade
    Upgrade.UpdateConfigOfCustomACL()
  File "/root/cyberpanel_upgrade_tmp/upgrade.py", line 3059, in UpdateConfigOfCustomACL
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 16, in setup
    from django.urls import set_script_prefix
  File "/usr/local/lib/python3.9/site-packages/django/urls/__init__.py", line 1, in <module>
    from .base import (
  File "/usr/local/lib/python3.9/site-packages/django/urls/base.py", line 9, in <module>
    from .exceptions import NoReverseMatch, Resolver404
  File "/usr/local/lib/python3.9/site-packages/django/urls/exceptions.py", line 1, in <module>
    from django.http import Http404
  File "/usr/local/lib/python3.9/site-packages/django/http/__init__.py", line 5, in <module>
    from django.http.response import (
  File "/usr/local/lib/python3.9/site-packages/django/http/response.py", line 15, in <module>
    from django.core.serializers.json import DjangoJSONEncoder
  File "/usr/local/lib/python3.9/site-packages/django/core/serializers/__init__.py", line 23, in <module>
    from django.core.serializers.base import SerializerDoesNotExist
  File "/usr/local/lib/python3.9/site-packages/django/core/serializers/base.py", line 7, in <module>
    from django.db import models
  File "/usr/local/lib/python3.9/site-packages/django/db/models/__init__.py", line 20, in <module>
    from django.db.models.fields.files import FileField, ImageField
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/files.py", line 8, in <module>
    from django.core.files.storage import Storage, default_storage
  File "/usr/local/lib/python3.9/site-packages/django/core/files/storage/__init__.py", line 3, in <module>
    from django.conf import DEFAULT_STORAGE_ALIAS, settings
ImportError: cannot import name 'DEFAULT_STORAGE_ALIAS' from 'django.conf' (/usr/local/lib/python3.9/site-packages/django/conf/__init__.py)
above command failed...

``` 
Used this: sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh)

Edit: Update, can not log in to cyberpanel anymore. Litespeed admin works.
On server ip I get this:
![image](https://github.com/user-attachments/assets/d9419917-c12d-4f75-9d9e-4dd31806f531)

On hostname I get this (three dots):
![image](https://github.com/user-attachments/assets/84218ac7-31e7-4e42-95bb-3b580359b6be)
