### ISSUE TITLE
[BUG] Firewall settings are not saved.

### ISSUE THREAD

**Issue by redquantum** [litespeedtech/cyberpanel#1358]
Hello,

Even though I changed the firewall ports, when I press the Change button, a black screen appears and there is no change. Even though I waited for a while for an answer, the result does not change. The black screen waits. When I go back to the firewall tab from the panel, I see that the new settings are not applied.

Thank you

**Comment by usmannasir** [comment]
firewalld or csf?

**Comment by AchrafBaznani** [comment]
csf

**Comment by redquantum** [comment]
hi, after you asked this question, I upgraded the panel again and the problem seems to be fixed on the firewall side. I have not tested the csf side. before, when I wanted to enter the firewall, a comprehensive panel like the csf panel would open. with the last update, the firewall screen comes directly and the settings seem normal. I have not activated and tested csf. 

Thank you.
