### ISSUE TITLE
[BUG] Can't upgrade control panel

### ISSUE THREAD

**Issue by itspasindu** [litespeedtech/cyberpanel#1361]
root@vps-07582bf4:/#   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   396  100   396    0     0   4632      0 --:--:-- --:--:-- --:--:--  4604
curl: (23) Failed writing body
--2024-11-15 01:56:13--  https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8001::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 396 [text/plain]
Saving to: ‘STDOUT’

-                                                 0%[                                                                                                     ]       0  --.-KB/s    in 0s

Cannot write to ‘-’ (Success).

**Comment by Lvl4Sword** [comment]
https://cyberpanel.net/version.txt currently gives 2.3 for the version, and this tag doesn't exist on Github right now: https://github.com/usmannasir/cyberpanel/tags

So, that's the problem right now. @usmannasir can fix this easily, though.

**Comment by usmannasir** [comment]
It gives v2.3.8 and its there,

**Comment by itspasindu** [comment]
> It gives v2.3.8 and its there,

How to update correctly?

**Comment by usmannasir** [comment]
Using: https://cyberpanel.net/KnowledgeBase/home/upgrade-cyberpanel/

**Comment by itspasindu** [comment]
> Using: https://cyberpanel.net/KnowledgeBase/home/upgrade-cyberpanel/

After your data breach my VPS got crashed and I can't login to VPS now. I can reinstall my VPS but how i get my old cyberpanel back.

**Comment by usmannasir** [comment]
For that you can write to our team at: help@cyberpanel.net, they will help you solve the issue.
