### ISSUE TITLE
[BUG] Github Webhook not working.

### ISSUE THREAD

**Issue by nabeelalihashmi** [litespeedtech/cyberpanel#1362]
Webhook is not working and it is required to manually press "Pull" in Manage Git section.

**Expected behavior**
Have webhook fired and changes pushed in repo must be pushed to server via webhook. 

**Operating system:**
AlmaLinux 9

**CyberPanel version:**
2.3.8 
848c47b35320c8ad33bba9ab21d35083706ba983

**Additional context**
When sending request from REST client with headers and body, this is the response displayed. 
```
{
  "error_message": "Error: 'dict' object has no attribute 'find'",
  "errorMessage": "Error: 'dict' object has no attribute 'find'"
}
```
Also, port is changed from 8090 to other. it was working correctly. it just recently got malfunctioned.

**Comment by usmannasir** [comment]
I am checking this.

**Comment by usmannasir** [comment]
Did you select json as delivery method? Because I've just tested and it is working fine.

```
{"status": 0, "error_message": "Pull not required.", "commandStatus": "Already up to date.\n"}
```

**Comment by sebacs2** [comment]
I have the same problem:
Content type application/json set

{"error_message": "Error: object 'dict' has no attribute 'find'", "errorMessage": "Error: object 'dict' has no attribute 'find'"}

It used to work fine for me, I think the last update broke it

**Comment by eplt** [comment]
I have updated to the latest build. 2.3.9 (68832c4820fac37db14bb7a4d183c411c5510c19)

And still getting the same error as others above.

{"error_message": "Error: 'dict' object has no attribute 'find'", "errorMessage": "Error: 'dict' object has no attribute 'find'"}

**Comment by eplt** [comment]
@usmannasir can we re-open this ticket? happy to help out to debug this issue.

**Comment by usmannasir** [comment]
Yes please write to help@cyberpanel.net

Mention this git issue, will try to reproduce on your server.

**Comment by Skopea** [comment]
I also still have this issue, any solutions found?
