### ISSUE TITLE
[BUG] CSF Upgrade Issue

### ISSUE THREAD

**Issue by abdulrehman-mr** [litespeedtech/cyberpanel#1363]
Minor Issue:
Upon Upgrading the CyberPanel it reset the ports opened previously in the csf. Inbound , Outbound.

**Comment by dcasters** [comment]
> Minor Issue:
> 
> Upon Upgrading the CyberPanel it reset the ports opened previously in the csf. Inbound , Outbound.

Yes still bugs

**Comment by redquantum** [comment]
Are you having problems registering after setting the port settings? I see that the current changes are not applied. Firewall is not set on my server.

**Comment by usmannasir** [comment]
Fixed with recent commit.
