### ISSUE TITLE
[BUG] Creating sub-domains don't create DNS records

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#1365]
In version 2.3.8, creating sub-domains don't add the DNS records to the DNS Zone.
So it won't get auto sent to CloudFlare.
OS: Almalinux 8.10

**Comment by usmannasir** [comment]
I've just created a subdomain and record was added.

**Comment by master3395** [comment]
I'll soon re-install the whole VPS, perhaps that will solve the issue.
