### ISSUE TITLE
CyberPanel version at Login Page

### ISSUE THREAD

**Issue by Tangol** [litespeedtech/cyberpanel#141]
Please note that @spyngamerman's fix https://github.com/usmannasir/cyberpanel/pull/132 , wasn't pushed to the [main branch](https://github.com/usmannasir/cyberpanel/blob/1.8.0/loginSystem/templates/loginSystem/login.html#L70).

Also, the current version is **1.9.0** (soon 1.9.1), but the dev branch is still 1.8.0 which is kinda confusing.
![cyber](https://user-images.githubusercontent.com/3336728/66836769-9b255e00-ef6a-11e9-98ef-a8e8e0d3f7ca.jpg)

And besides this, v1.9.0 doesn't even appear in the releases section: https://github.com/usmannasir/cyberpanel/releases
As such, the GitHub repo needs to get cleaned up and become more organised (maybe with a stable **master** branch and a **dev** one where all the testing is done).

Thanks!

**Comment by meramsey** [comment]
that fix did not work, unfortunately. which is why it got omitted

I tried to declare it so it would be accessible on the login page but it fails to load. Tried with all the same stuff i seen working in versionManagement page but no dice.


views.py
```
from .models import version

def loginVersion(request):
    try:
        
        vers = version.objects.get(pk=1)
        getVersion = requests.get('https://cyberpanel.net/version.txt')
        latest = getVersion.json()
        latestVersion = latest['version']
        latestBuild = latest['build']
        return render(request, 'loginSystem/login.html', {'build': vers.build,
                                                                      'currentVersion': vers.currentVersion,
                                                                      'latestVersion': latestVersion,
                                                                      'latestBuild': latestBuild})
```
login.html
```
{% load i18n %}

{{ currentVersion }}
```

models.py
```
class version(models.Model):
    currentVersion = models.CharField(max_length=50)
    build = models.IntegerField()

```

**Comment by spyngamerman** [comment]
```from .models import versiondef loginVersion(request):    try:                vers = version.objects.get(pk=1)        getVersion = requests.get('https://cyberpanel.net/version.txt')        latest = getVersion.json()        latestVersion = latest['version']        latestBuild = latest['build']        return render(request, 'loginSystem/login.html', {'build': vers.build,                                                                      'currentVersion': vers.currentVersion,                                                                      'latestVersion': latestVersion,                                                                      'latestBuild': latestBuild})```

**Comment by hennaboy** [comment]
Showing version numbers at login pages is a bad idea. It's against standard PCI compliance as a version number can be bot searched for and any vulnerabilities taken advantage of.

**Comment by Tangol** [comment]
I agree with @hennaboy on this one.
There's really no point in showing the version on the login page, and also it looks bad on mobile.
![Screenshot_20200216_140108_com android chrome](https://user-images.githubusercontent.com/3336728/74613267-6b06eb00-5115-11ea-89c0-2300e6237282.jpg)

**So I would remove it altogether.**

**Comment by jordanlambrecht** [comment]
Hi @Tangol @hennaboy. It's been a while since this was posted. If you think that removing the version number from the login page is the best way to go, please consider creating a pull request so the devs can focus on larger issues. I happen to agree with you from both a security and maintenance standpoint, but a greater case could be made if you could find and cite the aforementioned PCI compliance guideline. I tried to find it for you, but a quick google search did me no good.

**Comment by istiak101** [comment]
Upcoming versions will no longer show any version details on login page.
