### ISSUE TITLE
change user profile photo does not work

### ISSUE THREAD

**Issue by spirogg** [litespeedtech/cyberpanel#149]
version 1.9 build 1 cyberpanel litespeed ent edition 

CentOS 7 VPS
windows 10 latest version of chrome browser

when trying to change the user profile image it doesn't work

![Capture](https://user-images.githubusercontent.com/17736688/67569289-1538ae00-f6f4-11e9-830b-ca50050f433b.PNG)

**Comment by istiak101** [comment]
That feature will be made in the future

**Comment by APPSARA** [comment]
when in future, do you have any idea?

**Comment by istiak101** [comment]
This was removed for redundancy from top nav. So it's no longer a valid issue thus I am closing this. If this feature is still wanted please create it here https://feedback.cyberpanel.net
