### ISSUE TITLE
Incremental Backups to "Local" destination need to exclude the local backup folders

### ISSUE THREAD

**Issue by gabrielcossette** [litespeedtech/cyberpanel#151]
It seems the new Incremental Backups function, when used with the "Local" destination, includes the local backup folders of the website:

/home/WEBSITE_DOMAIN/incbackup
/home/WEBSITE_DOMAIN/backup

Therefore, each backup is even bigger than a regular full backup (because it includes at least the whole restic repository). The two folders need to be excluded.

Thanks for your hard work on this project!

**Comment by usmannasir** [comment]
Sorry, my bad. Excluded now https://github.com/usmannasir/cyberpanel/commit/71c97e0631af38c6cd4376b3eef1233970ff5c9f
