### ISSUE TITLE
DNS: Add/Delete domain alias and other extra dns

### ISSUE THREAD

**Issue by ecreality** [litespeedtech/cyberpanel#154]
I dont know if a bug or an logical error. I can only manage records for websites.

In dnsManager.py
deleteDNSZone have
domainsList = ACLManager.findAllDomains(currentACL, userID)
addDeleteDNSRecords have
domainsList = ACLManager.findAllWebsites(currentACL, userID)

I believe domainsList in addDelete have to be the same than in delete, and this is a bug

**Comment by istiak101** [comment]
Fixed in this commit. 
https://github.com/usmannasir/cyberpanel/commit/73bb9da0b9292e3619d0086d4e0774bae763e0bc
@usmannasir please close this.

**Comment by jordanlambrecht** [comment]
@creativequality Would you mind closing this issue since it has been fixed?

**Comment by ecreality** [comment]
Sorry, I forgot it.
Closing now.
Thanks.
