### ISSUE TITLE
[1.9] [Feature] List sites in alphabetical order

### ISSUE THREAD

**Issue by jsvini** [litespeedtech/cyberpanel#157]
I just found this project and it's awesome.

The site list page show the websites ordered by creation date, from the most old to the most recent, new sites will always be the last ones, would be nice to have the option to always list by name.

Also, this page is not optimized for a huge quantity of sites, each site in the list takes too much vertical space, would be nice if you could fit more sites on the viewport. 😄

**Comment by usmannasir** [comment]
I accpeted your pull and merged in the package to be released with v1.9.2.
