### ISSUE TITLE
[1.9] [Bug] Site preview image not working

### ISSUE THREAD

**Issue by jsvini** [litespeedtech/cyberpanel#158]
# Bug report

### What I did

Access the site list page `/websites/listWebsites`

### What I expected to happen

Show the preview image from each site

### What happened

I get this image instead:

![image](https://user-images.githubusercontent.com/4185886/68046675-316fb880-fcbb-11e9-98be-b3d517b3e4fd.png)

Would be nice to have an option to disable this preview image.

**Comment by xiaoyong-wang** [comment]
That feature will be made in the future

**Comment by istiak101** [comment]
This is now available. Can anyone please close? @usmannasir @aonsyed

**Comment by j-a-pope** [comment]
This seems temperamental, on some servers it's working beautifully for us and on some others it shows nothing.

**Comment by istiak101** [comment]
@S4-Hosting this came in v2.0.1 . It won't work on any previous version of CyberPanel. Also it loads on user-end. If https://cdn.statically.io doesn't work on user-end it won't work.
