### ISSUE TITLE
Cyberpanel fails PCI compliance

### ISSUE THREAD

**Issue by hennaboy** [litespeedtech/cyberpanel#162]
Fails PCI compliance in several areas

1. Cookie Does Not Contain The "secure" Attribute

2. Several security headers are missing.
X-XSS-Protection HTTP Header missing on port 8090.
Strict-Transport-Security HTTP Header missing on port 8090.
X-Frame-Options SAMEORIGIN missing on port 8090.
Header always set X-XSS-Protection "1; mode=block" missing on port 8090.

**Comment by usmannasir** [comment]
Take a look https://github.com/usmannasir/cyberpanel/commit/e4a375f4f1a14922031c84462141eac441774830

**Comment by hennaboy** [comment]
We just noticed that the security headers will now block the x-frame csf webadmin so perhaps a content security policy is also required and probably a good idea to have both the headers but then allow the features where required.

**Comment by usmannasir** [comment]
try to upgrade again. It should not be denied but sameorigin should be allowed.

Upgrade and you will see csf admin

**Comment by hennaboy** [comment]
Nothing in the plugins navigation which was there previously.

Also as I selected to use jsdelivr that is also blocked now as a Cross
Origin Read Block CORB

**Comment by usmannasir** [comment]
I need to check your server, I invited you to slack. Kindly message @Usman Nasir
