### ISSUE TITLE
Hardcoded Root user limitation in remote backups.

### ISSUE THREAD

**Issue by meramsey** [litespeedtech/cyberpanel#165]
As mentioned in:
https://forums.cyberpanel.net/discussion/2532/sftp-remote-specify-user-not-root#latest

No option is provided to specify the remote user and is currently hardcoded to root user. It should not require the remote user being root to be able to backup to the server.

ssh-copy-id -i /root/.ssh/cyberpanel username@hostname

ssh/scp/sftp -i /root/.ssh/cyberpanel username@hostname

Recommend we look into allowing the user to specify the desired remote user in the remote backup setup process and possibly the remote destination path as well.

I have some examples of rsync scripts that easily is able to take advantage of this functionality. SCP/SFTP uses almost the exact same formatting so would be easy to use dropdown for protocol type SCP/SFTP/Rsync and based on that structure the command dynamically for use transferring the backup.
https://gitlab.com/cyberpaneltoolsnscripts/cyberpanel-rsync-scripts

Current files:
https://github.com/usmannasir/cyberpanel/blob/2a4fa86716b484c8f69e3cf226a3525df7614544/plogical/backupSchedule.py#L230

https://github.com/usmannasir/cyberpanel/blob/2a4fa86716b484c8f69e3cf226a3525df7614544/backup/templates/backup/backupDestinations.html#L30

https://github.com/usmannasir/cyberpanel/blob/2a4fa86716b484c8f69e3cf226a3525df7614544/plogical/backupUtilities.py#L792-L999

**Comment by dedekorkud** [comment]
You have already stated that there will be a study on this subject.

I am using qnap and want to backup remotely.

But I cannot change the username. By default, it authorizes the "admin" user.

We cannot use the root user.
I want you to grant access to the root user.

So, I can transfer my backups to the qnap server.

**Comment by meramsey** [comment]
I wrote an experimental patch for enabling support for specifying any desired remote user for this. It has NOT been tested yet due to time constraints but it should be pretty close if not complete for what is needed to enable this :)

Related Pull request.
https://github.com/usmannasir/cyberpanel/pull/321
