### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by PowerChaos** [litespeedtech/cyberpanel#166]
hi,
after some testing i got this finaly working
but it is a mess for a fresh install

first of all , it try to install some stuff before it even checks if it contains the needed modules ... 
so lets break down the install steps so you can see what i exactly mean

PLEASE NOTE, THIS IS ABOUT CENTOS 7

lets start with Wget and Curl
first command you need to do before you can even get the installer is the following
`yum install curl wget ( curl and wget  )`
as the main page gives you a one liner for wget/curl
and in my case only the wget command works ... as curl trows a error with no permission stuff 

so you use the following command
```
wget cyberpanel ... .sh
./cyber.... sh
```

now the first thing you see is that it going install Curl and Wget for you .... makes no sense

so far so good
now it comes to the part of installing CERTBOT ( ACME SSL ) 
it directly fails to install certbot ... because 1 single thing that is missing

so put this also in the installer script 
`pip install requests urllib3 pyOpenSSL --upgrade`

because URLLIB3 is missing by a basic installation ... 
in my case i fixed it later on by instaling certbot manual and still needed to do above command
as certbot keeps failing if i do not issue the pip install first

also pip is out dated  and keeps trowing warnings about that

maybe you can took a look at it ?

**Comment by usmannasir** [comment]
Your provider? Are you running as root or sudo?

OpenVZ or KVM?

**Comment by PowerChaos** [comment]
i use XenServer as hypervisor
in current situation its from home hosting , so i got a public ip adress pointed to the router and DMZ to the vps itself so all ports are open
the vps is running on internal ip 192.168.0.52 ( host is on 192.168.0.3 ) 
the install has beein done on a fresh install of centos 7 minimal install ( minimall.iso ) with no extra packages selected
also the xenserver drivers are installed

i use it as root , centos mainly do not use sudo ( thats ubuntu ? )

also ssh does not seems to work for me , but thats possible that it is bound to ip instead of wildcard 😅 (ftp does work exept for sftp?) 

Greets from PowerChaos

**Comment by usmannasir** [comment]
I think Amazon lightsial is Xen and it runs fine there, for your home hypervisor I can't provide any support/insights. I've never tested there.

It is better you get a KVM/Xen from Cloud Provider

**Comment by PowerChaos** [comment]
that going to be hard
as i am my own provider ( starting up ) 

but what has kvm/xen/openVZ/Qemu/esxi/HyperV/SolusVM has to do with the installer that does not include the missing configs ? exept from the part that some PV drivers need to be installed ( xen is HVM , kvm is PV , only PV need drivers but HVM can use drivers for better speeds and more control)
sidenote: , in my case is it Hardware virtualization with paravirtualization drivers enabled (PVHVM)

anyway
next week my home server will be placed in the dc and then i am happy to provide you acces to the system so you can test out yourself in case the problem still exist
or if you want i can also provide now some limited access as a lot of things do not work in a private lan and only 1 external ip ( routed to private lan with DMZ ) 

all things i basicly do is just mounting a iso ( centos ) and run a clean install
then after installing wget i get the script and let it run

after the run is finished i manual need to install certbot and the urllib3 stuff else a lot of things do not work
example
htacces from control panel writing does not work .. urllib3 solve this ( i think )
autossl ( acme/lets encrypt ) fails because of certbot not found

if i use the preupdate script then the lswsd daemon does not start up anymore , but that could also be because of the above stuff i was trying out to get working

i dit a fresh test before i made this post
i used a pre configured vm , so it already included nano and wget and the pv drivers ( nothing more )
now it seems it works , exept for certbot , that still dit not get installed automatic
unless the extended function is changed ?

as it is not on a public ip is it not possible for me to acces it at this moment
so i will run the test again when it is in the datacenter so i can access it in full ( with out local ip's  )

if intrested , here is the video of the installer
https://dir.nu/5dc735d5bc6ec ( will get auto removed after 7 days or when the server is in the dc, it is stored on the test server  )

so at this moment it seems to be working like it need to be

Greets from PowerChaos
ps: keep up the good work

**Comment by qtwrk** [comment]
Hi,

Sorry to jump in ,  but doesn't centos 7 has curl pre-installed ? even in minimal.

Best regards,

**Comment by PowerChaos** [comment]
@qtwrk i guess so
first time i tried curl it was trowing out some permission errors , so i needed to install wget to get the files 
as soon the server is in the dc , then i will try again and let you know ( and record , as video shows more then text ^^ ) 

greets from PowerChaos

**Comment by qtwrk** [comment]
@PowerChaos 

cool ,  just let you know that install command was 

`sh <(curl https://cyberpanel.net/install.sh || wget -O - https://cyberpanel.net/install.sh)`

or

`sh <(curl cyberpanel.sh || wget -O - cyberpanel.sh)`

The reason for `install wget/curl` in script itself , as you thought you have to manually install it beforehand and makes no sense is because:

in CentOS or Ubuntu ,  curl and wget,  at least one of them should be pre-installed , I think curl on CentOS and wget on Ubuntu

so by that command with `||`  , it will try to use curl first, and if curl fails(or not installed) it will try again with wget, to get the script first , and then install curl/wget in case one of them is missing.

This should explain your doubt on this matter which is not exactly "no sense" :)

> as curl trows a error with no permission stuff

I must say this is really weird , if you could reproduce it again , please let me know , we will figure something out.

**Comment by PowerChaos** [comment]
after some more testing it just seems that the centos install i was using was a little corrupt
it was installed with minimal version, and curl dit not got installed correctly for some reason

for the other installs i dit , i never got this problem again so it is probably to blame to a "corrupt" install of centos
