### ISSUE TITLE
Unattended install no longer works

### ISSUE THREAD

**Issue by emilevirus** [litespeedtech/cyberpanel#168]
My unattended install (which was working before) no longer works. Why?
# sh install.sh -v ols -a 1 --password longpassword
Checking and installing curl and wget
unknown argument...

**Comment by qtwrk** [comment]
Hi,

Apologize for the inconvenience , there has been an update on the installer

please use    `-v ols -a --password longpassword` 

although the noninteractive was made long time ago but it was never publicly posted , so I didn't think of backward compatibility

**Comment by emilevirus** [comment]
``# sh install.sh -v ols -a --password longpassword`` 
Checking and installing curl and wget
./cyberpanel.sh: line 1017: [: longpassword: integer expression expected

**Comment by qtwrk** [comment]
please try `sh <(curl cyberpanel.sh || wget -O- cyberpanel.sh) -v ols -a -password longpassword`

I just tested and worked.

**Comment by emilevirus** [comment]
That worked. Thank you!
