### ISSUE TITLE
Problem with port 53

### ISSUE THREAD

**Issue by evil4u** [litespeedtech/cyberpanel#172]
I have a massive issue with port 53.
It's not open acording to isnic.is

The nameserver NS1.DOMAIN.IS (111.222.333.444) seems to ignore test queries to UDP port 53
The nameserver NS1.DOMAIN.IS (185.112.147.62) seems to reject connections to TCP port 53

I have installed csf and the issue is the same.
What can I do to fix this.

[root@hq ~]# netstat -tulpn | grep LISTEN
tcp        0      0 127.0.0.1:8891          0.0.0.0:*               LISTEN      1390/opendkim       
tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN      1333/dovecot        
tcp        0      0 0.0.0.0:995             0.0.0.0:*               LISTEN      1333/dovecot        
tcp        0      0 127.0.0.1:199           0.0.0.0:*               LISTEN      1297/snmpd          
tcp        0      0 0.0.0.0:7080            0.0.0.0:*               LISTEN      4474/openlitespeed  
tcp        0      0 0.0.0.0:587             0.0.0.0:*               LISTEN      1531/master         
tcp        0      0 127.0.0.1:11211         0.0.0.0:*               LISTEN      1379/./bin/lsmcd    
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      1289/redis-server 1 
tcp        0      0 0.0.0.0:110             0.0.0.0:*               LISTEN      1333/dovecot        
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN      1333/dovecot        
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/systemd           
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      4474/openlitespeed  
tcp        0      0 0.0.0.0:465             0.0.0.0:*               LISTEN      1531/master         
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      2712/pdns_server    
tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN      1409/pure-ftpd (SER 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1310/sshd           
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      1531/master         
tcp        0      0 0.0.0.0:8090            0.0.0.0:*               LISTEN      3717/lscpd (lscpd - 
tcp6       0      0 :::993                  :::*                    LISTEN      1333/dovecot        
tcp6       0      0 :::995                  :::*                    LISTEN      1333/dovecot        
tcp6       0      0 :::3306                 :::*                    LISTEN      2749/mysqld         
tcp6       0      0 :::587                  :::*                    LISTEN      1531/master         
tcp6       0      0 :::110                  :::*                    LISTEN      1333/dovecot        
tcp6       0      0 :::143                  :::*                    LISTEN      1333/dovecot        
tcp6       0      0 :::111                  :::*                    LISTEN      1/systemd           
tcp6       0      0 :::465                  :::*                    LISTEN      1531/master         
tcp6       0      0 :::53                   :::*                    LISTEN      2712/pdns_server    
tcp6       0      0 :::21                   :::*                    LISTEN      1409/pure-ftpd (SER 
tcp6       0      0 :::22                   :::*                    LISTEN      1310/sshd           
tcp6       0      0 :::25                   :::*                    LISTEN      1531/master

OS CentOs 7.7

**Comment by evil4u** [comment]
I found out why this is happening, I am unable to add more IPs to the server for ns1 and ns2 so I have to use the main server ip for the ns1 and ns2.

**Comment by jordanlambrecht** [comment]
Hey @evil4u, it sounds like you solved the problem. Please close this issue if it's resolved to help keep the Issues backlog clean.
