### ISSUE TITLE
File manager file download problem

### ISSUE THREAD

**Issue by hasarinda** [litespeedtech/cyberpanel#173]
Can't download file via  File manager 
404 Error 
fix it soon

**Comment by BurakBoz** [comment]
try to archive file(s), then download archive, after download complete, you can't delete that archive file WHY? fix permissions. then delete the archive file.

**Comment by jordanlambrecht** [comment]
Hi @hasarinda. It looks like you haven't responded in over a year. It's near impossible to diagnose what's going on with your install without additional information. Even then, this sounds like a configuration problem and not an issue with CyberPanel itself. Please close this issue to help keep the Issue backlog clean.

**Comment by istiak101** [comment]
This is resolved. Can you please close this @usmannasir @whattheserver ?
