### ISSUE TITLE
[enhancement] Make memcache service listen 127.0.0.1 by default

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#177]
I would suggest to make memcached service listen 127.0.0.1 by default to avoid security leaks like DDoS reflection. For UDP and TCP ports.

**Comment by qtwrk** [comment]
seems on Ubuntu , it seems already `-l 127.0.0.1`

will change it from `OPTIONS=""` to `OPTIONS="-l 127.0.0.1 -U 0"` on CentOS

Thanks for the suggestion.

**Comment by franciscopaniskaseker** [comment]
Thank you. I am using CentOS 7.

**Comment by qtwrk** [comment]
added in new script.
