### ISSUE TITLE
CyberPanel WHMCS Module Issue

### ISSUE THREAD

**Issue by UnendedRoyale** [litespeedtech/cyberpanel#179]
Hi,
I use cyberpanels whmcs module and every time I order a cyberpanel package on my whmcs site, it says in the system logs 'failed to approve order, data supplied not accepted.'
It looks like the module doesn't accept special characters automatically generated in the password, so i removed the special characters and ram the module create function and it worked.  I tested it multiple times and that was the issue.
How can I make special characters illegal?

**Comment by usmannasir** [comment]
take a look https://github.com/usmannasir/cyberpanel/commit/db444c7e1f982ab553fa79e8fd24e4298b05c237
