### ISSUE TITLE
chroot not enabled

### ISSUE THREAD

**Issue by jcn50** [litespeedtech/cyberpanel#182]
Created users can set-up SSH access for their website, I am talking about this page:
`https://$hostname:8090/websites/$website/sshAccess`

However **chroot is not enabled** so they have access to **everything** under / :
```
bin
boot
dev
etc
home
lib
lib64
lost+found
media
mnt
opt
privkey.pem
proc
root
run
sbin
srv
swapfile
sys
tmp
usr
var
webadmin.csr
```

I do not know if is the same with the Enterprise Edition, I am using the free one.

**Comment by usmannasir** [comment]
Hi,
There's nothing wrong with being able to view `/` on Linux, people cannot do harm by reading the root directory. If you like to hide something, then we suggest using CloudLinux to further restrict users from browsing various parts of the system
