### ISSUE TITLE
Gnupg php package is missing

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#184]
I am trying to installing Passbolt solution, but I am getting:

```bash
PHP Fatal error:  You must enable the gnupg extension to use Passbolt.
```

CentOS 7.7.

The problem is lsphp* packages does not provide gnpupg extension for php.

**Comment by usmannasir** [comment]
You can install this extension manually

`/usr/local/lsws/lsphpXX/bin/pecl install gnupg`

In the command above, replace XX with your php version like `71`

**Comment by arvindjkhr** [comment]
PECL is not available in new version of PHP now.

![image](https://user-images.githubusercontent.com/39983369/196214351-08d76b7b-0a1a-45db-a590-d1e205c27d2e.png)
