### ISSUE TITLE
How to remove Auto SSL ?

### ISSUE THREAD

**Issue by jsahani** [litespeedtech/cyberpanel#185]
Hi Team,

I would like to disable Auto SSL issue after adding any website inside CyberPanel.

Please advice how to do so as I use Cloudflare for Shared SSL for most of my Domains.

Thanks

**Comment by usmannasir** [comment]
```nano /etc/crontab``` and remove this line `0 2 * * * root /usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/renew.py`

**Comment by jsahani** [comment]
Okay so this will disable SSL Issue automatically after adding Website or Domain ?

Thanks, Tho I'll be able to issue an SSL manually right ?

**Comment by henscu** [comment]
@jsahani did you manage to work out a complete procedure to move your SSL setup from LetsEncrypt to Cloudflare Origin CA on CyberPanel?

**Here is my understanding so far of how I could move from LetsEncrypt to Cloudflare CA Certificate on CyberPanel. Please correct me...**

My LetsEncrypt certs were set up in CyberPanel (via acme.sh), so it looks like I need to:

1. **Disable my LetsEncrypt renewal cron job.**

    Looks like I do this by removing the cron job as described by @usmannasir above at: https://github.com/usmannasir/cyberpanel/issues/185#issuecomment-568714503

    However, it seems that the `acme.sh --remove` command described at the link below may also do this? I need to experiment...
https://github.com/acmesh-official/acme.sh#13-how-to-stop-cert-renewal


2. **Delete my current LetsEncrypt certificates.**

    From the `acme.sh --remove` description above, it seems like I can just delete the following directories:
`rm -rf ~/.acme.sh/example.com `


3. **Set up Cloudflare SSL cert and key on CyberPanel.**

    Generate Cloudflare Certificates as described at the link below and install the cert and key (using copy/paste) via the '**Add SSL**' option on the CyberPanel management page for my website.
    https://support.cloudflare.com/hc/en-us/articles/115000479507-Managing-Cloudflare-Origin-CA-certificates


4. **No CyberPanel server cron job needed for Cloudflare cert renewal as their certs are valid for 15 years.**

 
5. **I assume I don't need to install Cloudflare CA **root** certificates on CyberPanel?**

    https://support.cloudflare.com/hc/en-us/articles/115000479507-Managing-Cloudflare-Origin-CA-certificates#h_30cc332c-8f6e-42d8-9c59-6c1f06650639

 
6. **Is it possible to set up **Authenticated Origin Pulls** on CyberPanel?**

    To do this, I would need to download `origin-pull-ca.pem` and place the certificate in a file on my Ubuntu server, for example in `/path/to/origin-pull-ca.pem`
Then I would need to add these (Apache compatible) lines to the SSL configuration for my origin web server (ie LiteSpeed). Not sure how to do this, perhaps using the **vHost Conf** function on CyberPanel...:

    _Add these lines to the **vhssl** section???_
    `SSLVerifyClient require`
    `SSLVerifyDepth 1`
    `SSLCACertificateFile /path/to/origin-pull-ca.pem`

    Full Cloudflare instructions for Authenticated Origin Pulls are here:
    https://support.cloudflare.com/hc/en-us/articles/204899617-Authenticated-Origin-Pulls

7. **Anything else...?**

**Comment by DushanthaS** [comment]
Any update on this? @henscu you got this working?
