### ISSUE TITLE
Bugy Panel or Cyber Panel Bugs All Around Here!

### ISSUE THREAD

**Issue by ksaltik** [litespeedtech/cyberpanel#188]
Hi,

The latest version I think 1.9 or 1.9.1 both ubuntu and centos fresh install no phpmyadmin. Several people has already menion this in your website no solution.

Someone said upgrade your cyberpanel will fix it. Yes it fix the phpmyadmin. Then 500 internal server error in Cyberpanel login screen.

And you ask people to open tşcket you can see yourself just spare yoru 30 minutes to test it.

And several other bugs.

What is trhe fubctionality for defaukt nameserver configuration.

Dns I create dns server with on of my domain. Everything fine.
,Then add another website. When I look the dns NS record I see NS ns1.newlyaddeddomain.com 

Then add another website. This time I see dns NS record ns1.mydnsserverdomain.com

Then add another website this time I see dns NS record only hostname.newlyaddedwebsite.com

Everytime something different. And why do you need us to open TCP: 40110-40210 ports.

And I delete ubuntu vps machine.

Then install centos and same things happend. 

I delete it.

**Comment by usmannasir** [comment]
Provide these details please -> https://forums.cyberpanel.net/discussion/953/bug-report-template

Did you install the beta version during install? I just ran some tests and none of the mentioned bugs exists.
