### ISSUE TITLE
File Manager redirects to "/?"

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#189]
Hi there,

When when i click Create File or Create Folder on the CyberPanel File Manager, i type the file name, and i click enter, it goes to hostnamehere(this isnt really my hostname):8090/? instead of creating the new file/folder
it only works if i click the submit button, it redirects to hostnamehere(this isnt really my hostname):8090/?  if i click enter.

This doesnt happen with the rename file/folder feature
This also happens with Staging Setup and Alias Manager in cyberpanel

**Comment by usmannasir** [comment]
So far don't listen to `Enter` event in these fields.

**Comment by Kasper2040** [comment]
Is it possible that you can make it so that the enter key doesnt do anything in the fields?

**Comment by xiaoyong-wang** [comment]
Is it possible that you can make it so that the enter key doesnt do anything in the fields?
Or have it so the enter key submits the field

**Comment by usmannasir** [comment]
Fixed, related commits are attached to this issue.
