### ISSUE TITLE
question about an issue

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#190]
I created this issue yesterday: https://github.com/usmannasir/cyberpanel/issues/189

I was wondering, when will this issue with the file manager be solved?  I am asking this because some people that have access to my cyberpanel server are complaining because of this and i think that clicking enter should either do nothing or it should automatically submit the field

**Comment by usmannasir** [comment]
I've reopened the original issue, will discuss it there.
