### ISSUE TITLE
Won't install zip

### ISSUE THREAD

**Issue by ghost** [litespeedtech/cyberpanel#193]
![image](https://user-images.githubusercontent.com/40630518/71555246-a9263f00-29ef-11ea-825d-87646848f486.png)

![image](https://user-images.githubusercontent.com/40630518/71555248-b4796a80-29ef-11ea-9e93-025cdf983292.png)

Won't install zip

**Comment by ghost** [comment]
Yes, i can reproduce from my end too.

**Comment by usmannasir** [comment]
Can you create PHPinfo page and see if zip exits or not https://forums.cyberpanel.net/discussion/1077/tutorial-how-to-create-a-phpinfo-page

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/18012954/71556648-3c09bc80-2a76-11ea-8d10-02f4b9d78e81.png)

No zip.

**Comment by hennaboy** [comment]
yum search all lsphp74

There is no zip package.

Looking at 

https://forum.openlitespeed.org/threads/bzip2-and-zip-support-in-lsphp7-4.4012/

They are looking to push the packages so should be resolved soon

**Comment by ghost** [comment]
@usmannasir need to update the buildconf of zip

Zip:
--with-libzip has been removed.
--enable-zip becomes --with-zip .

**Comment by ghost** [comment]
My bad if its from repo i think litespeed has to fix it from their end.

Atm i have to recompile php from litespeed panel by editing /usr/local/lsws/admin/html/utility/build_php/buildconf.inc.php

**Comment by qtwrk** [comment]
Hi,

Yes, it needs to be fixed from source by LiteSpeed tech.

You don't have to re-compile entire PHP though , only zip extension ought do it.

**Comment by hifihedgehog** [comment]
Here is the workaround:
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:php:pecl-extension:lsphp74_zip

Source (LiteSpeed Slack channel):
https://golitespeed.slack.com/archives/C3RMQ3KGW/p1581011218070600

**Comment by hifihedgehog** [comment]
@usmannasir Please see above.

**Comment by qtwrk** [comment]
Hi,

It's already added into installer and upgrad script.

**Comment by hifihedgehog** [comment]
For some reason, it's still failing. I received the following error:
> shtool at '/var/tmp/zip/build/shtool' does not exist or is not executable.
> Make sure that the file exists and is executable and then rerun this script.
> 
> ERROR: `phpize' failed

**Comment by hifihedgehog** [comment]
I opened a ticket with LiteSpeed. Here is the LiteSpeed support ticket number for reference:
#849041

**Comment by hifihedgehog** [comment]
Solved:

```
yum install lsphp74-devel
mkdir /usr/local/lsws/lsphp74/tmp

 /usr/local/lsws/lsphp74/bin/pecl channel-update pecl.php.net
/usr/local/lsws/lsphp74/bin/pear config-set temp_dir /usr/local/lsws/lsphp74/tmp
/usr/local/lsws/lsphp74/bin/pecl install zip
echo "extension=zip.so" > /usr/local/lsws/lsphp74/etc/php.d/20-zip.ini
chmod 755 /usr/local/lsws/lsphp74/lib64/php/modules/zip.so
```

> the /tmp was mounted with noexec , that means no files can be executed in /tmp for security reason.
> 
> by default , pear and pecl uses /tmp , so use config-set temp_dir to change it to other dir and then build it.

**Comment by spacevega21** [comment]
I used the commands here > https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:php:pecl-extension:lsphp74_zip // and still getting the same issue > 
---
Loaded plugins: copr, fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.turhost.com
 * epel: ftp.nluug.nl
 * extras: mirror.isimtescil.com.tr
 * remi-php73: mirrors.ukfast.co.uk
 * updates: mirror.telepoint.bg
Package lsphp74-common-7.4.16-2.el7.x86_64 already installed and latest version
Nothing to do
PHP Extension Installed.
----
