### ISSUE TITLE
/usr/local/lsws/logs/ with high disk/storage usage

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#196]
**The problem:**
Full disk usage due a lot of log files.

**Explaining:**
I am seeing a lot of error.log files in /usr/local/lsws/logs/.

Ignoring at the moment the reason for so many error log files, the lsws:
-  not compress the files 
- these files must not compromise disk free space

For three times this customer had 100% of disk usage due a lot of error files.

How we can enchance the error log feature to now allow this situation?

**Comment by hennaboy** [comment]
You should take this issue up with openlitespeed or litespeed depending on the version you are running and ask to why they do not rotate the logs or compress. 

https://forum.openlitespeed.org/

You can also access the ols webadmin and turn error logging to Debug only or even setup a cron job to remove old logs.

**Comment by franciscopaniskaseker** [comment]
I will work with them and update here. If OLS can not do that for while, maybe cyberpanel can add these logs in rsyslog environment.

**Comment by franciscopaniskaseker** [comment]
> Default error log rotate is 30 days. So in general you won’t get disk full issue due to too many error logs.

> To prevent log fill up the disk, you can try method:

> Insert keepDays 1 to /usr/local/lsws/conf/httpd_config.conf errorlog logs/error.log section. In this way, the error log will only store for one day

> Use cron job to auto remove error.log.*. In this way, all archived log will be removed.

I will open a issue with them to try to make this more efficient.

Thank you for all.

**Comment by franciscopaniskaseker** [comment]
Opened a enchancement request with them:
https://github.com/litespeedtech/openlitespeed/issues/153

Thank you for all help.

**Comment by franciscopaniskaseker** [comment]
Only to update:
> Usually it won't use a large mount of your space when it is set to errorlog ERROR or DEBUG low.
> I will do some tuning of that part of code to avoid the crash when it happens.
https://github.com/litespeedtech/openlitespeed/issues/153

**Comment by franciscopaniskaseker** [comment]
@usmannasir openlitespeed, more than 3 versions after, did nothing to do rotation and compress the logs. we need to provide any solution on this to avoid fill all server space. With two commands  we can compress the error.log files and remove old error.log files.
