### ISSUE TITLE
Failed to upgrade centos 7

### ISSUE THREAD

**Issue by ghost** [litespeedtech/cyberpanel#199]
![image](https://user-images.githubusercontent.com/40630518/71773031-875f1780-2f1b-11ea-8413-d2be5ce40567.png)

give some weird errors

**Comment by qtwrk** [comment]
may I know what was the command you use to upgrade ?

**Comment by Alanon202** [comment]
Can confirm this, I got the same error today, the code I used was the one from the CyberPanel [blog entry](https://cyberpanel.net/docs/upgrading-cyberpanel/). The upgrade was "successful" in the end, but it still shows the old build in the panel interface.
