### ISSUE TITLE
[1.9] [Bug] Unable to access phpMyAdmin because of php version

### ISSUE THREAD

**Issue by jsvini** [litespeedtech/cyberpanel#220]
# Bug report

### What I did

Tried to access phpMyAdmin: https://[server]:8090/phpmyadmin/index.php

### What I expected to happen

Open the phpMyAdmin login screen

### What happened

Got an error because the latest version of phpMyAdmin requires PHP >= 7.1.3 and the current php is 7.0 

### What I've already tried to fix it

copy the php 7.2 to the fcgi-bin folder solved the issue
cp /usr/local/lsws/lsphp72/bin/lsphp /usr/local/lscp/fcgi-bin/lsphp

### Version

1.9 from DigitalOcean Marketplace

**Comment by qtwrk** [comment]
Hi,

Thanks for the report , it's already fixed in later upgrade.

**Comment by usmannasir** [comment]
Yes, if you upgrade this should be resolved. Closing now.
