### ISSUE TITLE
Cannot download files in file manager

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#222]
Hi there,
When i try to download files through the file manager it just goes to /filemanager/downloadFile?domainName=domain.com&fileToDownload=/home/domain.com/public_html/templates/it/filename.php

**Comment by usmannasir** [comment]
A fix is available in the beta branch, which you can get using 

```sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/v1.9.4/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/v1.9.4/preUpgrade.sh)```

But remember v1.9.4 branch is beta

**Comment by xiaoyong-wang** [comment]
Ok, thank you :)
