### ISSUE TITLE
Error message when creating a site and in file manager

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#225]
I randomly sometimes get this error "Error message: 'NoneType' object has no attribute 'splitlines'
even after upgrading" when trying to create a website or opening file manager.  it wont go away unless i restart my server and even after i restart it i will get that error within 1-2 hours for some reason.

**Comment by usmannasir** [comment]
This should resolve for you -> https://forums.cyberpanel.net/discussion/3839/error-message-nonetype-object-has-no-attribute-splitlines#latest
