### ISSUE TITLE
When i suspend a website i can still upload files through the file manager

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#226]
Hi,
When i suspend a website, i am still able to click "Manage" then go the file manager and upload files.

**Comment by usmannasir** [comment]
A new feature coming in v1.9.4 where you can suspend users (will suspend all sites under that user along with their child-domains).

The suspended user thus can't log in at all.

**Comment by xiaoyong-wang** [comment]
Will the whmcs module be updated to suspend the user too?

**Comment by usmannasir** [comment]
Please create forum thread, I will invite WHMCS dev to introduce this feature.

**Comment by xiaoyong-wang** [comment]
Ok, i created it at:
https://forums.cyberpanel.net/discussion/3861/suspend-user-through-whmcs
