### ISSUE TITLE
Cron Job page not working

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#227]
on the cron job page which is at /websites/listCron
it does not show any active cron jobs after creating one
i get this error in 1.9.3 and 1.9.4
screenshot: http://prntscr.com/qt6zxo

**Comment by usmannasir** [comment]
Can't reproduce, create support ticket so I can check -> https://platform.cyberpanel.net/

**Comment by xiaoyong-wang** [comment]
I am using Ubuntu
I created a support ticket:
https://platform.cyberpanel.net/support/XVCKS9/

**Comment by thomassiskos** [comment]
I have 3 servers after upgrade 1.9.3 not working to cron job all the sites not run auto
