### ISSUE TITLE
Problem OpenLiteSpeed

### ISSUE THREAD

**Issue by thomassiskos** [litespeedtech/cyberpanel#228]
After update 1.9.3 problem OpenLiteSpeed stop end put manual to start, change php 7.2 to 7.3 to 7.4 and back and again stop.
The site wordpress does not load images.
Does not load the entire site

**Comment by usmannasir** [comment]
Please create an issue here -> https://github.com/litespeedtech/openlitespeed/issues/new

Bug with OpenLiteSpeed.
