### ISSUE TITLE
 Cron Job page not working

### ISSUE THREAD

**Issue by thomassiskos** [litespeedtech/cyberpanel#229]
I have 3 servers after upgrade 1.9.3 not working to cron job all the sites not run auto

**Comment by usmannasir** [comment]
Fixed with https://github.com/usmannasir/cyberpanel/commit/2d509759e6f8b3a9bf994a45e4422530b1d9fa27

But to get the fix you will have to try v1.9.4 branch using

```
sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/v1.9.4/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/v1.9.4/preUpgrade.sh)
```
