### ISSUE TITLE
Disk not resizing

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#233]
I have resized the Disk in CyberPanel and it didn't update...
Before it was 500gb and CyberPanel had 492gb available disk space
And now I resized it to 550, and it's still showing as 492, but /dev/sda2 has been expanded to 550GB

**Comment by usmannasir** [comment]
output of `df -h` ?

**Comment by xiaoyong-wang** [comment]
Filesystem      Size  Used Avail Use% Mounted on
udev            5.8G     0  5.8G   0% /dev
tmpfs           1.2G  972K  1.2G   1% /run
/dev/sda2       492G   27G  440G   6% /
tmpfs           5.9G  784K  5.9G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           5.9G     0  5.9G   0% /sys/fs/cgroup
/dev/loop0       89M   89M     0 100% /snap/core/7270
/dev/loop1       90M   90M     0 100% /snap/core/8268
/dev/loop2      1.5G   18M  1.4G   2% /tmp
tmpfs           1.2G     0  1.2G   0% /run/user/1000

**Comment by usmannasir** [comment]
Your root mount point does not seem to be extended `/dev/sda2 492G 27G 440G 6% /`

still says 492G.

**Comment by xiaoyong-wang** [comment]
How can I resize it through SSH?
I used cfdisk and resized it but it still shows 492GB in df - h and cyberpanel

**Comment by hennaboy** [comment]
try resize2fs on ubunto

sudo resize2fs /dev/sda2 550G

**Comment by xiaoyong-wang** [comment]
Will that destory any data?
