### ISSUE TITLE
When i suspend a website it doesnt suspend the child domains

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#236]
Hi there, i suspended a website on my cyberpanel server and i noticed it didnt suspend the child domains on the website.  Is it possible u can add a feature where i can suspend a website and it will also suspend the child domains?

**Comment by usmannasir** [comment]
This issue is resolved in v1.9.4 which is to be released soon.

**Comment by xiaoyong-wang** [comment]
i am currently using 1.9.4 but i still receive the issue
