### ISSUE TITLE
Mail child domain

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#237]
Hi,
Is there any way I can stop cyberpanel from automatically creating the mail. Child domain name when I create a website on 1.9.4?
I find this feature a bit annoying because it says on my website if you order cyberpanel hosting from me you can't make child domains.

**Comment by usmannasir** [comment]
I can add check that if the package has domain creation disabled, we can skip that subdomain creation? However, it is needed for email function to work. 

You can see more details here -> https://forums.cyberpanel.net/discussion/3874/how-do-i-configure-multiple-domains-and-ssls-with-postfix

**Comment by xiaoyong-wang** [comment]
Is it possible you can make it so the .mail child domain is invisible?

**Comment by usmannasir** [comment]
That may create other problems if a user tries to create such a domain later.

**Comment by xiaoyong-wang** [comment]
If the .mail child domain does not exist will one of my users be able to send emails or receive emails?

**Comment by usmannasir** [comment]
mail child domain will solve an issue with Outlook/Thunderbird configurations. More details here -> https://forums.cyberpanel.net/discussion/3874/how-do-i-configure-multiple-domains-and-ssls-with-postfix

If you use only Rainloop and follow this tutorial -> https://blog.cyberpanel.net/2018/05/15/achieve-10-10-email-score-with-cyberpanel/

Email will go through.

**Comment by xiaoyong-wang** [comment]
Can you make it so if the package has domain creation disabled, it can skip that child domain creation?

**Comment by usmannasir** [comment]
I feel the domain should be created, as it is very important for mail clients configurations.

**Comment by xiaoyong-wang** [comment]
Ok, thank you

**Comment by ryansechrest** [comment]
Is this only required if a user sets up an email address on a particular domain? If so, maybe it can check to see if there are any mail accounts, and if not, don't create it. Then, if a user later decides to setup mail, it can check if it exists, and if not, create it. In my situation, I don't use mail for any of my sites, but it gets created for every site, which means I just end up having to delete the child domain (and the directory) right after creating a site.

**Comment by usmannasir** [comment]
I think it is best to add a configurable option during website creation, that would be best.

**Comment by ryansechrest** [comment]
That's a good idea, too!

**Comment by usmannasir** [comment]
Made it optional with this commit https://github.com/usmannasir/cyberpanel/commit/80eaf741bb89cf5a87bfde39b5a968de5e2dcb5f

Will come in v1.9.5.
