### ISSUE TITLE
crontab empty after upgrade to 1.9.4

### ISSUE THREAD

**Issue by gabrielcossette** [litespeedtech/cyberpanel#243]
Hi,

As reported in the [forum](https://forums.cyberpanel.net/discussion/3919/after-upgrading-to-1-9-4-etc-crontab-is-empty-setup-for-daily-backup-also-gone), /etc/crontab is empty after upgrade to 1.9.4.

Is that normal?

On 1.9.3, it was:

```
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root

# For details see man 4 crontabs

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name  command to be executed

0 * * * * root python /usr/local/CyberCP/plogical/findBWUsage.py
0 * * * * root /usr/local/CyberCP/postfixSenderPolicy/client.py hourlyCleanup
0 0 1 * * root /usr/local/CyberCP/postfixSenderPolicy/client.py monthlyCleanup
0 2 * * * root /usr/local/CyberCP/plogical/upgradeCritical.py
0 2 * * * root /usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/renew.py
0 12 * * * root /usr/local/CyberCP/bin/python /usr/local/CyberCP/IncBackups/IncScheduler.py Daily
0 0 * * 0 root /usr/local/CyberCP/bin/python /usr/local/CyberCP/IncBackups/IncScheduler.py Daily
```

Thanks!

**Comment by meramsey** [comment]
This is intentional as the crons are now setup under the root user crontab.
as root do this:
crontab -l
```

0 * * * * /usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/findBWUsage.py >/dev/null 2>&1
0 * * * * /usr/local/CyberCP/bin/python /usr/local/CyberCP/postfixSenderPolicy/client.py hourlyCleanup >/dev/null 2>&1
0 0 1 * * /usr/local/CyberCP/bin/python /usr/local/CyberCP/postfixSenderPolicy/client.py monthlyCleanup >/dev/null 2>&1
0 2 * * * /usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/upgradeCritical.py >/dev/null 2>&1
0 2 * * * /usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/renew.py >/dev/null 2>&1
```

This also fixed up the invalid paths alot of people had with the python and fixed people getting spammed to the root@localhost email account each time all these crons ran.

**Comment by gabrielcossette** [comment]
Weird, these commands are not in my root's crontab either?

**Comment by meramsey** [comment]
That is strange.. you can crontab -e and then paste them in then.

I have not heard of anyone else having that issue and it looks like this code should be in the /plogical/upgrade.py file which is in both stable and 1.9.4 upgrade.

https://github.com/usmannasir/cyberpanel/blob/1c3970aab3c75a74691e6c4fc92b9ee1c92204ad/plogical/upgrade.py#L2039-L2078

**Comment by Prahapp** [comment]
I have exact same issue. I've just added manually the commands that you posted up there

> 
0 * * * * /usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/findBWUsage.py >/dev/null 2>&1
0 * * * * /usr/local/CyberCP/bin/python /usr/local/CyberCP/postfixSenderPolicy/client.py hourlyCleanup >/dev/null 2>&1
0 0 1 * * /usr/local/CyberCP/bin/python /usr/local/CyberCP/postfixSenderPolicy/client.py monthlyCleanup >/dev/null 2>&1
0 2 * * * /usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/upgradeCritical.py >/dev/null 2>&1
0 2 * * * /usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/renew.py >/dev/null 2>&1

**Comment by gabrielcossette** [comment]
I upgraded 2 more servers and same issue. I already have other commands in root's crontab, could that be the reason?
If this is a widespread issue, servers of unaware users won't renew SSL certificates...

**Comment by meramsey** [comment]
I pinged @usmannasir about switching this to append method like install uses
https://github.com/usmannasir/cyberpanel/blob/1c3970aab3c75a74691e6c4fc92b9ee1c92204ad/install/install.py#L1682-L1688

but ideally there needs to be some checks to ensure its only adding the cronjob if its missing on upgrades and to the real root users cronjob.

Something like the below would be more future proof as they have options to edit stuff based on comments or search via regex to see if the cron already exists 
https://pypi.org/project/python-crontab/

`from crontab import CronTab

empty_cron    = CronTab()
my_user_cron  = CronTab(user=True)
users_cron    = CronTab(user='username')

job1 = cron.new(command='/usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/findBWUsage.py >/dev/null 2>&1', comment='findBWUsage')
job2 = cron.new(command='/usr/local/CyberCP/bin/python /usr/local/CyberCP/postfixSenderPolicy/client.py hourlyCleanup >/dev/null 2>&1', comment='postfixSenderPolicyhourly')
job3 = cron.new(command='/usr/local/CyberCP/bin/python /usr/local/CyberCP/postfixSenderPolicy/client.py monthlyCleanup >/dev/null 2>&1', comment='postfixSenderPolicymonthly')
job4 = cron.new(command='/usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/upgradeCritical.py >/dev/null 2>&1', comment='upgradeCritical')
job5 = cron.new(command='/usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/renew.py >/dev/null 2>&1', comment='LErenew')

job1.setall('0 * * * *')
job2.setall('0 * * * *')
job3.setall('0 0 1 * *)
job4.setall('0 2 * * *')
job5.setall('"0 2 * * *')

cron.write_to_user( user='root' )`

**Comment by usmannasir** [comment]
@whattheserver 

This should resolve https://github.com/usmannasir/cyberpanel/commit/ca88fa61e3d8fef3dcd975b9d2f0c22fedc56b6d
