### ISSUE TITLE
Litespeed server dies after issuing SSL to a domain

### ISSUE THREAD

**Issue by dyrer** [litespeedtech/cyberpanel#244]
After upgrade to 1.9.4 litespeed server dies after issuing SSL to a domain

**Comment by Prahapp** [comment]
Also happens to me not always but it happens every 2-3 times

**Comment by xiaoyong-wang** [comment]
Make a bash script in /root named script.sh which contains this:
#!/bin/bash

while [ true = true ]
do
systemctl status lsws

if [[ $? != "0" ]] ; then
    /usr/local/lsws/bin/lswsctrl stop
    systemctl stop lsws
    pkill openlitespeed
    pkill lsphp
    systemctl start lsws
    sleep 10
else 
    sleep 10
fi
done


After that run this command: nohup bash /root/script.sh > /dev/null 2>&1 &
Every time you reboot your server make sure to run: nohup bash /root/script.sh > /dev/null 2>&1 &

**Comment by usmannasir** [comment]
@Kasper2040 

Thanks for the temporary fix, but this is still a bug in OpenLiteSpeed and needs to resolve from the root, I will close this issue from cyberpanel repo.
