### ISSUE TITLE
Editing vhost context returns 404

### ISSUE THREAD

**Issue by jasonmoonen** [litespeedtech/cyberpanel#245]
We are running the latest version of openlitespeed (1.6.7)

On a vhost we've added this expression: exp:^(.*(?<!\/content)((\/help)|(\/setup)).*)$

I noticed that it uses javascript to load the configuration and when it does it returns an internal server error (500) on /view/confMgr.php

**Comment by usmannasir** [comment]
@jasonmoonen 

Kindly open this up in OpenLiteSpeed repo.
