### ISSUE TITLE
1.9.4 suspension issue

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#250]
In 1.9.4 when you suspend a website it doesn't suspend its child domains.
I was told in 1.9.4 this would be fixed but i use 1.9.4 and i still receive this issue

**Comment by usmannasir** [comment]
ok, let me check.

**Comment by usmannasir** [comment]
Resolved https://github.com/usmannasir/cyberpanel/commit/4ae815313af63724df8e163fd5d9c3b84333eadf
