### ISSUE TITLE
Convert child domain to website error

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#252]
On /websites/listChildDomains when you click Convert to Website, you are able to click the Convert button without filling out any fields.  Can you make it so all fields like Package are required before clicking Convert?  Otherwise, some people like my customers will click it and their child domain will just get deleted.

**Comment by usmannasir** [comment]
let me check.

**Comment by usmannasir** [comment]
Fixed in v1.9.5 branch, you will have to wait for this release or choose this branch when asked for during upgrade.
