### ISSUE TITLE
LiteSpeed Server Goes Offline Once I Try To Add A New Website.

### ISSUE THREAD

**Issue by DaljitKhalsa** [litespeedtech/cyberpanel#255]
Hi there, I have been using Litespeed from a year now. And I never faced this issue before, but from last few weeks, I noticed that when I try to add a new website to the LiteSpeed then it goes offline or something. Then I have to restart my VPS Server. Then LiteSpeed starts working again. Right now, I have to add a new website to the LiteSpeed, and I am not able to add it. Can anyone help, please?

**Comment by usmannasir** [comment]
If you are using OpenLiteSpeed, run this command and see if your issue is resolved -> `/usr/local/lsws/admin/misc/lsup.sh -d -e 1.6.9`

**Comment by DaljitKhalsa** [comment]
Hi there, I have run the command. Here you can see the screenshot --> https://prnt.sc/r2obsw (I got one error when I run the command, Please see the screenshot to see the error)

After that, I restarted my VPS server and after 5 mint's wait, I tried to add a new website and got this error --> https://prnt.sc/r2od1b

If I use 8090 port then I do not get an error, and I can add new websites to openlitespeed.
I have added a new website with the 8090 port but the issue is still there for non 8090 port.

**Comment by usmannasir** [comment]
From user profile try setting security level to low. 

Your IP changes frequently? More debugging tips are available here -> https://cyberpanel.net/docs/log-files-on-cyberpanel/

**Comment by DaljitKhalsa** [comment]
Hi there, Thank you for your message. Brother Usman, I just updated the user profile security level to low.

Brother, I am not sure if this change will help me not to get my client's websites and emails stopped. I mean, the main issue is that even after I run the command **/usr/local/lsws/admin/misc/lsup.sh -d -e 1.6.9** the websites and emails are still shutting down. In other words, after a few hours, the openlitespeed server auto shut down and never restart by itself. My clients call me and tell me that their emails and websites are not working then I have to restart my VPS server every few hours. My clients and I are very frustrated with this issue. I am losing trust from my clients because of this issue. Can you please do any solution for me where my Litespeed does not shut down. If it does, then it should restart in 5-10 seconds.

This issue is not letting me update any website. Because every time I try to update someone on the WordPress site, the webserver is down. Here you can see the screenshot http://prnt.sc/r39wv5 and this 500 error --> http://prnt.sc/r39y3e

I am not able to do any update on any of my client's website. As when I go to update anything on any page on any website, the server shut down or something and I get an error every time.

If you say, I can give you my cyberpanel login details privately so that you can let me know if I should get a fresh install of openlitespeed on a different IP/VPS will fix the issue? I can hire any developer who can help me to get a fresh install. But I want to know what do you recommend. All i want is to get this issue fixed ASAP.

I do not know if the update or downgrade was successful with the command you gave me. Here is the screenshot --> http://prnt.sc/r3a57y and my current version is V1.9. Here is the screenshot --> http://prnt.sc/r3a5v3

**Comment by usmannasir** [comment]
My advice is to switch to LiteSpeed Enterprise as you are managing end-clients. 

For your bugs, I will report internally to the OLS developer. You can also directly report an OLS bug here -> https://store.litespeedtech.com/store/contact.php

**Comment by DaljitKhalsa** [comment]
Thank you, Usman Nasir, I will definitely check enterprise version today.

Ok, I will create the ticket on that link you provided.

**Comment by DaljitKhalsa** [comment]
Update:- I just created that ticket on the provided link above. Ticket number: #534551
Thank you.

**Comment by DaljitKhalsa** [comment]
Brother, Can you please send me the script for me to update the cyber panel to the latest version? As i heard that there is a leatest version released by you guys few days ago.
