### ISSUE TITLE
Buttons display issue on mobile

### ISSUE THREAD

**Issue by Tangol** [litespeedtech/cyberpanel#262]
Please note that there are some issue with displaying the responsive buttons.
As you can see, the buttons are larger than the display area.

**Tested on v1.9.4**
![Screenshot_20200216_135954_com android chrome](https://user-images.githubusercontent.com/3336728/74613182-d7351f00-5114-11ea-93f4-e0cbd8505b76.jpg)
![Screenshot_20200216_140012_com android chrome](https://user-images.githubusercontent.com/3336728/74613183-d7cdb580-5114-11ea-856d-2abfa6eb48af.jpg)

**Comment by usmannasir** [comment]
Fixed. https://github.com/usmannasir/cyberpanel/commit/0367a718f01fa29991314b3e94555985b945b761
