### ISSUE TITLE
Wordpress refusing passwords

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#265]
I have one customer that upgraded his Cyberpanel ( #257 ) het get some problems. After cyberpanel support fixed the upgraded problem, we noted that all wordpress users can not login anymore.

We fixed that problem changing all passwords again. Some users have to be created again to work.

Today I have other customer with very fresh cyberpanel installation and after migration (everything was done manually) all wodpress users have the same problem: can not login.

I am trying to understand how this is relationated with cyberpanel modules.

I already tried "low" and "high" security levels. With and without modsecurity. Double check if selinux is offline.

**Seems related with:**
- https://forums.cyberpanel.net/discussion/1553/fresh-install-cannot-login-to-wordpress-admin
- https://forums.cyberpanel.net/discussion/769/wordpress-does-not-enter-admin-panel-sll
- https://forums.cyberpanel.net/discussion/1028/cannot-login-to-wordpress-backend-with-modpagespeed-enabled

**Comment by franciscopaniskaseker** [comment]
Openlitespeed version:

```bash
[root@ ~]# rpm -qa | egrep -i "openlite"
openlitespeed-1.6.8-2.el7.x86_64
```

**Comment by usmannasir** [comment]
Do you have such problem with LSWS Ent as well?

**Comment by franciscopaniskaseker** [comment]
In both cases they not use lsws enterprise.

**Comment by franciscopaniskaseker** [comment]
Moved php 7.4 to 7.3 fixed.

The problem persist if I move to 7.4 again.

I will try to troubleshoot that.

**Comment by franciscopaniskaseker** [comment]
I found the problem.

> User authentication broken for usernames that include spaces (PHP bug #78929)
https://core.trac.wordpress.org/ticket/49395

> There's already a RC for 7.4.3 which should include the fix from https://bugs.php.net/bug.php?id=79174.

You can close this issue.

**Comment by usmannasir** [comment]
great, thanks.
