### ISSUE TITLE
Normal and incremental backups cronjobs

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#266]
**Problem:**
Any backup are being created.

**As a reference I will use this crontab:**
https://github.com/usmannasir/cyberpanel/issues/216#issuecomment-575021907

There is no python2 file.

```bash
[root@host ~]# ls -l /usr/local/CyberCP/bin/python2 
ls: cannot access /usr/local/CyberCP/bin/python2: No such file or directory
[root@host ~]# 

[root@host ~]# ls -l /usr/local/CyberCP/bin/python*
lrwxrwxrwx. 1 root root     7 Feb 15 14:28 /usr/local/CyberCP/bin/python -> python3
-rwxr-xr-x. 1 root root 11408 Feb 15 14:28 /usr/local/CyberCP/bin/python3
lrwxrwxrwx. 1 root root     7 Feb 15 14:28 /usr/local/CyberCP/bin/python3.6 -> python3
-rwxr-xr-x. 1 root root  2336 Feb 15 14:28 /usr/local/CyberCP/bin/python-config
[root@host ~]# 
```

**Comment by franciscopaniskaseker** [comment]
I found this commit 8d77c7336f0cc1d47ee2937685e8c6edd3bda7e6

I think the dev team changed to python 3 and forgot to re-do the crontab. Or maybe who had the server broken due to upgrade fail ( #257 ) some scripts were not executed doing upgrade.

I fixed manually changing "python2" to "python".

**Comment by usmannasir** [comment]
I am sorry for that, glad you figured it out. New jobs are configured with py3.
