### ISSUE TITLE
Unable to move folders in file manager

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#268]
In the cyberpanel file manager, i am unable to move folders, i can only move files.

**Comment by usmannasir** [comment]
did you switch to v1.9.5?

**Comment by xiaoyong-wang** [comment]
Yes

**Comment by usmannasir** [comment]
v1.9.5 is active development and beta. Please use v1.9.4 which is the current official stable version.

**Comment by usmannasir** [comment]
However, I will check this issue in v1.9.5 and create a fix.

**Comment by usmannasir** [comment]
I tried moving a folder, it seems no issue. Kindly provide steps to reproduce the issue.

**Comment by xiaoyong-wang** [comment]
It looks like it was a permission issue.  I clicked fix permissions and it now works.
