### ISSUE TITLE
Setup Email Forwarding form problem

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#269]
**Problem:**
When I create more than one e-mail forwarding using the same session, the form does not refresh in the right way.

See an example.

Supose that I setup one e-mail forwarding.
1. select website
2. select email
3. select forward to email
4. fill the email field
5. click in blue button forward email

Then I want to create another forward in other website using the same form;

1. select website
2. select email
3. "forward to email" will be already selected due last email forward creation
4. In the step 4 I can not fill the "email field" due ajax not load the field. I have to click in "pipe to program" and then turn back to "forward to email" to load the email field
5. click in blue button forward 

I think when you select "website" or maybe the "email" listbox the next fields must be reloaded.

**Comment by usmannasir** [comment]
Fixed, but you will only get it if you upgrade to v1.9.5 branch. (This branch is active development)
