### ISSUE TITLE
add subdomain not work v1.9.4 and v1.9.5

### ISSUE THREAD

**Issue by benzbenz900** [litespeedtech/cyberpanel#270]
add subdomain not work v1.9.4 and v1.9.5
step

1. goto https://ip:8090/websites/cii3.net
2. Add Domain
3. Domain Name = jellys.cii3.net
4. Create Domain -> Error

![cyberpanel-add-sub-domain-not-work](https://user-images.githubusercontent.com/3780279/75468499-e42cfa80-59bf-11ea-9506-0780380040b9.gif)

**Comment by usmannasir** [comment]
Fixed this earlier today. Upgrade to v1.9.4 again

https://github.com/usmannasir/cyberpanel/commit/5d34aad07b27a922ec3b2e09cfa1a4fd9d508365
