### ISSUE TITLE
WordPress installer not working

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#271]
When i use the cyberpanel wordpress installer it will load for 3 seconds then say wordpress was successfully installed, when it wasnt.

**Comment by usmannasir** [comment]
`touch /usr/local/CyberCP/debug`

Again install WP, and share last 30 lines of main log file.

**Comment by xiaoyong-wang** [comment]
It shows a permissions issue.  I clicked fix permissions in file manager and it works now.
I also noticed that when you download a file through the file manager in 1.9.5 it redirects here again: downloadFile?domainName=example.com&fileToDownload=/home/example.com/public_html/index.html

**Comment by hennaboy** [comment]
1.9.5 is beta don't use in production

**Comment by usmannasir** [comment]
Please do not create a Github issue for any minor issue that you find. Use debugging tips to find if it really is a bug. 

And use our helpdesk if it is not a bug request, otherwise, I will have to close such issues.

Regards.
