### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#286]
Whenever i create a new website on cyberpanel, i cannot see what is inside public_html and when i visit the site it either shows a 404 error or a 403 error.  when i click fix permissions or change the permissions to 777 in the file manager, it does not change anything.  
I use ubuntu 18.04 
This happens on cyberpanel 1.9.5 ( i downgraded to 1.9.4 and the permissions issue is solved but it still happens on 1.9.5)

**Comment by usmannasir** [comment]
I see, right now v1.9.4 is stable.

But I fixed some permissions issues in v1.9.5. Can you reproduce even if you install v1.9.5 on a fresh server?

**Comment by aonsyed** [comment]
Hi, @materthewelon I have tried to recreate the issue but failed, can you open up a ticket at https://platform.cyberpanel.net/support/createTicket so I can get logs or access to diagnose the issue on your end?

**Comment by xiaoyong-wang** [comment]
Yes, I can create a ticket.
Also, could this be a configuration issue with the permissions?

**Comment by aonsyed** [comment]
If you have made some configuration changes, that might be the case, please open up a ticket so I can debug better.
