### ISSUE TITLE
cyberpanel.sh script host, no IPv6

### ISSUE THREAD

**Issue by Abd-w** [litespeedtech/cyberpanel#290]
The website for cyberpanel.sh script download, https://cyberpanel.sh has no AAAA records. So it doesn't install on IPv6 only machines.

**Comment by aonsyed** [comment]
CyberPanel is a IPv4 panel. IPv6 can be additionally supported but it needs IPv4 primarily for binding port 8090.

**Comment by qtwrk** [comment]
Hi,

Yes, well , the provide that server hosted , doesn't have IPv6

**Comment by qtwrk** [comment]
I set up a reverse proxy for ipv6 , but then I realize it won't work without ipv6 , at least not for now,   i will keep the ipv6 proxy and wait for Usman to implement ipv6 support.
