### ISSUE TITLE
Cloudflare Integration Not Working?

### ISSUE THREAD

**Issue by Whitei520** [litespeedtech/cyberpanel#291]
Unless i'm being thick and missing something, I cant seem to get the Cloudflare API integration working. I've tried using Ubuntu and CentOS, VM and Dedi, Different IP, Different Domain. Sadly every time I try and check the DNS entries tab, I get this error:

"Cannot fetch records. Error message:module 'CloudFlare' has no attribute 'CloudFlareAPIError'"

Can also be seen in screenshot:
https://i.imgur.com/Zwb26tZ.png

I did create the API key correctly, followed documentation verbatim.

Also cant seem to find any logs that relate to this. Any help would be super!

**Comment by aonsyed** [comment]
Hi, can you use global API to confirm?

**Comment by Whitei520** [comment]
Oh, that works perfectly. You have no idea how much time you have saved me!
As for why the original API key didn't work, any reason this config would fail?
https://i.imgur.com/frcuo9Y.png

**Comment by aonsyed** [comment]
I am going to test why that isn't working.

**Comment by usmannasir** [comment]
@aonsyed maybe update the documentation, so that people use Global API key.

**Comment by aonsyed** [comment]
@usmannasir updated.

**Comment by usmannasir** [comment]
I will close the issue now.

**Comment by meirroth** [comment]
Hi, @usmannasir is it possible to use a zone specific API token instead of a Global key? (for better security)

**Comment by usmannasir** [comment]
It is not possible to use the zone key.
