### ISSUE TITLE
Cron Jobs not running

### ISSUE THREAD

**Issue by Orel-A** [litespeedtech/cyberpanel#293]
CyberPanel 1.9.4
Ubuntu 18.04.4 LTS

Creating cron jobs via CyberPanel
https://IPADDRESS:8090/websites/listCron
Will create a cron file in /var/spool/cron/crontabs/USERNAME
with permissions -rw-r--r--
However this is wrong as it will give
(USERNAME) INSECURE MODE (mode 0600 expected) (crontabs/USERNAME)
It won't run!
setting chmod to 600 solves the problem

Another problem is that if you have more than 1 cron job, and you delete one in CyberPanel they will both be deleted.

**Comment by usmannasir** [comment]
Fixed on v1.9.5 branch

https://github.com/usmannasir/cyberpanel/commit/db17cd1dd3f0b39a8ea7836ff3692bb1bd7a603d
https://github.com/usmannasir/cyberpanel/commit/f71e052742984bdc65c5c256eb6a771c14af38e8
