### ISSUE TITLE
v2.0.0 Failed pull via webhooks in new Git manager

### ISSUE THREAD

**Issue by jovaniedelacruz** [litespeedtech/cyberpanel#296]
UpCloud VPS
CentOS 7
CP v2.0.0 (Upgraded 4/1/2020)

Failed pull via webhook. 

Updated to version 2.0.0, removed my repo and attached again, and cleared browser cache.
After following the documentation at https://cyberpanel.net/docs/automating-git-with-git-configure-and-webhooks/ 
I get a failed payload delivery from GitHub. I used the webhook URL similar to 

`https://<serverIP>:8090/websites/<domain>/webhook`

Headers

```
Connection: Keep-Alive
Content-Language: en
Content-Length: 145
Content-Type: text/html
Date: Wed, 01 Apr 2020 22:45:45 GMT
Server: LiteSpeed
Vary: Accept-Language, Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
```

Body

```
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
```

In previous versions of CP the webhook URL was 

`https://<serverIP>:8090/websites/<domain>/gitNotify`

If I try this instead it results as expected

Headers

```
Connection: Keep-Alive
Content-Language: en
Content-Length: 38
Content-Type: text/html; charset=utf-8
Date: Wed, 01 Apr 2020 21:52:56 GMT
Server: LiteSpeed
Vary: Accept-Language, Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
```

Body

```
{"pulled": 1, "error_message": "None"}
```

However, the pull is not reflected in web content, git manager does not show the new commit, and the CP main log reports
`[04.01.2020_21-42-30] local variable 'website' referenced before assignment [ApplicationInstaller.gitPull]`

Based on these few things I think it's an issue with variable assigning of the website and which webhook URL to use in Git Manager.

**Comment by usmannasir** [comment]
Can you do `rm -rf /home/cyberpanel/git` and try again.

However, you will lose your git configuration. And make sure to follow new documentation

https://cyberpanel.net/docs/how-to-use-git-manager-in-cyberpanel/
https://cyberpanel.net/docs/automating-git-with-git-configure-and-webhooks/

**Comment by jovaniedelacruz** [comment]
@usmannasir 
Hello, I have done rm -rf /home/cyberpanel/git and tried again. 
I followed both of those guides to no avail.

GitHub payload failed delivery due to server error 500.
CP main log reports this when I pushed two different commits to my repo.
`[04.02.2020_21-36-03] Expecting value: line 1 column 1 (char 0)`
`[04.02.2020_21-37-07] Expecting value: line 1 column 1 (char 0)`

Only a manual pull from the the new 2.0.0 git manager successfully pulls new commits. 

> Can you do `rm -rf /home/cyberpanel/git` and try again.
> 
> However, you will lose your git configuration. And make sure to follow new documentation
> 
> https://cyberpanel.net/docs/how-to-use-git-manager-in-cyberpanel/
> https://cyberpanel.net/docs/automating-git-with-git-configure-and-webhooks/

**Comment by jovaniedelacruz** [comment]
I restarted my server and it seems to work now. I no longer see the CP main log reporting
`Expecting value: line 1 column 1 (char 0)`

**Comment by ofyalcin** [comment]
https://IPADDRESS:8090/websites/WEBSITE/webhook address gives 500 error.

I am using CyberPanel version 2.3.
I have done all the settings correctly by following the documentation.
I also did " rm -rf /home/cyberpanel/git".
Nothing changed. The webhook address gives an error.
