### ISSUE TITLE
permission and ssl issues 2.0

### ISSUE THREAD

**Issue by adzkii-i** [litespeedtech/cyberpanel#299]
creating new sites throws a 404 not found error page, found out it was permission problems, 0711 set by cyberpanel. i have too manually set the permissions to the directory to 0755 for the site to work.
also noticed upgrading from previous version to 2.0, ssl no longer generates for the sites created. error logs showing nothing relevant to these problems.

ubuntu 18x
cyberpanel 2.0, openlitespeed

**Comment by usmannasir** [comment]
You service provider?

**Comment by usmannasir** [comment]
Fixed https://github.com/usmannasir/cyberpanel/commit/d0fd6316774443a8920d969df6e5895819bb8dde

You can change back public_html to 750, and group of folder to nogroup (this is only for ubuntu).

**Comment by mradzkii** [comment]
how shall i apply the fixes?
