### ISSUE TITLE
sub-domain home directory location

### ISSUE THREAD

**Issue by Ezyweb-uk** [litespeedtech/cyberpanel#300]
I've searched in Google and can't find any way to configure a sub-domain directory to appear at the same level as public_html, ie /home/domain.com/**sub.domain.com** instead of /home/domain.com/**public_html/sub.domain.com** 

With the current structure I'm not sure if I would be able to install a Laravel project which relies on the application files residing outside of public_html, normally one level above. Also on the forums I read that someone was not able to install WordPress after having setup a sub-domain. Seems to be a fundamental limitation for an otherwise brilliant control panel.

**Comment by usmannasir** [comment]
I can add it as feature but in v2.0.1. Dev already stopped for v2.0.0. Will create new branch today

**Comment by Ezyweb-uk** [comment]
Thanks, that would be brilliant!

**Comment by usmannasir** [comment]
https://github.com/usmannasir/cyberpanel/commit/2d891fdd46674ba8a4d6f31b530345104def1457

Ref https://forums.cyberpanel.net/discussion/comment/9061/#Comment_9061
