### ISSUE TITLE
CyberPanel to Google Drive or Dropbox Backups

### ISSUE THREAD

**Issue by jsahani** [litespeedtech/cyberpanel#304]
Hi Team,
Please add Google Drive or Dropbox v2 option for remote backup destination, as this is very important function, as right now we are unable to manage backups i have more than 36 VPS running for clients via Cyberpanel But we can't manage there backups, Would love to schedule backups and send them automatically to Google Drive or Dropbox v2.

Please if you can share some sort of "bash" script which can do this, Please help me with this.
Thanks, Quick reply will be appreciated.

**Comment by hennaboy** [comment]
This is more of a feature request then a bug. Kindly use our forums for feature requests. Kind Regards
