### ISSUE TITLE
Issue with Manage Github 

### ISSUE THREAD

**Issue by jsahani** [litespeedtech/cyberpanel#305]
Hi Team,

I installed Git in one of my "public_html" folder and initialized my first commit till this point everything is ok. But when i try to push my commit to my private repo it give me this error:-

**ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.
 
Please make sure you have the correct access rights
and the repository exists.**

Please advice.
Thanks

**Comment by aonsyed** [comment]
@jsahani please use the new git manager using this guide instead of older git installation using the following guides
https://cyberpanel.net/docs/how-to-use-git-manager-in-cyberpanel/
https://cyberpanel.net/docs/automating-git-with-git-configure-and-webhooks/

**Comment by jsahani** [comment]
Hey, I'm using this method only on v2.0 but its was not working and still not working.
So i did some RND and found the solution.

$ # Override SSH settings
$ vim ~/.ssh/config
```
# Add section below to it
Host github.com
  Hostname ssh.github.com
  Port 443

Please see to this.
Thanks
