### ISSUE TITLE
Qnap - Remote Backup Username

### ISSUE THREAD

**Issue by tariksisbacak** [litespeedtech/cyberpanel#320]
Hello there,

You have already stated that there will be a study on this subject.

I am using qnap and want to backup remotely.

But I cannot change the username. By default, it authorizes the "admin" user.

We cannot use the root user.
I want you to grant access to the root user.

So, I can transfer my backups to the qnap server.

Hope you can help
Thanks

**Comment by dedekorkud** [comment]
+

**Comment by meramsey** [comment]
https://github.com/usmannasir/cyberpanel/commit/da367bd776e7a830196edc9d4cd294e99a1156a6

This has been added in v 2.0.1 in case you have not seen it see reference commit above. If you have any issues with that please open a new bug with steps to reproduce and we can take a look into it.
