### ISSUE TITLE
[enhancement] backup remote transfer ajax update

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#329]
When one backup was finished to restore, you can see in the text area the message 

```bash
[04.29.2020_16-54-48] Backup Restore complete
completed[success]
```

but the page information (with green background) continue saying

```bash
Backup Process successfully started.
```

Will be good (and intuitive) to receive an update or other message saying "finished and the log was stored in(...)" as "Backup Process successfully started.".

**Comment by usmannasir** [comment]
Fixed in v2.0.1 branch. The box is removed once the local transfer is initiated.
