### ISSUE TITLE
Add user thru CLI

### ISSUE THREAD

**Issue by novuscloud** [litespeedtech/cyberpanel#335]
the only thing that is missing on CLI commands is user function, maybe you can add this as soon as possible

https://docs.cyberpanel.net/doku.php?id=cli

**Comment by franciscopaniskaseker** [comment]
I think there is other essential features needed too. May you can edit this topic to be more general.

- [ ] Add user
- [ ] Del user
- [ ] List users
- [ ] Suspend user
- [ ] Unsuspend user
- [ ] Edit user properties
- [ ] Add cronjob
- [ ] List cronjob
- [ ] Remove cronjob
- [ ] Set basedir config
- [ ] Unset basedir config

**Comment by usmannasir** [comment]
I solved the original issue in this thread. Will add following in v2.0.2

Add cronjob
List cronjob
Remove cronjob
Set basedir config
Unset basedir config

Rest of the features are added in v2.0.1 branch.

Regards
