### ISSUE TITLE
IPV6 Implementation

### ISSUE THREAD

**Issue by fmohican** [litespeedtech/cyberpanel#340]
Hello,
If it's possible, I would like to have support for IPV6 because at the moment the cyberpanel doesn't include that by default when the domain its added.

**Comment by j-a-pope** [comment]
I think this is only an issue in OpenLiteSpeed and Enterprise supports IPv6 out of the box. At the moment you need to go to the OLS webadmin and change the listener from ALL to ALL IPv6. 

It's a bit irritating actually, and if CyberPanel could set the listener to use ALL IPv6 by default it would be a good idea.

**Comment by istiak101** [comment]
Please request this here https://feedback.cyberpanel.net/

**Comment by fmohican** [comment]
sure.

**Comment by istiak101** [comment]
https://feedback.cyberpanel.net/b/requests/p/ipv6-implementation
Please close this issue @usmannasir @aonsyed
