### ISSUE TITLE
[v2.0.0 / CentOS8] failed to download from lux repostiory

### ISSUE THREAD

**Issue by IOAyman** [litespeedtech/cyberpanel#341]
_**OS: CentOS 8.1
CyberPanel v2.0.0**_

On a fresh machine, installation is completed "successfully". However, during the process, it failed to download packages from `lux` repository.

I could confirm this easily afterwards:

```
# dnf update
CentOS 8 - x86_64 - Lux                   3.9 kB/s | 226  B     00:00    
Failed to download metadata for repo 'lux'
Error: Failed to download metadata for repo 'lux'
```

It seems like the `lux` repo does not provide packages for CentOS 8.
A quick fix would be to fallback to the CentOS7 repo:
```
# cat /etc/yum.repos.d/lux.repo 
[lux]
name=CentOS $releasever - $basearch - Lux
baseurl=http://repo.iotti.biz/CentOS/7
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-LUX
```

However, this should be addressed during installation.

**Comment by hennaboy** [comment]
This is not an issue as such as Centos 7 is recommended at this time. Centos 8 is under way and a list of known issues including this one is already noted. Thanks for your contribution.

**Comment by IOAyman** [comment]
You're welcome :)
Is there an ETA for CentOS 8 full support, please?
