### ISSUE TITLE
WHMCS module cyber panel not working

### ISSUE THREAD

**Issue by royaljaat111** [litespeedtech/cyberpanel#345]
Hello,

Cyber panel whmcs module is not working. I have enabled api access to the user and whitelist Ips on whmcs as well on cyber panel. But I got this on module logs:

Request: 
/home/username/public_html/whmcs/modules/servers/cyberpanel/api.php
Response:
sds

Please help me out on this.

Best Regards

**Comment by hennaboy** [comment]
3rd party module.
