### ISSUE TITLE
PowerDNS Slave config not persisting (UI) & duplicating in pdns.conf

### ISSUE THREAD

**Issue by perf3ktion** [litespeedtech/cyberpanel#346]
Hey all,

I am setting up a CyberPanel hosting server with two DNS Slaves. All are currently running **CentOS Linux release 7.8.2003 (Core)** with **CyberPanel 2.0**.

**Issue**

When configuring PowerDNS as a Slave in the UI, after saving the config does not persist in the UI if you return / refresh the PDNS service page. If you make changes to the configuration in the PDNS service page and save them, instead of replacing the existing config in /etc/pdns/pdns.conf, it appears CyberPanel is appending this to the end of the existing config. The result is a repeated block of the following:

slave=yes
daemon=yes
disable-axfr=yes
guardian=yes
local-address=0.0.0.0
local-port=53
master=no
slave-cycle-interval=60
setgid=pdns
setuid=pdns
superslave=yes

This is duplicated approximately by how many times you save the configuration.

**Expected**

1. Configure PowerDNS as a Slave with slave hostname and master IP.
2. Configuration persists in the UI through a refresh of the page.
3. Configuration does not append to the end of the pdns.conf file and duplication existing conf.

**Steps to Reproduce**

1. Login to CyberPanel
2. Browse to Server > Manage Services > Manage PowerDNS
3. Select Function Mode: SLAVE
4. Enter in hostname of the slave (the server you're on)
5. Enter the IP address of the master server
6. Click Save Changes
7. Reload this same page (or navigate to it) and notice the configuration has not persisted.
8. View the pdns.conf file at /etc/pdns and notice the duplicated config at the end of the file

**Notes**

This does not appear to happen when configuring a master server. The config does not duplicate and it persists through refreshes of the page.

**Comment by jacewalker** [comment]
Same issue! +1

**Comment by usmannasir** [comment]
I will fix, can you confirm if it works when configured the first time?

**Comment by perf3ktion** [comment]
Can confirm, it does work the first time. Subsequent saves it does not appear to duplicate the config, and it does not work. Thanks for picking this one up 👍

**Comment by usmannasir** [comment]
I added 2 commits to address this issue, try by installing CyberPanel 2.0.1 on fresh Centos 7.x using below guide

```
wget https://raw.githubusercontent.com/usmannasir/cyberpanel/v2.0.1/cyberpanel.sh
chmod +x cyberpanel.sh
./cyberpanel.sh
````

when asked please input version 2.0.1.
