### ISSUE TITLE
Can't count 100GB of ram?

### ISSUE THREAD

**Issue by theraw** [litespeedtech/cyberpanel#350]
![image](https://user-images.githubusercontent.com/32969774/82767772-3bf5c900-9e2a-11ea-85c3-abd026da5a69.png)

**Comment by aonsyed** [comment]
Fixed in https://github.com/usmannasir/cyberpanel/commit/c1f560001881a4337aee110c2c652604b31eb972

Fix will be released with 2.0.1, however you can manually change for now.
