### ISSUE TITLE
Installer won't install CyberPanel to Ubuntu 20.04 as listed in release 2.01

### ISSUE THREAD

**Issue by themew** [litespeedtech/cyberpanel#352]
Error msg:  CyberPanel is supported on Ubuntu 18.04, CentOS 7.x and CloudLinux 7.x... 

2.0.1 listed as stable > https://cyberpanel.net/docs/change-log-for-cyberpanel/

**Comment by qtwrk** [comment]
v2.0.1 is not in stable release yet , so stable installer won't work.

you can use v2.0.1 installer on ubuntu 20 , or wait for v2.0.1 merged into stable.
