### ISSUE TITLE
Error with used disk is greater than the allowed disk

### ISSUE THREAD

**Issue by haidv35** [litespeedtech/cyberpanel#355]
![z1908533865029_618bc95eb522a7febfee3a633e5fdb10](https://user-images.githubusercontent.com/20736458/83671278-9fd47a80-a5fe-11ea-9c98-fad4513ec60a.jpg)

**Comment by xiaoyong-wang** [comment]
if you try uploading something else while its above the limit does it let you upload it?

**Comment by haidv35** [comment]
> if you try uploading something else while its above the limit does it let you upload it?

Yes

**Comment by haidv35** [comment]
> if you try uploading something else while its above the limit does it let you upload it?

Can you help me ?

**Comment by xiaoyong-wang** [comment]
this is most likely an issue with cyberpanel itself, so they will need to fix it

**Comment by haidv35** [comment]
@usmannasir  Can you help me ?

**Comment by usmannasir** [comment]
Will take a look.

**Comment by haiclover** [comment]
> Will take a look.

Can you help me quickly? I am working on a project related to it

**Comment by istiak101** [comment]
@usmannasir @whattheserver I think this can be closed now as there is a feature now that makes users home directory immutable if enforced disk limit is enabled in the package.
