### ISSUE TITLE
Port 8090 not loading

### ISSUE THREAD

**Issue by xiaoyong-wang** [litespeedtech/cyberpanel#356]
When i visit port 8090 on my website, it doesnt work.  but OLS is running and lscpd is running

![image](https://user-images.githubusercontent.com/54741819/83697540-1dbf6400-a5b4-11ea-977d-e1b1943c6efc.png)

**Comment by hennaboy** [comment]
systemctl stop firewalld

which OS?

**Comment by xiaoyong-wang** [comment]
that worked, thanks
