### ISSUE TITLE
traditional backup cronjob: if removed, cyberpanel will not add anymore

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#372]
The cronjob

```bash
0 3 * * * root /usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/backupScheduleLocal.py
```

if removed (for any reason) and you try to schedule a new backup, cyberpanel will not guarantee if the cronjob is there. It can hide from user the correctly backup configuration. No backups will be created without the cronjob.

**Comment by meramsey** [comment]
This has been fixed for awhile pretty sure by this
https://github.com/usmannasir/cyberpanel/blob/stable/plogical/upgrade.py#L2357-L2411
