### ISSUE TITLE
I wasnt able to access the interface on port 8090 after install

### ISSUE THREAD

**Issue by enniosousa** [litespeedtech/cyberpanel#374]
I followed the doc on https://cyberpanel.net/docs/installing-cyberpanel/

1. Install from DigitalOcean Market Place
First I had tried install CyberPanel from DigitalOcean market place. Once droplet installed any relevant information how to proceed after install.

2. Manual Install
So I droped the previous droplet and I created a new empty with ubuntu 20.04. After 10 minutes the install was successfuly, but I wasnt able to access the port 8090 <https://<public-ip>:8090

**Comment by qtwrk** [comment]
Hi,

Please run following command , and post result

```
netstat -lnp | grep 8090

curl -I -XGET https://127.0.0.1:8090 -k

curl -I -XGET https://$(curl cyberpanel.sh/?ip):8090 -k
```

**Comment by enniosousa** [comment]
> Hi,
> 
> Please run following command , and post result
> 
> ```
> netstat -lnp | grep 8090
> 
> curl -I -XGET https://127.0.0.1:8090 -k
> 
> curl -I -XGET https://$(curl cyberpanel.sh/?ip):8090 -k
> ```

My ISP is blocking the outgoing port 8090. So I've been used a VPN. Thanks!
