### ISSUE TITLE
The script upgrade not correct

### ISSUE THREAD

**Issue by quyennguyenvan** [litespeedtech/cyberpanel#377]
in the line from 1458 to 1515 
not check all case of copy folder /usr/local/CyberCP/lscpd-0.2.5
exactly, not verify that the folder exists

`
            lscpdPath = '/usr/local/lscp/bin/lscpd'
if os.path.exists(lscpdPath):
                os.remove(lscpdPath)

            command = 'cp -f /usr/local/CyberCP/lscpd-0.2.5 /usr/local/lscp/bin/lscpd-0.2.5'
            Upgrade.executioner(command, command, 0)

            command = 'rm -f /usr/local/lscp/bin/lscpd'
            Upgrade.executioner(command, command, 0)

            command = 'mv /usr/local/lscp/bin/lscpd-0.2.5 /usr/local/lscp/bin/lscpd'
            Upgrade.executioner(command, command, 0)`
4 action not have strong verify and when all the action finished, not verify again, 
impact: the lcspd not exists and the web server for https:/ip-server:8090 not running

**Comment by quyennguyenvan** [comment]
the solution, create zip file in folder cyberpanel  and copy and unzip then can help avoid this impact !

**Comment by hennaboy** [comment]
I cannot replicate this on any upgrade on any OS. I believe this is a localized upgrade fail and you should run the upgrade script again.
