### ISSUE TITLE
CSF vs any firewall plugin vs cyberpanel firewall: avoid use multiple firewalls

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#381]
cyberpanel v2.0.1
centos 7 x64

When you install and enable CSF, if you try to use cyberpanel firewall, you will create a mess in iptables rules.

Will be good to show at least a red message about "CSF is enabled, please do not use this" or "XXX firewall plugin is bein used(...)".

**Comment by usmannasir** [comment]
CSF install disabled firewalld. thus the interface wont work.
