### ISSUE TITLE
Local Backups: wrong status on gui and "status" file

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#384]
cyberpanel v2.0.1 enterprise
litespeed enteprise
centos 7

Today I manually created one backup. The cyberpanel status gui, at this moment, show "Backing up email accounts..". And the "status" file on user home is the same.

I was curious why it take a lot of time if I do not have e-mails on that account. Then I discovered what actually is happening: The cyberpanel backup tool was creating .tar..gz file and not doing mail backups.

I think it need to be fixed because  some users can think the backup was failed (mainly if the user account, as my case, has a lot of gigabytes).

**Comment by usmannasir** [comment]
Thank you for mentioning this, fixed.
