### ISSUE TITLE
Ubuntu: GD library (built into PHP binary) does not come with websupport.

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#386]
cyberpanel enterprise v2.0.1
litespeed enterprise
ubuntu 18.04
fresh installation

GD library (built into PHP binary) does not come with websupport on Ubuntu. 

On Centos  the WebP is supported.

**Comment by qtwrk** [comment]
It's known issue ,  I reported this yesterday to LiteSpeed Tech package manager , waiting for their update.
