### ISSUE TITLE
Restore local backups is not working v2.0.1

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#387]
cyberpanel enterprise v2.0.1
litespeed enterprise
centos 7 x64
fresh server

I tried to manually copy the old server backup and the panel does not show any backup to be recovered.
Then I tried create a local backup and even the backup created by the new server, the web gui does not show.

I found a lot of backup issues today and I reported all of them here on git... is not good a basic feature like restore backups is not work :(

```bash
[root@itestore backup]# ls -lhrt
total 12G
-rw-------. 1    XXX    XXX  12G Jul  3 14:25 backup-XXX.YYY-07.03.2020_12-49-38.tar.gz
-rw-------. 1 XXX XXX 5.5K Jul  3 15:29 backup-XXX.YYY-07.03.2020_14-29-34.tar.gz
```

I tried as admin user and as XXX user and the web interface show nothing!

**Comment by usmannasir** [comment]
kindly chmod this file to 644.

```chmod 644 backup-XXX.YYY-07.03.2020_14-29-34.tar.gz```

**Comment by franciscopaniskaseker** [comment]
@usmannasir 

The first one (12G) I copied from old server, but the second one  (5.5K) was created by new server. So I think the chmod need to be fixed by cyberpanel backup system also.

**Comment by usmannasir** [comment]
I chmod this to `600` when backup is created so other users can not read the backup file as it contains MySQL logins and other important data.
