### ISSUE TITLE
Top Processes Incorrect Information

### ISSUE THREAD

**Issue by themew** [litespeedtech/cyberpanel#388]
Not sure if this was fixed in 2.0 b2 (didn't see it in the changes).  Server is a 4GB Ubuntu 20.04 server.  Swap is 4GB as well.

![image](https://user-images.githubusercontent.com/7772702/86540431-e00f6d00-beca-11ea-8860-cb287502b0dc.png)

**Comment by usmannasir** [comment]
I will check

**Comment by usmannasir** [comment]
Fixed.
