### ISSUE TITLE
API function to install WordPress [feature request]

### ISSUE THREAD

**Issue by Ezyweb-uk** [litespeedtech/cyberpanel#390]
It would be great if the brilliant CyberPanel could be extended to include an API function that would run an application install for WordPress, PrestShop, Joomla, or Magento. Would that be feasible?

**Comment by istiak101** [comment]
Please open this here https://feedback.cyberpanel.net/

**Comment by Ezyweb-uk** [comment]
@istiak101 thanks for the feature request link, I've added a request.
