### ISSUE TITLE
Compress auto-generated html .

### ISSUE THREAD

**Issue by XuJinsheng** [litespeedtech/cyberpanel#391]
How about to compress the auto-generated html codes to improve the speed when viewing the panel?
The html generated is so large that it's very slow to view the panel on my meterd host server.

**Comment by hennaboy** [comment]
The panel is slow to load? I think that is more an issue with the network you are on and the speed between your server and your location.

**Comment by XuJinsheng** [comment]
I tested it in virtual machine,and it's a bit slow.So I view the html generated and found there are so many whitespaces.

**Comment by hennaboy** [comment]
Of which is a very tiny issue. This would not cause the panel to load slowly this is clearly a network issue as per my previous reply.
