### ISSUE TITLE
Cant install imunify

### ISSUE THREAD

**Issue by mgilank** [litespeedtech/cyberpanel#392]
hi
i using cyberpanel version 2.0
already install cloudlinux + cagefs, kernel already load LVE
got this, it wont install
![2020-07-20 19_24_20-Not available - CyberPanel](https://user-images.githubusercontent.com/4758636/87937297-a93a7900-cabe-11ea-8e8a-dcbdeeee3a00.png)

**Comment by usmannasir** [comment]
Can you create ticket and let me know ticket id here.

**Comment by istiak101** [comment]
As this an old issue can you upgrade your installation to check if you still have this issue on latest version.

To upgrade follow this guide: https://cyberpanel.net/docs/upgrading-cyberpanel/

I will close this after few days assuming this is resolved.
