### ISSUE TITLE
Add Restart and Kill Detached PHP Processes buttons to Litespeed Status

### ISSUE THREAD

**Issue by meramsey** [litespeedtech/cyberpanel#397]
Add
- [[Restart detached PHP processes for the server level option](https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:php:detached_mode#for_the_server) ] 
- [[Kill detached PHP processes for the server level](https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:php:detached_mode#stop_all_immediately) ] 

Should be on the Litespeed Status page here where the reboot litespeed 
![image](https://user-images.githubusercontent.com/1596188/89143606-30550b80-d519-11ea-9c82-2a629b7bd319.png)

This will help admins when debugging to be able to easily restart/kill all detached processes when they restarted Litespeed but still seeing an issue they thought was fixed but not appearing to be fixed as the process was not restarted or stuck.

Like this:
https://forums.cyberpanel.net/discussion/comment/6360#Comment_6360

**Comment by usmannasir** [comment]
doing now in v2.0.3-dev branch on php and Litespeed pages.

**Comment by usmannasir** [comment]
I've added `Restart PHP` button on `:8090/managephp/editPHPConfigs` this is where users PHP settings and need to restart PHP directly from there.

thanks.
