### ISSUE TITLE
Following port 8090 removal tutorial + SSL causes buggy experience

### ISSUE THREAD

**Issue by ghost** [litespeedtech/cyberpanel#414]
Following the port 8090 removal tutorial which involves using some rewrite rules and adding an SSL cert to the hostname used in there causes cyberpanel views to fail often, the error is purely visual, most actions are performed correctly but sometimes a "Could not establish connection to server. Please refresh this window" error comes out, these errors appear on most pages like:

- add a new site
- configure one click apps
- Manage SSL for sites
- suspending sites
- saving configurations
- restarting litespeed
- and more

**Comment by aonsyed** [comment]
Issue has been fixed in 2.0.3-dev with a built in option to change port without using reverse proxy. Either use beta development version or wait for stable roll out.
