### ISSUE TITLE
CyberPanel: Operations Log

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#416]
Will be good to have a way to check all CyberPanel operations (creation, delete, changes etc). I am not asking from full details, but at least the command / script executed and its parameters.

Today I had a bunch of empty dirs created in /home/ about some domains that does not exist anymore (in cyberpanel and openlitespeed) and I can not have any kind of CyberPanel history to check what is happened.

**Comment by istiak101** [comment]
Around 0.10 am everyday some of my older domains folder gets created which no longer exist. I thought I was only having this weird issue. Will check which cron was doing this.

**Comment by franciscopaniskaseker** [comment]
Same time here.

**Comment by istiak101** [comment]
Check your /root/.acme.sh folder

I think this cron
7 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null

**Comment by meramsey** [comment]
I totally agree that better/improved logging for auditing activity sessions and logins needs to be implemented. I have previously mentioned some ideas about this on the forums as linked below.
https://forums.cyberpanel.net/discussion/1997/improved-logging-and-standardized-log-paths#latest
https://forums.cyberpanel.net/discussion/4151/cyberpanel-login-security#latest

Also submitted feature request referencing this issue.
https://feedback.cyberpanel.net/features/detailed-logging-for-login-activity-session-api-auditing

**Comment by usmannasir** [comment]
acme generate folders for deleted sites too?

**Comment by istiak101** [comment]
After deleting older domains folder from /root/.acme.sh folder it no longer creates any folder on /home during acme cron.

**Comment by usmannasir** [comment]
This folder is same on ubuntu?

**Comment by istiak101** [comment]
Yes. Default acme path

**Comment by usmannasir** [comment]
Fixed.

**Comment by franciscopaniskaseker** [comment]
@usmannasir the main question here was about cyberpanel logs to audit. is good that we found one bug, however the lack of ways to audit the things make harder the way to troubleshooting problems.
