### ISSUE TITLE
PowerDNS failed: Error message: (1406, "Data too long for column 'type' at row 1")

### ISSUE THREAD

**Issue by chiareu** [litespeedtech/cyberpanel#436]
After update to Cyberpanel 2.0.2 on CloudLinux7 server, PowerDNS is offline.
serverstatus/services/ PowerDNS Stopped
Manual starting give a Action Completed message, but PoweDNS it's still offline.

manageservices/managePowerDNS/ PowerDNS status: OFF
changing status give error: PowerDNS failed: Error message: (1406, "Data too long for column 'type' at row 1")

In order to resolve domains, I run pdns_server in console.
From time to time PowerDNS is down again and need to manual start it.

**Comment by usmannasir** [comment]
Fixed https://github.com/usmannasir/cyberpanel/commit/b427f9916164b958788d1a66ab68baafb8eb937f
