### ISSUE TITLE
Move mail child domain from public_html

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#438]
1. Users can remove that directory without understand what they are doing
2. Domains used to server set mail server configuration do not make sense to be inside of public_html
3. If we have more than one mail child domain, we can only set one per time in the server (postfix and dovecot), so child mail domain does not make sense to be available to everyone

I understand that the cyberpanel tried to reuse the child domain functionality, however it can make cyberpanel more confuse.

**Comment by istiak101** [comment]
#610 fixes this. Please close @usmannasir @whattheserver
