### ISSUE TITLE
cat: /home/cyberpanel/9494: No such file or directory

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#440]
Environment:
Centos 7 X64 server with cyberpanel fresh install (did some minutes ago).
The account use php 7.3.

Steps:
1. Login in the account
2. Select Magento to install
3. Fill the form
4. Start the installation

Error:
```bash
cat: /home/cyberpanel/9494: No such file or directory
```
![Screenshot from 2020-09-22 05-58-36](https://user-images.githubusercontent.com/8779476/93862603-ab74ab80-fc98-11ea-98aa-52a22b783f1c.png)

**Comment by istiak101** [comment]
commit ref: https://github.com/usmannasir/cyberpanel/commit/fda1749754d3c3d425f298a1ba3643f9b9701dd2
@usmannasir @aonsyed

**Comment by r3cha** [comment]
Hello @istiak101 why comment out magneto instillation? something unstable?
I spent sometime trying understand why I can’t :)

**Comment by istiak101** [comment]
There was an indentation error. Check history of that file.

**Comment by naflan121** [comment]
still this issue exist on CP 2.1

**Comment by istiak101** [comment]
> Hello @istiak101 why comment out magneto instillation? something unstable?
> I spent sometime trying understand why I can’t :)

Magento doesn't work with MariaDB 10.5.

**Comment by yuri12344** [comment]
Same issue here, solved puting something in "path", like "/magento"
After this I created and don't get more this error, also I can access my website.com//magento

Or try remove, create dkim, and sub-domain e-mail.

Ty

**Comment by dankoz51** [comment]
I have the same issue adding a path does not help

**Comment by tmunsch** [comment]
Why is this still an issue on 2.3.1? This is ridiculous. I am having the same issue on Arma 8 and wordpress, The cyberpanel literally can't do what it's whole purpose is. This is beyond absurd

**Comment by usmannasir** [comment]
We've discontinued Mangento installations due to its latest requirments and not really suitable to run on OLS.

**Comment by tmunsch** [comment]
This is happening with Wordpress installs as well on 2.3.1
add me on discord teddytuned#5672 and i will give you access etc

**Comment by usmannasir** [comment]
I don't use discord anymore, you can open a thread here: https://community.cyberpanel.net/

**Comment by tmunsch** [comment]
How about i just create one here. Not trying to have another account to track

**Comment by tmunsch** [comment]
https://github.com/usmannasir/cyberpanel/issues/891
