### ISSUE TITLE
All error_log files under users directories are ampty

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#441]
**The problem:**
All error_log files under user log directoy are empty. The users can not see their logs.

**How I checked:**
I manage more than 30 servers running cyberpanel under CentOS 7 and I checked the same behavior.

**The sysadmin workaround:**
As root, check the lsws logs under /usr/local/lsws/logs/. However the users will not have access to those log files.

**Comment by istiak101** [comment]
OLS log level is ERROR in Vhost configuration which will generate less error logs. You can try switching to NOTICE and that should generate more verbose error logs.

**Comment by ghost** [comment]
I have installed the current version of cyberpanel this week and have the same issue.
:8090/websites/test.de/ -> Error Logs is always empty
regardless of occurring errors in php or other problems
