### ISSUE TITLE
v2.0.3 does not install imunifyav

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#446]
When I try to click in install, nothing happen.

![Screenshot from 2020-09-24 22-19-11](https://user-images.githubusercontent.com/8779476/94215835-236aed80-feb4-11ea-9568-5573a1a1bc6a.png)

**Comment by usmannasir** [comment]
Working fine for me, which OS are you trying?

**Comment by franciscopaniskaseker** [comment]
CentOS x86_64 and cyberpanel 2.0.3.
