### ISSUE TITLE
mail child domain is being create with www alias

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#447]
**Problem:**
child mail domain is being create with www alias. So when the client try to issue or renew this mail child domain, it will fail for www.

**What is expected:**
mail child domain do not create www alias.

**Comment:**
I understand that problem is because you are using same functionality from child domains that create www alias by default, however I think this behavior >> maybe << is useful for main domain only. To subdomains, mainly to mail child domain, www alias are not used most of the time.

**Comment by usmannasir** [comment]
I will close this, as CyberPanel later try to issue SSL for non-www version.
