### ISSUE TITLE
Magento 2.4 not compatible with MariaDB 10.5

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#453]
I upgraded one server to get Elasticsearch from Cyberpanel, however it also upgraded the MariaDB version to 10.5, which make Magento 2.4 incompatible (as only 10.4 is supported). It will break also the one-click magento installation from Cyberpanel.

I think cyberpanel have to control the mariadb upgrade to avoid this kind of problems... mariadb downgrade is not supported and if you do not have recent backups, you are in trouble.

**Comment by ru-dmitry** [comment]
Moreover, I think there should be on option to choose between MariaDB and MySQL Server (5.7, 8.0) during installation process.

**Comment by istiak101** [comment]
Fixed.
