### ISSUE TITLE
Mautic installation fails at "Running Mautic installer"

### ISSUE THREAD

**Issue by ghost** [litespeedtech/cyberpanel#458]
Current Mautic one click app fails at:

Running Mautic installer
`La instalacion ha fallado. Error: [404]` or "installation has failed. Error: [404]"

Details to reproduce this issue:

Cyberpanel details:

```
Latest Version
2.0
Latest Build
3
```

OS: Ubuntu 18.04

Steps:

* Create new site
* Choose PHP 7.3 (Mautic doesn't support 7.4 don't even try it)
* Add SSL to site
* Tap on "Mautic"
* Fill in details
* Everything performs well until "Running Mautic Installer" phase.

**Comment by usmannasir** [comment]
@aonsyed 

can you reproduce?

**Comment by aonsyed** [comment]
Is this in a child domain?

**Comment by ghost** [comment]
@aonsye A subdomain yes.

I think this might be related but installing it manually shows a Database population error since the row size is too low.

**Comment by ghost** [comment]
@VentGrey Upgrade to latest cyberpanel version. Just done test installation of mautic on latest version of cyberpanel without any issue. (and yes I was installing it on subdomain) with configured let's encrypt certificate.

@aonsyed is it possible to change installer so it will follow recommended security practices?
![1](https://user-images.githubusercontent.com/56940608/118372013-95ad5100-b5af-11eb-9f5e-2c45ad177c63.png)

![2](https://user-images.githubusercontent.com/56940608/118372015-980fab00-b5af-11eb-8268-639f6f006a46.png)

![3](https://user-images.githubusercontent.com/56940608/118372017-99d96e80-b5af-11eb-8e52-d3f459c1d0d7.png)

Automatic installer will set all paths to public_html
![4](https://user-images.githubusercontent.com/56940608/118372022-9e9e2280-b5af-11eb-842c-2f2629972fbf.png)

If you use mail queue there is another path that needs to be in private location /var/spool
![5](https://user-images.githubusercontent.com/56940608/118372084-f9377e80-b5af-11eb-946a-ce3fe09c4e8c.png)

**Comment by ghost** [comment]
Already tried again, the installer still gets stuck on the "Extracting core phase" and just cancels everything with a `[404] Error` I could open more issues reporting how the only installer that really works without issues is the WP + LSCache one, however it might be pointless. 

It is best to do the process manually for the sake of sanity.
