### ISSUE TITLE
rainloop admin password

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#461]
**Question:**
How can I retrieve or change the rainloop admin password?

**I want to access this interface:**
https://my_ip:8090/rainloop/?admin

**Comment by usmannasir** [comment]
`cat /usr/local/CyberCP/public/rainloop.php`

**Comment by franciscopaniskaseker** [comment]
Thank you. Maybe this info should be showed at the end of the cyberpanel setu, like cyberpanel and OLS services.
