### ISSUE TITLE
Can I find your API description to help you?

### ISSUE THREAD

**Issue by wartw98** [litespeedtech/cyberpanel#47]
Users who can only create English names in WHMCS modules will not be able to create them if they use other languages. Can I find your API description to help you?

**Comment by usmannasir** [comment]
Have a look at this https://note.youdao.com/share/?id=f7ffbb4dc8c1f11e43ff9ae4c595443f&type=note#/

This is still a work in progress, you can also look into code https://github.com/usmannasir/cyberpanel/blob/v1.7.1-dev/api/views.py

**Comment by wartw98** [comment]
{"createWebSiteStatus": 1, "error_message": "None", "existsStatus": 0}1
Creating an account on WHMCS will result in an Oops error in line 53.
Can I fix this?

**Comment by jezztify** [comment]
@wartw98 this is opensource, you can prolly create an issue for that problem, fork the repo, fix it there, create a merge request and reference the issue there :)

**Comment by usmannasir** [comment]
@wartw98 I've tested APIs via Postman, this should be an error on WHMCS side, you can download module code and see what is going on.
