### ISSUE TITLE
Child Domain - This site can’t be reached

### ISSUE THREAD

**Issue by plant7403** [litespeedtech/cyberpanel#471]
### Trying to create a child domain
Automatic mail domain creation works fine
But adding additional domains seems to not work
<img width="682" alt="Screenshot 2020-10-26 154821" src="https://user-images.githubusercontent.com/24483751/97152542-a62ce400-17a3-11eb-81be-8427c868de43.png">
it adds dns records the same with "mail" domain (which works)
but if I go to the page of my new child domain
<img width="899" alt="Screenshot 2020-10-26 154927" src="https://user-images.githubusercontent.com/24483751/97152704-deccbd80-17a3-11eb-9164-9f7e982c599b.png">
what do i need to do, what can be wrong?
i need to create child domains, thank you 😀

**Comment by istiak101** [comment]
Simply adding DNS records won't work. You will have to add child domain from List Website>Manage>Add Domains.

Please read the docs https://cyberpanel.net/docs/3-creating-and-managing-child-domains/

Please close if your issue is solved.

**Comment by jordanlambrecht** [comment]
Hi @xxxcrow. Please close this issue to help keep the Issues backlog clean <3

**Comment by plant7403** [comment]
@istiak101 @jordanlambrecht i found the problem, sorry for not closing
I needed to add the domain in linode/do panel 🙄
