### ISSUE TITLE
MYSQL 8 on CentOS 8.2 

### ISSUE THREAD

**Issue by domaingood** [litespeedtech/cyberpanel#479]
I want to install MYSQL 8 In CentOS 8.2 Because Most of the time MariaDB 10.5.5 shows the throughput under 100 tps (while MySQL averages above 5000 tps).

**Comment by usmannasir** [comment]
You can use MySQL repo to install MySQL 8 but it is not recommended and will not be supported by our support team incase anything goes wrong.

**Comment by domaingood** [comment]
Hi @usmannasir  please add support MYSQL 8 too Because its native centOS 8 database.

Thanks
