### ISSUE TITLE
.htaccess not working

### ISSUE THREAD

**Issue by ponasromas** [litespeedtech/cyberpanel#48]
```
# Deny access
Order allow, deny
Deny from all

# HTTP -> HTTPS redirect
rewriteCond %{HTTPS} !on
rewriteRule ^(.*)$ https://%{SERVER_NAME}%{REQUEST_URI} [R,L]
```

Part "Deny access" not working. File edited via "Rewrite Rules" in CP. No errors in logs.

**Comment by usmannasir** [comment]
**Order and Deny** directives are not supported by OpenLiteSpeed. **RewriteRule and RewriteCond** are supported. For **Order, Deny** you will have to use native conf, for more details you can read https://forums.cyberpanel.net/discussion/468/what-is-the-best-way-to-deal-with-htaccess-files-in-subdirectories
