### ISSUE TITLE
firewall is not working

### ISSUE THREAD

**Issue by alireza-salehi** [litespeedtech/cyberpanel#481]
VPS (2Core CPU/4GB RAM)
CentOS Linux release 8.2.2004 (Core)
CyberPanel 2.03

When I try to turn firewall on from (Security>Firewall), it flashes the rules on the page for a second, too fast to tell what is happening, and then it stays disabled. 

```
$ firewall-cmd --version
FirewallD is not running
```

```
$ systemctl status firewalld
● firewalld.service
   Loaded: masked (Reason: Unit firewalld.service is masked.)
   Active: inactive (dead)
```

there is no log file inside '/var/log/firewalld'

how to enable and manage firewall.

**Comment by domaingood** [comment]
Please try this 
Unmask
On analyzing the firewalld service we found a mask firewall set. Thus to resolve the error we unmask the firewalld service. We can enable the firewall service if it is not masked.

To unmask the service we use the command

systemctl unmask --now firewalld
After executing the command we get the output as

failed to start firewalld service unit is masked

Now we enable the firewalld service using the command

systemctl enable firewalld
Finally, we start the firewalld service using the command

systemctl start firewalld
 

Mask link is broken
One of the common reasons for the error is when starting the service the masked link is broken. Thus we need to link the mask location once again to resolve the error.

To unmask the service we use the command.

systemctl unmask firewalld
Thus, if the service still fails to unmask we need to manually mask it first. The location will change based on the Linux flavors.

ln -s /etc/systemd/system/firewalld.service /dev/null
Thus we unmask it. Then we start the service using the command

systemctl start firewalld
Finally, we find the status using

firewall-cmd --state
 

Failed to start firewalld service
If the above solution did not fix the error. We need to analyze the logs to determine more details about the error.

Our Support Engineers find more information using the command

systemctl status firewalld.service
We find further information from journalctl -xn

**Comment by alireza-salehi** [comment]
>
> To unmask the service we use the command 
> systemctl unmask --now firewalld
> systemctl enable firewalld
> systemctl start firewalld
> 

it is fixed now,
