### ISSUE TITLE
EMAIL FORWARDING not working

### ISSUE THREAD

**Issue by Piradoxlanieve** [litespeedtech/cyberpanel#485]
I have activated EMAIL FORWARDING, but it doesn't work.
The email is sent from gmail to the domain that is in cyberpanel, but from cyberpanel it is not forwarded to another gmail account.

Nov 20 20:10:24 vmi433971 postfix/pipe[7045]: DBC93801A56: to=<info@domain.tld>, relay=spamassassin, delay=3.5, delays=3.3/0.01/0/0.25, dsn=2.0.0, status=sent (delivered via spamassassin service)
Nov 20 20:10:24 vmi433971 postfix/pipe[7044]: DBC93801A56: to=<xxxxxmail@gmail.com>, orig_to=<info@domain.tld>, relay=spamassassin, delay=3.5, delays=3.3/0/0/0.25, dsn=5.1.1, status=bounced (user unknown)
Nov 20 20:10:24 vmi433971 postfix/cleanup[7009]: 46934801A54: message-id=<20201120191024.46934801A54@srv1.xxxxx.com>
Nov 20 20:10:24 vmi433971 postfix/qmgr[2887]: 46934801A54: from=<>, size=4874, nrcpt=1 (queue active)
Nov 20 20:10:24 vmi433971 postfix/bounce[7052]: DBC93801A56: sender non-delivery notification: 46934801A54
Nov 20 20:10:24 vmi433971 postfix/qmgr[2887]: DBC93801A56: removed
Nov 20 20:10:24 vmi433971 spamd[704]: prefork: child states: BI
Nov 20 20:10:24 vmi433971 spamd[704]: prefork: child states: II
Nov 20 20:10:24 vmi433971 postfix/smtp[7053]: connect to gmail-smtp-in.l.google.com[2607:f8b0:4003:c05::1a]:25: Network is unreachable
Nov 20 20:10:24 vmi433971 postfix/smtp[7053]: 46934801A54: to=<sendmailxxx@gmail.com>, relay=gmail-smtp-in.l.google.com[74.125.133.26]:25, delay=0.62, delays=0/0.01/0.33/0.27, dsn=2.0.0, status=sent (250 2.0.0 OK 1605899424 o128si3532245wmb.143 - gsmtp)
Nov 20 20:10:24 vmi433971 postfix/qmgr[2887]: 46934801A54: removed

The problem is related to the MailScanner, I did a clean installation, and after installing it the error has returned.

Sorry my bad english

**Comment by usmannasir** [comment]
Connect server to https://cloud.cyberpanel.net/ and reset email configurations. For now we don't provide support for mailscanner, its integrated by community effort.
