### ISSUE TITLE
Command Injection

### ISSUE THREAD

**Issue by JoaoReis98** [litespeedtech/cyberpanel#49]
I just tried your demo page "https://demo.cyberpanel.net:8090/" and i could inject commands remotely fix the injected input on server side and restrict the input on client side, for example if you try to create a database with the name: test; shudown          ( this is dangerous... i could just download a file and execute and take over the machine ... )
And yes it was me, i shutted down your demo page with that "hack" and now iam posting this so you can do a quick fix, the whole system is vulnerable.

Best regards.

**Comment by usmannasir** [comment]
The demo server is open with admin level access and resets every day, for commands shell is disabled, unless you have a full access how can you execute this case?

**Comment by JoaoReis98** [comment]
Look again, i shutted down the demo server again

**Comment by JoaoReis98** [comment]
i see that u patched the Database Create, but there are other places vulnerable.

**Comment by usmannasir** [comment]
You are right there was some issue on the database module only, which was shutting down mysql. I've added some additional checks, see if you still face the issue.
