### ISSUE TITLE
Cyberpanel upgrade script stopped working

### ISSUE THREAD

**Issue by ghost** [litespeedtech/cyberpanel#490]
I usually update my cyberpanel releases but since last week the cyberpanel script has stopped working suddenly. I don't know the exact reason why.

I am sure I'm using `sudo su - ` to avoid permissions conflicts. But the command just lays on the terminal, no output whatsoever.

**Comment by usmannasir** [comment]
Contact our support team at https://cloud.cyberpanel.net/
