### ISSUE TITLE
Add PHP 8 Support

### ISSUE THREAD

**Issue by maicol07** [litespeedtech/cyberpanel#492]
Currently, even with PHP 8 installed, it can't be selected from the PHP selector. Cyberpanel should detect installed PHP versions and show them

**Comment by usmannasir** [comment]
ok

**Comment by usmannasir** [comment]
Added https://github.com/usmannasir/cyberpanel/commit/4fb826861ef7ec5de03bb35a9bad2bf2f1183ae6
