### ISSUE TITLE
adding translation for CyberPanel

### ISSUE THREAD

**Issue by ghost** [litespeedtech/cyberpanel#494]
Hello,

I have seen the post on https://forums.cyberpanel.net/discussion/1680/how-to-write-translation-for-cyberpanel and I would like to add translation for CyberPanel.

The links in that post are not valid anymore.

What file do you recommend to select to do the translation? Do you notify people to add new strings when new functions are implemented?
- https://raw.githubusercontent.com/usmannasir/cyberpanel/v2.0.4-dev/locale/br/LC_MESSAGES/django.po 
- https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/locale/br/LC_MESSAGES/django.po

Or any other file?

How fast is the translation added and can be installed on server? Can you also manually install it on the server so you can test the translation?

Thank you!

**Comment by usmannasir** [comment]
Hello

Yes you can download latest file from current dev branch which is ```https://raw.githubusercontent.com/usmannasir/cyberpanel/v2.0.4-dev/locale/br/LC_MESSAGES/django.po```

However if this is some new language please take care of appropriate directory structure, if you take care of proper directory structure or if it is just addition to current language then you can directly make pull request to current stable branch and it will go live as soon as pull is merged.

Regards

**Comment by milanmaximo** [comment]
@usmannasir
I got it. 
Thank you so much for assistance.

Best regards
