### ISSUE TITLE
Mail domain is always generating SSL certs

### ISSUE THREAD

**Issue by gabriel-curtino** [litespeedtech/cyberpanel#496]
Hi!

When creating a new website WITHOUT "SSL" but WITH "Create Mail Server", CyberPanel is requesting and generating a Let's Encrypt cert. 

I think it shouldn't. 

Thanks for this great work!

**Comment by usmannasir** [comment]
The mail ssl is very important and which is why this feature was done, more details here -> https://cyberpanel.net/docs/6-self-signed-ssl-error-on-outlook-thunderbird/
