### ISSUE TITLE
Infinite loading when clicking on Manage on a website

### ISSUE THREAD

**Issue by maicol07** [litespeedtech/cyberpanel#497]
When I click manage on a website it takes forever to go to the website management page

**Comment by jordanlambrecht** [comment]
@maicol07 This isn't very helpful without any additional information. Please either include more info (such as a lighthouse audit or the info from the Chrome Performance DevTool) or close the issue.

**Comment by maicol07** [comment]
It ended up that my VPS has a slow HDD. So this can be closed
