### ISSUE TITLE
Minor UI Fix: Use Flexbox on Cyberpanel Login Page

### ISSUE THREAD

**Issue by jordanlambrecht** [litespeedtech/cyberpanel#500]
This is a super minor request, but would be a pretty quick fix to check off. The login page is a little awkward right now. Switching to flexbox and having the content be 100vh would clean it up a ton.

Current:
<img width="1435" alt="Screen Shot 2020-12-19 at 3 14 07 PM" src="https://user-images.githubusercontent.com/54866853/102699951-98796500-420e-11eb-8b54-c2a529077822.png">

With Flexbox:
<img width="1430" alt="Screen Shot 2020-12-19 at 3 24 14 PM" src="https://user-images.githubusercontent.com/54866853/102699953-9ca58280-420e-11eb-8149-0a51cbca138a.png">

**Comment by istiak101** [comment]
@jordanlambrecht create a PR.

**Comment by jordanlambrecht** [comment]
Done.

**Comment by jordanlambrecht** [comment]
@istiak101 done and done.

**Comment by istiak101** [comment]
@jordanlambrecht looking awesome!

**Comment by jordanlambrecht** [comment]
@istiak101 Thanks! This is the first time I've ever done a pull request on a repo that wasn't mine, so let me know if I did anything incorrectly.
