### ISSUE TITLE
Feature Request: Whitelabel Options on Cyberpanel Login Screen

### ISSUE THREAD

**Issue by jordanlambrecht** [litespeedtech/cyberpanel#501]
It would be amazing if we could upload an image, change the background color, add a logo, and update the body copy on the login screen via the cyberpanel settings. Especially for those of us that use the reseller aspects of CP. Probably low priority for you, but I wanted to put it on your radar as one of your devout users <3

**Comment by istiak101** [comment]
@jordanlambrecht Github is not for feature request. Please close this issue and open your feature request here https://feedback.cyberpanel.net/ .
