### ISSUE TITLE
very slow panel because of external resources

### ISSUE THREAD

**Issue by alireza-salehi** [litespeedtech/cyberpanel#509]
50 seconds to load resources from: code.angularjs.org
40 seconds to load resources from: code.jquery.com
5 seconds to load resources from: cdn.jsdelivr.net

jquery
angular
fontawsome
....

i get different results in different times for diffrent resources, but most of the time it takes about 1-2 minutes to load a page on cyberpanel admin.
please remove external js dependencies and make theme local.

**Comment by meramsey** [comment]
this sounds like it is a network issue with your server vs a cyberpanel "problem".

If you would like to submit a merge request which addresses the "problem" or wanted to adjust it yourself you can definitely do so as the source code is open.

There is also feedback.cyberpanel.net/ where you can leave feedback or ideas. Ones with more upvotes tend to get more attention for things that aren't bugs

**Comment by alanvar** [comment]
> 50 seconds to load resources from: code.angularjs.org 40 seconds to load resources from: code.jquery.com 5 seconds to load resources from: cdn.jsdelivr.net
> 
> jquery angular fontawsome ....
> 
> i get different results in different times for diffrent resources, but most of the time it takes about 1-2 minutes to load a page on cyberpanel admin. please remove external js dependencies and make theme local.

it's my issue too
please remove external dependencies and meke theme local
