### ISSUE TITLE
Upgraded redis to a version more stable than 3.x

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#512]
From 3.x to 5.x redis team fixed a lot of crashes, memory leaks, security problems, performance etc. Since 6.x it started to be more stable and fast. I recommend to upgrade and install redis 6.0.x by default.

Procedure using remi repository:
```bash
yum -y install http://rpms.remirepo.net/enterprise/remi-release-7.rpm 
yum-config-manager --disable remi
yum-config-manager --disable remi-safe
yum -y --enablerepo=remi install redis
```

**Comment by usmannasir** [comment]
@qtwrk 

Can you take care of this.

**Comment by qtwrk** [comment]
thanks , added into installer

**Comment by usmannasir** [comment]
Will consider resolved.
