### ISSUE TITLE
Suggestion: Reinstall-module

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#516]
It might be needed to re-install a module if it fails.
Such as Rainloop, can fail sometimes, then it might need help to get re-installed or "re-configured" by re-configured i mean clean the config page.

I have a rainloop that does not work at this time, and I do not know how to fix it.
And think a reinstall would fix it.
![image](https://user-images.githubusercontent.com/4199669/104956153-d4e5df80-59cb-11eb-9539-b74501eb4233.png)

**Comment by meramsey** [comment]
the best way to fix these kinds of things is to just run the upgrade thing with dev branch and then run the same thing after to switch back to stable it usually fixes the mismatches like this where it blindly reinstalls/upgrades.

If unsure take a snapshot beforehand if possible so you can rollback but when i get in a jam that's what I do.

Latest Dev
`bash <(curl https://cyberpanel.sh/new_upgrade.sh) -b 2.1.1-dev`

Latest version
`bash <(curl https://cyberpanel.sh/new_upgrade.sh) -b 2.1.1`

I do think having an option though to reinstall each core piece would be a nice feature for all the different stuff. I noticed we have code for it all already so having them as functions so they can be installed/uninstalled/reinstalled would make stuff like this a breeze once setup.

If you feel confident doing it manually reference:
https://github.com/usmannasir/cyberpanel/blob/stable/install/install.py#L1210-L1284

**Comment by master3395** [comment]
> the best way to fix these kinds of things is to just run the upgrade thing with dev branch and then run the same thing after to switch back to stable it usually fixes the mismatches like this where it blindly reinstalls/upgrades.
> 
> If unsure take a snapshot beforehand if possible so you can rollback but when i get in a jam that's what I do.
> 
> Latest Dev
> `bash <(curl https://cyberpanel.sh/new_upgrade.sh) -b 2.1.1-dev`
> 
> Latest version
> `bash <(curl https://cyberpanel.sh/new_upgrade.sh) -b 2.1.1`
> 
> I do think having an option though to reinstall each core piece would be a nice feature for all the different stuff. I noticed we have code for it all already so having them as functions so they can be installed/uninstalled/reinstalled would make stuff like this a breeze once setup.
> 
> If you feel confident doing it manually reference:
> https://github.com/usmannasir/cyberpanel/blob/stable/install/install.py#L1210-L1284

What is the benefit of going back to stable, can't I just stay on the dev version until a new stable comes?
Or won't it change back later?

**Comment by istiak101** [comment]
> What is the benefit of going back to stable, can't I just stay on the dev version until a new stable comes?
Or won't it change back later?

Dev version of any kind of software is not meant for production. Things can break and break badly.

**Comment by istiak101** [comment]
Feature request should be here.

https://feedback.cyberpanel.net/
