### ISSUE TITLE
Support for Redis in PHP 8.0

### ISSUE THREAD

**Issue by goshku** [litespeedtech/cyberpanel#519]
Hello, 
when will be able to add redis support in php 8.0?

Greetings

**Comment by jordanlambrecht** [comment]
This is a question (and maybe even a [feature request](https://forums.cyberpanel.net/categories/feature-request)), not an issue. Please close this issue out to help keep the backlog clean. The CyberPanel forums would be a far more suitable place to generate discussion about this, please consider using it.

**Comment by jordanlambrecht** [comment]
@gstamosbg Can you please close out this issue?

**Comment by goshku** [comment]
Sure.
