### ISSUE TITLE
Centos 8 Install fails

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#520]
Hello, i have been trying all day, to install CP on CentOS Linux 8.3.2011

It has been running fine earlier on Centos 8 with Webmin and Lamp.

But today, when I tried to do a clean install.
It all failed.

Error 500, issues with python 3, and the MySQL password not working for the local account...
I have tried all ways to fix this.

Here is the install log file:
[installLogs.txt](https://github.com/usmannasir/cyberpanel/files/5876583/installLogs.txt)

![unknown](https://user-images.githubusercontent.com/4199669/105913804-aef4b680-602d-11eb-8cc3-8ac1fca2492f.png)

((1045, "Access denied for user 'cyberpanel'@'localhost' (using password: YES)"))

I have tried all options below.

https://cyberpanel.net/docs/installing-cyberpanel/

https://cyberpanel.net/docs/upgrading-cyberpanel/

https://forums.cyberpanel.net/discussion/3376/installing-cyberpanel-with-python-3

https://forums.cyberpanel.net/discussion/344/access-denied-for-user-cyberpanel-localhost-using-password-yes

https://forums.cyberpanel.net/discussion/4928/install-fails-on-centos-8-2

https://www.rosehosting.com/blog/how-to-install-and-configure-cyberpanel-on-centos-8/

When doing "Manually set up virtualevn"

[root@ ~]# virtualenv --system-site-packages /usr/local/CyberCP
Using base prefix '/usr'
  No LICENSE.txt / LICENSE found in source
New python executable in /usr/local/CyberCP/bin/python3.6
Not overwriting existing python script /usr/local/CyberCP/bin/python (you must use /usr/local/CyberCP/bin/python3.6)
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/virtualenv.py", line 870, in main
    symlink=options.symlink,
  File "/usr/local/lib/python3.6/site-packages/virtualenv.py", line 1162, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/usr/local/lib/python3.6/site-packages/virtualenv.py", line 1691, in install_python
    raise e
  File "/usr/local/lib/python3.6/site-packages/virtualenv.py", line 1683, in install_python
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 40] Too many levels of symbolic links: '/usr/local/CyberCP/bin/python3.6'

**Comment by usmannasir** [comment]
You are running CyberPanel along side webmin?

**Comment by master3395** [comment]
> You are running CyberPanel alongside webmin?

Correct.
I reverted back to an earlier stage where it was working.
I thought a clean install of Centos 8 with Webmin and lamp would do good with CP.
But it broke :/

But it is working fine on my older version.
