### ISSUE TITLE
Stuck At Login Page

### ISSUE THREAD

**Issue by joeyboli** [litespeedtech/cyberpanel#522]
Cyberpanel  Has Been Loading For About 2 Hours Now On The Login Page.

URL : web.ghanacloud.ga:8090/

**Comment by jordanlambrecht** [comment]
It's loading perfectly fine for me: [
<img width="1436" alt="Screen Shot 2021-02-05 at 5 12 59 PM" src="https://user-images.githubusercontent.com/54866853/107098969-249f1600-67d6-11eb-8672-8bed96e4801e.png">


Please try clearing your cache. Regardless, this is most likely an issue with your configuration and not CyberPanel itself. If the problem persists, the correct place to post this (and a quicker way to get help!!) would be the [CyberPanel forums](https://forums.cyberpanel.net/). Additionally, CyberPanel has a pretty active Discord Server that you should check out.

Please close this issue to help keep the Issues log clean.

**Comment by joeyboli** [comment]
Sorry, Works Fine Now after update.

**Comment by jordanlambrecht** [comment]
@adoboligh1 that's great to hear!! If you don't mind - please close this issue.
