### ISSUE TITLE
SSO Login support 

### ISSUE THREAD

**Issue by rizwan95** [litespeedtech/cyberpanel#523]
Is it possible to support SSO login in the admin panel?

**Comment by jordanlambrecht** [comment]
Not as of yet. If this is something you would like to see, the best place to get your idea implemented is the [CyberPanel forums](https://forums.cyberpanel.net/categories/feature-request)

This is technically a feature request and not an issue with CyberPanel. Please close this issue to help keep the Issues backlog clean <3

**Comment by rizwan95** [comment]
Thank you @jordanlambrecht

**Comment by jordanlambrecht** [comment]
@rizwan95 No problem, man! I think it's a great idea. Deff post about it in the forums.

If you don't mind, please close this issue.

**Comment by rizwan95** [comment]
> @rizwan95 No problem, man! I think it's a great idea. Deff post about it in the forums.
> 
> If you don't mind, please close this issue.

Sure, I will post it in the forums! 
Closing this issue.
