### ISSUE TITLE
100 % CPU LOAD

### ISSUE THREAD

**Issue by joeyboli** [litespeedtech/cyberpanel#526]
100 % CPU LOAD After Installing Mailscanner.

**Comment by jordanlambrecht** [comment]
@adoboligh1 You gotta give us more info than that, my dude. What does `top –i` give you? How many emails did you have in your inbox when you installed it? Error logs? Does the problem persist when you reboot your server? Did you run `apt update apt upgrade`?

**Comment by jordanlambrecht** [comment]
@adoboligh1 are you still experiencing this issue or were you able to solve it? If not, please close this to help keep the issue backlog tidy
