### ISSUE TITLE
Git Manager internal 500 error

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#529]
Hello, when going to the webhook ID
https://IP:8090/websites/newstargeted.com/webhook
I get the error on the image below. I do not know what to do about that.
I get e-mails once it is finished even if I delete the git repository every day.
It's quite annoying to get an e-mail if I delete the repository from CyberPanel.

How can I stop the e-mails from being generated every day?
Does the Git Manager support "Private" repository using webhook?

Git Log:

INFO | 02.19.2021_11-00-12 | [Daily Cron] Finished checking for newstargeted.com on 02.19.2021_11-00-07.
-- | -- | --
INFO | 02.19.2021_11-00-07 | [Daily Cron] Checking if newstargeted.com has any pending commits on 02.19.2021_11-00-07.

![image](https://user-images.githubusercontent.com/4199669/108557537-0a4a5980-72f9-11eb-8ae7-4ca5fbd2d4d1.png)

![image](https://user-images.githubusercontent.com/4199669/108557654-3239bd00-72f9-11eb-9c0f-5c35c8bc219f.png)

![image](https://user-images.githubusercontent.com/4199669/108557363-c9524500-72f8-11eb-9563-b87642c6cf16.png)

**Comment by usmannasir** [comment]
Hello

https://cloud.cyberpanel.net/

Can you create a ticket with us in sales department, please mention this github issue and provide CyberPanel login details.

also mention to pass it on to Usman.

thanks.

**Comment by master3395** [comment]
I don't have a CyberPanel Cloud Support plan.

When I try to submit, I get this error

(1062, "Duplicate entry 'YECSNP' for key 'identifier'")
![image](https://user-images.githubusercontent.com/4199669/108609234-fc660880-73cc-11eb-9e12-a93c48aa994f.png)

**Comment by usmannasir** [comment]
Try now in sales department.

**Comment by master3395** [comment]
> Try now in sales department.

Worked, sent in :)
