### ISSUE TITLE
Creating the mail subdomain should not be in the public_html directory

### ISSUE THREAD

**Issue by nickfrosty** [litespeedtech/cyberpanel#531]
When you create a new website and choose to create the mail domain during this initial process, the mail subdomain is created and defaults to the public directory. 
Making it possible to navigate to example.com/mail.example.com in the browser. this makes little sense

The mail subdomain should be created at the same directory level as the domains "public_html" directory (e.g. /home/example.com/mail.example.com instead of /home/example.com/public_html/mail.example.com

**Comment by netorigin** [comment]
Yes please! is there a way to remove subdomains from public_html!?

**Comment by nickfrosty** [comment]
What I did was manually modify the OpenLiteSpeed config file for the website it self. First manually move the mail.domain folder up one directory, into the same one as the public_html. Then modify the location of that mail folder in the OLS config script. Then restart OLS

**Comment by jordanlambrecht** [comment]
@nickfrosty is the OLS config file something you could create a PR for so this is the default moving forward? I agree that it makes more sense to have it in the domain's root directory.

**Comment by nickfrosty** [comment]
@jordanlambrecht I guess there could be. But to the best of my knowledge the OLS config is auto generated using the python based backend. The python also generated the mail.domain.tld folder too.
Sadly, I do not know python. So I am very out of my zone to create such a PR. I can post my OLS config script I used for my setup if you think it would help? Or maybe just create a PR with my OLS config and describe the problem and goal?

**Comment by nickfrosty** [comment]
@jordanlambrecht I finally was able to fork the repo and start digging around in the code. 

I just created a PR that should fix the issue: https://github.com/usmannasir/cyberpanel/pull/606

**Comment by jordanlambrecht** [comment]
Hot damn. You rock dude

**Comment by istiak101** [comment]
As this is fixed in #610 in think this can be closed. @usmannasir @whattheserver

**Comment by nickfrosty** [comment]
Agreed!
