### ISSUE TITLE
Password issue Suggestion

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#533]
Hello, so far i like using CyberPanel.
But there are a few limitations.
Such as the list below.

I suggest allowing special characters to be allowed on the admin logins and
a config button for the password generator on MySQL, where you can choose how long and how strong the passwords should be (With or without special characters)
When I say special characters, I mean !"#¤%&/()=?` and ÆØÅ

1. Admin users can't use special characters in the password.
2. MySQL password generator can't use special characters.

**Comment by meramsey** [comment]
the main limitation i see here is that javascript makes it really hard to escape every possible scenario to send these kinds of special characters through without errors for the login forms and update profile settings. Having been down that rabbithole before im guessing this is most likely why.

If you know of a solution that allows those to be passed properly through the login/update forms with proper escaping feel free to submit a Pull Request

**Comment by master3395** [comment]
Found no solution, but closing this issue, as it's not needed to have open with no solution.
