### ISSUE TITLE
Error downloading Comodo Rules

### ISSUE THREAD

**Issue by Tangol** [litespeedtech/cyberpanel#538]
I had enabled the Comodo modsecurity package for 2 months, and today I disabled it to do some tests.
When I tried to enable it again, I got the following error:
![error](https://user-images.githubusercontent.com/3336728/109643533-04584200-7b5d-11eb-8474-069020c5c552.png)

Running the latest stable version https://github.com/usmannasir/cyberpanel/commit/599ddf46c105e27f4f93b3d4ff8f0b96d27d3455

**Comment by chiareu** [comment]
The same error for OWASP.
Also if you try to save firewall/modSecRules, you got another error:
`Could not save rules, Error message: write() argument must be str, not list`

**Comment by usmannasir** [comment]
Hello

It is fixed.

thanks.

**Comment by chiareu** [comment]
Thank you, but since the rules are downloaded from Cyberpanel (https://cyberpanel.net/modsec/comodo.tar.gz) can we update the package to last Comodo rules set?
I manually use 3-1.233
