### ISSUE TITLE
Mod_security issue

### ISSUE THREAD

**Issue by ponasromas** [litespeedtech/cyberpanel#54]
Hello,

Latest CP version. When trying to disable Mod_security via panel it produce error:

> Failed to save ModSecurity configurations. Error message: Data supplied is not accepted.

Frustrating error. That error was in 17.1 with Litespeed settings editor, but it was fixed in 17.2. Overall it seems CP doesn't have any code QA policy in place. Hope I'am wrong.

**Comment by usmannasir** [comment]
@ponasromas 1.7.2 was mostly a security release. Due to which some issues came up, as most of the request body need to be inspected. Try the force upgrade for your Ent installation, it should fix your issue: https://cyberpanel.net/docs/upgrading-cyberpanel-ent/

**Comment by ponasromas** [comment]
That does not resolve problem. Just removed CP and got VestaCP. Enough.
