### ISSUE TITLE
CentOS repo issue - frozen installation

### ISSUE THREAD

**Issue by ljubacanoa** [litespeedtech/cyberpanel#540]
GCP, when script arrive till rpm -Uvh http://rpms.litespeedtech.com/centos/litespeed-repo-1.1-1.el8.noarch.rpm, became unresponsive (cannot be installed anymore). Maybe as it is now litespeed-repo-1.2-1.el8.noarch.rpm? I tried also to first add repo (successfully), but script keep to frozing at that place.

**Comment by qtwrk** [comment]
```
[root@test1 ~]# curl -I -XGET http://rpms.litespeedtech.com/centos/litespeed-repo-1.1-1.el8.noarch.rpm
HTTP/1.1 200 OK
Connection: Keep-Alive
Keep-Alive: timeout=5, max=100
etag: "538c-5dd7145a-2b3c6e"
last-modified: Thu, 21 Nov 2019 22:48:58 GMT
content-type: application/octet-stream
accept-ranges: bytes
content-length: 21388
date: Sun, 07 Mar 2021 23:46:14 GMT
server: LiteSpeed
```

the link still works , maybe network hiccup somewhere.

**Comment by ljubacanoa** [comment]
3 days hiccup on Google CP??? OK, I will try it also on Linode and let you know what is going on.

**Comment by netorigin** [comment]
Any fix? can't deploy anymore on multiple VPS instance

We are not able to run rpm -ivh http://rpms.litespeedtech.com/centos/litespeed-repo-1.2-1.el7.noarch.rpm return code:

**Comment by istiak101** [comment]
@ljubacanoa do you still have this issue? It would be nicer if you have any output or error logs from terminal. Requesting @usmannasir to close this. If you still have this issue feel free to reopen.
