### ISSUE TITLE
Apache issue

### ISSUE THREAD

**Issue by ljubacanoa** [litespeedtech/cyberpanel#542]
I thought that CyberPanel run on Apache and now I'm kind of confused. While on Ubuntu all sims to be fine, on CentOS, I have message that Apache is dead (and some modules missing). Basically, whatever combo I try, no chance to run useful installation.

**Comment by qtwrk** [comment]
no , it doesn't install Apache at all , what did you see ?

**Comment by ljubacanoa** [comment]
Well, it is about official CyberPanel package on Linode on CentOS 8 and I have next

`# systemctl status httpd
● httpd.service - The Apache HTTP Server
Loaded: loaded (/usr/lib/systemd/system/httpd.service; disabled; vendor preset: disabled)
Active: inactive (dead)
Docs: man:httpd.service(8)`

**Comment by ljubacanoa** [comment]
And missing modules are:

mod_access_compat
mod_authz_core
mod_rewrite

P.S. - Who set package on Linode, you (or Linode)?

**Comment by qtwrk** [comment]
not me , and I jsut checked with image maker 

the Linode doesn't support "image" , the way it does is more like to have a pre-defined CyberPanel installer script to run on  launch/start up 

so the Apache must be coming from the base OS image

**Comment by ljubacanoa** [comment]
thanks for clearing
