### ISSUE TITLE
Aceesability issues

### ISSUE THREAD

**Issue by JimTR** [litespeedtech/cyberpanel#545]
Hi is there a way of applying a color change to cyberpanel ? I have an eye sight problem & can not look at white screens for too long ... currently I'm at 
<img src = "https://i.imgur.com/Zg8iwRG.png" />
but some css classes appear to be replicated in multiple css files and you end up with loads of !important statements ... If you could give me an idea on who to get the panel to read a different set of css files

**Comment by usmannasir** [comment]
This is the last CSS file that gets loaded -> https://github.com/usmannasir/cyberpanel/blob/v2.0.5-dev/websiteFunctions/static/websiteFunctions/websiteFunctions.css

You can put changes in this file. You have to do all the usual django stuff as well like collect static file etc.

thanks.

**Comment by JimTR** [comment]
Thanks for that
