### ISSUE TITLE
PHP cli - note to developers

### ISSUE THREAD

**Issue by JimTR** [litespeedtech/cyberpanel#547]
Note for PHP developers
Ditstro Ubuntu 20.04
if you install cyberpanel on a machine running the above distro the php **CLI** version is set at version 7.3.23 and not  7.4.3 (Ubuntu default for 20.04) .
If your cli code relies on PHP >7.4 it will fail as your using a lower version. 
running apt on your machine will return that version 7.4.3 is installed and at the latest version so apt is of no use to here, I managed to fix this by installing PHP 8.0, this in turn upgraded all the 7.3 packages to 7.4, everything works again now.
To date I have not purged PHP 8.0 to see if the CLI version returns to 7.3.
I am not sure if litespeed or cyberpanel installs this version of php CLI but I guess it may need to be addressed at some point to save software failures that rely on the expected version of php cli to be installed on a given distro

**Comment by usmannasir** [comment]
How did you install php 8? I think you have not installed lsphp80  as it is different from the one that is used with apache or nginx

**Comment by JimTR** [comment]
I think you miss the point so I'll try again

1.  Install a Ubuntu 20.04 server
1a. install php apt install php 
2. open a terminal and type php -v 
3. php will return 7.4.3
4. install cyberpanel 
5. open a terminal and type php -v
6. php will return 7.3.23
7. run apt upgrade php 
8. apt will return php is already the newest version
9. at this point the software I have developed fails due to the php version being to low
10. php 8 installation
11. run add-apt-repository ppa:ondrej/php
12. apt install php8.0
13. open a terminal and type php -v
14. php will return 8.03
15. my software works again

This is a bit of a deal breaker using cyberpanel, as I intended to install cyberpanel with my software on clients servers looks like I will have to look at other options.
Aside there are some issues after you have installed cyberpanel & try to access a remote mysql 8 database, this fails due to the user auth method (mysql uses caching_sha2_password and maria uses mysql_native_password) being mismatched. As I don't have access to the remote database which would be the best method to change maria to use the same method as mysql ?

**Comment by JimTR** [comment]
you could try this code on a running server
`<?php
echo 'Current user '.get_current_user ( ).'<br>';
echo 'System php version '.shell_exec("php -v").'<br>';
echo 'Current PHP version: ' . phpversion();
?>
`

**Comment by usmannasir** [comment]
> I think you miss the point so I'll try again
> 
>     1. Install a Ubuntu 20.04 server
>        1a. install php apt install php
> 
>     2. open a terminal and type php -v
> 
>     3. php will return 7.4.3
> 
>     4. install cyberpanel
> 
>     5. open a terminal and type php -v
> 
>     6. php will return 7.3.23
> 
>     7. run apt upgrade php
> 
>     8. apt will return php is already the newest version
> 
>     9. at this point the software I have developed fails due to the php version being to low
> 
>     10. php 8 installation
> 
>     11. run add-apt-repository ppa:ondrej/php
> 
>     12. apt install php8.0
> 
>     13. open a terminal and type php -v
> 
>     14. php will return 8.03
> 
>     15. my software works again
> 
> 
> This is a bit of a deal breaker using cyberpanel, as I intended to install cyberpanel with my software on clients servers looks like I will have to look at other options.
> Aside there are some issues after you have installed cyberpanel & try to access a remote mysql 8 database, this fails due to the user auth method (mysql uses caching_sha2_password and maria uses mysql_native_password) being mismatched. As I don't have access to the remote database which would be the best method to change maria to use the same method as mysql ?

Yes that is what I am saying the php that you get after CyberPanel installation is from lsphp which is available at `/usr/local/lsws/lsphpXX/bin`

you can replace XX with php version and copy to your current bin.

You are installing system provided php which CyberPanel don't use nor installs.

**Comment by JimTR** [comment]
ok you still don't get it ... using the php function shell_exec  such as `shell_exec('php -v'); ` will return the default binary in this case the default binary is /bin/php as per the users path statement so you are saying alter the path to suit whatever is set by cyberpanel ?  but this still does not explain why after a cyberpanel install /bin/php is altered from version 7.4 to 7.3

**Comment by qtwrk** [comment]
https://github.com/usmannasir/cyberpanel/blob/79f1fe469b353db649aee44f85acee9a82d59955/cyberpanel.sh#L1427  


maybe this should give ubuntu 20 to php74 ?

**Comment by JimTR** [comment]
does that alter /bin/php ?

**Comment by qtwrk** [comment]
yes, it links lsphp73/bin/php to /usr/bin/php

**Comment by JimTR** [comment]
ok that works but over rides  the installed version of PHP from apt therefore php will not get any updates apt is now confused and will not receive any updates as it appears up to date when it is not, just copied 7.3 to the target destination, this is now out of date, running apt update php  still returns uptodate where in fact it is well out of date .. perhaps cyberpanel needs to just adjust the litespeed version of php and not the system version

**Comment by JimTR** [comment]
Just thought .. assuming apt updates to a new binary this may break the whole infrastructure

**Comment by qtwrk** [comment]
okay ?   so what do you have in mind for this ?

**Comment by JimTR** [comment]
I'm thinking cyberpanel should leave apt/yum to update php and the cli binary to be left as installed rather than copying the binary from the installed versions over the current binary  additional versions of php  (litespeed/apache/whatever) should be handled by cyberpanel,  and the install of the binarys should be addressed that way. Cyberpanel should just adjust what litespeed delivers and not the underlying php infrastructure

**Comment by qtwrk** [comment]
maybe a soft link from `/usr/local/lsws/lsphp74(or 73)/bin/php` to `/usr/bin/php` ?  so whenever lsphp package updates ,  `/usr/bin/php` will alone with it.

**Comment by JimTR** [comment]
see below

**Comment by qtwrk** [comment]
it should be the line I showed in previous reply

**Comment by JimTR** [comment]
Ok I removed & purged php* from the machine then re installed from apt, which installed the expected version of php, rebooted the machine to ensure the session was clean, then ran up cyberpanel it did not complain about the version change at all so it begs the question, why on install does cyberpanel have to fiddle with php in the first place ? I've just proved that it does not make any difference to cyberpanel what version of php is installed ?

**Comment by JimTR** [comment]
having a dig about found line 1721 in the installer script copies the php 7.3 binary to /bin. perhaps you should check if there is already a file at /bin before copying ? if it is a requirement of cyberpanel to use one of the binarys the installer has installed why not ask the question at install time so the user can choose which file to use rather than just copying a file
