### ISSUE TITLE
Mail suggestion

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#552]
Maybe a new mail client such as SOGo. [https://www.sogo.nu/](https://www.sogo.nu/)
It has the same features as Roundcube and rainloop.
But it has a more active community when it comes to updates and plugin support.

**Comment by master3395** [comment]
Or even better this maybe?
https://github.com/Foundry376/Mailspring

**Comment by j-a-pope** [comment]
Mailspring is not a webmail client, it's a desktop mail client.

**Comment by jordanlambrecht** [comment]
@master3395 is there anything preventing you from installing this in a docker container? This would be a pretty big overhaul since SOGo and Rainloop serve different purposes and have very different use cases.

**Comment by master3395** [comment]
> @master3395 is there anything preventing you from installing this in a docker container? This would be a pretty big overhaul since SOGo and Rainloop serve different purposes and have very different use cases.

I haven't been working with dockers yet.
But I'm looking into it.
Also not sure if it's related, but you can't make dockers even if it's installed?
![image](https://user-images.githubusercontent.com/4199669/113738651-60375d00-96ff-11eb-8077-4f50aae2d05f.png)

**Comment by master3395** [comment]
> @master3395 is there anything preventing you from installing this in a docker container? This would be a pretty big overhaul since SOGo and Rainloop serve different purposes and have very different use cases.

I haven't been working with dockers yet.
But I'm looking into it.
Also not sure if it's related, but you can't make a container even if it's installed?
![image](https://user-images.githubusercontent.com/4199669/113738793-7f35ef00-96ff-11eb-8324-65e6ef12ad4c.png)

**Comment by master3395** [comment]
I found this.
But i have no idea how to make the docker or get it in.
https://hub.docker.com/r/jenserat/sogo

https://hub.docker.com/r/sabaitech/sogo/

**Comment by meramsey** [comment]
Want to start here granted your VPS/Server supports docker. Some like openvz may not support it without special kernels.
https://cyberpanel.net/docs/1-getting-started-with-cyberpanel-docker-manager/
