### ISSUE TITLE
phpMyAdmin Error Code 200 - Error Processing request

### ISSUE THREAD

**Issue by patrickgarsow** [litespeedtech/cyberpanel#559]
Without change suddenly phpmyadmin is giving the following error message when users try to login to view their databases.

![phpmyadmin_error200](https://user-images.githubusercontent.com/79234786/112560836-60079b00-8daa-11eb-91c7-7dbc07028e61.png)

**Comment by patrickgarsow** [comment]
@qtwrk thanks for the assist with this. 

**Cause:** As your database structure becomes larger and larger with further utilization of databasing with CyberPanel the default settings in the php.ini file for post_max_size is insufficient to support phpMyAdmin's functionality. 

**Workaround:** If Error Code 200 is occurring on every access/login of phpmyadmin it seems to be the entry post_max_size in the php.ini version your server is running. Follow the procedure below to resolve:

1.  Find the version of PHP your webserver is running. This can be seen after clicking on the error 200 message which dismisses the alert and looking at the web server information in the phpmyadmin dashboard.
![webserver_php_version](https://user-images.githubusercontent.com/79234786/112571400-525c1080-8dbe-11eb-9654-597a79fd6d0d.png)

2. Browse the php.ini file for your version of PHP denoted by the major release (ie 71, 72, 73, 74, 80) using Vim.
`vi /usr/local/lsws/lsphp73/etc/php.ini`

3. Search for 'post_max_size'
`/post_max_size`

4. Edit the text from the default 32 to some value higher like 128 or 256.
- Press 'i' for insert and delete the 32 and enter in 256. The Press 'esc', then `:wq`

5. Restart Litespeed PHP process
`pkill lsphp`

Your problem should now be resolved.

**Comment by istiak101** [comment]
As this is resolved I am closing this.
