### ISSUE TITLE
v2.0.3, is not detecting there's a new release (v2.1.1)

### ISSUE THREAD

**Issue by inspiredearth** [litespeedtech/cyberpanel#560]
I see there's a new version (v2.1.1) mentioned on the [changelog](https://cyberpanel.net/docs/change-log-for-cyberpanel/).

However, it's not reported in the versionManagment system in our v2.0.3 installation.

Is there a reason for this?

Is it safe to migrate using the usual script? 
```
sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh)
```

**Comment by srv1emoving** [comment]
use "cyberpanel upgrade"

**Comment by Prahapp** [comment]
@srv1emoving "cyberpanel upgrade" downgraded my 2.1.1

**Comment by chiareu** [comment]
/base/versionManagment reported
Current Version 2.0
Build 3
Latest Version 2.0
Latest Build 3

**Comment by chiareu** [comment]
Kindly reminder. This problem still persist.
Definitively there is a problem, please check the upgrade script as do not run upgrade process to latest stable version. 
cheers

**Comment by usmannasir** [comment]
We've reverted the change-log. Kindly wait, v2.1.1 is still under testing.
