### ISSUE TITLE
[critical bug] Backup will fail if is not a regular file or if file was removed

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#565]
## envrironment
- cyberpanel 2.0.3
- centos 7

## issues related
- symbolic link will also stop the backup https://github.com/usmannasir/cyberpanel/issues/534

## how to reproduce
I am using cyberpanel cli commnad to create backups.
```bash
/usr/bin/cyberpanel createBackup --domainName xyz.com
```
If some file disappear during the process or is not a regular file, the entire cyberpanel backup process fail.

## the problem relevance
THIS IS CRITICAL. I found a lot of backups not happening due this problem (mainly due temporary files being removed during the process).

## what I expect
- ANYTHING will stop the backup.If if a mysql dump fail. Is better to have something than nothing.
- Any notification in somewhere about the problem happened. A simple warning of failure.
- The backup strategy have to do the best effort to have all data synced, but without suspend the site and WITHOUT FAIL THE BACKUP PROCESS.

It is unbeliavable that entire backup process will fail due those reasons.

**Comment by usmannasir** [comment]
Install v2.1.1 and see if same happens, I made some tweaks.

**Comment by franciscopaniskaseker** [comment]
I am testing the new version. Seems to be fixed, but I will return when I have more feedbacks.

**Comment by usmannasir** [comment]
So I will close this now. if there is anything else let me know.

**Comment by franciscopaniskaseker** [comment]
i am considering thia fixed.  Everything worked in this 8 days.
