### ISSUE TITLE
Debian Support when?

### ISSUE THREAD

**Issue by Joshua2504** [litespeedtech/cyberpanel#566]
![image](https://user-images.githubusercontent.com/11087078/112762146-8291f200-8ffe-11eb-8cf2-ced630d08de7.png)

What is the reason for not supporting Debian?

Ubuntu is more a Desktop OS than something I want to run on my servers.

**Comment by usmannasir** [comment]
I am sorry, we will not be supporting Debian, at least not officially.

thanks.

**Comment by AtomRun-Code** [comment]
你好，我是一位来自中国的粉丝，由于这边暂时没有什么好用的panel，其中一个很出名的在近期要求使用者的手机注册，并登记在服务器上。这给我们新手带来安全忧虑。另外是Centos的长期支持也发布了关闭公告。所以更偏向祖辈级的Debian.真心希望你们能开拓Debian的生态。

即使未能达成，也希望你们越来越好。加油！

**Comment by qtwrk** [comment]
> 你好，我是一位来自中国的粉丝，由于这边暂时没有什么好用的panel，其中一个很出名的在近期要求使用者的手机注册，并登记在服务器上。这给我们新手带来安全忧虑。另外是Centos的长期支持也发布了关闭公告。所以更偏向祖辈级的Debian.真心希望你们能开拓Debian的生态。
> 
> 即使未能达成，也希望你们越来越好。加油！

Ubuntu LTS 也不错的  : )    

CentOS 没了  你可以试试 RockyLinux 或者 AlmaLinux

**Comment by AtomRun-Code** [comment]
> > 你好，我是一位来自中国的粉丝，由于这边暂时没有什么好用的panel，其中一个很出名的在近期要求使用者的手机注册，并登记在服务器上。这给我们新手带来安全忧虑。另外是Centos的长期支持也发布了关闭公告。所以更偏向祖辈级的Debian.真心希望你们能开拓Debian的生态。
> > 
> > 即使未能达成，也希望你们越来越好。加油！
> 
> Ubuntu LTS 也不错的  : )    
> 
> CentOS 没了  你可以试试 RockyLinux 或者 AlmaLinux

😂已经转用了ubuntu20了。感谢分享。
