### ISSUE TITLE
Phpmyadmin corrupting exported database

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#568]
# environment
- centos 7
- last OLS stable
- last cyberpanel stable (updated today)

# the problem
When I go to phpmyadmin and try to export a database with more than 32Mb (in this example +100Mb) when it get 32M of the SQL file the download stop and I can see this message in the last line of the SQL file:

```bash
The dynamic response body size is over the limit, the response will be truncated by the web server. The limit is set in the key 'maxDynRespSize' located in the tuning section of the server configuration, and labeled 'max dynamic response body size'
```

I checked the maxDynRespSize limit and it was the maximum value (2047M). I tried other limits (less than 2047M) just to test and the problem continue.

I am not sure if this problem is OLS exclusively or is due phpmyadmin + cyberpanel integration. I will test.

# how to test
1. create a database with 100Mb
2. try to export using quick action (without compress)
3. wait the download finish
4. see the last line

# what I expect
A complete SQL dump. I know that I can ask to compress to have a file less than 32M, but sometime with huge databases is not possible to have a .sql.zip less than 32M.

**Comment by franciscopaniskaseker** [comment]
I tested with external phpmyadmin installation and I did not see the problem happening.

When I say external phpmyadmin I mean that I installed the last stable phpmyadmin (5.1) and installed in one cyberpanel domain. Logged as root and exported the database.

The other thing is the download was 10 times faster with my own phpmyadmin that cyberpanel integrated phpmyadmin. I tested more than one time.

**Comment by chiareu** [comment]
try to change the Max Dynamic Response Body Size configuration in LightSpeed, web admin default port is :7080

**Comment by franciscopaniskaseker** [comment]
Please read all the issue. This was done. Also the default is 2047M, the maximum value.

**Comment by chiareu** [comment]
What version of CP you have?
I just tested on CyberPanel 2.0.3, exported an uncompressed database of over 32Mb without problems.
also pls check and adjust php values as needed - CP 2.0.3 use php7.3
/etc/my.cnf.d/server.cnf
ADD max_allowed_packet = 200M
/usr/local/CyberCP/public/phpmyadmin/config.inc.php
ADD $cfg['ExecTimeLimit'] = 6000;

**Comment by chiareu** [comment]
CyberPanel 2.0.3, OpenLiteSpeed 1.6.20
Max Dynamic Response Body Size (bytes): 2047M
Database dump 32.5Mb
`The dynamic response body size is over the limit, the response will be truncated by the web server. The limit is set in the key 'maxDynRespSize' located in the tuning section of the server configuration, and labeled 'max dynamic response body size'`

Database dump 25.2Mb OK

**Comment by chiareu** [comment]
Hi, I just observed that this issue was closed. There is some solution for that error?

**Comment by SaJeTek-Developer** [comment]
Hi,
This is still an issue even in the latest 2.3.4 commit.
@usmannasir was this confirmed and tested before closing?
I can see that the last test before you closed, the export failed for 32Mb but was Ok for  25.2Mb OK in https://github.com/usmannasir/cyberpanel/issues/568#issuecomment-812236813

Increasing the Max Dynamic Response Body Size does nothing to solve the issue.
Any DB export is truncated at 30MB with the error:

"The dynamic response body size is over the limit, the response will be truncated by the web server. The limit is set in the key 'maxDynRespSize' located in the tuning section of the server configuration, and labeled 'max dynamic response body size'."

There are folks I know has lost lots of data because of this.
