### ISSUE TITLE
How to edit core .py files

### ISSUE THREAD

**Issue by rallisf1** [litespeedtech/cyberpanel#569]
Please don't laugh, I haven't worked with django before. I am making changes to core .py files, but are ignored.

I tried implementing a clear cache cli function
```python
    elif args.function == "clearcache":

        completeCommandExample = 'cyberpanel clearcache'

        from django.core.cache import cache
        cache.clear()
```
but running it didn't make a difference. Restarting lscpd or even rebooting the server won't cut it either.

How am I supposed to edit a live installation?

P.S. html templates I can edit fine and already figured out upgrade.sh for the javascript part.

**Comment by jordanlambrecht** [comment]
Hey @rallisf1, no one will make fun of you for taking a serious investment in an open source project and trying to learn 😘 however, since this isn’t a bug with CP, the correct (and better) place to post this would be the forums. You’re 10x more likely to get a solid response there, and by closing out this issue you’re helping keep the bug backlog tidy. Thanks 🙏

**Comment by rallisf1** [comment]
> Hey @rallisf1, no one will make fun of you for taking a serious investment in an open source project and trying to learn 😘 however, since this isn’t a bug with CP, the correct (and better) place to post this would be the forums. You’re 10x more likely to get a solid response there, and by closing out this issue you’re helping keep the bug backlog tidy. Thanks 🙏

I understand, still there is no dev category in the forums and makes more sense to me to get a dev related answer on github. Anyway, once I get my answer I will close this issue.

**Comment by usmannasir** [comment]
what is this supposed to do ?

**Comment by rallisf1** [comment]
> what is this supposed to do ?

It's just a question. I edit a .py file inside `/usr/local/CyberCP` and don't see the changes applied. What should I do for changes to take effect? Never worked with django before. I tried clearing django cache with the code above but didn't make any difference.

**Comment by usmannasir** [comment]
To see the effect of changed .py file on frontend you have to do `systemctl restart lscpd`

just to be sure you can also do `killall lswsgi`. If you still dont see a change, it something wrong in the code.
