### ISSUE TITLE
Possible support for AlmaLinux

### ISSUE THREAD

**Issue by Tim-NL** [litespeedtech/cyberpanel#570]
Hi,

Today AlmaLinux came out, this is a 1:1 compatible open-source RHEL clone, just like CentOS was before the changed to "CentOS Stream", and just like CloudLinux is (it's created by them). I'd love to see support for AlmaLinux for this project.

-Tim

**Comment by usmannasir** [comment]
Yess

**Comment by usmannasir** [comment]
@Tim-NL I just stumbled upon https://ostechnix.com/migrate-to-almalinux-from-centos-8-using-almalinux-deploy-script/

Did you try?

Install CyberPanel on centos8 and convert to alma linux

**Comment by Tim-NL** [comment]
Hi,

I have not tried that, but I did see it as an option. I do, however, prefer a clean install of an OS, instead of having a converted system from CentOS to AlamaLinux. I'm not sure if my causion is justified, it might just be as stable.

-Tim

**Comment by usmannasir** [comment]
Not for production, just for testing. You can test and let us know if all the functionalities are working after conversion we can then add support in the install script.

**Comment by Tim-NL** [comment]
That seems to work as expected, I successfully installed & converted a server from CentOS 8 to AlmaLinux. And the panel functions correctly. I have only tried clicking through some things.

-Tim

**Comment by j-a-pope** [comment]
I've also given this a go, converting a CentOS 8 install with CP to Alma, and didn't seem to hit any issues or roadblocks. 

I also posted on the CP forum last week asking what the team thoughts are about RHEL-based distro support going forward, whether the intention was to jump to Stream, Alma, Rocky, or some other path?

**Comment by qtwrk** [comment]
I was trying to make installation work on AlmaLinux directly , instead of going on CentOS 8 then convert 

but hit some error due to package conflict between MariaDB 10.5 and MySQL 8.0 :(

**Comment by usmannasir** [comment]
This has also been done, thanks
