### ISSUE TITLE
What is my database???

### ISSUE THREAD

**Issue by ljubacanoa** [litespeedtech/cyberpanel#571]
I just now found huge problem. I have over 10 child (WP) sites and I should to remove one database, but when I opened dialog ==> SURPRISE. All databases are with random characters. Anybody have idea how to find correct database?

P.S. - I think that there is also technical issue (BUG) as deleting website is actually nothing deleted in HDD itself, it should to be deleted manually. So, if I'm not wrong, deleting website in CP should be deleted FOLDERS, FILES and DATABASE, but NOTHING is deleted except website in CP dashboard.

**Comment by rallisf1** [comment]
Database names are randomly generated for security reasons. Check wp-config.php for your database name.

I agree there should be an option of whether to keep the files associated with a website when removing it or not, including databases, emails, dns zones and ssl certificates. Also creating a backup before deletion should be an automated option.
