### ISSUE TITLE
MariaDB remote access is not working.

### ISSUE THREAD

**Issue by pasamsin** [litespeedtech/cyberpanel#572]
MariaDB remote access is not working. I'm adding a % or ip address, but it's not accessible.

**Comment by pasamsin** [comment]
I could not find a space where I can change its privileges for the database user. I guess there is no such feature, I hope this feature will be added in the future.

**Comment by usmannasir** [comment]
I am going to fix this

**Comment by usmannasir** [comment]
I've fixed this in v2.1.1 https://github.com/usmannasir/cyberpanel/commit/37e79c60cf7c215699fdae320e02387855cb125e
