### ISSUE TITLE
OpenLiteSpeed In FireWall by default

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#576]
I think OpenLiteSpeed port 7080 should be whitelisted on install.
As the whole CP is run on OpenLiteSpeed or OpenLiteSpeedEnt by default.

**Comment by j-a-pope** [comment]
This makes sense to me too. I don't know what percentage of CP users are also going to regularly use OLS/LSWS webadmin but it must be fairly high. 

Ditto with issuing TLS for 7080 at the same time as 8090.

**Comment by qtwrk** [comment]
I would say like 70% users don't even know about it,  and I am not really comfortable to open a port for users who may not even know its usage and existence. 

For people who needs to use webadmin,  he or she can open it up and reset password

**Comment by usmannasir** [comment]
This is highly not recommended, it should be manually opened if required.
