### ISSUE TITLE
Mautic installer is not present in subdomain

### ISSUE THREAD

**Issue by hydrosIII** [litespeedtech/cyberpanel#577]
While the mautic installer is present in any domain, whem you create a subdomain there is no mautic installer present. Making it difficult to install mautic in a subdomain, having it to install it by hand. 

Cyberpanel version 2.1

First Screenshot domain page.
Second Screenshot: subdomain page.
![Captura de pantalla de 2021-04-09 20-59-32](https://user-images.githubusercontent.com/7807363/114254763-e3aeb380-9976-11eb-8671-4d5db78b492a.png)
![Captura de pantalla de 2021-04-09 20-59-43](https://user-images.githubusercontent.com/7807363/114254766-e6a9a400-9976-11eb-8fb6-152522398707.png)

**Comment by usmannasir** [comment]
It not an issue, its a feature request.

**Comment by hydrosIII** [comment]
Ok i did not know it was not planned that you cannot install mautic in a subdomain but In a domain you can. Seems weird.
