### ISSUE TITLE
Containerization not working in Centos 8, needs refactoring. 

### ISSUE THREAD

**Issue by hydrosIII** [litespeedtech/cyberpanel#578]
The Cyberpanel container system is based in cgroups, specifically Cyberpanel looks for cgred.service in Centos 8. But cgred.service was deprecated and is not present in Centos 8. 

https://bugzilla.redhat.com/show_bug.cgi?id=1034248

Official documentation from RHEL advides to use systemd's Control Group Interface. 

I am not sure if containerization works in ubuntu 20.04, and if cgred.service is present there.

![Captura de pantalla de 2021-04-12 11-29-06](https://user-images.githubusercontent.com/7807363/114439556-b6d4e900-9b8e-11eb-875a-8aae4fe6716a.png)

Cyberpanel version 2.1.1 in Centos 8.3.2011 up to date to the 12th of april 2021.

**Comment by usmannasir** [comment]
Yes this will not work because redhat have deprecated required libraries, better to use Cloudlinux.
