### ISSUE TITLE
restic failed to install on cp install

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#580]
Below is the error i get every time I try to do an Incremental Back up. This happens on V2.1

It seems restic is not installed, for incremental backups to work restic must be installed. You can manually install restic using this guide -> http://go.cyberpanel.net/restic. [5009]

**Comment by meramsey** [comment]
I put in an experimental fix for this in the dev branch. If you don't mind trying out the dev branch which is riskier then stable can try upgrading and see if it self corrects it.

`bash <(curl https://cyberpanel.sh/new_upgrade.sh) -b 2.1.1-dev `

Alternatively if your comfortable on command line you can manually run through the same installer steps as in the commit to manually install it
https://github.com/usmannasir/cyberpanel/commit/55c40f1bb919666d1115f6192c1c059e0e8202aa

If the upgrade fixes it please report back so we can close this out.

**Comment by master3395** [comment]
> I put in an experimental fix for this in the dev branch. If you don't mind trying out the dev branch which is riskier then stable can try upgrading and see if it self corrects it.
> 
> `bash <(curl https://cyberpanel.sh/new_upgrade.sh) -b 2.1.1-dev `
> 
> Alternatively if your comfortable on command line you can manually run through the same installer steps as in the commit to manually install it
> [55c40f1](https://github.com/usmannasir/cyberpanel/commit/55c40f1bb919666d1115f6192c1c059e0e8202aa)
> 
> If the upgrade fixes it please report back so we can close this out.

Trying to do it manually first.
Because I upgraded my Centos 8 install into Arch Linux.

But it seems like the Certificate for cyberpanel has expired, because of this, it did not get installed correctly I believe.
As I got the same error on cp after this.
![image](https://user-images.githubusercontent.com/4199669/115149456-85638e00-a064-11eb-9012-482563a1f9d2.png)

And I had to use the commands below because the centos did not work.
" if distro == 'centos' and 'el7' in release:
                        command = 'yum install restic -y'"
![image](https://user-images.githubusercontent.com/4199669/115149503-bc39a400-a064-11eb-8b89-948fbd271f6c.png)

RHEL & CentOS
restic can be installed via copr repository, for RHEL7/CentOS you can try the following:

$ yum install yum-plugin-copr
$ yum copr enable copart/restic
$ yum install restic

**Comment by master3395** [comment]
After clean install of V2.1.1-dev i get this problem on Incremental Back up. It does not look like it gets done. (If i refresh the page it is not done, does not show up as done at all).
![image](https://user-images.githubusercontent.com/4199669/115154306-78519980-a07a-11eb-8081-a827ce5eac57.png)

**Comment by meramsey** [comment]
So the original script was not adjusted in dev since i posted last time. So if you tried upgrading to it via dev branch then it would not have accounted for your issue which you identified when manually trying it.

If you can tell me what the output from the below is that would be helpful.

`python3 -c 'import platform; print(platform.uname().release)'`


We can possibly just switch it to the below if its going to work for all Centos/RHEL versions but i don't have anything setup to test that.
```
yum install yum-plugin-copr
yum copr enable copart/restic
yum install restic
```

**Comment by master3395** [comment]
> So the original script was not adjusted in dev since i posted last time. So if you tried upgrading to it via dev branch then it would not have accounted for your issue which you identified when manually trying it.
> 
> If you can tell me what the output from the below is that would be helpful.
> 
> `python3 -c 'import platform; print(platform.uname().release)'`
> 
> We can possibly just switch it to the below if its going to work for all Centos/RHEL versions but i don't have anything setup to test that.
> 
> ```
> yum install yum-plugin-copr
> yum copr enable copart/restic
> yum install restic
> ```

I used the tutorial that I posted and it worked on V2.0.3 but sadly 2.1 and 2.1.1 do not work for some reason.
So my install will stay on 2.0.3 (I do have a second VPS i can test other things on later), that one also uses 2.0.3 atm

The output from the command is below.

> python3 -c 'import platform; print(platform.uname().release)'

4.18.0-240.22.1.el8_3.x86_64

![image](https://user-images.githubusercontent.com/4199669/115157413-5ca1bf80-a089-11eb-9303-5ae2dd3123db.png)

**Comment by meramsey** [comment]
Seems like the logic should have worked to select the OS if nothing was downloaded could be something else. I tested the logic for the centos detection with the release provided and it was valid.

I have another idea i think should work well but would you to confirm if the latest release binary works.

This will download latest restic source and extract and chmod it so it can be used at > /usr/local/bin/restic which should be in your path already and hopefully fix the issue.

`wget -c https://github.com/restic/restic/releases/download/v0.12.0/restic_0.12.0_linux_amd64.bz2 -O - | bzip2 -dc  > /usr/local/bin/restic && chmod +x /usr/local/bin/restic`

If it does I have the python code already made up to automatically detect latest release and to automate that in the installer for centos so it just always uses latest binary vs trying the failing repos.

```
import json
import requests
url = 'https://api.github.com/repos/restic/restic/releases/latest'
releases = json.loads(str(requests.get(url).text))
version = releases['tag_name'].strip('v')
download_url = f'https://github.com/restic/restic/releases/download/v{version}/restic_{version}_linux_amd64.bz2'
ResticArchivePath = f'/root/restic_{version}_linux_amd64.bz2'
ResticBinPath = '/usr/local/bin/restic'
command = 'wget -O %s %s' % (ResticArchivePath, download_url)
ProcessUtilities.executioner(command)
command = 'bzip2 -dc %s > %s' % (ResticArchivePath, ResticBinPath)
ProcessUtilities.executioner(command)
```

**Comment by master3395** [comment]
> Seems like the logic should have worked to select the OS if nothing was downloaded could be something else. I tested the logic for the centos detection with the release provided and it was valid.
> 
> I have another idea i think should work well but would you to confirm if the latest release binary works.
> 
> This will download latest restic source and extract and chmod it so it can be used at > /usr/local/bin/restic which should be in your path already and hopefully fix the issue.
> 
> `wget -c https://github.com/restic/restic/releases/download/v0.12.0/restic_0.12.0_linux_amd64.bz2 -O - | bzip2 -dc > /usr/local/bin/restic && chmod +x /usr/local/bin/restic`
> 
> If it does I have the python code already made up to automatically detect latest release and to automate that in the installer for centos so it just always uses latest binary vs trying the failing repos.
> 
> ```
> import json
> import requests
> url = 'https://api.github.com/repos/restic/restic/releases/latest'
> releases = json.loads(str(requests.get(url).text))
> version = releases['tag_name'].strip('v')
> download_url = f'https://github.com/restic/restic/releases/download/v{version}/restic_{version}_linux_amd64.bz2'
> ResticArchivePath = f'/root/restic_{version}_linux_amd64.bz2'
> ResticBinPath = '/usr/local/bin/restic'
> command = 'wget -O %s %s' % (ResticArchivePath, download_url)
> ProcessUtilities.executioner(command)
> command = 'bzip2 -dc %s > %s' % (ResticArchivePath, ResticBinPath)
> ProcessUtilities.executioner(command)
> ```

Sadly that did not work.

![image](https://user-images.githubusercontent.com/4199669/115270471-a0a1cc80-a13c-11eb-84ac-a00dfb2ea232.png)

The only way I've gotten it to work on V2.0.3, V2.1.1, and V2.1.1-dev

Is to use these on centos 8.

```
yum install yum-plugin-copr
yum copr enable copart/restic
yum install restic
```

**Comment by meramsey** [comment]
Well i feel silly i was unsure at first but apparently i totally missed that actually worked for both old and new and for both c7 and c8. :facepalm: 

So that seems like an easy fix by shifting the logic out of only being applied to c7 but to all centos in the bash preinstall thing.
https://github.com/usmannasir/cyberpanel/commit/048e17a1b0a5deeb4191cd4cf5324755e2ce8bb3

We will need to remove or update the python install.py file to match the same expectations too then which would simplify things greatly
