### ISSUE TITLE
Suggestion: Uninstall Mailscanner

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#581]
There should be an "uninstall Mailscanner" button on the cp rather than you having to go to each folder and delete everything manually.

**Comment by aonsyed** [comment]
Use this
https://github.com/usmannasir/cyberpanel/blob/stable/CPScripts/mailscanneruninstaller.sh

**Comment by usmannasir** [comment]
https://cyberpanel.net/docs/how-to-install-remove-mailscanner-on-cyberpanel/
