### ISSUE TITLE
Cyberpanel 2.1 Fresh Cloudlinux install, 404 post to CloudLinux/submitCageFSInstall

### ISSUE THREAD

**Issue by aitpnadmin** [litespeedtech/cyberpanel#582]
Hi Mr. Nasir,

I installed Cyberpanel on a fresh Centos7 instance like I have many times before and I find that after activating cloudlinux and rebooting I cannot submit a cagefs install job from the Cyberpanel UI.
The POST returns a 404.
Could you help me understand why I cannot call the submitCageFSInstall script?
Thanks in advance for your guidance.

<img width="955" alt="Screenshot 2021-04-15 152712" src="https://user-images.githubusercontent.com/82222564/114946206-92337800-9dff-11eb-9ea2-a17742d8b3a7.png">

**Comment by usmannasir** [comment]
Fixed here https://github.com/usmannasir/cyberpanel/commit/52a489460de1345f824ba3cd41a26375e2bf3b7e

**Comment by aitpnadmin** [comment]
@usmannasir ,
I saw you commit that for me. Thank you again! Your work is super appreciated by us. :)

**Comment by bashcode** [comment]
On fresh install with latest update,  on submitCageFSInstall script
cat: /home/cyberpanel/switchLSWSStatus: No such file or directory

**Comment by harryfear** [comment]
Same issue as bashcode
