### ISSUE TITLE
LXC Incompatibility check should be removed from the installer

### ISSUE THREAD

**Issue by webdock-io-admin** [litespeedtech/cyberpanel#589]
Hello

We are a VPS provider specializing in fast LXD backed VPS machines. We did a test to see if Cyberpanel would work in our VPS environment and the community version of Cyberpanel seems to work totally fine under LXC. LXC and the Linux kernel are constantly being updated with more and more compatibility so I suspect your LXC incompatibility check is no longer valid. 

**Some more detail:**

- We did this on our SSD Bit server profile (see webdock.io for details) which had a system on Kernel 5.4.0-29-generic on Ubuntu 20.04 Focal
- We simply commented out the LXC check, ran the installer and asked it to install all the bells and whistles.

Testing reveals Cyberpanel seems to work fine and anything we tested seemed to work. Setting up a site, SSL, installing WP etc. we even tried to see if ftp would work as there was some mention online of that being the reason for LXC being blocked at install-time and that also works fine.

Besides, we have been using PureFTP in our stacks from day 1 and have never had any problems - see https://webdock.io/en/docs/perfect-server-stacks/nginx-stacks/ubuntu-lemp-80#setup-and-configure-ftp

It really seems like the hard LXC failure check should be removed, or if there are still some issues in some components then a nicer behavior would be to warn the user about which components may have issues rather than block installation completely, as all basic functionality seems to work fine.

If you need LXD/LXC backed instances to test with, please be in touch with us and we will provide these for free.

If anyone else wants to do what we did here, simply run the installer one-liner on a clean Ubuntu 20.04 system. Once it has errored out with the LXC error, simply edit cyberpanel.sh which will be in the directory you are in, with nano or your favorite editor, and comment out the following lines (around line 270):

```
# if hostnamectl | grep -q "Virtualization: lxc"; then
#  echo -e "\nLXC detected..."
#  echo -e "CyberPanel does not support LXC"
#  echo -e "Exiting..."
#  Debug_Log2 "CyberPanel does not support LXC.. [404]"
#  exit
# fi
```

Then, re-run ./cyberpanel.sh and the installation will proceed normally.

Thanks :)

**Comment by usmannasir** [comment]
@qtwrk can you check and remove this test?

**Comment by qtwrk** [comment]
Could you please test it on other system like centos 7/8 , ubuntu 18 on LXC ?

**Comment by webdock-io-admin** [comment]
Hi - we can't test on CentOS as our platform doesn't support it. I did a test for you on Ubuntu 18.04 and while the installation took a lot longer (seemed like many more components were being installed/built from source - felt that way anyway) the results were identical: Cyberpanel seems to work just fine from what I can tell - I even tried more stuff than just setting up a site and a Wordpress installation - I fooled around with Docker and email and all seems to work.

Thanks.!

**Comment by usmannasir** [comment]
@webdock-io you don't offer centos operating system? May I know why?

**Comment by webdock-io-admin** [comment]
@usmannasir No particular reason other than we don't want to support more than 1 operating system and we feel Ubuntu is the best choice for us. Also all our tooling and software stack is built around Ubuntu. Centos works fine in LXC so there's no technical hurdle in play if that's what you are asking 

If you have no other way to test Centos on LXC, i could ask an engineer here to set up a Centos container to test, but that requires manual setup and might take a few days

**Comment by usmannasir** [comment]
No issue. @qtwrk you can remove LXC check.

**Comment by qtwrk** [comment]
https://github.com/usmannasir/cyberpanel/commit/53ebf12d6e5e876a58cc951227b4895745fac36a

done it

**Comment by usmannasir** [comment]
okay. thanks @qtwrk I will close this now.
