### ISSUE TITLE
Guest user can see the dashboard contents.

### ISSUE THREAD

**Issue by iamprogrammerlk** [litespeedtech/cyberpanel#593]
https://server.domainname:8090/base/ This page should redirect to the login page when the guest (NOT LOGIN) user tries to access it. but it shows dashboard content instead.
![CyberPanelError](https://user-images.githubusercontent.com/17584831/115137141-10974200-9fd9-11eb-81cb-26c2cf652cc2.png)

Other links that have the same issue

Shows: ERROR Error: 'userID'
https://server.domainname:8090/base/versionManagment
https://server.domainname:8090/users/createNewACL
https://server.domainname:8090/users/deleteACL
https://server.domainname:8090/users/modifyACL
https://server.domainname:8090/packages/
https://server.domainname:8090/email/
https://server.domainname:8090/ftp/
https://server.domainname:8090/Terminal/
https://server.domainname:8090/CloudLinux/listPackages
https://server.domainname:8090/CloudLinux/monitorUsage
https://server.domainname:8090/serverstatus/
https://server.domainname:8090/serverstatus/topProcesses
https://server.domainname:8090/serverstatus/cyberCPMainLogFile
https://server.domainname:8090/serverstatus/services
https://server.domainname:8090/serverstatus/CyberPanelPort
https://server.domainname:8090/serverstatus/packageManager
https://server.domainname:8090/managephp/installExtensions
https://server.domainname:8090/managephp/editPHPConfigs
https://server.domainname:8090/serverlogs/
https://server.domainname:8090/serverlogs/serverMail
https://server.domainname:8090/serverlogs/accessLogs
https://server.domainname:8090/serverlogs/errorLogs
https://server.domainname:8090/serverlogs/emaillogs
https://server.domainname:8090/serverlogs/ftplogs
https://server.domainname:8090/serverlogs/modSecAuditLogs
https://server.domainname:8090/firewall/csf
https://server.domainname:8090/CloudLinux/CageFS
https://server.domainname:8090/firewall/imunify
https://server.domainname:8090/firewall/imunifyAV
https://server.domainname:8090/emailPremium/mailQueue
https://server.domainname:8090/emailPremium/emailPolicyServer
https://server.domainname:8090/emailPremium/listDomains
https://server.domainname:8090/emailPremium/SpamAssassin
https://server.domainname:8090/emailPremium/MailScanner
https://server.domainname:8090/manageservices/manageApplications
https://server.domainname:8090/manageservices/managePowerDNS
https://server.domainname:8090/manageservices/managePostfix
https://server.domainname:8090/manageservices/managePureFtpd
https://server.domainname:8090/plugins/installed

Shows: Server Error (500)
https://server.domainname:8090/users/
https://server.domainname:8090/users/viewProfile
https://server.domainname:8090/users/createUser
https://server.domainname:8090/users/listUsers
https://server.domainname:8090/users/modifyUsers
https://server.domainname:8090/users/resellerCenter
https://server.domainname:8090/users/apiAccess
https://server.domainname:8090/websites/
https://server.domainname:8090/manageSSL/
https://server.domainname:8090/manageSSL/manageSSL
https://server.domainname:8090/manageSSL/sslForMailServer

Shows: {"status": 0, "creatFTPStatus": 0, "error_message": "'userID'"}
https://server.domainname:8090/ftp/submitFTPCreation

**Comment by h1dd3nsn1p3r** [comment]
👍 Nice find.

**Comment by usmannasir** [comment]
CyberPanel now loads through a central template loader thats why you see it. But guest can't see any private info at all it will keep getting this error, even the IP and name on top is hidden as you can see.

**Comment by iamprogrammerlk** [comment]
OK then... But I still think that an un-appropriate behavior...
