### ISSUE TITLE
Fix Permissions breaks Permissions

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#595]
When i click "Fix Permissions" i get my whole account locked out from public_html.
I have to use the tutorial below in order to fix permissions again.
V2.1.1 and V2.1.1-dev
https://github.com/whattheserver/cyberpanel-fixperms

**Comment by meramsey** [comment]
can you do a stat on your account  home directory and also the public_html folder before and after you do this?

Also are you perchance hitting that from the base homedirectory vs inside of the public_html or other website folder?

I was looking to replace the code in the backend that fixes stuff with the new stuff in future i made here
https://github.com/usmannasir/cyberpanel/blob/v2.1.1-dev/plogical/filesPermsUtilities.py

**Comment by master3395** [comment]
> can you do a stat on your account home directory and also the public_html folder before and after you do this?
> 
> Also are you perchance hitting that from the base home directory vs inside of the public_html or other website folder?
> 
> I was looking to replace the code in the backend that fixes stuff with the new stuff in the future i made here
> https://github.com/usmannasir/cyberpanel/blob/v2.1.1-dev/plogical/filesPermsUtilities.py

Will try this again in a few hours, I need to fix up other issues with mail on my install :/
There's been more and more issues lately :/
I even re-installed CP many times now.
This last week, I think I've re-installed CP up to 20 times because things break.

**Comment by master3395** [comment]
Can't replicate it now that i reverted back to an earlier stage.
Will close this.
