### ISSUE TITLE
imagick on PHP 8 - CP says it install extension but does not

### ISSUE THREAD

**Issue by j-a-pope** [litespeedtech/cyberpanel#596]
Trying to install the imagick extension under PHP 8 from within CP does not work. 

The messages imply that it does:

```
Reading package lists...
Building dependency tree...
Reading state information...
PHP Extension Installed.
```

but it is not installed and revisiting the php config page just shows the option to install it available again. 

I understand that this might be an issue with imagick in PHP 8 more generally than in CP - but then it should not be shown as an option and say that it has been installed when it hasn't.

**Comment by iamprogrammerlk** [comment]
I have the same problem, but turnout this problem is not with the CyberPanel but LiteSpeed server by its self. Litespeed uses LSPHP and they don't have developed PHP8 supported Imagick extension yet.

**Comment by usmannasir** [comment]
I've dynamically loaded php extensions in v2.3.2-dev and it will come with v2.3.2, so if extension is installed it will be shown as instlaled.
