### ISSUE TITLE
Broken Admin Left Menu

### ISSUE THREAD

**Issue by kuwaitman** [litespeedtech/cyberpanel#60]
hi, for some reason i just installed the latest Cyberpanel. in google chrome
i got a broken left menu. but when i hide it from the top. it closes fine.
i cleared the cache and tired again. same issue. i also tired safari same issue. so i decided to report the issue here. (image attached) hopefully someone can resolve it. thank you.

![menu-issue](https://user-images.githubusercontent.com/33569492/48644595-26614100-e9f4-11e8-9f70-31db6716a5d4.png)

**Comment by usmannasir** [comment]
Try setting your first name to just **Abdul** or **Rahman**.
