### ISSUE TITLE
CloudFlare changes to DNS

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#604]
Hello, not sure if there is something that needs to be changed in CP for CloudFlare's upcoming changes in May this year.
But I thought it would be good to ask.
![image](https://user-images.githubusercontent.com/4199669/116135151-0c51df80-a6d1-11eb-81b2-e308ec1f230e.png)

https://developers.cloudflare.com/cloudflare-one/policies/filtering/dns-policies-builder

**Comment by usmannasir** [comment]
I don't see any change in API.
