### ISSUE TITLE
Preview page should not be accessible to guests

### ISSUE THREAD

**Issue by nickfrosty** [litespeedtech/cyberpanel#611]
When you are in the control panel and selected to viewing a specific website, their is a "preview" button that goes to a page that allows you to "preview" the website on that specific domain. The browser takes you to "0.0.0.0/preview/domain.tld".

Any person can browse to that same url and view the "preview" page of your website. Even guests/unauthenticated users.
This would be fine if a valid and authorized user is logged into the control panel.

I personally don't think this "preview" feature has a lot of worth and would remove it. But at the very least should have some authentication on it

**Comment by usmannasir** [comment]
The preview feature does not pose any security thread. Because it just proxy web request internally to your domain which is what happens when user open the domain on browser.

But the only thing that it does is bypass global dns resolution and request to local server directly.
