### ISSUE TITLE
Connection to Amazon RDS private database error because the install create user with public_IP and connect with private_IP

### ISSUE THREAD

**Issue by adeogliari** [litespeedtech/cyberpanel#612]
When we setup a connection to a RDS private database the install fail because the installer get "user@$Server_IP" and when we use a private database, the connection is made with "user@Private_IP(from instance)".

I'm studying and I found this line for IP consult in install script cyberpanel.sh but I don't know where and how to create a option to insert the private IP of instance to connect in Amazon RDS private database:

This is the line of user creation:
"CREATE USER 'cyberpanel'@'public_ip' IDENTIFIED BY 'rSZHbKeE62PtWa'"

This is the line of user connection:
(1045, "Access denied for user 'cyberpanel'@'private_IP' (using password: YES)")

**Comment by usmannasir** [comment]
I've not added support for amazon private ip yet.
