### ISSUE TITLE
Add OpenLightSpeed Options In CyberPanel

### ISSUE THREAD

**Issue by MaximKing1** [litespeedtech/cyberpanel#617]
Some options for websites are only on OpenLightSpeed panel and users can’t access that, maybe adding some of the GZip and other optimisation and security stuff in the CyberPanel for each website would be great for users of it, also maybe have a panel for the API which shows how to use it for end users..

**Comment by MaximKing1** [comment]
Hmm? Did I say something lol

**Comment by usmannasir** [comment]
you asked the same question on forums and its not a bug.
