### ISSUE TITLE
Installation failed. Error message: [404] While Installing Wordpress

### ISSUE THREAD

**Issue by abhranil26** [litespeedtech/cyberpanel#619]
![image](https://user-images.githubusercontent.com/30792751/118635805-a3521900-b7f1-11eb-9ed6-7f8163adb8ff.png)
 
This is the error I am getting while trying to install Wordpress on a newly created website.
Using the latest version of Cyberpanel - 
![image](https://user-images.githubusercontent.com/30792751/118636509-663a5680-b7f2-11eb-9d1d-73fabfdc40a5.png)

What I have noticed is the Wordpress files are copied to the public_html folder 
![image](https://user-images.githubusercontent.com/30792751/118636584-781bf980-b7f2-11eb-8e5d-41826543d40c.png)

Also database is created 
![image](https://user-images.githubusercontent.com/30792751/118636708-9a157c00-b7f2-11eb-837f-41ad6181093b.png)

But the database is not linked automatically like it does always.
Opening Wp-admin presents you with the setup window 
![image](https://user-images.githubusercontent.com/30792751/118636791-b3b6c380-b7f2-11eb-819d-e2a4c924e98e.png)

**Comment by rallisf1** [comment]
Seems like a permission issue, wp-config.php doesn't get generated.

Try again and post your cp and litespeed logs to make sure. Logs paths and info found here: https://cyberpanel.net/docs/log-files-on-cyberpanel/

**Comment by usmannasir** [comment]
Also check this guide -> https://forums.cyberpanel.net/discussion/5342/wordpress-installation-failed-error-message-404

This is not an error, could be a small mistake on your end.

**Comment by abhranil26** [comment]
You are right
I tried on another installation of CP, works fine. I guess I'll perform a clean install of CP on this one

**Comment by abhranil26** [comment]
Altough in the logs it seems it is unable to connect with mysql

**Comment by johnjoemorgan** [comment]
Work around found: Had to use PHP MyAdmin to look at what CyberPanel had set the DB details to and then edit  wp-config  in the newly in installed WordPress to match that.

**Comment by kangarooo** [comment]
Fresh DO server with DO Cyberpanel.
WP with php 8.0
Got this error.
No database created.
wp files in place in file manager.
