### ISSUE TITLE
spamassassin fails after install

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#621]
Hello.

CP 2.1.1 (Also tried on 2.1.1-dev)

After installing spamassassin, all e-mails go to the drain, and gives the user automatic e-mail
Image below shows me having installed spamassassin and the e-mail the user get's on all e-mails sent to the domains.
If I use the debugger on https://cloud.cyberpanel.net/debugger/debugEmail/domain/
Then it uninstalls/deaktivates spamassassin, and that fixes the issue.
I have tried with report_safe on and off, same result.
The e-mails get sent from hotmail and gmail, both fails.
Removing spamassassin makes it work.

![image](https://user-images.githubusercontent.com/4199669/118869375-99a9dd80-b8e5-11eb-8302-2c8369a4b064.png)

![image](https://user-images.githubusercontent.com/4199669/118869266-72531080-b8e5-11eb-9429-de3d1c6fbab0.png)

**Comment by usmannasir** [comment]
Can you also share logs from `journalctl -f | grep postfix` ?

**Comment by master3395** [comment]
> Can you also share logs from `journalctl -f | grep postfix` ?

I got the MailQueue text, that said following:
![image](https://user-images.githubusercontent.com/4199669/118986321-8c413180-b97f-11eb-817a-b1c54af0b2ca.png)
[MAIL QUEUE.txt](https://github.com/usmannasir/cyberpanel/files/6516227/MAIL.QUEUE.txt)

Below is from the command you posted over.
[journalctl.txt](https://github.com/usmannasir/cyberpanel/files/6516228/journalctl.txt)

**Comment by usmannasir** [comment]
```May 20 15:23:26 User.contaboserver.net postfix/pipe[162540]: 92E9783C64: to=<MAILER-DAEMON@localhost.localdomain>, relay=spamassassin, delay=0.64, delays=0.09/0/0/0.55, dsn=2.0.0, status=sent (delivered via spamassassin service)```

seems like spamassasin is delivering the email.

**Comment by usmannasir** [comment]
This is the last line I took from the logs, there are other lines above which says the same.

**Comment by master3395** [comment]
I tried again, and got this:
It gets delivered to the sender's e-mail saying it can't be delivered.

[emaillogs.txt](https://github.com/usmannasir/cyberpanel/files/6517419/emaillogs.txt)

![image](https://user-images.githubusercontent.com/4199669/119014399-3a58d580-b998-11eb-9fa2-6ecc9788a8ea.png)

![image](https://user-images.githubusercontent.com/4199669/119014666-7ee47100-b998-11eb-837d-e3c94db2268a.png)

**Comment by master3395** [comment]
I tried again, and got this:
It gets delivered to the sender's e-mail saying it can't be delivered.

[emaillogs.txt](https://github.com/usmannasir/cyberpanel/files/6517419/emaillogs.txt)

![image](https://user-images.githubusercontent.com/4199669/119014399-3a58d580-b998-11eb-9fa2-6ecc9788a8ea.png)

![image](https://user-images.githubusercontent.com/4199669/119014954-c23edf80-b998-11eb-9b06-22af148cd193.png)

**Comment by usmannasir** [comment]
What is the full error?  I can see half the image only.

**Comment by master3395** [comment]
It kept going, it never ended.
It said the same thing over and over

On the image below, is the same message that comes over and over.
I had to do the debug e-mail from cloud to get the e-mail working again (disabling spamassassin).

I can try again, but I think it will still do the same issue over and over.

![image](https://user-images.githubusercontent.com/4199669/119181980-a27bea00-ba72-11eb-9658-f64f00673cf7.png)

**Comment by usmannasir** [comment]
May I know which OS is this ?

**Comment by master3395** [comment]
> May I know which OS is this ?

Centos 8
CP 2.1.1

**Comment by usmannasir** [comment]
I am going to close this now, because I've been testing this on a DO Centos8 vm for past few hours and my emails are going through, you need to provide more details or open a separate issue because it looks like you might be doing something else too.
