### ISSUE TITLE
Rainloop update

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#622]
Hello.

Not sure how to bump the rainloop from 1.15.0 up to 1.16.0?
Maybe it should be done in the core package?

**Comment by usmannasir** [comment]
The update should bring you latest version?

**Comment by usmannasir** [comment]
I am closing this issue, because update will get you a new version of rain loop ->https://github.com/usmannasir/cyberpanel/blob/4740fa1db25e35bafc90197e3a53f752adad866a/plogical/upgrade.py#L401

**Comment by master3395** [comment]
> I am closing this issue, because update will get you a new version of rain loop ->
> 
> https://github.com/usmannasir/cyberpanel/blob/4740fa1db25e35bafc90197e3a53f752adad866a/plogical/upgrade.py#L401

I just tried the normal "upgrade" way https://cyberpanel.net/docs/upgrading-cyberpanel/
It didn't result in giving me 1.16.0?
I did check the link, and it does indeed download 1.16.0
I'm confused.

Image below is from 8090/?admin

![image](https://user-images.githubusercontent.com/4199669/118988586-9ebc6a80-b981-11eb-8ce6-251924ce830c.png)

**Comment by master3395** [comment]
This is how it looks right after i tried to upgrade again, to see what happen.
I can't see anywhere in the output of SSH where it even mentions rainloop

![image](https://user-images.githubusercontent.com/4199669/118998699-ee9f2f80-b989-11eb-8306-29b97127a183.png)

**Comment by master3395** [comment]
This is how it looks right after i tried to upgrade again, to see what happen.
I can't see anywhere in the output of SSH where it even mentions rainloop

![image](https://user-images.githubusercontent.com/4199669/118998844-10001b80-b98a-11eb-85d1-feb2b6adc27a.png)

**Comment by master3395** [comment]
> I am closing this issue, because update will get you a new version of rain loop ->
> 
> https://github.com/usmannasir/cyberpanel/blob/4740fa1db25e35bafc90197e3a53f752adad866a/plogical/upgrade.py#L401

What can I do to get the new version?
I tried re-install, but it seems to have skipped the e-mail :/
