### ISSUE TITLE
This isnt an issue just a question, how to I change the look?

### ISSUE THREAD

**Issue by MadMacMig** [litespeedtech/cyberpanel#627]
I am trying to start my own cloud hosting company and I though going with Cyberpanel would be a great idea, id just like to know how I can change the look of the whole panel and rebrand it. Because Cyberpanel is open source I should be able to do that, its just the how to do that.

**Comment by tbhaxor** [comment]
@MadMacMig Check this out

https://forums.cyberpanel.net/discussion/234/whitelabel-option-customize-interface

**Comment by istiak101** [comment]
@MadMacMig all individual modules are Django apps. you will find these in /usr/local/CyberCP in your system. To modify any specific modules html go to that module directory. You will find templates directory and inside that you will find all the html templates. After modifying run "systemctl restart lscpd" from terminal and your changes will be loaded. And all static css and js files are in /usr/local/CyberCP/public/static. Modify those and restart lscpd.

Please don't issues like this. Github is for tracking bugs. Use facebook group/discord/CyberPanel forum. I will close this after few days from now if I don't get any response from you.
