### ISSUE TITLE
Won't install ZIP archive management extension for PHP 7.4 and above (CentOS 7)

### ISSUE THREAD

**Issue by spacevega21** [litespeedtech/cyberpanel#628]
Loaded plugins: copr, fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.turhost.com
 * epel: ftp.nluug.nl
 * extras: mirror.isimtescil.com.tr
 * remi-php73: mirrors.ukfast.co.uk
 * updates: mirror.telepoint.bg
Package lsphp74-common-7.4.16-2.el7.x86_64 already installed and latest version
Nothing to do
PHP Extension Installed.

----

I have followed the commands linked here > https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:php:pecl-extension:lsphp74_zip?rev=1580248954 // but I am still getting the same issue...

**Comment by qtwrk** [comment]
What's the OS? 

What error you see whhe you follow that wiki?

**Comment by spacevega21** [comment]
CentOS 7. The commands ran pefectly and I was still unable to install Zip PHP. I got the same message as shown in the above message.

**Comment by spacevega21** [comment]
<img width="1368" alt="Screenshot 2021-05-29 at 13 44 20" src="https://user-images.githubusercontent.com/85022004/120073709-6c052700-c091-11eb-8c65-64d2f9d557cc.png">

<img width="1368" alt="Screenshot 2021-05-29 at 13 44 30" src="https://user-images.githubusercontent.com/85022004/120073720-7fb08d80-c091-11eb-8ed3-182d73f8d92c.png">

**Comment by qtwrk** [comment]
try 

```
yum remove -y libzip-devel
yum install -y https://cyberpanel.sh/misc/libzip-0.11.2-6.el7.psychotic.x86_64.rpm
yum install -y https://cyberpanel.sh/misc/libzip-devel-0.11.2-6.el7.psychotic.x86_64.rpm
yum install lsphp74-devel
mkdir /usr/local/lsws/lsphp74/tmp
/usr/local/lsws/lsphp74/bin/pecl channel-update pecl.php.net
/usr/local/lsws/lsphp74/bin/pear config-set temp_dir /usr/local/lsws/lsphp74/tmp
/usr/local/lsws/lsphp74/bin/pecl install zip
echo "extension=zip.so" >/usr/local/lsws/lsphp74/etc/php.d/20-zip.ini
pkill lsphp
```


then check with phpinfo page

**Comment by spacevega21** [comment]
Do I type in ---- echo "extension=zip.so" ??

<img width="880" alt="Screenshot 2021-05-29 at 15 25 11" src="https://user-images.githubusercontent.com/85022004/120073864-0feed280-c092-11eb-823b-fc929f3cd63f.png">

**Comment by qtwrk** [comment]
`echo "extension=zip.so" >/usr/local/lsws/lsphp74/etc/php.d/20-zip.ini`

this will do that for you

**Comment by spacevega21** [comment]
Okay thank you, I have ran that command now.

**Comment by spacevega21** [comment]
<img width="901" alt="Screenshot 2021-05-29 at 15 33 03" src="https://user-images.githubusercontent.com/85022004/120074218-b9829380-c093-11eb-9778-f53ccb95340c.png">
<img width="901" alt="Screenshot 2021-05-29 at 15 34 50" src="https://user-images.githubusercontent.com/85022004/120074222-bbe4ed80-c093-11eb-94d1-75df66cd7755.png">

**Comment by qtwrk** [comment]
it says zip is already installed  , you can verify with phpinfo

**Comment by spacevega21** [comment]
Just typed in the php command phpinfo() and nothing is appearing.

**Comment by qtwrk** [comment]
you need to create it as page and access it by browser , or `/usr/local/lsws/lsphp74/bin/lsphp -i | grep -i zip`

**Comment by spacevega21** [comment]
<img width="1611" alt="Screenshot 2021-05-29 at 15 53 16" src="https://user-images.githubusercontent.com/85022004/120074716-0e270e00-c096-11eb-9b61-e94ba80be363.png">

**Comment by qtwrk** [comment]
so you do have zip extension installed

**Comment by spacevega21** [comment]
It's just that when I go to Cyberpanel and try to install it. It doesn't show the extenstion as installed afterwards...

Before:
<img width="1391" alt="Screenshot 2021-05-29 at 16 00 10" src="https://user-images.githubusercontent.com/85022004/120074905-f603be80-c096-11eb-82c1-4436674374e8.png">
After:
<img width="1391" alt="Screenshot 2021-05-29 at 16 01 37" src="https://user-images.githubusercontent.com/85022004/120074936-28152080-c097-11eb-972c-8ac9d3c6249b.png">

**Comment by qtwrk** [comment]
yes, it's little known display bug 

despite the panel shows not installed , but it is actually installed already

**Comment by spacevega21** [comment]
Thank you :)
