### ISSUE TITLE
Switching to Litespeed Enterprise after install fails

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#629]
Hello.
I have done 2 trials.

1 where i install Enterprise on the first install (works fine) but CP does not say I got a license.
I do indeed have LiteSpeed Ent on port 7080.

But if if I go into CP and add the license there, I get the error below.

![image](https://user-images.githubusercontent.com/4199669/120116228-73a6f780-c187-11eb-87ad-d0b300aec06d.png)

**Comment by usmannasir** [comment]
You was trying with trial or an actual license? If an actual license was the license released from store?

Secondly, if it was trial, I hope this server did not get the trial in past?

**Comment by master3395** [comment]
> 
> 
> You was trying with trial or an actual license? If an actual license was the license released from store?
> 
> Secondly, if it was trial, I hope this server did not get the trial in past?

This server uses the free tier license.
I used it on first install, but one I logged into CP, it asked me to input the license again, and it showed the errors over.
If I on the other hand, install openlitespeed CP then goes into CP and enables the license, then it works fine, both inside CP and on 7080.

**Comment by usmannasir** [comment]
1. Installed CyberPanel with OLS - Converted to Ent with trial - OK
2.  Installed CyberPanel with OLS - Converted to Ent with trial - Applied Free Starter - OK

Now checking other use cases. OS Ubuntu 20.04

**Comment by usmannasir** [comment]
1. Installed CyberPanel with LSWS Ent Trial - OK.

Now I am not sure where you are getting the issue or it is only specific to you, could be your license issue.
