### ISSUE TITLE
Ubuntu 20.04 crashes

### ISSUE THREAD

**Issue by drillsar** [litespeedtech/cyberpanel#630]
I tried installing on a fresh install and gives no error it closes terminal and goes back to login screen.

**Comment by qtwrk** [comment]
what exactly was the command you run ?  
what provider ?

**Comment by drillsar** [comment]
I used the command 

wget -O installer.sh https://cyberpanel.net/install.sh

then chmod 755 installer.sh
After that used sh installer.sh

it seems to install stuff but at somepoiny screen goes black than to login screen.

**Comment by qtwrk** [comment]
maybe you can do a quick video recording ?

and what is the provider ? I will try to reproduce

**Comment by drillsar** [comment]
What you mean by provider? Now weird thing I have no internet. If you mean isp verizon

**Comment by qtwrk** [comment]
no , I mean where did you get the server ?

**Comment by drillsar** [comment]
I guess can do quick video. Where I send video? Is there away to clean it. Like do it all over again?

**Comment by drillsar** [comment]
The server is my computer MSI tomahawk max is motherboard

**Comment by qtwrk** [comment]
you need to resintall the server system  

you can put it on youtube , or google driver or something then share the link

**Comment by drillsar** [comment]
Ubuntu 20.04 should I perhaps use an older version

**Comment by qtwrk** [comment]
reinstall it to minimal version

**Comment by drillsar** [comment]
Ok I think did that. I’ll try again

**Comment by iamaldi** [comment]
> I used the command
> 
> wget -O installer.sh https://cyberpanel.net/install.sh
> 
> then chmod 755 installer.sh
> After that used sh installer.sh
> 
> it seems to install stuff but at somepoiny screen goes black than to login screen.

You can try `bash installer.sh` instead of `sh install.sh` and see if that resolves the issue.
Also make sure you are running as `root`.

**Comment by usmannasir** [comment]
I can not reproduce this issue.
