### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by MaximKing1** [litespeedtech/cyberpanel#635]
When I use the install command, with the root user `sudo su -` it gives this error.

```
debconf: falling back to frontend: Noninteractive
debconf: unable to initialize frontend: Noninteracitve
debconf: (Can't locate Debconf/FrontEnd/Noninteracitve.pm in @INC (you may need to install the Debconf::FrontEnd::Noninteracitve module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at (eval 18) line 2.)
debconf: falling back to frontend: Noninteractive
mount: /var/lib/grub/esp: special device /dev/disk/by-id/scsi-36d4ae5207ba60100281c3dca06914a86-part1 does not exist.
dpkg: error processing package grub-efi-amd64-signed (--configure):
 installed grub-efi-amd64-signed package post-installation script subprocess returned error exit status 32
dpkg: dependency problems prevent processing triggers for shim-signed:
 shim-signed depends on grub-efi-amd64-signed | grub-efi-arm64-signed; however:
  Package grub-efi-amd64-signed is not configured yet.
  Package grub-efi-arm64-signed is not installed.

dpkg: error processing package shim-signed (--configure):
 dependency problems - leaving triggers unprocessed
Errors were encountered while processing:
 grub-efi-amd64-signed
 shim-signed
E: Sub-process /usr/bin/dpkg returned an error code (1)
above command failed...
root@hs1:~#
```
Any idea how to fix this? Thanks maxim

**Comment by qtwrk** [comment]
what's the OS and provider ?

**Comment by MaximKing1** [comment]
> what's the OS and provider ?

It’s Ubuntu 20.04 and the provider is my garage server rack lol

**Comment by MaximKing1** [comment]
![47A189D2-4653-43C5-9BCF-ACE0608A701A](https://user-images.githubusercontent.com/73140396/120846738-78deba80-c56a-11eb-96dd-5ece7e083c19.jpeg)
I know it’s messy
![E46707A7-31CF-4706-9780-8B3A4473B5F5](https://user-images.githubusercontent.com/73140396/120846753-7da36e80-c56a-11eb-9ea1-19a03b6650b3.jpeg)

**Comment by MaximKing1** [comment]
Sorry didn’t mean to close, phone is glitching 
![DC07C367-96A2-4BBF-B627-BFCAF3C27487](https://user-images.githubusercontent.com/73140396/120846858-9e6bc400-c56a-11eb-8c96-f64eaaabc0a4.jpeg)

**Comment by qtwrk** [comment]
you don't need to post your server rack  ..

anyway , please make sure it is ubuntu 20.04 minimal , then run this before you run installer 


```
echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
sudo apt-get install -y -q
```


see if it helps

**Comment by iamaldi** [comment]
Taking a quick look at the error message, it says:
```
  Package grub-efi-amd64-signed is not configured yet.
  Package grub-efi-arm64-signed is not installed.
```
A quick google search for `Package grub-efi-arm64-signed is not installed.` results in the following AskUbuntu post which might resolve the issue https://askubuntu.com/a/1239594

**Comment by MaximKing1** [comment]
> Taking a quick look at the error message, it says:
> 
> ```
>   Package grub-efi-amd64-signed is not configured yet.
>   Package grub-efi-arm64-signed is not installed.
> ```
> 
> A quick google search for `Package grub-efi-arm64-signed is not installed.` results in the following AskUbuntu post which might resolve the issue https://askubuntu.com/a/1239594

Thanks and sorry, just got it feel like a kid on Christmas 😂

**Comment by MaximKing1** [comment]
Thanks so much,
For anybody facing the same issue use 
```
sudo apt-get purge grub\*
sudo apt-get install grub-efi
sudo apt-get autoremove
sudo update-grub
```

**Comment by MaximKing1** [comment]
Okay now there is another issue, after the CyberPanel install failed I cannot run `apt update`

```
root@hs1:~# apt-get update
Err:1 http://gb.archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'gb.archive.ubuntu.com'
Err:2 https://updates.atomicorp.com/channels/atomic/ubuntu focal InRelease
  Temporary failure resolving 'updates.atomicorp.com'
Err:3 http://rpms.litespeedtech.com/debian focal InRelease
  Temporary failure resolving 'rpms.litespeedtech.com'
Err:4 https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 InRelease
  Temporary failure resolving 'repo.mongodb.org'
Err:5 https://aquasecurity.github.io/trivy-repo/deb focal InRelease
  Temporary failure resolving 'aquasecurity.github.io'
Err:6 https://packages.cisofy.com/community/lynis/deb stable InRelease
  Temporary failure resolving 'packages.cisofy.com'
Err:7 http://gb.archive.ubuntu.com/ubuntu focal-updates InRelease
  Temporary failure resolving 'gb.archive.ubuntu.com'
Err:8 http://gb.archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'gb.archive.ubuntu.com'
Err:9 http://gb.archive.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'gb.archive.ubuntu.com'
Reading package lists... Done
W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
W: Failed to fetch https://updates.atomicorp.com/channels/atomic/ubuntu/dists/focal/InRelease  Temporary failure resolving 'updates.atomicorp.com'
W: Failed to fetch https://packages.cisofy.com/community/lynis/deb/dists/stable/InRelease  Temporary failure resolving 'packages.cisofy.com'
W: Failed to fetch http://rpms.litespeedtech.com/debian/dists/focal/InRelease  Temporary failure resolving 'rpms.litespeedtech.com'
W: Failed to fetch https://repo.mongodb.org/apt/ubuntu/dists/focal/mongodb-org/4.4/InRelease  Temporary failure resolving 'repo.mongodb.org'
W: Failed to fetch https://aquasecurity.github.io/trivy-repo/deb/dists/focal/InRelease  Temporary failure resolving 'aquasecurity.github.io'
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@hs1:~# apt update 
Err:1 http://gb.archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'gb.archive.ubuntu.com'
Err:2 https://updates.atomicorp.com/channels/atomic/ubuntu focal InRelease
  Temporary failure resolving 'updates.atomicorp.com'
Err:3 https://packages.cisofy.com/community/lynis/deb stable InRelease
  Temporary failure resolving 'packages.cisofy.com'
Err:4 http://rpms.litespeedtech.com/debian focal InRelease
  Temporary failure resolving 'rpms.litespeedtech.com'
Err:5 https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 InRelease
  Temporary failure resolving 'repo.mongodb.org'
Err:6 https://aquasecurity.github.io/trivy-repo/deb focal InRelease
  Temporary failure resolving 'aquasecurity.github.io'
Err:7 http://gb.archive.ubuntu.com/ubuntu focal-updates InRelease
  Temporary failure resolving 'gb.archive.ubuntu.com'
Err:8 http://gb.archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'gb.archive.ubuntu.com'
Err:9 http://gb.archive.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'gb.archive.ubuntu.com'
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
W: Failed to fetch https://updates.atomicorp.com/channels/atomic/ubuntu/dists/focal/InRelease  Temporary failure resolving 'updates.atomicorp.com'
W: Failed to fetch https://packages.cisofy.com/community/lynis/deb/dists/stable/InRelease  Temporary failure resolving 'packages.cisofy.com'
W: Failed to fetch http://rpms.litespeedtech.com/debian/dists/focal/InRelease  Temporary failure resolving 'rpms.litespeedtech.com'
W: Failed to fetch https://repo.mongodb.org/apt/ubuntu/dists/focal/mongodb-org/4.4/InRelease  Temporary failure resolving 'repo.mongodb.org'
W: Failed to fetch https://aquasecurity.github.io/trivy-repo/deb/dists/focal/InRelease  Temporary failure resolving 'aquasecurity.github.io'
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@hs1:~# 
```

**Comment by iamaldi** [comment]
> Okay now there is another issue, after the CyberPanel install failed I cannot run `apt update`
> 
> ```
> root@hs1:~# apt-get update
> Err:1 http://gb.archive.ubuntu.com/ubuntu focal InRelease
>   Temporary failure resolving 'gb.archive.ubuntu.com'
> Err:2 https://updates.atomicorp.com/channels/atomic/ubuntu focal InRelease
>   Temporary failure resolving 'updates.atomicorp.com'
> Err:3 http://rpms.litespeedtech.com/debian focal InRelease
>   Temporary failure resolving 'rpms.litespeedtech.com'
> Err:4 https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 InRelease
>   Temporary failure resolving 'repo.mongodb.org'
> Err:5 https://aquasecurity.github.io/trivy-repo/deb focal InRelease
>   Temporary failure resolving 'aquasecurity.github.io'
> Err:6 https://packages.cisofy.com/community/lynis/deb stable InRelease
>   Temporary failure resolving 'packages.cisofy.com'
> Err:7 http://gb.archive.ubuntu.com/ubuntu focal-updates InRelease
>   Temporary failure resolving 'gb.archive.ubuntu.com'
> Err:8 http://gb.archive.ubuntu.com/ubuntu focal-backports InRelease
>   Temporary failure resolving 'gb.archive.ubuntu.com'
> Err:9 http://gb.archive.ubuntu.com/ubuntu focal-security InRelease
>   Temporary failure resolving 'gb.archive.ubuntu.com'
> Reading package lists... Done
> W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
> W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
> W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
> W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
> W: Failed to fetch https://updates.atomicorp.com/channels/atomic/ubuntu/dists/focal/InRelease  Temporary failure resolving 'updates.atomicorp.com'
> W: Failed to fetch https://packages.cisofy.com/community/lynis/deb/dists/stable/InRelease  Temporary failure resolving 'packages.cisofy.com'
> W: Failed to fetch http://rpms.litespeedtech.com/debian/dists/focal/InRelease  Temporary failure resolving 'rpms.litespeedtech.com'
> W: Failed to fetch https://repo.mongodb.org/apt/ubuntu/dists/focal/mongodb-org/4.4/InRelease  Temporary failure resolving 'repo.mongodb.org'
> W: Failed to fetch https://aquasecurity.github.io/trivy-repo/deb/dists/focal/InRelease  Temporary failure resolving 'aquasecurity.github.io'
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> root@hs1:~# apt update 
> Err:1 http://gb.archive.ubuntu.com/ubuntu focal InRelease
>   Temporary failure resolving 'gb.archive.ubuntu.com'
> Err:2 https://updates.atomicorp.com/channels/atomic/ubuntu focal InRelease
>   Temporary failure resolving 'updates.atomicorp.com'
> Err:3 https://packages.cisofy.com/community/lynis/deb stable InRelease
>   Temporary failure resolving 'packages.cisofy.com'
> Err:4 http://rpms.litespeedtech.com/debian focal InRelease
>   Temporary failure resolving 'rpms.litespeedtech.com'
> Err:5 https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 InRelease
>   Temporary failure resolving 'repo.mongodb.org'
> Err:6 https://aquasecurity.github.io/trivy-repo/deb focal InRelease
>   Temporary failure resolving 'aquasecurity.github.io'
> Err:7 http://gb.archive.ubuntu.com/ubuntu focal-updates InRelease
>   Temporary failure resolving 'gb.archive.ubuntu.com'
> Err:8 http://gb.archive.ubuntu.com/ubuntu focal-backports InRelease
>   Temporary failure resolving 'gb.archive.ubuntu.com'
> Err:9 http://gb.archive.ubuntu.com/ubuntu focal-security InRelease
>   Temporary failure resolving 'gb.archive.ubuntu.com'
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> All packages are up to date.
> W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
> W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
> W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
> W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'gb.archive.ubuntu.com'
> W: Failed to fetch https://updates.atomicorp.com/channels/atomic/ubuntu/dists/focal/InRelease  Temporary failure resolving 'updates.atomicorp.com'
> W: Failed to fetch https://packages.cisofy.com/community/lynis/deb/dists/stable/InRelease  Temporary failure resolving 'packages.cisofy.com'
> W: Failed to fetch http://rpms.litespeedtech.com/debian/dists/focal/InRelease  Temporary failure resolving 'rpms.litespeedtech.com'
> W: Failed to fetch https://repo.mongodb.org/apt/ubuntu/dists/focal/mongodb-org/4.4/InRelease  Temporary failure resolving 'repo.mongodb.org'
> W: Failed to fetch https://aquasecurity.github.io/trivy-repo/deb/dists/focal/InRelease  Temporary failure resolving 'aquasecurity.github.io'
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> root@hs1:~# 
> ```

This does not seem an issue with CyberPanel itself. However, taking a look at the logs this seems to not be resolving any of the APT sources. Could you try `sudo apt-get clean` - https://askubuntu.com/a/1268839

If that does not work, maybe try changing the Ubuntu Software Server to another server then run,

```console
$ apt-get clean
$ apt-get update
```

See if these help.

**Comment by netbospl** [comment]
> Temporary failure resolving 'gb.archive.ubuntu.com'

It will help but error say
Temporary failure resolving 'gb.archive.ubuntu.com',
DNS resolution is not working. surely
add to /etc/resolv.conf or create this file with
`nameserver 8.8.8.8`

**Comment by MaximKing1** [comment]
> > Temporary failure resolving 'gb.archive.ubuntu.com'
> 
> It will help but error say
> Temporary failure resolving 'gb.archive.ubuntu.com',
> DNS resolution is not working. surely
> add to /etc/resolv.conf or create this file with
> `nameserver 8.8.8.8`

Yeah, I had to reset in the end luckily the other RAID drive saved me 🤞
Thank You
