### ISSUE TITLE
In the dashboard username didn't show/display

### ISSUE THREAD

**Issue by Beatdown032** [litespeedtech/cyberpanel#636]
Hi guys! I have installed CyberPanel latest version, Ubuntu 20.04 and centOS 8, however the username didn't show/display, see below. Any help? 

[https://drive.google.com/file/d/1JFQTaiLBde4dJgNWIcNW1bCwO_or_r-5/view?usp=sharing](url)

**Comment by usmannasir** [comment]
As I explained in the group, I've removed that bar, it was redundant.
