### ISSUE TITLE
Power DNS server error (500)

### ISSUE THREAD

**Issue by Beatdown032** [litespeedtech/cyberpanel#637]
Hi Everyone,

I have fresh install the latest version of CP but I have an issue with the PowerDNS any advice on this Error OS Ubuntu 20.04 or CentOS.

**Comment by netbospl** [comment]
I'm unable to replicate, using VM and ubuntu 20.04 image
Where/Which page?
Do You have yo do anything to see this warning?
Does PowerDNS still work after this shows or work at all?

**Comment by Beatdown032** [comment]
Hi, I have checked the status of the PowerDNS it's active and running..

root@vmi603486:~# systemctl restart pdns
root@vmi603486:~# systemctl start pdns
root@vmi603486:~# systemctl status pdns
● pdns.service - PowerDNS Authoritative Server
     Loaded: loaded (/lib/systemd/system/pdns.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-06-05 23:35:01 +08; 26s ago
       Docs: man:pdns_server(1)
             man:pdns_control(1)
             https://doc.powerdns.com
   Main PID: 117244 (pdns_server)
      Tasks: 8 (limit: 19148)
     Memory: 6.7M
     CGroup: /system.slice/pdns.service
             └─117244 /usr/sbin/pdns_server --guardian=no --daemon=no --disable-syslog --log-timestamp=no --write-pid=no

**Comment by netbospl** [comment]
> Hi, I have checked the status of the PowerDNS it's active and running..
> 
> root@vmi603486:~# systemctl restart pdns root@vmi603486:~# systemctl start pdns
> root@vmi603486:~# systemctl status pdns
> ● pdns.service - PowerDNS Authoritative Server
> Loaded: loaded (/lib/systemd/system/pdns.service; enabled; vendor preset: enabled)
> Active: active (running) since Sat 2021-06-05 23:35:01 +08; 26s ago
> Docs: man:pdns_server(1)
> man:pdns_control(1)
> https://doc.powerdns.com
> Main PID: 117244 (pdns_server)
> Tasks: 8 (limit: 19148)
> Memory: 6.7M
> CGroup: /system.slice/pdns.service
> └─117244 /usr/sbin/pdns_server --guardian=no --daemon=no --disable-syslog --log-timestamp=no --write-pid=no

Good, what would Yoiu have to do to see this error? Or me to replicate?

**Comment by Beatdown032** [comment]
https://000.000.00.000:8090/manageservices/managePowerDNS <----- When you clicking the Manage PowerDNS the link is "Server Error (500)" so, is there any way to fix it? or I will leave this?

**Comment by netbospl** [comment]
Simply going on that page you mean? I don't seem to expirience this.
![2021-06-05_17-43](https://user-images.githubusercontent.com/39229923/120899101-eb60a080-c625-11eb-8f58-b00604381942.png)

**Comment by Beatdown032** [comment]
![image](https://user-images.githubusercontent.com/85406541/120899281-f6c0c580-c63f-11eb-8183-e47bce8e92bb.png)
 Look at mine..

**Comment by netbospl** [comment]
Right, you need someone who is more familiar with CP code.
I can provoke tsame page by logging out, and going onto CSF page tho. https://IP/configservercsf
It's exactly the same as on the screenshot provided, not on PowerDNS page tho.

**Comment by Beatdown032** [comment]
sorry, would you mind if you can explain further?

**Comment by netbospl** [comment]
I can see the same message if I'm not logged in into CP, by trying to access https://x.x.x.x:8090/configservercsf which is understandable to cause error of some sort.
Only thing in common is that error 500 page, I don't knowy which part of the CP could potentially cause that apart from this example of mine :(
Hopefully when main developer have a look here, will have answer for You, I don't have an answer for time being unfortunatly.

**Comment by Beatdown032** [comment]
![image](https://user-images.githubusercontent.com/85406541/120912015-d4a96080-c69c-11eb-869f-90798d725b18.png)
Thanks

**Comment by usmannasir** [comment]
@Beatdown032 csf pages only works if you have csf installed.

**Comment by usmannasir** [comment]
Resolved https://github.com/usmannasir/cyberpanel/commit/70af19378d6a24f72a11b5c0bacb2bcb0c9e83e4
