### ISSUE TITLE
HTTP to HTTPS redirect not working

### ISSUE THREAD

**Issue by rakshitbharat** [litespeedtech/cyberpanel#64]
I have tried below links:

https://forums.cyberpanel.net/discussion/263/redirect-http-80-to-https-443

and every online help i can get.

**Comment by usmannasir** [comment]
RewriteCond %{HTTPS} !=on
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

https://cyberpanel.net/docs/6-rewrite-rules/

**Comment by rakshitbharat** [comment]
still its not working for me.
i think this issue should be re-opened

**Comment by usmannasir** [comment]
This is not a code related bug. You can contact support or open a forum thread.
