### ISSUE TITLE
external resources

### ISSUE THREAD

**Issue by krakazyabra** [litespeedtech/cyberpanel#640]
Hi! Today fastly.com CDN became down, and a lot of site were not accessible, including angularjs.org. In this case I couldn't login inside the panel.  
![image](https://user-images.githubusercontent.com/26598203/121171224-83dd6780-c856-11eb-8f94-bef9668a13fe.png)

![image](https://user-images.githubusercontent.com/26598203/121171301-9eafdc00-c856-11eb-805d-9fc6aa81c615.png)

Is it possible to store common libs on panel's host to avoid such problems?

**Comment by usmannasir** [comment]
It is fine now, even the github was down.

**Comment by krakazyabra** [comment]
A lot of resources were down. You, as contributor of cyberpanel, cannot give guarantees, that similar situation will not happen again, that's why I'm asking: is it possible to include all external libs and packages into cyberpanel, not to depend on CDN.
