### ISSUE TITLE
Self-hosted cyberpanel HA

### ISSUE THREAD

**Issue by krakazyabra** [litespeedtech/cyberpanel#643]
Hello. 
I'm searching the way, how can I scale self-hosted servers with cyberpanel, without Cloud. Is there clustering function? Is it possible to run multiple servers with cyberpanel "under" one domain? Something similar as Cyberpanel Cloud, but also self-hosted. 
May be is it possible to run cyberpanel in docker or kubernetes?

Thanks in advance!

**Comment by usmannasir** [comment]
No it's not possible.

Also not recommended to run CyberPanel inside docker.
