### ISSUE TITLE
How to disable or add https for cyberpanel dashboard

### ISSUE THREAD

**Issue by tbhaxor** [litespeedtech/cyberpanel#644]
I want to host the website on a subdomain pane.example.com

It is asking for HTTPS redirect and I am unable to add SSL for the cyberpanel dashboard. Can I remove it or how to add SSL 

PS: I am asking for cyberpanel dashboard, not any other website

**Comment by qtwrk** [comment]
https://cyberpanel.net/blog/2018/12/25/how-to-remove-port-8090-from-cyberpanel/

have you checked this ?

**Comment by tbhaxor** [comment]
> https://cyberpanel.net/blog/2018/12/25/how-to-remove-port-8090-from-cyberpanel/
> 
> have you checked this ?

Yes, I just tried and followed the steps in the blog. I am getting 500 Error

```
"IP - - [13/Jun/2021:09:04:16 +0000] "GET / HTTP/1.1" 500 430 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36""
"IP - - [13/Jun/2021:09:04:16 +0000] "GET /favicon.ico HTTP/1.1" 500 430 "https://devpanel.localhost.tech/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36""

```

**Comment by qtwrk** [comment]
500 error usually means the backend connection failed ,  please share the conf and htaccess rule

**Comment by tbhaxor** [comment]
Htaccess

```
REWRITERULE ^(.*)$ HTTP://cyberpanel/$1 [P]
```

The config I added in `/usr/local/lsws/conf/httpd_config.conf`
```
extprocessor cyberpanel {
  type                    proxy
  address                 https://devpanel.localhost.tech:8090
  maxConns                100
  pcKeepAliveTimeout      60
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}
```

PS: Domain name changed to avoid its misuse

**Comment by qtwrk** [comment]
try use `https://127.0.0.1:8090`

**Comment by tbhaxor** [comment]
With localhost, it worked.
