### ISSUE TITLE
zope.interface==4.5.0 ERROR on Ubuntu

### ISSUE THREAD

**Issue by daxthenuke** [litespeedtech/cyberpanel#654]
zope.interface==4.5.0 pactet give error for ubuntu 20.04 and 18.04. OLS  instalations 
i have try on 2 hosting providers , and it give same error.
Please update packet to  new version  that it is  suported like  zope.interface ==5.3.0  or  5.4.0
Thanks .

**Comment by usmannasir** [comment]
Fixed.
