### ISSUE TITLE
Upgrading imunifyav keeps old folders

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#655]
Hello everyone.

As seen below, the old install version's folder persists after upgrading the application.
Does anyone have a suggestion on how to not make it do that?

![image](https://user-images.githubusercontent.com/4199669/122654470-fd752f80-d14b-11eb-9b8f-31c63283667a.png)

**Comment by usmannasir** [comment]
How did you upgrade it? It must be created by imunify upgrade script not CP.

**Comment by master3395** [comment]
Seems to have been imunifyav internal upgrader.
It made a new folder, and moved all the files, so the .old folder is empty.

But it got a new issue.
It shows permission denied when I enter imunifyav.

sh: /usr/local/CyberCP/public/imunifyav/classes/panels/../../bin/execute.py: Permission denied

There is no /../../bin folder.

![image](https://user-images.githubusercontent.com/4199669/122679749-585e6380-d1ec-11eb-93d4-ed8ce89851df.png)

**Comment by usmannasir** [comment]
How did you upgrade it?

Please share exact commands.

**Comment by master3395** [comment]
> 
> 
> How did you upgrade it?
> 
> Please share exact commands.

I do not know how it upgraded.
All I did was log into ImunifyAv, and it said it had upgraded.

Version: 5.7.4-4

**Comment by usmannasir** [comment]
Use this for upgrade again -> https://docs.imunifyav.com/imunifyav/#update-instructions
This should resolve the is issue, if not then ImunifyAV guys must have changed something.
