### ISSUE TITLE
FTP account path bug

### ISSUE THREAD

**Issue by joer80** [litespeedtech/cyberpanel#656]
When you create an ftp account for something like a subdomain that exists outside the primary public_html folder, you can not set the path.  

ie. If subdomain.domain.com and public_html are next to each other, you can not create an ftp account using this path: /subdomain.domain.com/anything/.

The work around is to create the ftp account with no path and add /subdomain.domain.com/anything/ to the path of your program.  You will start out in the users home directory until you type anything in the path box.  

If you type anything in the path box, you start out in public_html instead of home.

**Comment by usmannasir** [comment]
fixed.
