### ISSUE TITLE
TLS feedback & ECDSA certificates

### ISSUE THREAD

**Issue by publicarray** [litespeedtech/cyberpanel#660]
Please start to allow the generation of ECDSA certificates 🚀 (Needed to get an A+ in [ssllabs server test](https://www.ssllabs.com/ssltest/index.html), and it recommended [for the future](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility).

https://github.com/usmannasir/cyberpanel/blob/8cad5200f3f390d0aa5b302872646aead72750b1/plogical/sslUtilities.py#L299-L301

`--ecc -k [ one of ec-256, ec-384, ec-521]`
https://github.com/acmesh-official/acme.sh/wiki/Options-and-Params

And I recommend to leave 

https://github.com/usmannasir/cyberpanel/blob/a23718680094dacc956ccd389c27116bf5bdf781/plogical/sslUtilities.py#L164

As defaults (empty), so that admins can set secure defaults for all virtual hosts at once (via the listener) rather of having to edit each one.

Regarding ZeroSSL the potential benefit of using them is that there is no rate limit.
https://github.com/acmesh-official/acme.sh/wiki/Change-default-CA-to-ZeroSSL

**Comment by istiak101** [comment]
Also RSA should be avoided according to ROBOT (https://robotattack.org/).

**Comment by usmannasir** [comment]
Resolved
