### ISSUE TITLE
phpmyadmin not installed in fresh install

### ISSUE THREAD

**Issue by xdnroot** [litespeedtech/cyberpanel#665]
I installed cyberpannel using this way.
```
sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh)
```

but when I access phpmadmin via MAIN > DATABASES > phpMyAdmin, there is 404 not found.

I found solution to add phpmyadmin files manually in /usr/local/CyberCP/public. However, the autologin doesn't work and also phpmyadmin import function error.

How to install phpmyadmin in correct way. 
Thanks.

**Comment by usmannasir** [comment]
OS?

**Comment by xdnroot** [comment]
> OS?

I am using CentOS 7.

**Comment by istiak101** [comment]
Using upgrade script as a way to install CyberPanel is not recommended. Try installer instead.

https://cyberpanel.net/docs/installing-cyberpanel/

Also it would be more helpful if you had provided enough logs from terminal to investigate your issue better.

I am labeling this as #needmoreinfo right now. If I don't receive any I will close it after few days.

**Comment by istiak101** [comment]
Take a look at phpMyAdmin install function.

https://github.com/usmannasir/cyberpanel/blob/stable/install/install.py#L681-L762

**Comment by oguz6578** [comment]
wget -O /usr/local/CyberCP/public/phpmyadmin.zip https://%s/misc/phpmyadmin.zip

404 not found phpmyadmin.zip

--2021-10-02 12:43:13--  https://cdn.cyberpanel.sh/misc/phpmyadmin.zip
Resolving cdn.cyberpanel.sh (cdn.cyberpanel.sh)... 185.40.106.117
Connecting to cdn.cyberpanel.sh (cdn.cyberpanel.sh)|185.40.106.117|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-10-02 12:43:14 ERROR 404: Not Found.

Archive:  /usr/local/CyberCP/public/phpmyadmin.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /usr/local/CyberCP/public/phpmyadmin.zip or
        /usr/local/CyberCP/public/phpmyadmin.zip.zip, and cannot find /usr/local/CyberCP/public/phpmyadmin.zip.ZIP, period.
mv: cannot stat '/usr/local/CyberCP/public/phpMyAdmin-*-all-languages': No such file or directory



[10.02.2021_12-43-14] #########################################################################

[10.02.2021_12-43-14] [Errno 2] No such file or directory: '/usr/local/CyberCP/public/phpmyadmin/config.sample.inc.php' [download_install_phpmyadmin]

[10.02.2021_12-43-14] #########################################################################

@usmannasir

**Comment by oguz6578** [comment]
> wget -O /usr/local/CyberCP/public/phpmyadmin.zip https://%s/misc/phpmyadmin.zip
> 
> 404 not found phpmyadmin.zip
> 
> --2021-10-02 12:43:13-- https://cdn.cyberpanel.sh/misc/phpmyadmin.zip Resolving cdn.cyberpanel.sh (cdn.cyberpanel.sh)... 185.40.106.117 Connecting to cdn.cyberpanel.sh (cdn.cyberpanel.sh)|185.40.106.117|:443... connected. HTTP request sent, awaiting response... 404 Not Found 2021-10-02 12:43:14 ERROR 404: Not Found.
> 
> Archive: /usr/local/CyberCP/public/phpmyadmin.zip End-of-central-directory signature not found. Either this file is not a zipfile, or it constitutes one disk of a multi-part archive. In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive. unzip: cannot find zipfile directory in one of /usr/local/CyberCP/public/phpmyadmin.zip or /usr/local/CyberCP/public/phpmyadmin.zip.zip, and cannot find /usr/local/CyberCP/public/phpmyadmin.zip.ZIP, period. mv: cannot stat '/usr/local/CyberCP/public/phpMyAdmin-*-all-languages': No such file or directory
> 
> [10.02.2021_12-43-14] #########################################################################
> 
> [10.02.2021_12-43-14] [Errno 2] No such file or directory: '/usr/local/CyberCP/public/phpmyadmin/config.sample.inc.php' [download_install_phpmyadmin]
> 
> [10.02.2021_12-43-14] #########################################################################
> 
> @usmannasir

resolved
