### ISSUE TITLE
APPLICATION INSTALLER git not working

### ISSUE THREAD

**Issue by rakshitbharat** [litespeedtech/cyberpanel#67]
APPLICATION INSTALLER git not working with gitlab it always shows 400

i have tested with github and it takes clone successfully.

Please also check the clone code which you gets from repo, i think was not showing in folder and clone was actually successful.

One more think is website should automatically detect if it is git repo because once i faced issue to get clone i used root ssh and setup the website.

There should also be some options like repository update(git pull), repo information, updates available and auto git pull etc if we put git option in APPLICATION INSTALLER then this is important and i think its is really easy to make.

**Comment by usmannasir** [comment]
Just tested with GitLab after this commit. Make sure to add account wide dev keys provided by CyberPanel.

https://github.com/usmannasir/cyberpanel/commit/b3dbd36dc90ebef6608152585db6f9fc0b9c5d89
