### ISSUE TITLE
Wrong permission at /var/lib/php/session

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#676]
Today I updated the openlitespeed (1.6.21 to 1.7.11) and cyberpanel (last stable).

The server is using CentOS 7.9.2009.

After that, the sites started to get this problem:
```bash
[STDERR] PHP Warning:  Unknown: open(/var/lib/php/session/sess_sua7sadv9iqffmnq9ce2ouoq64, O_RDWR) failed: Permission denied (13) in Unknown on line 0
Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php/session) in Unknown on line 0
```

I tried to fix doing:
```bash
chmod -R 1773 /var/lib/php/session/
chmod -R 1773 /var/lib/lsphp/session/
```

And did not work.

**Comment by franciscopaniskaseker** [comment]
PS: the permissions after the upgrade was 1777.

**Comment by qtwrk** [comment]
please try 

`bash <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/CPScripts/setup_php_sessions.sh)`
