### ISSUE TITLE
Deleting Backup not deleting the backups

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#679]
Hello.

When i tried deleting the backup files from CP, it didn't delete the files at all.
They remained under "/home/backups"

![image](https://user-images.githubusercontent.com/4199669/124194165-5a67d280-dac8-11eb-8421-8685af659c50.png)

**Comment by usmannasir** [comment]
you mean /home/domain.com/backups?

**Comment by master3395** [comment]
> 
> 
> you mean /home/domain.com/backups?

Well, they get posted under /home/backups and /home/domain.com/backups/

They don't get deleted from either of the folders, if I click "delete"

**Comment by usmannasir** [comment]
They will not be posted under /home/backup only /home/domain.com/backup and just deleted a backup without an issue.
