### ISSUE TITLE
DOMAIN ALIASES static path and so  that showig wrong path

### ISSUE THREAD

**Issue by rakshitbharat** [litespeedtech/cyberpanel#68]
DOMAIN ALIASES page shows static path in File System Path and so that showing wrong path

File System Path
/public_html (dont know why looks like hard coded)

even we change from vhost of its website then also it shows /public_html/ but it works fine there is no issue in its functionality.

**Comment by usmannasir** [comment]
Do you mean that things work as expected, but it shows the wrong path?

**Comment by rakshitbharat** [comment]
![domain aliases cyberpanel](https://user-images.githubusercontent.com/17176729/50837903-c5fed800-1382-11e9-8ddf-d8b30ea3863a.png)

Yes you got it what i am mean to say.

**Comment by usmannasir** [comment]
Does not look wrong to me, any pointers?

**Comment by rakshitbharat** [comment]
just try to make website other than /public_html/

and add domain alians

**Comment by usmannasir** [comment]
Sorry?

**Comment by jlawrence-yellostudio** [comment]
@usmannasir 
I think he was trying to say that even if the file system path is set differently in the vhost configuration that this page still adds 'public_html' to the end of the path. I have noticed this happening too.

**Comment by Markovnin** [comment]
Did you figure out how to fix it @jlawrence-yellostudio @rakshitbharat ?

**Comment by packetdog** [comment]
So, a Domain **Alias** is a different top level domain that points to the same website files/folder structure. If you are using a different domain to point to another set of files/folders unrelated to the first, then you want to create a new **website.** If you're adding a subdomain like sub.tld.com to point at the same files/folder structure, or beneath that of a website, then you can do that today, (e.g. /home/tld.com/public_html/sub_files) with the add subdomain section. We do that with some of our sites.

I suspect you could point to a subfolder under public_html/ (i.e. public_html/foo) that would load directly from https://$ALIASDOMAIN/ but also be accessible via https://$PRIMARYDOMAIN/foo/

So it sounds like you're using the domain alias function to add a new website? If you're adding sites and then manually adjusting the vHost config, I wouldn't expect CyberPanel to know about that. It seems like it would store some of that information in the CyberPanel database, and unless you update it there you can't expect the info to populate in the CyberPanel user interface.

**Comment by Markovnin** [comment]
Yes, that's true. I ended up editing vhost file for the alias domain manually.
