### ISSUE TITLE
[request]dark theme

### ISSUE THREAD

**Issue by rafalohaki** [litespeedtech/cyberpanel#680]
Dark theme is needed.
Its too bright
![image](https://user-images.githubusercontent.com/20607107/124220119-a7b26700-dafd-11eb-9062-860fca1a61a7.png)

**Comment by usmannasir** [comment]
Please use git for issues only.

**Comment by rafalohaki** [comment]
how?

**Comment by istiak101** [comment]
Use https://feedback.cyberpanel.net/

**Comment by Brugman** [comment]
Couldn't agree more @rafalohaki 

With the new custom CSS option we can do it ourselves until an official, more efficient, theming feature is added.

Check out my [Dark Theme Plus](https://github.com/Brugman/cyberpanel-dark-theme-plus).

**Comment by rafalohaki** [comment]
@Brugman thanks
