### ISSUE TITLE
Default DNS

### ISSUE THREAD

**Issue by PRQAE** [litespeedtech/cyberpanel#686]
Hello, I need help with default DNS settings, I want to create custom DNS records and if I create a new website, it will be added by default to the DNS record.

I know it's the wrong place for help, but I hope you can help me.

**Comment by netbospl** [comment]
Right...
[URL1](https://cyberpanel.net/docs/category/cyberpanel/dns/)
[URL2](https://wiki.archlinux.org/title/Domain_name_resolution)
That should help.

**Comment by istiak101** [comment]
@PRQAE I think your issue might got solved at this moment. I also request you not to open any issues for general questions like this one.

Take a look at CyberPanel docs whenever you need any help with general questions. If you are still confused about what to do with your issue get back to the community on Facebook, Discord and CyberPanel forum.

CP docs: https://cyberpanel.net/docs/
Facebook: https://www.facebook.com/groups/cyberpanel
Discord: https://discord.gg/g8k8Db3
CP forum: https://forums.cyberpanel.net/

Requesting @usmannasir to close this.
