### ISSUE TITLE
ssl renew notification email error Relay access denied

### ISSUE THREAD

**Issue by larrypaul93** [litespeedtech/cyberpanel#687]
if domain admin email set to external email. its not sending email getting error Relay access denied.
issue is from address of email is set to domain admin email. should sent from main server email address
in **sslUtilities.py** 
![image](https://user-images.githubusercontent.com/10649897/124970605-90b1ce80-e041-11eb-9ebd-46b0133f972a.png)
sender and receiver both set to domain admin email. it cause issue when domain admin email set to external email address

**Comment by istiak101** [comment]
Fixed in #22abe1 in branch 2.1.2-dev.
