### ISSUE TITLE
Mail closed after upgrade

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#698]
Hello, these ports are "closed" after your upgrade.
You can use the web panel to "reset" the configs to fix this issue.
But wouldn't it be better not to have this issue?

Port 25	Closed, mail will not go through.	
Port 587	Closed, mail will not go through.	
Port 465	Closed, mail will not go through.

**Comment by usmannasir** [comment]
Can not reproduce, also depends on provider to provider and OS. Different packages on different providers, that's why we've email reset from cloud.
