### ISSUE TITLE
Support newer Ubuntu versions

### ISSUE THREAD

**Issue by maicol07** [litespeedtech/cyberpanel#699]
Instead of checking singular versions (`Ubuntu == 20.04 or 18.04 ...`), check if the system has `Ubuntu >= 18.04`

**Comment by qtwrk** [comment]
It won't work , it will error out on 18.10 , 20.10 as LiteSpeed tech doens't have apt repo for  .10 , only for .04

https://rpms.litespeedtech.com/debian/pool/main/

**Comment by maicol07** [comment]
Ah, didn't know that. Guess we'll need to wait LS then :smiley:

**Comment by istiak101** [comment]
They probably won't support it maybe. As webservers need stable environment LTS distros ensure that by not providing too many updates. As one package might rely on another updating dependency package might lead to incompatibility.

**Comment by usmannasir** [comment]
So I will close this now.
