### ISSUE TITLE
Lot of issues while installing

### ISSUE THREAD

**Issue by blaazetech** [litespeedtech/cyberpanel#705]
Hi,

am new to cyberpanel but am trying to setup cyberpanel on oracle cloud instance

first i tried to install latest version of cyberpanel on Arm instance(VM.Standard.A1.Flex) with ubuntu 20.04 but am getting openlitespeed installation error, as it cannot find the package openlitespeed

second time i tried to change the instance type to AMD(VM.Standard.E2.1.Micro) but in this the build fails for acme

please note am trying this in hyderabad/ap/India zone.

let us know what is the best OS and options to use for oracle cloud.

Thanks

**Comment by qtwrk** [comment]
ARM CPU won't work,  many components don't have packages for it 

What's error on second attempt with ACME?

**Comment by blaazetech** [comment]
some build fail errors were seen, i didn't captured it.

**Comment by qtwrk** [comment]
please try capture it then...

**Comment by istiak101** [comment]
ARM architecture isn't supported at this moment. And for AMD architecture I believe that ACME error was not related to CP. That probably was some sort of temporary error from ACME script. Try again and get back to us with logs. I will close this after few days if I don't get response from you.

**Comment by istiak101** [comment]
On fresh instance run these commands

`wget -O acme.sh https://get.acme.sh`
`chmod +x acme.sh`
`./acme.sh`

After installing acme.sh rerun the installation script.
