### ISSUE TITLE
ManagePHP: Install and display all available PHP extensions

### ISSUE THREAD

**Issue by merkys7** [litespeedtech/cyberpanel#717]
We install all PHP 8 extensions but we don't enable them in PHP selector (managePHP), perhaps it's possible to create a loop to display all installed PHP extensions and use description from ManagePHP (if description missing, you can still enable that PHP extension you only wouldn't see PHP extension description,details,etc)

like this case with sodium, lsphp8 sodium extension was already installed but not being displayed in PHP selector
Related: https://github.com/usmannasir/cyberpanel/pull/716

**Comment by usmannasir** [comment]
This has also been fixed in `v2.3.2-dev`
