### ISSUE TITLE
Unable to install to Fresh ubuntu 20.04

### ISSUE THREAD

**Issue by skitzo2000** [litespeedtech/cyberpanel#721]
Provider: Digital Ocean
Server: 1cpu 1gb ram

Note I didn't install powerdns, or ftp, just postfix
yes memchaced
yes redis

I run apt-upgrade before install, but other wise a fresh server:

Install fails somewhere around docker with the following  onscreen:
/usr/local/CyberCP/dockerManager/container.py:122: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if image is None or image is '' or tag is None or tag is '':

I can pull the full install log if needed.

**Comment by skitzo2000** [comment]
After a quick search it appears this is a newer python(3.8) check on data types when using the "is" operand.

I was able to get around the issue by changing the container.py file to use the following on line 122:
if image == None or image is '' or tag == None or tag is '':

**Comment by usmannasir** [comment]
Just installed on 2 DigitalOcean VPS without any problem.
