### ISSUE TITLE
Please fix the installation and upgrade script for ghettoforge repo url.

### ISSUE THREAD

**Issue by MG8853** [litespeedtech/cyberpanel#724]
Please fix the installation and upgrade script for ghettoforge repo url.
I'm sorry I'm not good at English. I am Japanese. 

My Server : Linode
OS : CentOS8

dnf --nogpg install -y https://mirror.ghettoforge.org/distributions/gf/el/8/gf/x86_64/gf-release-8-11.gf.el8.noarch.rpm
↓
dnf --nogpg install -y https://mirror.ghettoforge.org/distributions/gf/gf-release-latest.gf.el8.noarch.rpm

http://ghettoforge.org/index.php/Usage

**Comment by MG8853** [comment]
Branch version is v2.1.1

**Comment by usmannasir** [comment]
Please shift to use Ubuntu 20.04.

**Comment by qtwrk** [comment]
https://github.com/usmannasir/cyberpanel/commit/8f462739f4c79acb1723d91f151d4bcf8c48e6f0#diff-d16ca31ade292114a0dd1bfd6b63dcd91434fae0f1c9637e2acd881f031d01db

https://github.com/usmannasir/cyberpanel/commit/0f1a808f36c377b2fa2ab69e8c7e7dd8a48727d2

updated
