### ISSUE TITLE
2.1.2-dev Sieve issue

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#727]
When you restart dovecot and postfix, you get this error:

OS: Centos 7

** (pkttyagent:393736): WARNING **: 01:48:05.359: Unable to register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Cannot determine user of subject
Error registering authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Cannot determine user of subject (polkit-error-quark, 0)

Every received mail, get's hold up in the queue, and never reaches the inbox.
If I do not enable the sieve, and use the debugger on cyberpanel cloud, I can get e-mail again.
But I use folders and sieve.

**Comment by usmannasir** [comment]
Do you see this issue only after configuring sieve?

**Comment by master3395** [comment]
> 
> 
> Do you see this issue only after configuring sieve?

Yes, it only comes if I configure sieve.

**Comment by master3395** [comment]
I got the same sieve issue on V2.1.1 and V2.1.2.
Not sure what the issue is.
But it's related to Dovecot.
Postfix is fine.

I have both Mailscanner and SpamAssassin enabed.
Postfix is fine at all times.

**Comment by master3395** [comment]
f i don't enable Sieve, i can get e-mails, but then i can't filter them to folders. (And when i have small errors, my inbox get's spammed because it's not filteered).

I have been searching around, but can't find a good solution.

I have also searched around, and found a few articles below.

But it still does not work.

https://cyberpanel.net/blog/2019/04/18/filtering-spam-in-rainloop-autoreply-and-email-filters-with-sieve/


https://forums.cyberpanel.net/discussion/2043/emails-are-not-delivered-to-inbox#latest

And this.

https://forums.cyberpanel.net/discussion/3852/help-me-email-not-receiveing-after-setting-up-filtering-spam-in-rainloop#latest

**Comment by master3395** [comment]
I ran into these two issues when re-upgrading again today to 2.1.2-dev.
Not sure if these are related to my issue.

![1](https://user-images.githubusercontent.com/4199669/134435173-16f7f191-94d9-47d0-8a57-d05cc5f70500.PNG)

![2](https://user-images.githubusercontent.com/4199669/134435183-e7c53865-0976-43ef-a4a8-bd9ac3c259fc.PNG)

**Comment by master3395** [comment]
This issue breaks mail on 2.1.2-dev when trying to add Sieve code to the dovecot file.

**Comment by master3395** [comment]
This error happens still, but using this post by whattheserver fixed Sieve for me at least.

https://forums.cyberpanel.net/discussion/3852/help-me-email-not-receiveing-after-setting-up-filtering-spam-in-rainloop

**Comment by master3395** [comment]
Will most likely be fixed in SnappyMail.
