### ISSUE TITLE
Issue in adding the port 1883 & 8883 using cyberpanel & shell

### ISSUE THREAD

**Issue by KewalT** [litespeedtech/cyberpanel#729]
Hello There, we are facing issue to add / allow port for mqtt. We tried to follow the guide as per doc. https://cyberpanel.net/docs/1-firewall/ but we are not getting option to add firewall rule. We also tried Temporarily allow option under firewall in cyberpanel though it says allowed but not reflecting under 'view listening ports' & can access.

(A) changed ui and out of date docs
(B) no knowing how to reload after adding a rule

Stack/System info.: We are having Cyberpanel 2.1.1 installed on Ubuntu 20.04 on oracle cloud.

Request your assistance on a workaround to allow the port.

**Comment by qtwrk** [comment]
`we are not getting option to add firewall rule`

what do you see in your screen ?   please do a screenshot

**Comment by KewalT** [comment]
![Capture1](https://user-images.githubusercontent.com/52283926/133915419-2b151aa2-7dec-4313-8058-56ca05615cbd.PNG)
![Capture2](https://user-images.githubusercontent.com/52283926/133915420-09c59cb6-aa0c-47ef-9d9a-16e62b06d7a7.PNG)
Thanks for your quick response. I have attached the screenshots for your quick reference & assistance on workaround.

**Comment by KewalT** [comment]
As mentioned earlier : We also tried Temporarily allow option under firewall in cyberpanel though it says allowed but not reflecting under 'view listening ports' & cant access these ports.

**Comment by qtwrk** [comment]
you are using CSF, it's bit of different ,  go edit `/etc/csf/csf.conf` ,  looking for lines  `TCP_IN` ,  `TCP_OUT` , `UDP_IN`, `UDP_OUT` , `TCP6_IN` , `TCP6_OUT` , `UDP6_IN` and `UDP6_OUT`  ,  add your port there accordingly , then `csf -r` to reload it

**Comment by KewalT** [comment]
Thank you for your response. Can you please suggest simple process to deactivate csf also kindly suggest suitable firewall to have best possible protection.

**Comment by istiak101** [comment]
CyberPanel makes managing your web server easier. But you're still expected manage linux servers on your own. Do not ask/open any issue asking for support. Github is only for bug reports. Asking for any support in github issue is not allowed and any such issues will be closed.

Use CyberPanel Facebook group or forum.
https://www.facebook.com/groups/cyberpanel/
https://forums.cyberpanel.net/
