### ISSUE TITLE
Cannot login on wp on SSL

### ISSUE THREAD

**Issue by navotera** [litespeedtech/cyberpanel#73]
I cannot login to WP on SSL if I activated the Mod_security. No error on web page shown, just infinite loading on the browser tab bar. 

On Mod Security disabled, it works flawlessly.

**Comment by usmannasir** [comment]
Which OLS version it is?

**Comment by navotera** [comment]
1.8

if you want to check i can provide you with my vps or wp password, just tell me where i can send them.

**Comment by navotera** [comment]
updated to 1.8.1 but still not work

**Comment by usmannasir** [comment]
It was a CyberPanel upgrade. OpenLiteSpeed is still the old version. Please open your issue at https://github.com/litespeedtech/openlitespeed

**Comment by navotera** [comment]
did you mean this is OLS error / bug ?

**Comment by usmannasir** [comment]
Yup.
