### ISSUE TITLE
(1054, "Unknown column 'user.Password' in 'field list'") [207][5009]

### ISSUE THREAD

**Issue by leobaccili** [litespeedtech/cyberpanel#730]
Hi,
When i trying to create a backup for my website, cyberpanel return this error:
`[09.20.2021_13-48-31] hDtOFkkBMs5+9tXVvLyK1XZROzu8tA7Psudo chown cyberpanel:cyberpanel /home/avesui.bacctecnologia.com.br/backup/status
[09.20.2021_13-48-31] Creating meta for avesui.bacctecnologia.com.br.
[09.20.2021_13-48-31] (1054, "Unknown column 'user.Password' in 'field list'") [207][5009]`

**Comment by usmannasir** [comment]
Please provide these details -> https://forums.cyberpanel.net/discussion/953/bug-report-template

**Comment by leobaccili** [comment]
Provider:  KingHost

Virtualization Type: xen.

System: Ubuntu 20.04

Installation option:   since during the installation.
there will be few option to choose,so please provide it as well.

OLS or Enterprise?
OLS

Installing from official server or mirror server?
official

Install Memcached extension for PHP?
no

Install LiteSpeed Memcached?
yes

Install Memcached?
no

Install Redis extension for PHP?
yes

Install Redis?
yes


Problem:

When i trying to create a backup for my website, cyberpanel return this error:

[09.20.2021_13-48-31] hDtOFkkBMs5+9tXVvLyK1XZROzu8tA7Psudo chown cyberpanel:cyberpanel /home/avesui.bacctecnologia.com.br/backup/status [09.20.2021_13-48-31] Creating meta for avesui.bacctecnologia.com.br. [09.20.2021_13-48-31] (1054, "Unknown column 'user.Password' in 'field list'") [207][5009]

I tried to reinstall many time but the problem persists

**Comment by leobaccili** [comment]
The database is installed on another VPS at version 8.0.26

**Comment by leobaccili** [comment]
This happens when i trying to change access from db user too

**Comment by leobaccili** [comment]
I found the problem. I'm using MySQL 8.0 and the users table dont have the password column, the correct column is authentication_string. I made a change to cover my case but i will improve te code and put db version verification
