### ISSUE TITLE
Remote backup fail / cat: /home/backup/transfer-5405/backup_log: No such file or directory

### ISSUE THREAD

**Issue by thuanduongpa** [litespeedtech/cyberpanel#732]
Hi,
Curently i testing feature remote backup from cyberpanel to cyberpanel but when i fetch account, still get the account from old server, but when transfer, error show

cat: /home/backup/transfer-5405/backup_log: No such file or directory

What can i do on this issue?

Rgs,

**Comment by usmannasir** [comment]
After waiting few seconds, it should continue to work.
