### ISSUE TITLE
Letsencrypt Self Sign and Other Related Problems are related to PowerDNS.

### ISSUE THREAD

**Issue by ksaltik** [litespeedtech/cyberpanel#733]
ksaltik
12:15PM in Bug Report Flag
Letsencrypt Self Sign and Other Related Problems are related to PowerDNS.

I updated my cyberpanel from 1.x to 2.x. I am not sure if the ssl issue problem exist before.

I have a domain which uses cloudflare dns and i can able to issue ssl sertificates without any problem. But I have domains which uses powerdns on cyberpanel I cannot issue any ssl just self-signed ones.

SSL problems related to powerdns not acme.sh script or any other things.

**Comment by usmannasir** [comment]
Can not reproduce this issue on my end.
