### ISSUE TITLE
Email Forwarding and Addon Domain

### ISSUE THREAD

**Issue by vpsinghbaghel** [litespeedtech/cyberpanel#734]
CyberPanel Version: Latest Stable.
OS: Ubuntu20. Seen same issue on CentOS too.

I am including 2 issues in same ticket. Both are related to Mails.

Issue1: We can create Email account inside an addon domain but we can't delete it. Also we can't configure Email Forwarding for email id which is under an addon domain. For addon domain I had to manually add forwarding entry in directly on database and then it worked.

Issue2: For any normal domain, if Email Forwarding is enabled, 1 email is delivered 2 times to receiver.  For a temporary fix I had to delete 1 forwarding entry(which is going to itself) from cyberpanel database and keeping the 2nd entry for the forwarded mail. So email is only delivered to forwarded mail id not to local mailbox. This way mail is forwarded only 1 time which fixes it temprarily.

**Comment by usmannasir** [comment]
This was an issue with earlier versions, I've resolved it couple of months ago. Just tested and can't reproduce. (for issue one create a seprate issue.)

```Sep 25 10:25:39 cpverifymain postfix/qmgr[204702]: 44CC1BE8E1: from=<usman@cyberpanel.net>, size=2734, nrcpt=2 (queue active)
Sep 25 10:25:39 cpverifymain postfix/pipe[205565]: 44CC1BE8E1: to=<usman@wpmautic.net>, relay=dovecot, delay=0.78, delays=0.72/0.03/0/0.03, dsn=2.0.0, status=sent (delivered via dovecot service)
Sep 25 10:25:39 cpverifymain postfix/smtpd[205476]: disconnect from sender4-of-o53.zoho.com[136.143.188.53] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Sep 25 10:25:40 cpverifymain postfix/smtp[205566]: 44CC1BE8E1: to=<my personal mail>, orig_to=<usman@wpmautic.net>, relay=gmail-smtp-in.l.google.com[2a00:1450:400c:c0c::1b]:25, delay=1.1, delays=0.72/0.03/0.17/0.21, dsn=2.0.0, status=sent (250 2.0.0 OK  1632558340 s21si15579540wmh.113 - gsmtp)
Sep 25 10:25:40 cpverifymain postfix/qmgr[204702]: 44CC1BE8E1: removed

**Comment by vpsinghbaghel** [comment]
> 0470

Ok. I am creating a separate issue for issue 1.
