### ISSUE TITLE
Create Mail Domain inside of main domain

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#735]
Hello.

I think the mail.domain.com should be located outside of the main domain.
Like at the location shown below.
![image](https://user-images.githubusercontent.com/4199669/135139040-40c540b3-ad36-4a80-b01e-73d8c16951c9.png)

**Comment by istiak101** [comment]
#610 fixed this.

**Comment by master3395** [comment]
That didn't fix the issue.
I installed a clean install of 2.1.2-dev today on that server.
I know it was mentioned before but wasn't sure where.

![image](https://user-images.githubusercontent.com/4199669/135141924-71498f9a-de34-48f0-98e1-726b79feacf1.png)

**Comment by istiak101** [comment]
This is for newer domain creations, older domains will remain same.

**Comment by master3395** [comment]
I'm not sure if this code was implemented into 2.1.2, it was merged into 2.1.1-dev
Also, this is a 100% newly created domain in CP today using 2.1.2

**Comment by master3395** [comment]
It wasn't merged into 2.1.2-dev
https://github.com/usmannasir/cyberpanel/blob/v2.1.2-dev/plogical/virtualHostUtilities.py

![image](https://user-images.githubusercontent.com/4199669/135142759-d846efd0-7d01-4903-8174-369fdea25260.png)

**Comment by istiak101** [comment]
That was actually merged in 2.1.1-dev. Looks like someone messed up while merging branches.

**Comment by istiak101** [comment]
Current code was in 2.1.1-usman branch which probably did a overwrite on that commit. Fixed.

**Comment by master3395** [comment]
That merge does not work on let's encrypt it seems.

Error message: Self signed certificate was issued. [issueSSLForDomain] [404]
I normally use CloudFlare for my websites, so perhaps I can create a website when re-enabling Cloudflare?

![image](https://user-images.githubusercontent.com/4199669/135153856-2765524e-e512-4022-a072-40b19e4605ce.png)

**Comment by master3395** [comment]
It refuses to make a domain if letsencrypt fails.
![image](https://user-images.githubusercontent.com/4199669/135155275-a24567b9-8ae9-47a6-a68c-71eeee0fcec4.png)

**Comment by master3395** [comment]
If i don't let the creation of the website add SSL, then the creation of the domain works.

**Comment by istiak101** [comment]
Can you confirm if you have the last commit from 2.1.2-dev branch?

https://github.com/usmannasir/cyberpanel/commit/10b15ebd8d117d2f26fda79bb27ab692e627e11c

**Comment by istiak101** [comment]
#610 had an issue. Fixed.

**Comment by master3395** [comment]
Found another, not really an issue, but yeah.

It now says in the log that it makes a self-ss when Cloudflare already has the DNS recorded
![bilde](https://user-images.githubusercontent.com/4199669/135237856-86a1c398-016e-4ed3-96ad-32e9c9a7377c.png)

**Comment by istiak101** [comment]
If you have any proposed solution please make a PR.

**Comment by istiak101** [comment]
I am locking this thread as there is nothing new that can be addressed for this issue. Also the log you are mentioning was already there. No code changes were made to those part of code.
