### ISSUE TITLE
Restore Backup not showing anything

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#736]
If you click Back up Website then the backup comes if it's made by the current CP.
![2](https://user-images.githubusercontent.com/4199669/135249797-b09f0537-4873-4192-814f-f29f48b0e2ee.PNG)

This backup is manually uploaded and permissions are matched a newly made backup to ensure it could be shown, but sadly it can't for some reason

backup-newstargeted.com-09.27.2021_19-18-29.tar.gz
![bilde](https://user-images.githubusercontent.com/4199669/135250145-58592e08-db86-4213-a990-8d5f3e911a6d.png)

It does not matter if you made the backup inside of the current CP or a duplicate re-uploaded, it will not show up under
Restore Website

![bilde](https://user-images.githubusercontent.com/4199669/135249743-bd701e9b-f35d-47c0-b1d8-7afc5f79e7eb.png)

**Comment by istiak101** [comment]
From your Restore Website image I can see "This page can be used to restore your websites, Back up should be generated from CyberPanel Back up generation tool, it will detect all Back ups under /home/backup."

But you don't bother to read anything. Do you? Open your eyes and mind before creating your next issue.

**Comment by master3395** [comment]
The issue is that you can't restore a backup file that you re-upload to the same folder with the same permissions.
If you read closely, it's NOT a file made on a clean install of CyberPanel.

If there is NO way to restore a full backup, it should be explained better than to say "don't you bother to read".
I do read more than you think.

All permissions are set equal to the file generated on a clean install.
So in theory it should be detected as a file that can be restored.

The backup was made on my old install of CyberPanel, and moved into the /home/backup manually, and fixed the permission to be equal to a clan backup I did after I installed CyberPanel, to make sure it was the same permissions.

The ONLY way I managed to get it working on a clean install now, is that I made a backup inside of /home/newstargeted,com/backup then right-click that folder and duplicate it to /home.
So it has the same permission as /home/newstargeted.com.
The /home/backup folder is not created on CyberPanel creation.
So I was confused if it was supposed to have root permission, cyberpanel permission, or user permission for that site.
Turns out it needed the website permission for that folder...

So either the documentation is lacking here https://cyberpanel.net/docs/1-backup-restore/
Or something should be changed to make it work where it's generated rather than making a separate place to restore, where the files aren't originally stored.
Because the backup generator makes it under /home/domain.tld/backups rather than /home/backup
