### ISSUE TITLE
moved mail in 2.1.2-dev issue

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#737]
This happens when i try to issue SSL for the SMTP.

Because the location moved, CP will not issue SSL to the right place in CP

It still thinks the location is inside of the domain.

![bilde](https://user-images.githubusercontent.com/4199669/135604439-d4065894-46d0-4acd-b9c6-21538848ebe3.png)

[Fri Oct 1 10:16:27 UTC 2021] Registering account: https://acme-v02.api.letsencrypt.org/directory [Fri Oct 1 10:16:29 UTC 2021] Already registered [Fri Oct 1 10:16:29 UTC 2021] ACCOUNT_THUMBPRINT='4o4RU3e48Enkj9SVPHb5_gNSO5-1cDkZi57oZ8SBqqI' [Fri Oct 1 10:16:32 UTC 2021] Create new order error. Le_OrderFinalize not found. { "type": "urn:ietf:params:acme:error:rateLimited", "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/", "status": 429 } [Fri Oct 1 10:16:32 UTC 2021] Please check log file for more details: /root/.acme.sh/acme.sh.log [Fri Oct 1 10:16:35 UTC 2021] Create new order error. Le_OrderFinalize not found. { "type": "urn:ietf:params:acme:error:rateLimited", "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/", "status": 429 } [Fri Oct 1 10:16:35 UTC 2021] Please check log file for more details: /root/.acme.sh/acme.sh.log Generating a 2048 bit RSA private key .............+++ ...........+++ writing new private key to '/etc/letsencrypt/live/mail.newstargeted.com/privkey.pem' ----- 0,210 Failed to install SSL for domain. [issueSSLForDomain]

**Comment by master3395** [comment]
![image](https://user-images.githubusercontent.com/4199669/135670463-45a4f9d5-7c1a-4ac0-9783-51aa8252beef.png)

**Comment by istiak101** [comment]
Perhaps you don't read logs at all. You're rate limited.

`{ "type": "urn:ietf:params:acme:error:rateLimited",`

This is a ChildDomains object but a Websites object is being fetched 

https://github.com/usmannasir/cyberpanel/blob/v2.1.2-dev/plogical/sslUtilities.py#L68-L72

`Websites matching query does not exist. [installSSLForDomain]`

And last thing is you have some sort of IO error that prevented vhost.conf creation.
