### ISSUE TITLE
Merge phpconfigs and php-configs directory

### ISSUE THREAD

**Issue by fransvanberckel** [litespeedtech/cyberpanel#74]
Taking a look into the sources for the first time. I found out, in install there are two php configs directories; phpconfigs and php-configs. That got to be a typo? Or otherwise can these merged?

**Comment by usmannasir** [comment]
Earlier they were required, they are not required now.

**Comment by fransvanberckel** [comment]
Is there more code in the repo, that are not required, now anymore?

**Comment by usmannasir** [comment]
At some places, yes.

**Comment by usmannasir** [comment]
We can close if you don't have any further questions.

**Comment by fransvanberckel** [comment]
Yes sure, but you did not remove the superfluous code?
