### ISSUE TITLE
phpmyadmin not installed in fresh install v2.1

### ISSUE THREAD

**Issue by oguz6578** [litespeedtech/cyberpanel#740]
wget -O /usr/local/CyberCP/public/phpmyadmin.zip https://%s/misc/phpmyadmin.zip

404 not found phpmyadmin.zip

--2021-10-02 12:43:13-- https://cdn.cyberpanel.sh/misc/phpmyadmin.zip
Resolving cdn.cyberpanel.sh (cdn.cyberpanel.sh)... 185.40.106.117
Connecting to cdn.cyberpanel.sh (cdn.cyberpanel.sh)|185.40.106.117|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-10-02 12:43:14 ERROR 404: Not Found.

Archive: /usr/local/CyberCP/public/phpmyadmin.zip
End-of-central-directory signature not found. Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive. In the
latter case the central directory and zipfile comment will be found on
the last disk(s) of this archive.
unzip: cannot find zipfile directory in one of /usr/local/CyberCP/public/phpmyadmin.zip or
/usr/local/CyberCP/public/phpmyadmin.zip.zip, and cannot find /usr/local/CyberCP/public/phpmyadmin.zip.ZIP, period.
mv: cannot stat '/usr/local/CyberCP/public/phpMyAdmin-*-all-languages': No such file or directory

[10.02.2021_12-43-14] #########################################################################

[10.02.2021_12-43-14] [Errno 2] No such file or directory: '/usr/local/CyberCP/public/phpmyadmin/config.sample.inc.php' [download_install_phpmyadmin]

[10.02.2021_12-43-14] #########################################################################

@usmannasir

**Comment by qtwrk** [comment]
fixed , a cert issue on that server needed `yum update ca-certificates`

**Comment by oguz6578** [comment]
your cdn files not sync

185.40.106.117 source not file but another source find file ;)

**Comment by oguz6578** [comment]
> fixed , a cert issue on that server needed `yum update ca-certificates`

not this problem

**Comment by qtwrk** [comment]
```
[root@test1 ~]# wget -O /dev/null https://cdn.cyberpanel.sh/misc/phpmyadmin.zip
--2021-10-02 15:29:29--  https://cdn.cyberpanel.sh/misc/phpmyadmin.zip
Resolving cdn.cyberpanel.sh (cdn.cyberpanel.sh)... 89.187.169.47
Connecting to cdn.cyberpanel.sh (cdn.cyberpanel.sh)|89.187.169.47|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15357438 (15M) [application/zip]
Saving to: ‘/dev/null’

100%[========================================================================================================================>] 15,357,438  4.31MB/s   in 3.9s

2021-10-02 15:29:34 (3.79 MB/s) - ‘/dev/null’ saved [15357438/15357438]
```

**Comment by oguz6578** [comment]
> ```
> [root@test1 ~]# wget -O /dev/null https://cdn.cyberpanel.sh/misc/phpmyadmin.zip
> --2021-10-02 15:29:29--  https://cdn.cyberpanel.sh/misc/phpmyadmin.zip
> Resolving cdn.cyberpanel.sh (cdn.cyberpanel.sh)... 89.187.169.47
> Connecting to cdn.cyberpanel.sh (cdn.cyberpanel.sh)|89.187.169.47|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 15357438 (15M) [application/zip]
> Saving to: ‘/dev/null’
> 
> 100%[========================================================================================================================>] 15,357,438  4.31MB/s   in 3.9s
> 
> 2021-10-02 15:29:34 (3.79 MB/s) - ‘/dev/null’ saved [15357438/15357438]
> ```

--2021-10-02 12:43:13-- https://cdn.cyberpanel.sh/misc/phpmyadmin.zip
Resolving cdn.cyberpanel.sh (cdn.cyberpanel.sh)... 185.40.106.117
Connecting to cdn.cyberpanel.sh (cdn.cyberpanel.sh)|185.40.106.117|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-10-02 12:43:14 ERROR 404: Not Found.

diffrend ip address  @qtwrk  :)

**Comment by oguz6578** [comment]
The problem occurs because your data on the cdn is not up to date.  @qtwrk @usmannasir

**Comment by qtwrk** [comment]
I just purged CDN cache , wait for a moment , it should re-fetch again from origin.
