### ISSUE TITLE
OLS does not show logs anymore from CP V 2.1.1 - 2.1.2

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#741]
Hello.

I have been trying to locate the logs and giving them the permissions to get access, but OLS does not seem to be able to read the logs in any way.
It was working on 2.0.3, but not after, from what I've seen.

Where OLS just does not show the logs, even if there are error logs?
(This is a clean install of 2.1.2 Centos 7)

https://www.facebook.com/groups/cyberpanel/permalink/2891103154534647/

![image](https://user-images.githubusercontent.com/4199669/135732903-199a449e-6ed1-4ee3-95ee-e7561188f00d.png)

**Comment by master3395** [comment]
If i change this permission from root to my lsadm it will show again.
Not sure why it didn't do that before.
But could there be a flaw in permission giving when setting up CyberPanel with OLS where it skips this folder?

![image](https://user-images.githubusercontent.com/4199669/135735908-d813c5f5-a4f0-4ae5-9b57-237ee72ff1db.png)

**Comment by usmannasir** [comment]
Please open this up in OLS repo as there are some permission changes due to security.
