### ISSUE TITLE
Fresh DO server with DO Cyberpanel.

### ISSUE THREAD

**Issue by kalhara07761** [litespeedtech/cyberpanel#742]
Fresh DO server with DO Cyberpanel.
WP with php 8.0
Got this error.
No database created.
wp files in place in file manager.

_Originally posted by @kangarooo in https://github.com/usmannasir/cyberpanel/issues/619#issuecomment-931820527_

**Comment by miloman** [comment]
Having the exact same issue for a couple weeks now. Have to create the database manually and then edit wp-config. Used to work seamlessly. Hope this gets fixed soon

**Comment by ErikSRoth** [comment]
Fresh install on VULTR using the preconfigured Cyberpanel on Ubuntu 20.04 LTS. Same Issue. Wordpress with LSCache does not install from the quick install application installer. Once you enter the basic info (blog name,  user name and pass and dir), the application install begins, but then errors out. It does install the base WP files in the specified dir, but does not create a database. The database creation is the failure point. Once it fails you get the attached message...

![Screen Shot 2021-10-05 at 8 21 37 PM](https://user-images.githubusercontent.com/37046891/136130813-2a8f2751-7cd4-47bf-84c4-22c9bf929f85.png)

If you go back and create a database and then manually go and edit the wp-config.php with you newly created database info, you can then load and install Wordpress. Once installed everything works as it should. One other thing... doing it manually also does not install or configure the LSCache plugin. So now that I have downloaded that I am trying to figure out all the options - 😕

**Comment by usmannasir** [comment]
Use this guide for manual installation to always get the latest code -> https://cyberpanel.net/docs/installing-cyberpanel/

**Comment by kangarooo** [comment]
> Use this guide for manual installation to always get the latest code -> https://cyberpanel.net/docs/installing-cyberpanel/

This is not fixing code in this github.
How your link is different from my link? Its the same- doesnt work. WTF is wrong if you are posting the same instructions and removing my link i found that has more options then your link https://quickfever.com/cyberpanel/
This is not a fix. Probem still exists, so no need to close until its fixed, cause people will still write that it isnt fixed, so you keep it open so people can read about your solution while fix isnt made in this github.
