### ISSUE TITLE
ChangePHP shows error

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#743]
Hello.
When changing the PHP version inside of subdomains on 2.1.1 and 2.1.2 it will show an IO error in the cyberCPMainLogFile.
And the SSL will sometimes not be generated.
I do not see any .lsphp_restart.txt file on this location.

[10.03.2021_01-34-35] [Errno 2] No such file or directory: '/home/mas.newstargeted.com/.lsphp_restart.txt' [IO Error with per host config file [changePHP]

**Comment by istiak101** [comment]
Not reproducible. Find out why you have that odd I/O issue. Try on another VPS/provider or do a new install. Or if you can find any permission related issue that might've prevented file creation let us know. I am closing this now. Do not open any new issues regarding this.
