### ISSUE TITLE
 can't access PHPMyAdmin 

### ISSUE THREAD

**Issue by enezatech** [litespeedtech/cyberpanel#746]
Hi
In my new installation of the Cyber panel, 2.1  build 1on Ubuntu but can't access PHPMyAdmin  with a message 
![image](https://user-images.githubusercontent.com/33986509/136473373-26359b84-1565-4529-8e4e-26d40fb9ccd7.png)

How do I resolve this issue any help will be appreciated.

**Comment by istiak101** [comment]
Try upgrading CyberPanel. It will try to install phpMyAdmin again.

https://cyberpanel.net/docs/upgrading-cyberpanel/

**Comment by enezatech** [comment]
Hi istiak101 
Thank you for this resolved the issue.
