### ISSUE TITLE
cat: .litespeed_password: No such file or directory

### ISSUE THREAD

**Issue by kangarooo** [litespeedtech/cyberpanel#749]
After reboot cant get admin password
root@Litebuntu:~# sudo cat .litespeed_password
cat: .litespeed_password: No such file or directory
root@Litebuntu:~#

**Comment by qtwrk** [comment]
that cat command only works on these market-launched image as of `Option 1.a Create One-click CyberPanel server via DigitalOcean Marketplace` , not on fresh install.

**Comment by kangarooo** [comment]
Ah ok, then only for DO droplet. https://github.com/usmannasir/cyberpanel/issues/738#issuecomment-937791323
