### ISSUE TITLE
[BUG] Internal error 2.1.2

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#751]
I think one of the latest updates has broken the V2.1.2 CyberPanel dashboard.

I now only get an internal error on my test install :)
Not sure if there is an error log I can check to figure out what can cause it.

![Internal-error](https://user-images.githubusercontent.com/4199669/136998091-3a6a78f5-0fb0-4da0-ba11-2eb5fcbbcbe7.png)

**Comment by usmannasir** [comment]
Not sure what you are trying to say?

**Comment by master3395** [comment]
It was fixed in 2.1.2 :)
