### ISSUE TITLE
Attempted to create a website and received an error 

### ISSUE THREAD

**Issue by qadeer819** [litespeedtech/cyberpanel#757]
hi i installed cyberpanel on my server with when i use backup it restore the website but when try makeing new sub domain for my website or try makeing website it says error below if i type my website foodinmarket.com dont let me go ahead make website but any domain it lets it work 
i have checked this file but do not contain my domain inthere
/Downloads/cyberpanel-stable/plogical/acl.py
*

*NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occurred? 
1. Ex.: Click on the "Websites" tab.
2. Ex.: Click on "Create Website" add domain https://foodinmarket.com
3. Ex.: Attempted to create a website and received an error 
Starting creation..
70% Complete
Error message: Blacklisted domain..

**Expected behavior**

**Screenshots**
![Screenshot 2021-10-24 at 14 05 17](https://user-images.githubusercontent.com/58487315/138595539-3cec22fe-21c1-4160-ab7c-8a978213b32a.png)

![Screenshot 2021-10-23 at 21 02 49](https://user-images.githubusercontent.com/58487315/138595317-45ee382e-1f95-435c-993a-e5c3a84bb199.png)

**Operating system:**
rocky linux 
digital ocean

**CyberPanel version:**
Please enter your answer here (e.g. 2.1.2).

**Comment by usmannasir** [comment]
Is this domain the hostname of your server?

**Comment by qadeer819** [comment]
To be ownest I ain’t got clue about these a lot I done everything same before I was doing to set this up server  can you please help me how to find if it host name 
I have been using cyber panel for year only had issues after new droplets

**Comment by usmannasir** [comment]
Please check this -> https://www.facebook.com/groups/cyberpanel/posts/2907810692863893/?__cft__[0]=AZVPmdF4oxR_eEjm0zyrcRNINj4yeUyuJa6GfMy1dxDcov1V5WvDxWcKikILYjgSknwaGDRWvgKkgl-IumRxNMhxHsrrevBgyaZu7QDsINYpHxj9Vi-VrNQWqNLABILlXpvr1UlhANDFrggxqaCY30aF87rK7ZZ1ASqAdrP2yVPyyqTTA7FK2qKH1JgEoaZ-gf4&__tn__=%2CO%2CP-R
