### ISSUE TITLE
Migrate from cPanel to CyberPanel 2.1.2

### ISSUE THREAD

**Issue by tips2fix** [litespeedtech/cyberpanel#758]
Hello , 
This module to restore websites from fullbackup of cPanel to cyberpanel  does not work fully!
i did follow this instructions 
https://cyberpanel.net/docs/auto-import-cpanel-sites-to-cyberpanel
im able to restore backup but it only restore the wordpress folder , it create an new website in ctberpanel control panel
i also see that database in phpmyadmin its created but , not in cyberpanel, and website it shows "Error establishing a database connection."
also emails are not recover at all.

**Comment by usmannasir** [comment]
Kindly show restore logs, cPanel version and what kind of backup file you generated from cPanel? jetbackup files dont work.

**Comment by mauamolat** [comment]
For jetbackup files, when is ETA it can work?

**Comment by usmannasir** [comment]
Jetbackup wont be supported, you need to generate cPanel backup file through backup wizard.
