### ISSUE TITLE
 Disk full (/tmp/#sql_1a2838_1.MAI); waiting for someone to free some space 

### ISSUE THREAD

**Issue by aminweb2** [litespeedtech/cyberpanel#760]
hi,
I get this message every morning,

> Error: Disk full (/tmp/#sql_1a2838_1.MAI); waiting for someone to free some space... (errno: 28 "No space left on device")

and then I have to **restart MariaDB** from the site.com:8090/serverstatus/services

screenshot of df -h command:

```
Filesystem Size Used Avail Use% Mounted on
udev 15G 0 15G 0% /dev
tmpfs 3.0G 692K 3.0G 1% /run
/dev/sda3 194G 21G 164G 11% /
tmpfs 15G 108M 15G 1% /dev/shm
tmpfs 5.0M 0 5.0M 0% /run/lock
tmpfs 15G 0 15G 0% /sys/fs/cgroup
/dev/loop0 1.5G 1.4G 0 100% /tmp
/dev/sda2 2.0G 144M 1.7G 8% /boot
tmpfs 3.0G 0 3.0G 0% /run/user/0
```

OS:Ubuntu 20.4
Panel: Cyberpanel 2.1.1 + Openlitespeed 1.7.14 

my VPS:
8 vCPU Cores
30 GB RAM
200 GB NVMe

**Comment by usmannasir** [comment]
This is not a CyberPanel bug, please check why your disk is getting full.

**Comment by aminweb2** [comment]
@usmannasir but my disk just 17% used 
https://imgur.com/a/U9Zp7qW

**Comment by usmannasir** [comment]
Your /tmp is full

/dev/loop0 1.5G 1.4G 0 100% /tmp

**Comment by aminweb2** [comment]
yes, but why? how solve it? please guide me

**Comment by aminweb2** [comment]
also I was changed  Swapping Directory value in OpenLiteSpeed panel to :
Swapping Directory	/dev/shm

but still have same problem and every morning  /tmp folder is full

**Comment by usmannasir** [comment]
Ask this question on our forums so that you can get the answer -> https://forums.cyberpanel.net/

**Comment by aminweb2** [comment]
@usmannasir  I created: https://forums.cyberpanel.net/discussion/5908/disk-full-tmp-sql-1a2838-1-mai-waiting-for-someone-to-free-some-space/p1?new=1
