### ISSUE TITLE
[BUG] auditmodsec.log does not appear to be rotated

### ISSUE THREAD

**Issue by davelozier** [litespeedtech/cyberpanel#762]
auditmodsec.log does not appear to be rotated.

```
-rw-r----- 1 nobody nogroup  674 Nov  4 05:53 access.log
-rw-r--r-- 1 root   nogroup 134M Sep 20 11:35 auditmodsec.log
-rw-r--r-- 1 nobody nogroup 9.9M Nov  4 05:54 error.log
-rw-r--r-- 1 nobody nogroup  11M Nov  1 14:45 error.log.2021_11_01
-rw-r--r-- 1 root   root     25K Nov  4 04:48 lsrestart.log
-rw-r--r-- 1 root   nogroup    0 Aug 29 14:26 modsec.log
-rw-r--r-- 1 nobody nogroup 770K Nov  3 13:35 stderr.log
-rw-r--r-- 1 nobody nogroup  11M Oct 16 00:54 stderr.log.2021_10_16
```

On Ubuntu, use command `ls -lh  /usr/local/lsws/logs` to view logs.

**Expected behavior**
All logs rotated.

**Operating system:**
Ubuntu 20.04 LTS

**CyberPanel version:**
2.1.1

**Comment by usmannasir** [comment]
Looking into this.

**Comment by usmannasir** [comment]
I am closing this because in OLS there is no directive available to rotate this.

**Comment by davelozier** [comment]
Seems to be a known issue. https://github.com/litespeedtech/openlitespeed/issues/214

I'm going to try and set up some sort of rotation for the modsec logs.

**Comment by usmannasir** [comment]
yes, but nothing I can do about.
