### ISSUE TITLE
[BUG] google drive an additional option

### ISSUE THREAD

**Issue by dfag86** [litespeedtech/cyberpanel#765]
backup on google drive. is there an option to choose whether it will be the main drive or a shared drive? I am asking because I have unlimited space on the shared drive, but the cyberpanel does not save a copy there. is there any chance for an update to be able to choose a shared drive?

**Operating system:**
 Ubuntu 20.04 LTS

**CyberPanel version:**
 2.1.2

**Comment by die2mrw007** [comment]
I dont think its a bug and shouldn't be tagged under bug report. Also I believe the google drive is integrated via google cloud api access in which it will have elevated access only to the account connected and shared folders are actually not a part of your account permission level.
