### ISSUE TITLE
Install Cyberpanel on Ubuntu 21.04 

### ISSUE THREAD

**Issue by mhr5246** [litespeedtech/cyberpanel#767]
can you help me to install Cyberpanel on Ubuntu 21.04 ?

===================================================

sudo sh <(curl https://cyberpanel.net/install.sh || wget -O - https://cyberpanel.net/install.sh)
sh: 0: cannot open /dev/fd/63: No such file
root@mehrana:~#   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--      0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--    100  1305  100  1305    0     0    483      0  0:00:02  0:00:02 --:--:--   483
curl: (23) Failed writing body
--2021-11-13 22:42:09--  https://cyberpanel.net/install.sh
Resolving cyberpanel.net (cyberpanel.net)... 176.31.154.14
Connecting to cyberpanel.net (cyberpanel.net)|176.31.154.14|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1305 (1.3K) [application/x-sh]
Saving to: ‘STDOUT’

-                    0%[                 ]       0  --.-KB/s    in 0s      

Cannot write to ‘-’ (Success).

**Comment by qtwrk** [comment]
it won't install on ubuntu 21.04 , you need to use 20.04 or 18.04

and don't do `sudo sh <(xxx)`

you need to run `sudo su -` , then `sh <(xxx)`

**Comment by mhr5246** [comment]
thank you
but it doesn't install again
is there any OS image that contains Cyberpanel?
or docker image?

**Comment by usmannasir** [comment]
Kindly use our community forums for non-bug related things -> https://community.cyberpanel.net/

Please post complete details there, like your OS, provider, etc so that you can get good help.
