### ISSUE TITLE
Old php version as option

### ISSUE THREAD

**Issue by fransvanberckel** [litespeedtech/cyberpanel#77]
While installing i have got several questions. Options for parts you want to, or don't want to install. But why isn't the php version an option, i don't want to install? What is it you wanna do with php 5, if it's gonna be end of life? Or even a old php 7 (not maintained) version, you don't wanna install. That isn't an option now.

**Comment by hulst88** [comment]
I agree.. removing or installing php versions would be great to have clean install.
