### ISSUE TITLE
Please fix ssl error in cyberpannel admin

### ISSUE THREAD

**Issue by prtechindiaoss** [litespeedtech/cyberpanel#772]
**Describe the bug**
the SSL certificate of cyberpannel has errors the SSL certificates for websites are fine

**To Reproduce**
Opening Cyberpannel :8090

**Expected behavior**
Port :8090 always shows a SSL error even with a domain which has a SSL Certificate

**Operating system:Ubuntu 20.04**

**CyberPanel version:2.1**

**Comment by qtwrk** [comment]
You need to access it as https://domain:8090 once you have set hostname SSL

The IP address URL will always give error as you can't get cert for IP from let's encrypt

**Comment by prtechindiaoss** [comment]
@qtwrk im accessing it from domain

**Comment by bartoszpijet** [comment]
Provide at least screenshots of this error, there is not enough info to suggest anything

**Comment by PREKNOWLEDGEWEB** [comment]
![image](https://user-images.githubusercontent.com/83751707/143878383-ae61ebe9-2097-4c8f-b899-1f5c8ce7744f.png)
![image](https://user-images.githubusercontent.com/83751707/143878632-bf1aa1e8-f9e9-4599-9609-4413fdb3083b.png)

**Comment by qtwrk** [comment]
you need to go to SSL -> hostname SSL , and choose that domain

**Comment by prtechindiaoss** [comment]
![image](https://user-images.githubusercontent.com/83751707/143879323-d087c0e4-1418-4a6c-b6a0-e32c324ecdaf.png)
![image](https://user-images.githubusercontent.com/83751707/143879394-3d5bca40-4070-4f1d-8776-ab317bc94c65.png)
@qtwrk it had ssl

**Comment by qtwrk** [comment]
you need to go to SSL -> hostname SSL , and choose that domain

otherwise it will use self-signed cert if you don't do this step

**Comment by prtechindiaoss** [comment]
thx @qtwrk it worked , suggestion : add "issue hostname SSL" in create website section

**Comment by sawrubgupta** [comment]
Hello, I am facing a ssl issue, I have installed ssl and its showing also but not working, what to do ?

![image](https://user-images.githubusercontent.com/55241111/206850949-8e13c48b-6719-480c-bad5-89fe07907c23.png)
