### ISSUE TITLE
CSF error on new install - AlmaLinux 8.5 & Ubuntu Server 20.04.3 LTS

### ISSUE THREAD

**Issue by jtechbus** [litespeedtech/cyberpanel#776]
Error displayed when clicking on Firewall Configuration of CSF:
It looks like the webpage at https://hostname.domain.com:8090/configservercsf/iframe/ might be having issues or it may have moved permanently to a new web address.

Steps to reproduce:

1. Install CyberPanel on AlmaLinux 8.5 or Ubuntu Server 20.04.3 LTS
2. CyberPanel menu: SERVER > Security > CSF
3. Install CSF
2. CyberPanel menu: SERVER > ConfigServer Services > ConfigServer Security & Firewall
4. Click on "Firewall Configuration" under csf - ConfigServer Firewall

Workaround is to open CyberPanel in Inprivate/Incognito browser window.

New installation of OS & CyberPanel - latest version.

**Comment by GTMAN** [comment]
I cannot reproduce the error. Linode VPS AlmaLinux 8.5
Operating System: AlmaLinux 8.5 (Arctic Sphynx)
       CPE OS Name: cpe:/o:almalinux:almalinux:8::baseos
            Kernel: Linux 4.18.0-348.2.1.el8_5.x86_64

**Comment by qtwrk** [comment]
Alma 8 , can't reproduce it 

what exactly is the error message you see ?

https://i.imgur.com/8TZYpw8.png

**Comment by jtechbus** [comment]
Sorry must be something on my end.
