### ISSUE TITLE
Github Private Repo clone/pull not working

### ISSUE THREAD

**Issue by mrpatg** [litespeedtech/cyberpanel#78]
I have setup an empty repo initially as private. The git setup wouldn't work, failed with error 404. I made the repo public and I was able to clone and pull updates. As soon as I made the repo private again, it no longer pulls. The webhook log in github shows a 200 status for the webhook with the response:

`{"error_message": "None", "pulled": 1}`

**Comment by yndj** [comment]
{"error_message": "None", "pulled": 1}

**Comment by mrpatg** [comment]
> {"error_message": "None", "pulled": 1}

This is what the webhook response shows. But the new updates from the repo **have not been pulled**, despite what it is saying.

**Comment by usmannasir** [comment]
Will look into the private repo issue, and get back with updates.

**Comment by usmannasir** [comment]
Pushed a fix, try a forced upgrade. You will need to add the dev key on your Github account https://help.github.com/en/articles/adding-a-new-ssh-key-to-your-github-account

https://github.com/usmannasir/cyberpanel/commit/5d104c30d186aa7d4662cad5b403cc74d5e6c331
https://github.com/usmannasir/cyberpanel/commit/a4fd57685c58faa777602a2e033f0181c30da3fb

**Comment by mrpatg** [comment]
Thank you I'll try to this morning. Really appreciate the quick turnaround!

**Comment by mrpatg** [comment]
@usmannasir thank you, it's working great!

**Comment by usmannasir** [comment]
You can close the issues if no longer required.
