### ISSUE TITLE
Avoid third party hosts for libraries

### ISSUE THREAD

**Issue by Brugman** [litespeedtech/cyberpanel#789]
I think it is best practice nowadays to host your own libraries.

By loading assets from angularjs.org, cloudflare.com, jquery.com, jsdeliver.net, googleapis.com and gstatic.com we are increasing the chance of a service outage affecting our control panel by 6x.

We are forced to trust our VPS, but if we load JS from (for example) angularjs.org we also have to trust all adminstrators of that third party.

![third-parties](https://user-images.githubusercontent.com/2203813/148864212-e4260b52-b820-462f-9e4a-15789f099e70.jpg)

Please thumbs up if you agree.

**Comment by PowerChaos** [comment]
loading external libary's is to offload the plugins and also to improve speed with parallell loading
this also means that you always got the latest files , the files are loaded from a CDN service so it is unlikely they ever go down 
it even load the files based on where you are located to minimise lag and response time
also a CDN makes your maintained files smaller as it is one thing less to worry about ( look at bootstrap , its massive  ) 

so if you combine those 2 factors then it is better to use a CDN then self hosting
it loads parrallel and one less thing to worry about in case you need to update files

Greetings from PowerChaos

**Comment by Brugman** [comment]
- It's an admin only control panel, it doesn't have the same speed problems as a public website.
- "smaller files" Add a build system to the dev version, ship your own minified code to master.
- "The latest files" In 2010 some people would load `jquery-latest.min.js`. This is now a bad practice. You code for v2, you ship v2. If you upgrade and code for v3 then you ship v3.
- "CDNs are unlikely to go down" I countered in the issue.

Appreciate your input tho.

**Comment by usmannasir** [comment]
resolved.

**Comment by Brugman** [comment]
Thanks!
