### ISSUE TITLE
Admin user email address

### ISSUE THREAD

**Issue by Brugman** [litespeedtech/cyberpanel#790]
Why does the admin user have email `usman@cyberpersons.com` by default?

If it has to be a working email address: Why? What's possibly being sent? Why is it going to Usman and not us?

If it does not: Why not change it to something like `example@example.org` ?

I wouldn't want my email address spread around thousands of servers for no good reason. I don't know why you would.

Please thumbs up if you agree.

**Comment by PowerChaos** [comment]
this is just a placeholder and he is the developer so if he feels safe to put his email/signature as default then what is the harm in it ?
at least you got a way to contact him in case something goes wrong
and the other reason is most likely to have statics of where everything get installed and how many installs there are with out the need to hard code a lot of tracking into the script
it is more easy to dispose of a email address then to rewrite a script to disable tracking/stats

Greetings from PowerChaos

**Comment by j-a-pope** [comment]
Ideally you should be asked to specify the admin address either during installation or at the first login.

**Comment by usmannasir** [comment]
resolved.

**Comment by Brugman** [comment]
Thanks!
