### ISSUE TITLE
Inspect the default ACL settings

### ISSUE THREAD

**Issue by Brugman** [litespeedtech/cyberpanel#791]
When I go to "Users > View Profile" and "Users > Create New User" I see ACL options admin/reseller/user and I get curious about what that means. So I go to "Users > Modify ACL", and none of these 3 are listed. I now assume we are not allowed to edit these. Ok, fine. But I also cannot view what settings they contain.

We shouldn't expect people to use presets that they don't know the meaning of.

Blocking editing the defaults is fine, but add a way to display them.

I see #99 also addressed this issue but was ignored.

Please thumbs up if you agree.

**Comment by PowerChaos** [comment]
They are the defaults and generate a new page for login
they are also place holders for the system for it to work
so no point in letting them be edited as it breaks the panel, also no point in showing what they contain as it is a mandatory thing to start with
just create your own ACL and go back to default in case you mess up, in this case you know that the defaults will work.

Greetings from PowerChaos

**Comment by Brugman** [comment]
> no point in showing what they contain as it is a mandatory thing to start with just create your own ACL

If I could see what they contain, and I happen to completely agree with the default choices, then I don't have to make custom ones.

I would prefer that over having to see `[ A, B, C, Custom A, Custom B, Custom C ]` every time I add/edit a user.

**Comment by Brugman** [comment]
Why close this?
