### ISSUE TITLE
Add classes to top level menu items

### ISSUE THREAD

**Issue by Brugman** [litespeedtech/cyberpanel#793]
Could we add unique ids/classes to the `#sidebar-menu li`'s that refer to their name?
I.e. `<li class="sidebar-menu-item-users">` for the Users top level menu item, etc.

In my CyberPanel CloudLinux, Containerization and Docker are not installed and I don't think I will need/want these for a long time, maybe forever. If the nav items had classes I could hide these nav items with the custom CSS feature and have a less cluttered smaller navigation pane. Cleanliness is next to godliness!

**Comment by PowerChaos** [comment]
i dont think it would be a good idea to hide all the functions the panel has
as sometimes you hide stuff and forget you have hidden it and then it get reported as a bug

on other side , at this moment it get also clustered with the "new' label, so a way to group them by used and non used functions could be nice, but i wont recommerd a "hide" function as it will cause confusion and you will forget about those functions

Greetings from PowerChaos

**Comment by Brugman** [comment]
A "hide" feature for menu items would be perfect for me, but I totally agree that some users would hide stuff and then forgot that they did. It is also much more work to add a hide feature.

I'm proposing adding classes so that weirdos like me, who know the risks, can hide them with custom CSS.

**Comment by erobertsme** [comment]
> i dont think it would be a good idea to hide all the functions the panel has as sometimes you hide stuff and forget you have hidden it and then it get reported as a bug
> 
> on other side , at this moment it get also clustered with the "new' label, so a way to group them by used and non used functions could be nice, but i wont recommerd a "hide" function as it will cause confusion and you will forget about those functions
> 
> Greetings from PowerChaos

This is an entirely useless point. Just because you can imagine someone possibly being negligent or forgetful doesn't make any good points against adding something so simple that allows for extra customization.

**Comment by j-a-pope** [comment]
Adding classes would be really useful and clearly a lot simpler than implementing any 'hide menu' function. 

A different class for the entire page depending on the access level of the user who is logged in, admin, reseller, user, etc. would also be really useful.

**Comment by usmannasir** [comment]
pull request merged.

**Comment by Brugman** [comment]
Thank you!
