### ISSUE TITLE
[BUG] Upgrader not working on Almalinux 8.5

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#796]
Unable to detect your system...
CyberPanel is supported on Ubuntu 18.04 x86_64, Ubuntu 20.04 x86_64, CentOS 7.x, CentOS 8.x and CloudLinux 7.x...

**Comment by qtwrk** [comment]
how did you upgrade ?  what command you used ?

**Comment by master3395** [comment]
bash <(curl https://cyberpanel.sh/new_upgrade.sh) -b 2.1.2

**Comment by qtwrk** [comment]
try this way 

`bash <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/cyberpanel_upgrade.sh)`
