### ISSUE TITLE
Cant Create Website with IP address

### ISSUE THREAD

**Issue by rakshitbharat** [litespeedtech/cyberpanel#80]
Cant Create Website with IP address

in simple language just try to create new website and write domain name like http://192.168.2.3/
then this will create error
Error message: [Errno 2] No such file or directory: u'/home/cyberpanel/2064' <<<< this is random number

solution for this is if we make a website with fake domain and make an aliens of IP then it works

**Comment by usmannasir** [comment]
Try without http such as `192.168.2.3`

**Comment by rakshitbharat** [comment]
nup , not working
