### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by dfag86** [litespeedtech/cyberpanel#800]
adding PHP 8.1 version Not working. there is a choice, but nothing follows. the highest version is still 8.0.

https://user-images.githubusercontent.com/92047835/147505144-c9f44436-9954-4aaa-9b18-f6da215091f7.jpg

https://user-images.githubusercontent.com/92047835/147505154-558873b6-91e0-47de-b677-eca5460ab2e9.jpg

**Comment by usmannasir** [comment]
You can install lsphp81 from cli depending upon your OS command will change. example `yum install lsphp81*` or `apt-get install lsphp81*`
