### ISSUE TITLE
Incremental Backup - Restore from Remote failed

### ISSUE THREAD

**Issue by eboppel** [litespeedtech/cyberpanel#801]
**Describe the bug**
When trying to restore a website from AWS, I get the error "Operation Failed!  Could not connect to server, please refresh this page".  I am able to create an incremental backup to AWS successfully and the backup does appear in AWS.  The problem is when I attempt to restore the website, it won't connect and fetch the restore points.

This is a completely fresh install of CyberPanel v2.1.2, absolutely nothing has been configured (except for the 1 website and AWS credentials).  There is no firewall active and no configurations have been changed.

After trying many things unsuccessfully, I tried re-installing CyberPanel to version 2.1.1 and everything worked perfectly, I was able to create a backup and restore it again, therefore ruling out server or firewall issues.  I then upgraded CyberPanel to the newest version, and the problem returned.

**To Reproduce**
What steps did you take when the issue occurred? 
1. Click on "Incremental Backup" tab
2. Click on "Restore from Remote"
3. Select the website, destination (AWS) and enter password

**Expected behavior**
Connect to AWS and fetch all restore points in order to restore website.

**Screenshots**
Screenshot attached
video: [(https://www.loom.com/share/f4f94163dec245928500e5628afb1266?sharedAppSource=personal_library)]

**Operating system:**
Ubuntu 20.04

**CyberPanel version:**
2.1.2

**Additional context**

![bug-screenshot](https://user-images.githubusercontent.com/22431232/150611251-1a42af5c-761e-495b-b3ae-91ff69d2333f.png)

**Comment by usmannasir** [comment]
Will try to reproduce and get back to you.

**Comment by usmannasir** [comment]
We've tried but can not reproduce this bug on our end.
