### ISSUE TITLE
[BUG] Setting PHP version for domains

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#802]
I have tried setting the php version from within the subdomain's page.
That did not work.
Setting it from the main domains "domain list" works.

![image](https://user-images.githubusercontent.com/4199669/150647102-cba46218-017f-44ce-85d0-967bcfd0973f.png)

Looks like it could not find any PHP files using the subdomains config.

![image](https://user-images.githubusercontent.com/4199669/150647154-c5cf4d45-1241-47c6-b995-26c1d9af778b.png)

Changing it from the main domain's list worked.
![image](https://user-images.githubusercontent.com/4199669/150647176-51d75dc6-ab97-415d-a02d-d561a2d59317.png)

**Comment by usmannasir** [comment]
I can confirm that it is working from both cases, provided that the php version is installed on the backend.
