### ISSUE TITLE
SSL problems OR DNS Problem

### ISSUE THREAD

**Issue by ksaltik** [litespeedtech/cyberpanel#805]
I have several domains one of them uses Coudflare DNS and I can issue SSL certificates without any problem.

I cannot issue SSL certicate for the domains uses local powerdns.

My cyberpanel upgareded from 1.9 to 2.1.2 for every new release.

The issue is not about acme.sh or folder permi,ssions etc. 

I try to issue manuelly no success.

This issue is exist and for years there is no proper solution for this.

If you want to recreate this issue just install 1.9 versio than configure the server and create any domain and one by one upgradew to the closest version u8ntil 2.x than you will face with the problem.

**Comment by usmannasir** [comment]
Don't use git for support issues, use our community forums.
