### ISSUE TITLE
Backup Destination

### ISSUE THREAD

**Issue by vpsinghbaghel** [litespeedtech/cyberpanel#806]
OS: CentOS or Ubuntu.
CyberPanel version: Latest.
**Feature: Backup to remote destination.**
Is there a way to add a remote backup destination of another Linux system with a non-root user credentials?
At present it's only possible with root user.

Please allow option to add remote destination using a non-root user.

Thank You.

**Comment by usmannasir** [comment]
It is not possible now. For feature request kinly use our community forums.

**Comment by vpsinghbaghel** [comment]
Ok. I have raised feature request in community forum. Thank you.
