### ISSUE TITLE
[BUG] - Can’t validate SSL Certificate

### ISSUE THREAD

**Issue by tiendungdev** [litespeedtech/cyberpanel#814]
I just bought ssl (Sectigo SSL)  and added it to Cyberpanel

But my site [[vutruso.com](https://vutruso.com)] can’t validate SSL Certificate when share on Facebook

`Can’t validate SSL Certificate. Either it is self-signed (which will cause browser warnings) or it is invalid.`

Temporary solution i overwrite 2 files with ssl certificate i just bought

- /etc/letsencrypt/live/vutruso.com/fullchain.pem
- /etc/letsencrypt/live/vutruso.com/privkey.pem

fullchain.pem can get in this url: https://whatsmychaincert.com/

I tried with more than 3 servers using CyberPanel and same issue.

**Comment by usmannasir** [comment]
If you put your SSL manually in 

    /etc/letsencrypt/live/vutruso.com/fullchain.pem
    /etc/letsencrypt/live/vutruso.com/privkey.pem

it works?

**Comment by tiendungdev** [comment]
Yes, it working.

Currently, I am using this method for my 3 websites

**Comment by usmannasir** [comment]
But if you Add SSL from CyberPanel, it pretty much do the same thing.

You sure that you added private key and certification in right boxes?

**Comment by tiendungdev** [comment]
Yes, if I add SSL from CyberPanel, it working, BUT when you share your url on Facebook or social networks, it will warn you as shown below

https://community.cyberpanel.net/uploads/default/optimized/2X/d/d3b2b4a8f85c6d0f55c83f5d390b7f4f25211477_2_1035x442.png

> Can’t validate SSL Certificate. Either it is self-signed (which will cause browser warnings) or it is invalid.

It seems that Cyberpanel does not configure the fullchain.pem file correctly?!!

**Comment by usmannasir** [comment]
Alright, if you already have a community thread we can continue there.

**Comment by tiendungdev** [comment]
Okay bro.

**Comment by tiendungdev** [comment]
This bug still exists, I hope you will fix it in the next version.

Ussing this method, but after 30 days, CyberPanel auto-reinstall R3 ssl :(

> /etc/letsencrypt/live/vutruso.com/fullchain.pem
> /etc/letsencrypt/live/vutruso.com/privkey.pem
