### ISSUE TITLE
[BUG] Upgrade failure - /usr/local/CyberCP/lib64: No such file or directory

### ISSUE THREAD

**Issue by Lvl4Sword** [litespeedtech/cyberpanel#817]
disregard

**Comment by rafakwolf** [comment]
I am facing this error running this script:
`sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh)`

After running it I am also facing 503 - Service Unavailable

How can I fix it?

Thanks!

**Comment by Lvl4Sword** [comment]
> I am facing this error running this script: `sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh)`
> 
> After running it I am also facing 503 - Service Unavailable
> 
> How can I fix it?
> 
> Thanks!

This is a separate thing. If you'd look further into it, you'd see https://cyberpanel.net/version.txt currently gives 2.3 for the version, and this tag doesn't exist on Github right now: https://github.com/usmannasir/cyberpanel/tags

**Comment by rafakwolf** [comment]
I even changed this line of the script
![image](https://github.com/user-attachments/assets/535e1973-1f9e-4cf1-adb5-26abfde0c4f3)
but it does not solve the issue, the only message I can see is this
![image](https://github.com/user-attachments/assets/832b7616-c699-4869-849c-610661186552)
