### ISSUE TITLE
Disabling service does not remove menu

### ISSUE THREAD

**Issue by Brugman** [litespeedtech/cyberpanel#818]
https://cyberpanel.net/docs/manage-services/

> Disable DNS Service (powerdns)
> Please note that once you disable the DNS services, **DNS menu will go away from sidebar.**
> Disable Email Service (postfix)
> Please note that once you disable the Email services, **Email menu will go away from sidebar.**

I've disabled DNS and Email service, rebooted the server, and the menus are still on the sidebar.

**Operating system:**
Ubuntu 20.04.4 LTS

**CyberPanel version:**
Current Version: 2.1
Build: 2
Latest Version: 2.1
Latest Build: 2

**Comment by usmannasir** [comment]
Let me check

**Comment by usmannasir** [comment]
Resolved

**Comment by Brugman** [comment]
Thanks!
