### ISSUE TITLE
[BUG] Error on email login "Invalid password in passdb"

### ISSUE THREAD

**Issue by M1000fr** [litespeedtech/cyberpanel#822]
Hi !
I have issue when i'm connect to a new email.
The domain have a SSL.

```
Feb 26 08:05:40 localhost dovecot: auth-worker(3474): Error: sql(root@ME.fr,127.0.0.1,<JY8CSOfY9tV/AAAB>): Invalid password in passdb: crypt() failed: Invalid argument
Feb 26 08:05:42 localhost dovecot: imap-login: Disconnected (auth failed, 1 attempts in 2 secs): user=<root@ME.fr>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, TLS, session=<JY8CSOfY9tV/AAAB>
```

I have try to edit file ``/etc/dovecot/dovecot-dict-auth.conf.ext`` to change ``default_pass_scheme = MD5`` to ``default_pass_scheme = CRYPT`` but any change :/

**Comment by usmannasir** [comment]
Please open this as thread in our community ```https://community.cyberpanel.net/```
