### ISSUE TITLE
Add PHP 8.1 Extensions

### ISSUE THREAD

**Issue by diver2567** [litespeedtech/cyberpanel#826]
Hi, 

Would it be possible to add PHP 8.1 extensions currently when loading the following message shows and i assume it's because no xml file exists?

1. X.X.X.X:8090/managephp/installExtensions
2. Select PHP 8.1
3. Error: Cannot fetch details. Error message: PHP matching query does not exist.

**Comment by die2mrw007** [comment]
Thats because your OS doesnt have the PHP 8.1 files it seems. Please run this command `ls -la /usr/local/lsws` and see if lsphp81 is shown

**Comment by diver2567** [comment]
![image](https://user-images.githubusercontent.com/16355355/158911616-300321ac-31a3-45f2-8371-48881ed221d5.png)

See above 8.1 exists.

**Comment by muhammetdemirel** [comment]
I have the same problem as well.

**Comment by die2mrw007** [comment]
Just checked and extensions not added by litespeed officially for LSPHP8.1. We will have to wait until they add it
http://rpms.litespeedtech.com/debian/pool/main/focal/

**Comment by diver2567** [comment]
Have they added these yet?

**Comment by usmannasir** [comment]
Fixed
