### ISSUE TITLE
file manager file names

### ISSUE THREAD

**Issue by AhmedShadyElsadany** [litespeedtech/cyberpanel#83]
file manager doesn't work well with spaces in files/folders name
You can before deleting or renaming, etc for file you can do ls command to check if there is a spaces and when deleting them or renaming you can escape the spaces in name by using ( \ ) to delete, rename, compress, extract files correctly

**Comment by usmannasir** [comment]
Spaces are being catered through another mechanism, however, if you are having an issue can you provide an example file name which is creating an issue?

**Comment by far-dev** [comment]
- If there is a compressed file with a numerical value in its name and you try to uncompress it, it will cause problems. for e.g.: file(1).zip, another(12).zip
- If a compressed file has only numbers in its name, it will not delete. for e.g.: 1.zip
- If you try to hit enter to rename a file, it will fail.
- While file renaming, the current name of the file is not picked

**Comment by usmannasir** [comment]
This has been fixed.
