### ISSUE TITLE
[SNAPPYMAIL]

### ISSUE THREAD

**Issue by voigtman** [litespeedtech/cyberpanel#841]
We love cyberpanel and want to make sure everything it provides continues to be secure and minimizes the headaches you, the developers, endure by repeatedly solving problems caused by the inactive development of services connected to cyberpanel.

Suggestion: Replace support for the aging and less secure Rainloop with Snappymail, a fork of the original Rainloop with active development and support. 

Pros:
Direct replacement for Rainloop
Updated security and php
Proper Mobile Support

Cons: not all rainloop plugins will work with snappymail

From: [https://github.com/the-djmaze/snappymail/wiki/Installation-instructions](https://github.com/the-djmaze/snappymail/wiki/Installation-instructions)
_

> SnappyMail is a semi-drop-in replacement for RainLoop. Due to changes in the plugin/extension management code, most plugins from RainLoop are not compatible, so you will need to replace them with equivalents from this SnappyMail repository, or if they're custom plugins, modify the code for compatibility with SnappyMail. See the plugins directory in this repository for samples to determine how best to modify your custom plugins to work with SnappyMail.
> 
> 1. Backup your RainLoop directory and database (this is essential in case of issues with the migration)
> 2. In the RainLoop admin, make note of each plugin you have which is activated and check to be sure a [SnappyMail equivalent exists here](https://github.com/the-djmaze/snappymail/tree/master/plugins). If you have plugins for which there is no equivalent, you'll need to write that code or hire a dev to do so before proceeding.
> 3. Extract the latest SnappyMail release over top of your RainLoop folder structure (the data folder is not touched)
> 4. Navigate to data/_data_/_default_/plugins and backup the contents (tar -cvzf rainloop_plugins.tgz *) then erase the folder contents.
> 5. Ensure file and folder permissions are set correctly by running the commands above under "Set the correct permissions"
> 6. Visit the SnappyMail admin URL and attempt logging in as the admin. If admin login fails, with an unknown error, edit data/_data_/_default_/configs/application.ini and comment out the admin_password line (;admin_password=) then try your admin login again using the newly generated password that SnappyMail placed in data/_data_/_default_/admin_password.txt
> 7. Once you have successfully logged in as admin, remove that admin_password.txt file and either save or change the password to another secure value
> 8. Install each SnappyMail replacement plugin for the plugins you noted in step (2)

_

As previously discussed: https://community.cyberpanel.net/t/cyberpanel-on-aws-cannot-use-rainloop-after-snapshot-restore-advice/32315/29

**Comment by master3395** [comment]
I like the idea.
It isn't really much improved, but it helps.
Below is an comparison between Rainloop and SnappyMail.

https://snappymail.eu/comparison.html

**Comment by master3395** [comment]
You should close this.
SnappyMail is coming in V2.3.2 or so.
