### ISSUE TITLE
[BUG] Custom Error Pages from template do not exist

### ISSUE THREAD

**Issue by Brugman** [litespeedtech/cyberpanel#855]
I found out that when adding websites the OLS vhost gets a custom 404, 403 and 500 error page set to "404.html", "403.html" and "500.html". However, these files are not created in the `public_html`.

So what happens is...

(short version)
When you get a 404 (or 403/505) it's not dealt with properly.

(long version)
If you upload a basic `index.html`, but no `favicon.ico`, Chrome and Firefox will still look for `favicon.ico`, it's not there, so they get redirected to `404.html`, but that is not there, so they get redirected to `404.html`, but that is not there, so they get redirected to `404.html`, but that is not there, so they get redirected to `404.html`, but that is not there, so they get redirected to `404.html`, but that is not there, so they get redirected to `404.html`, but that is not there, so they get redirected to `404.html`, but that is not there... Now your network tab is giant mess.

**Expected behavior**
Do not set custom error pages for new sites.

**Screenshots**
![2022-04-16-06-02-23](https://user-images.githubusercontent.com/2203813/163661447-f78e45a3-5727-495f-9bb6-9d99eab9d941.jpg)

**CyberPanel version:**
Current Version
2.1
Build
2

**Additional context**
I think the template that is being used for new sites is `/usr/local/CyberCP/plogical/vhostConfs.py`. I removed the error pages from this file and the next site I added did not have them.

Revert this commit? f1a722a739250613b6c23b4ebc486f629205f205

**Comment by master3395** [comment]
I got the same issue for all my sites, they got infinite redirect.

**Comment by master3395** [comment]
@usmannasir Perhaps a way to solve infinite redirect if page does not exist?

**Comment by usmannasir** [comment]
resolved.

**Comment by Brugman** [comment]
Thanks!
