### ISSUE TITLE
file manager download file high load CPU

### ISSUE THREAD

**Issue by habibulilalbaab** [litespeedtech/cyberpanel#857]
after archive folder i download file from filemanager, download not running & server high load cpu
how to fix it?
![Screenshot (14)](https://user-images.githubusercontent.com/28334523/164070390-cd4764fd-ee58-46b0-94a3-0e321c9b1277.png)

**Comment by usmannasir** [comment]
On the background does not look like lscpd process taking any CPU. Also you only have 1 CPU.
