### ISSUE TITLE
[BUG/VULNERABILITY] Unpatched Bug in RainLoop Webmail Could Give Hackers Access to all Emails

### ISSUE THREAD

**Issue by MrEddX** [litespeedtech/cyberpanel#860]
**Describe the bug**
An unpatched high-severity security flaw has been disclosed in the open-source RainLoop web-based email client that could be weaponized to siphon emails from victims' inboxes.
Full blog article is available [Here](https://thehackernews.com/2022/04/unpatched-bug-in-rainloop-webmail-could.html?m=1).

**To Reproduce**
[Watch this video](https://youtu.be/6dSiQH0pijk)

**Possible Solution**
[SnappyMail](https://github.com/the-djmaze/snappymail), although my favorite is [Roundcube](https://roundcube.net/).

**Comment by master3395** [comment]
SnappyMail is based upon Rainloop source code.
Have you checked if it has the same issue?

**Comment by lsthompson** [comment]
[CrossBox](https://crossbox.io/) seems to be the favourite these days in lieu of RainLoop & forks.

**Comment by MrEddX** [comment]
> SnappyMail is based upon Rainloop source code.
Have you checked if it has the same issue?

We are awaiting a response from the developer.

**Comment by lsthompson** [comment]
> We are awaiting a response from the developer.

https://blog.sonarsource.com/rainloop-emails-at-risk-due-to-code-flaw

The responsible reporter made contact with SnappyMail already, and they've confirmed it's OK.

> We recommend the RainLoop fork [SnappyMail](https://snappymail.eu/). It has great security improvements and is actively maintained. We would like to thank the maintainers of this fork for their quick response and analysis of this issue. They confirmed to us that they are not affected. **For this reason, we recommend users of RainLoop migrate to SnappyMail in the long term.**

Repo's linked here, and looks to be a wise move: https://github.com/the-djmaze/snappymail

Certainly simpler than uprooting and shifting to an entirely different platform (likely for little real gain).

**Comment by master3395** [comment]
Changing to SnappyMail is just replacing the folder and re-add the code from rainloop into the snappy config.
Then make a pull request here :)

I'll see if I can help out with that.

**Comment by master3395** [comment]
Trying to change it out.

I think I've replaced most of it, but the unzip isn't working as I've not fully worked with tar.gz unzipping.
Made a draft here:
[https://github.com/usmannasir/cyberpanel/pull/865](https://github.com/usmannasir/cyberpanel/pull/865)

**Comment by lowshadow** [comment]
> [CrossBox](https://crossbox.io/) seems to be the favourite these days in lieu of RainLoop & forks.

We are using CrossBox with Mxroute and I'm very familiar with their software.  It is not a fork of anything. It was developed from the ground up and written in Golang. You can see their tech stack here: https://crossbox.io/technology

**Comment by master3395** [comment]
> > [CrossBox](https://crossbox.io/) seems to be the favourite these days in lieu of RainLoop & forks.
> 
> We are using CrossBox with Mxroute and I'm very familiar with their software. It is not a fork of anything. It was developed from the ground up and written in Golang. You can see their tech stack here: https://crossbox.io/technology

This look seems really cool.
I have no idea how to integrate that.

It would be a complete replacement for both RoundCube and Rainloop + SnappyMail as it also integrate calender, 3-party apps such as nextcloud (Werry handy)

**Comment by usmannasir** [comment]
I've added SnappMail as default in v2.3.2, there were issues in @master3395 pull request, which i've resolved now, thanks for your work.
