### ISSUE TITLE
GitHub Releases no longer being used (v1.9.1 Release vs v2.3.1 Branch); Update flow to tag/package each release?

### ISSUE THREAD

**Issue by lsthompson** [litespeedtech/cyberpanel#862]
At the moment CyberPanel's at [v2.3.1](https://github.com/usmannasir/cyberpanel/blob/stable/version.txt) ([branch](https://github.com/usmannasir/cyberpanel/tree/v2.3.1)) from 2022, while the latest GitHub Release [package](https://github.com/usmannasir/cyberpanel/releases) is at [v1.9.1](https://github.com/usmannasir/cyberpanel/releases/tag/v1.9.1) from 2019.

If there's no capacity to bundle and upload these, I'm happy to sort them - though believe I'd need access to do so.

Would be great to be able to leverage releases through GitHub if it was possible to adjust the processes. :-)

**Comment by Brugman** [comment]
Tags are a small step required before using Releases. Let's get tags first. No effort needed other than tagging and pushing the commits that mark versions since 1.9.1. A total workload of 5 minutes.

I posted about this in #853

**Comment by lsthompson** [comment]
Closing issue #862 as #853 by @Brugman covers it off.
