### ISSUE TITLE
[BUG] Subdomains leading the user to 403 after 2.3.1

### ISSUE THREAD

**Issue by CypherPotato** [litespeedtech/cyberpanel#871]
After upgrading CyberPanel to 2.3.1, newly created sub-domains leads the user to an 403 page. I'm using CloudFlare as DNS management, but before this version everything was working fine.

No setting or configuration was touched since it.

CyberPanel 2.3.1 at CentOS 8.5.

**Comment by CypherPotato** [comment]
Also, with some subdomains created on other domains I have a "404" instead of a "403". No error log is generated for them.

**Comment by CypherPotato** [comment]
I've rolled-back my server to a past backup, at version 2.1.2 and the error is not reproducible, everything worked as it should. I won't update to the new version until I'm sure this was fixed.

**Comment by usmannasir** [comment]
Ok, let me reproduce this.

**Comment by usmannasir** [comment]
Just set up fresh node, created subdomain, works fine `http://incbackus.cyberpanel.net/`

**Comment by CypherPotato** [comment]
But this is happening with me, and idk what to do. Just created a fresh new subdomain and i'm getting 404 on it. On Cyberpanel main log, i'm getting this on CyberPanel main log:

```
[05.18.2022_16-41-07] [Errno 2] No such file or directory: '/etc/letsencrypt/live/test.frontflame.com/fullchain.pem'
[05.18.2022_16-49-03] [Errno 2] No such file or directory: '/etc/letsencrypt/live/test.frontflame.com/fullchain.pem'
[05.18.2022_16-59-44] Failed to obtain SSL for: test.frontflame.com and: www.test.frontflame.com
[05.18.2022_16-59-44] Trying to obtain SSL for: test.frontflame.com
[05.18.2022_16-59-48] Failed to obtain SSL, issuing self-signed SSL for: test.frontflame.com
[05.18.2022_16-59-48] {'xxxxx@frontflame.com': (554, b'5.7.1 <xxxxx@frontflame.com>: Relay access denied')}
[05.18.2022_16-59-49] Websites matching query does not exist. [installSSLForDomain:72]
[05.18.2022_16-59-49] Self signed SSL issued for test.frontflame.com.
```

It seems it is trying to find the privatekeys of the SSL. I've deleted the website from the CyberPanel and created it, this time with SSL checkbox checked in, and the directories at /etc/ was created, however, no success with the website access.

If wondering, i'm using CloudFlare as DNS service, but all other subdomains are working fine.

**Comment by CypherPotato** [comment]
Problem solved after giving permissions `0755` to the $VH_ROOT as `root`. As `test.frontflame.com` was giving me 404 or 403, running

```
chmod 755 /home/frontflame.com/test
```

solved the issue. However, I have to do this procedure for every site I'm going to add. I have to do this for domains too, as the problem applies.

**Comment by CypherPotato** [comment]
Update: the above solution works only for static websites. Websites which it's index is `.php` the following error will be throw:

```
2022-05-25 17:53:22.660285 [ERROR] [34992] [XXX.XXX.XXX.XXX:45986] MIME type [application/x-httpd-php] for suffix '.php' does not allow serving as static file, access denied!
```

Any ideas to solve it?

**Comment by CypherPotato** [comment]
It was solved after logging into LSPD and changing this option at subdomain virtual host:

![](https://i.imgur.com/xEWjlQ1.png)

**Comment by CypherPotato** [comment]
To reproduce this:

Create a subdomain, you'll get a 403, then

```
chmod 755 /home/domain.com/subdomain
```

The website will work, however, if you create an `index.php` into it with anything, you'll get 403 again. To fix this, go to LSWC console, navigate into the virtual host of the subdomain/domain and on External App, tap Edit of the main app

after it, `Command` should be `/usr/local/lsws/lsphp81/bin/lsphp`, which ins't a valid directory in the server. After changing it to `/usr/local/lsws/lsphp80/bin/lsphp` the website worked well even with PHP.

**Comment by divineniiquaye** [comment]
> But this is happening with me, and idk what to do. Just created a fresh new subdomain and i'm getting 404 on it. On Cyberpanel main log, i'm getting this on CyberPanel main log:
> 
> ```
> [05.18.2022_16-41-07] [Errno 2] No such file or directory: '/etc/letsencrypt/live/test.frontflame.com/fullchain.pem'
> [05.18.2022_16-49-03] [Errno 2] No such file or directory: '/etc/letsencrypt/live/test.frontflame.com/fullchain.pem'
> [05.18.2022_16-59-44] Failed to obtain SSL for: test.frontflame.com and: www.test.frontflame.com
> [05.18.2022_16-59-44] Trying to obtain SSL for: test.frontflame.com
> [05.18.2022_16-59-48] Failed to obtain SSL, issuing self-signed SSL for: test.frontflame.com
> [05.18.2022_16-59-48] {'xxxxx@frontflame.com': (554, b'5.7.1 <xxxxx@frontflame.com>: Relay access denied')}
> [05.18.2022_16-59-49] Websites matching query does not exist. [installSSLForDomain:72]
> [05.18.2022_16-59-49] Self signed SSL issued for test.frontflame.com.
> ```
> 
> It seems it is trying to find the privatekeys of the SSL. I've deleted the website from the CyberPanel and created it, this time with SSL checkbox checked in, and the directories at /etc/ was created, however, no success with the website access.

I encountered the same problem, after reading the comment above, all I did was to click the **Issue SSL** button on the subdomain. All went well

![image](https://user-images.githubusercontent.com/53147395/175276401-b566568c-86f8-4937-92b6-dac907c33bb6.png)

**Comment by usmannasir** [comment]
Are you on latest commit and version ?
