### ISSUE TITLE
Mailbox size info?

### ISSUE THREAD

**Issue by lahorenc** [litespeedtech/cyberpanel#872]
Is there a way to see the mailbox size for a particular mail address or domain anywhere? Anyway, currently all users have unlimited large mailbox.

**Comment by MyIDKaTePe** [comment]
https://community.cyberpanel.net/t/user-quota-vmail/34185

 

agree.. i have same post about this

**Comment by lahorenc** [comment]
Yes, these are some basic functionalities that I would think were made first. Without them the cyberpanel is a semi-finished product.

**Comment by MyIDKaTePe** [comment]
> these are some basic functionalities that I would think were made first

yes.. for us.... 
but, for usmannasir he made cyberpanel first time is for him self hhaha
but now cyberpanel getting bigger and as one of top hosting control panel .. quota is one of the most important thing

**Comment by usmannasir** [comment]
I will add this

**Comment by MyIDKaTePe** [comment]
glad to hear that... one more point for cyberpanel...

**Comment by usmannasir** [comment]
![disk-usage](https://user-images.githubusercontent.com/17538454/169686536-51212413-e112-451e-b693-ee86c4700426.png)

Added

**Comment by lahorenc** [comment]
Hi
Update to latest and still not see Disk usage?
Regards,
Lahor

**Comment by usmannasir** [comment]
This is not in current stable branch yet.

**Comment by MyIDKaTePe** [comment]
> This is not in current stable branch yet.

it will counted as a hosting quota size or just "info" at email section ?

**Comment by usmannasir** [comment]
in `v2.3.2` it will be info only.

**Comment by MyIDKaTePe** [comment]
> in `v2.3.2` it will be info only.

so the user quota will still not counted ?
that will be a big trouble when we have mail hosting client :(
