### ISSUE TITLE
[BUG] Error when running installation script

### ISSUE THREAD

**Issue by Scraayp** [litespeedtech/cyberpanel#874]
**Describe the bug**
When following the installation docs, I came across a error which stops the process of installation!

**To Reproduce**
What steps did you take when the issue occurred? 
1. Create a ubuntu 20.4 LTS vps.
2. Follow the documentation installation steps
3. You will get stuck at the script installation part

**Expected behavior**
The installation should continue and give me options

**Operating system:**
Ubuntu 20.04 LTS

**CyberPanel version:**
None

**Additional context**
Error and command I ran:

```
ubuntu@vps-55514fca:~$ sudo sh <(curl https://cyberpanel.net/install.sh || wget -O - https://cyberpanel.net/install.sh)
sh: 0: Can't open /dev/fd/63
  % Total    % Received % Xferd  Average Speed   Timeubuntu@vps-55514fca:~$     Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1802  100  1802    0     0  23402      0 --:--:-- --:--:-- --:--:-- 23402
(23) Failed writing body
```

**Comment by qtwrk** [comment]
Run 

`sudo su -`


Then run 

`sh <.........`

**Comment by Scraayp** [comment]
That fixed it. Thanks!
