### ISSUE TITLE
[BUG] /etc/adminPass doesnt get updated when you use adminPass command

### ISSUE THREAD

**Issue by nickchomey** [litespeedtech/cyberpanel#875]
**Describe the bug**
When you change the cyberpanel admin password using the `adminPass` command, the value in `/etc/adminPass` does not get updated. This was first reported in the forum 1.5 years ago. https://community.cyberpanel.net/t/side-effects-of-changing-admin-password/18989/2

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occurred? 
1. enter `adminPass [newpw]`
2. enter `nano /etc/adminPass`

**Expected behavior**
adminPass file would be updated

**Operating system:**
Ubuntu 20.04

**CyberPanel version:**
2.3.1

**Comment by qtwrk** [comment]
fixed in https://github.com/usmannasir/cyberpanel/pull/876
