### ISSUE TITLE
RainLoop Webmail "Domain is not allowed" Error

### ISSUE THREAD

**Issue by 395Tech** [litespeedtech/cyberpanel#879]
I am getting the "Domain is not allowed" when trying to log into the RainLoop Webmail.  I am running the latest version as of this post.

I go to https://********:8090/rainloop/index.php
Enter the email address and password
And I get this error
![RainLoop Webmail](https://user-images.githubusercontent.com/42765315/168072195-2e846333-7d17-4d8c-ab23-80be3ad856ed.png)

Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-110-generic x86_64)

Current Version :  2.3
Build :  1
Current Commit :  01a9093bdbc2bbf14c9ab67133c248588dd8b225

Let me know what log files you would like and how to get them.

**Comment by 395Tech** [comment]
I just realized that I can not access or create any files/folders in the https://********::8090/filemanager/*Domain*.com

**Comment by usmannasir** [comment]
Did you create the email for this domain?

**Comment by 395Tech** [comment]
Yes

![RainLoop List Websites](https://user-images.githubusercontent.com/42765315/168416666-a735ea63-52bb-4cc5-ab2d-911afbae3aa3.png)

![RainLoop List Email Accounts](https://user-images.githubusercontent.com/42765315/168416792-b3a01516-a831-4dea-9706-21ac81448fab.png)

![RainLoop File Manager](https://user-images.githubusercontent.com/42765315/168416674-1ff17a61-1573-4d3d-8d53-235ca96f2f9a.png)

**Comment by usmannasir** [comment]
Please do this once and see if your issue is resolved: https://community.cyberpanel.net/t/9-how-to-debug-and-reset-email-settings-using-cyberpanel-cloud/106

**Comment by 395Tech** [comment]
Its connected but I can not run the debugger

![eMail Debugger](https://user-images.githubusercontent.com/42765315/168417669-92b8df5e-3327-4fcb-ad4e-f1e8ffe31f59.png)

**Comment by usmannasir** [comment]
ask support as mentioned in the article and they will enable for you.

**Comment by 395Tech** [comment]
> ask support as mentioned in the article and they will enable for you.

Ok thanks I have put in a support ticket
Ticket #IU7U6SFBK - Enable Debug Mail

**Comment by usmannasir** [comment]
Great, i will close this from here
