### ISSUE TITLE
How to setup laraval smtp mail server

### ISSUE THREAD

**Issue by wdsmaduranga** [litespeedtech/cyberpanel#883]
How to setup laraval smtp mail server cyber panel

**Comment by lsthompson** [comment]
Please close this issue, and instead raise a thread at the CyberPanel Community if you can't find a solution.

https://community.cyberpanel.net/

For example:

https://community.cyberpanel.net/docs?search=SMTP&topic=109
https://community.cyberpanel.net/t/troubleshooting-cyberpanel/155

**Comment by wdsmaduranga** [comment]
> Please close this issue, and instead raise a thread at the CyberPanel Community if you can't find a solution.
> 
> https://community.cyberpanel.net/
> 
> For example:
> 
> https://community.cyberpanel.net/docs?search=SMTP&topic=109 https://community.cyberpanel.net/t/troubleshooting-cyberpanel/155

Bro not send mails my laravel project  how to set up this

**Comment by lsthompson** [comment]
Step 1: Please close this issue, as it's unlikely to be an issue in CyberPanel itself.

Step 2: Please open a new thread at the CyberPanel Community -> https://community.cyberpanel.net/

There's a very active community of users and admins there who'd likely be happy to help you. It's the right place for this.

**Comment by wdsmaduranga** [comment]
Ok
