### ISSUE TITLE
Replace rainloop with alternatives

### ISSUE THREAD

**Issue by Jaspix** [litespeedtech/cyberpanel#886]
Rainloops suffers from an unpatched XSS security issue for several months now. This compromises the security of thousands of cyberpanel installations. Rainloop seems to be an abandoned product as of now. Please replace the rainloop client with more secure alternatives like SnappyMail.
https://thehackernews.com/2022/04/unpatched-bug-in-rainloop-webmail-could.html

**Comment by lsthompson** [comment]
Please close - already resolved in #860 - thank you.
