### ISSUE TITLE
[BUG] Create domain error powerdns

### ISSUE THREAD

**Issue by wellesximenes** [litespeedtech/cyberpanel#889]
Greetings when I create domains that have not been terminated .com it removes the beginning of the domain in the powerdns database.

example: lcl.ufrj.br

in the bank it looks like this: ufrj.br

More in the domain list is correct error occurs only in dns

**Comment by usmannasir** [comment]
In powerdns zone will be created for `ufrj.br` because its TLD. `lcl.ufrj.br` will be created as A record under this zone.

**Comment by wellesximenes** [comment]
My problem is that after creating I can't edit dns  look at the photos in the link please

https://uploaddeimagens.com.br/imagens/vy9Pt9c

https://uploaddeimagens.com.br/imagens/nPeX9MU
