### ISSUE TITLE
[BUG] Wordpress installs fail with Curl 

### ISSUE THREAD

**Issue by tmunsch** [litespeedtech/cyberpanel#891]
**Describe the bug**
Cannot install wordpress receive the error below

**To Reproduce**
What steps did you take when the issue occurred? 
1. Add website
2. Install wordpress

**Expected behavior**
Click install wordpress and it installs wordpress

**Screenshots**
![image](https://user-images.githubusercontent.com/27962004/172192791-b5251401-59e7-42af-8864-987fb92c217f.png)

**Operating system:**
Arma 8

**CyberPanel version:**
2.3.1

**Additional context**
Really excited about getting away from Cpanel but i need to install wordpress at a bare minimum.

**Comment by usmannasir** [comment]
CyberPanel does not work on arm. Also the recommended operating system in Ubuntu 20.04

**Comment by tmunsch** [comment]
I meant alma 8

**Comment by tmunsch** [comment]
![image](https://user-images.githubusercontent.com/27962004/172195473-85179922-570c-4cab-89a0-c9d6ba0053e6.png)

**Comment by tmunsch** [comment]
Should i use centos 8?

**Comment by tmunsch** [comment]
I really need this to work, was going to move everything to cyberpanel today. Thank you for making this

**Comment by usmannasir** [comment]
Who is your vps provider? use Ubuntu 20

**Comment by tmunsch** [comment]
Myself, I don't want to use Ubuntu because it doesn't support containerization

**Comment by usmannasir** [comment]
I asked you a question above.

**Comment by tmunsch** [comment]
Myself is the Answer, I am the VPS provider

**Comment by usmannasir** [comment]
kvm, openvz?

**Comment by tmunsch** [comment]
kvm, I don't see how this is relevant

**Comment by tmunsch** [comment]
So, no request for logs or any  attempt to troubleshoot the issue? I am just told...Use Ubuntu, even thought the documentation clearly states it can support Alma Linux. You avoid my questions, then pretend I avoided yours. When in fact i answered them. Can you provide some help on this matter?

**Comment by usmannasir** [comment]
As matter of fact logs should be in your original post with all the questions I just asked. I've also written guide on how to get the maximum detailed logs `https://community.cyberpanel.net/t/log-files-on-cyberpanel/154`, you should have followed and provided the logs in your first post.

**Comment by tmunsch** [comment]
Then why not request them?

**Comment by tmunsch** [comment]
There is nothing in the log but ssl stuff

**Comment by tmunsch** [comment]
Nothing mentioning the install

**Comment by usmannasir** [comment]
As I said those should be in your original post along with all the questions I've asked above, I was getting to the logs part next. 

But you are being impatient here and I am just trying to help, and I doubt that you have enabled debug logs and just directly checked the logs.

Read this part really carefully and then share logs: https://community.cyberpanel.net/t/log-files-on-cyberpanel/154#improved-and-detailed-dynamic-logging-2

**Comment by tmunsch** [comment]
Sorry been working on this for awhile. Thank you for your patience. I will do the above

**Comment by tmunsch** [comment]
```[06.06.2022_17-06-03] /usr/bin/env: 'php': No such file or directory```

**Comment by usmannasir** [comment]
Share few lines above this too

**Comment by tmunsch** [comment]
```[06.06.2022_17-05-38] Expecting value: line 1 column 1 (char 0). [setupConnection:75]
[06.06.2022_17-05-38] CREATE DATABASE r2WLj0tAxMc2Zc
[06.06.2022_17-05-38] CREATE USER 'r2WLj0tAxMc2Zc'@'localhost' IDENTIFIED BY 'TDmMg2Hv4yOxzp'
[06.06.2022_17-05-38] GRANT ALL PRIVILEGES ON r2WLj0tAxMc2Zc.* TO 'r2WLj0tAxMc2Zc'@'localhost'
[06.06.2022_17-05-38] OHK8cgyu3ycs81L2I5023HqysNI7C6/Q-u newmi6894 mkdir -p /home/new.midcarolinagunclub.com/public_html/
[06.06.2022_17-05-38] OHK8cgyu3ycs81L2I5023HqysNI7C6/Q-u newmi6894 ls /home/new.midcarolinagunclub.com/public_html/ | wc -l
[06.06.2022_17-06-03] OHK8cgyu3ycs81L2I5023HqysNI7C6/Q-u newmi6894 wp core download --allow-root --path=/home/new.midcarolinagunclub.com/public_html/
[06.06.2022_17-06-03] /usr/bin/env: 'php': No such file or directory```

**Comment by usmannasir** [comment]
Looks like this not working, if your version manager are you on latest commit? Did you delete any php from lsws?

```wp core download --allow-root --path=/home/new.midcarolinagunclub.com/public_html/```

whats the output of `which php`

**Comment by tmunsch** [comment]
```/usr/bin/which: no php in (/sbin:/bin:/usr/sbin:/usr/bin)```

**Comment by tmunsch** [comment]
``` Current Version :  2.3
Build :  1
Current Commit :  d3256678becae4aa4ecebb5f3efe6cf087df3904

**Comment by usmannasir** [comment]
Yeah thats the problem there is no default php.

`cp /usr/local/lsws/lsphp74/bin/php /usr/bin/php`

run this and install wp again.

**Comment by tmunsch** [comment]
I tried that but there is no php in the bin folder, Very strange as i haven't removed anything and I reran the update

**Comment by tmunsch** [comment]
Should i yum install lsphp74?

**Comment by usmannasir** [comment]
Then your install is badly corrupted I doubt that if lsws even got installed. Try Ubuntu 20 I suppose.

I will later check if there is anything wrong in almalinux installation. 

Even if you yum install lsphp74, there might be other things not working.

**Comment by tmunsch** [comment]
It seems there is no php in any /lsphp* folder

**Comment by tmunsch** [comment]
The install was done on a fresh copy, I will mess around with it. Let me know what you find and thank you for your help so far. I really need to be able to limit the cpu on a website by website basis. Can i accomplish this with ubuntu?

**Comment by usmannasir** [comment]
Check this https://openlitespeed.org/kb/using-cgroups-with-openlitespeed/

**Comment by tmunsch** [comment]
I really need something automated. This looks pretty manual. Does the API support the limits?

**Comment by tmunsch** [comment]
```Errors during downloading metadata for repository 'powertools-for-cyberpanel':
  - Status code: 404 for http://mirror.centos.org/almalinux/8/PowerTools/x86_64/os/repodata/repomd.xml (IP: 216.176.179.218)
Error: Failed to download metadata for repo 'powertools-for-cyberpanel': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried```

**Comment by tmunsch** [comment]
The fun continues. I'll install it on ubuntu, Thank you for your help and let me know what you find for AlmaLinux

**Comment by usmannasir** [comment]
ok

**Comment by tmunsch** [comment]
So... A lot to unfold here. I received a similar error on Ubuntu. Then i typed a subfolder and it seemed to work after that. I am really stuck here though. I can't decide between, Alma Linux or Cloud Linux. The features for Cloud Linux are great but there are some things that I would want that are only in the shared pro license. If i get that then i am back to Cpanel pricing again. Any thoughts on an automated way to limit servers cpu/ram from whmcs? I don't see anything in the api for it. Please advise and thank you for your time

**Comment by usmannasir** [comment]
What extra do you get with Shared Pro?

Just go with CloudLinux + CyberPanel. You can easily limit resources + you have cagesfs. If you think think about shared pro, you are not at cPanel pricing because there you might also get shared pro.

I don't really know what exactly shared pro offers, because I only did integration of normal CloudLinux and if they offer any extra features which require extra code it might not be there.

**Comment by tmunsch** [comment]
Gotcha thanks for the info. So it seems that Cloud Linux Shared is the way to go?

**Comment by usmannasir** [comment]
simple cloudlinux shared, not the pro one.

**Comment by tmunsch** [comment]
Have you seen this? 
https://blog.cloudlinux.com/ubuntu-powered-by-cloudlinux-subsystem-beta-release

**Comment by tmunsch** [comment]
I got an error 
Conversion from Ubuntu is not supported. 
Please, use the ubuntu2cloudlinux.py script to convert to CloudLinux OS

**Comment by tmunsch** [comment]
Wiping it again, installing almalinux testing some things then doing a cloudlinux convert. I'll report back what I find.

**Comment by usmannasir** [comment]
Almalinux is also supported by CyberPanel, I tested on EC2 and there were no errors, I just you are doing some custom settings. We shall stop our discussion here if you want to further disucuss anything please move to community --> https://community.cyberpanel.net/

**Comment by tmunsch** [comment]
I am not doing custom settings, I just did a fresh install using Almalinux and it's the same issue. It seems the installs for lsphp* aren't successful on Almalinux 8 using your script.

**Comment by tmunsch** [comment]
selinux is disabled so that's not it....

**Comment by tmunsch** [comment]
![image](https://user-images.githubusercontent.com/27962004/172450608-18374efc-79b9-4446-bf32-a8b90f57e3a9.png)

**Comment by tmunsch** [comment]
I see the issue now

**Comment by tmunsch** [comment]
This is still an issue, i've tried Centos 8, Almalinux 8, Rocky Linux 8, Cloud linux 8 and none of them install anything into the /lsphp/bin folder. Please FIX THIS!!!!!!!!!!!!!!!

**Comment by usmannasir** [comment]
Record a small video of how you install CyberPanel, let me see it.

**Comment by tmunsch** [comment]
Ummm,
I run dnf update
I install wget and curl
and I run your script
Do you really need a video for that?
If i run it on Ubuntu it works fine, any other OS is a no go

**Comment by tmunsch** [comment]
Do you really think  i don't know how to run a script? This is really starting to frustrate me. Have you even attempted to install it yourself on Almalinux?

**Comment by usmannasir** [comment]
I am not saying that you don't know, it can simply be a human error.

Btw I am sorry regarding Almalinux, just found out that LSPHP had some conflicting packages creating issue.

Run

```dnf install lsphp71* lsphp72* lsphp73* lsphp74* lsphp80* --exclude lsphp73-pecl-zip --exclude *imagick* -y```

After I ran that, I've everything as it should 

```
[root@ip-172-31-6-32 bin]# ls
debugclient  lsphp  pear  peardev  pecl  phar  phar.phar  php  php-cgi  php-config  phpdbg  phpize
[root@ip-172-31-6-32 bin]# pwd
/usr/local/lsws/lsphp74/bin
```

**Comment by tmunsch** [comment]
Well, i just wiped it again to make your video so....

**Comment by usmannasir** [comment]
As I said yesterday I did check on Almalinux and installation went through, but today again by looking further closely I can see that LSPHP packages are not getting installed. If you run the above command it should install required LSPHPs. 

I will check in code to resolve this, sorry for trouble.

**Comment by tmunsch** [comment]
Here is your video you requested
[Here](https://youtu.be/tHn1Of8uNNg)

**Comment by usmannasir** [comment]
Thanks after the install process on alma is done, run 


```dnf install lsphp71* lsphp72* lsphp73* lsphp74* lsphp80* --exclude lsphp73-pecl-zip --exclude *imagick* -y```

**Comment by tmunsch** [comment]
That seems to of worked. Hey, I noticed that you have some installations in the code for WHMCS and a few other applications. Why aren't those on the frontend?

**Comment by tmunsch** [comment]
Thank you for you help btw

**Comment by tmunsch** [comment]
Is there a way to enable the WHMCS install button on the frontend? I noticed it was in [plogical/applicationInstaller.py](https://github.com/usmannasir/cyberpanel/blob/7632b14c122f5b2ce72215d85ba7358141e711e9/plogical/applicationInstaller.py)

**Comment by usmannasir** [comment]
This function is not written by me and I am yet to check if install even works because it also require whmcs key, will have to check.

**Comment by lsthompson** [comment]
We're a WHMCS Reseller, I'm happy to give you a key for the purpose of testing. Let me know @usmannasir - thanks!

**Comment by usmannasir** [comment]
Personally I don't think its worth investing the time, its not like people will be installing WHMCS every day, WordPress on the other hand gets installed every day.

We can have a poll in our fb group, see if masses have interest.

**Comment by lsthompson** [comment]
WHMCS is a fair bit more demanding in terms of the environment too, so makes sense to leave it be.

The offer stands if you later come back to it! We appreciate all that you do for the community.

**Comment by tmunsch** [comment]
K, sounds good. I agree, once you get WHMCS installed its a done deal and all you have to do is setup a database. Thanks again for the help! I really like this project much better now that i can use it lol

**Comment by paulkeys73** [comment]
Hello there, great conversation from great minds. interested in the FB group for CP&WHMCS
i am using WHMCS to manage my web hosting business with CyberPanel and multiple servers. everything works perfectly well
Here's my link https://togetherhosting.com/

@usmannasir was thinking of a BROWSER APP within CyberPanel Control Panel, so users can browse the internet directly from their VPS. this will be a killer i think :)))
