### ISSUE TITLE
[BUG]  mem file

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#896]
When trying to upgrade a clean 2.3.2 version with the bash command below.
I got a strange error message, even if the upgrade continues.

`bash <(curl https://cyberpanel.sh/new_upgrade.sh) -b 2.3.2-dev`

Error:
`/dev/mem: No such file or directory`

![image](https://user-images.githubusercontent.com/4199669/174456392-78617106-b9d2-452e-b37a-44010d7c9842.png)

**Comment by qtwrk** [comment]
it happens when try to access dmidecode to check the server provider , but sometimes some host node doesn't allow such access so it errors out , safe to ignore

**Comment by master3395** [comment]
It was on a hosting provider that restricts things Caught: [Hostinger.com](hostinger.com)
I've had 0 problems with [contabo.com](https://www.kqzyfj.com/click-100276077-1379647)
