### ISSUE TITLE
[BUG] Imunify AV losing permission when update cyberpanel

### ISSUE THREAD

**Issue by Dreamer41** [litespeedtech/cyberpanel#897]
Every time I update cyberpanel after update when try login Imunify AV give message when try login: Can’t connect to agent. Check php part of application.
I get this same issue on multiple server (DO, Vultr, Linode, Oracle) All running on ubuntu 20.04
I did notice on my oracle free where I never did chmod +x, Imunify AV had not run for months. So issue disable Imunify AV after update.

Every time after update need to run below issue permission.
cd /usr/local/CyberCP/public/imunifyav
chmod +x ./bin/execute.py

**To Reproduce**
What steps did you take when the issue occurred? 
1. Install Imunify AV
2. Run cyberpanel update script
3. Try login to Imunify AV dashboard

**Comment by usmannasir** [comment]
Let me check and revert.

**Comment by usmannasir** [comment]
Resolved
