### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PRQAE** [litespeedtech/cyberpanel#899]
I'm facing an issue after upgrading from 2.1 to 2.3.2, when I try to enter cyber panel IP:8090 it shows me PHPMyAdmin without redirect
![Screenshot_1](https://user-images.githubusercontent.com/28864448/175320212-7f4e0d36-dcee-4c05-9278-07d79ea5346f.png)

**Comment by qtwrk** [comment]
what was command you used to upgrade ?

**Comment by PRQAE** [comment]
sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh)

**Comment by loxiry** [comment]
I did a clean install. I have that same problem.

**Comment by qtwrk** [comment]
go delete file /usr/local/CyberCP/public/index.php will bring back the panel access

this seems to be issue with upgrade script , will ask dev to check

**Comment by PRQAE** [comment]
worked for me

**Comment by aprinciple** [comment]
> go delete file /usr/local/CyberCP/public/index.php will bring back the panel access
> 
> this seems to be issue with upgrade script , will ask dev to check

Not only updates, but also installations, this problem is after installing the panel. And installing previous versions doesn't help. On Cent OS, Ubuntu doesn't work, but work on Rocky Linux

I would like to note that the testing of updates is very strange, given that the bug is visible immediately after installation.

**Comment by aprinciple** [comment]
+ When go to phpmyadmin from the admin panel, it shows an error: **Not Found The requested resource was not found on this server.**

**Comment by master3395** [comment]
> I'm facing an issue after upgrading from 2.1 to 2.3.2, when I try to enter cyber panel IP:8090 it shows me PHPMyAdmin without redirect ![Screenshot_1](https://user-images.githubusercontent.com/28864448/175320212-7f4e0d36-dcee-4c05-9278-07d79ea5346f.png)

Have a look here, perhaps this fixes it for you.
https://community.cyberpanel.net/t/how-to-update-phpmyadmin-to-the-latest-version-in-cyberpanel/32224/4

**Comment by master3395** [comment]
> I'm facing an issue after upgrading from 2.1 to 2.3.2, when I try to enter cyber panel IP:8090 it shows me PHPMyAdmin without redirect ![Screenshot_1](https://user-images.githubusercontent.com/28864448/175320212-7f4e0d36-dcee-4c05-9278-07d79ea5346f.png)

You upgraded to 2.3.3-dev most likely.
I just tried that on a clean OS, and it seems that is the landing page if you go to base CP panel, pinging you usman, in case you want to have a look at 2.3.3 (Dev) @usmannasir

**Comment by usmannasir** [comment]
There was an issue yesterday with our DC, now everything is resolved.
