### ISSUE TITLE
[BUG] Imunify AV losing permission when update cyberpanel

### ISSUE THREAD

**Issue by Dreamer41** [litespeedtech/cyberpanel#900]
This same issue was marked fixed before, I just updated multiple server all have same issue again.

Every time I update cyberpanel after update when try login Imunify AV give message when try login: Can’t connect to agent. Check php part of application.
I get this same issue on multiple server (DO, Vultr, Linode, Oracle) All running on ubuntu 20.04
I did notice on my oracle free where I never did chmod +x, Imunify AV had not run for months. So issue disable Imunify AV after update.

Every time after update need to run below issue permission.
cd /usr/local/CyberCP/public/imunifyav
chmod +x ./bin/execute.py

To Reproduce
What steps did you take when the issue occurred?

Install Imunify AV
Run cyberpanel update script
Try login to Imunify AV dashboard
![Screenshot 2022-06-24 161508](https://user-images.githubusercontent.com/106725009/175505329-90f39ba9-6539-4a15-9d60-38bda8e31db6.jpg)

**Comment by usmannasir** [comment]
There was one mistake, resolved now.

Upgrade and try.

**Comment by Dreamer41** [comment]
Confirm problem fixed.
