### ISSUE TITLE
[BUG] Rainloop/SnappyMail sieve

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#904]
Hello.

Not sure if the mail fix works on SnappyMail, I haven't gotten a working SnappyMail on my main domain yet.
Not sure what the problem is, but I have a white page when trying snappymail, and rainloop is still working fine on 2.3.2

I have also tried enabling sieve on my main domain and a clean Centos 7 with 2.3.2 and the sieve refuses to work.

CyberPanel
Current Version :  2.3
Build :  1Current Commit :  9c0f4927ae12589c9e64fd48f841a15ff7027360
Latest Version :  2.3
Latest Build :  2Latest Commit :  6e28128f640a114af26731efb4bda53689b91d64

https://community.cyberpanel.net/t/problems-with-dovecot-in-latest-2-3-1-and-2-3-2-cp/35254/2

**Comment by usmannasir** [comment]
```https://13.48.13.153:8090/snappymail/index.php```

On my test server, works fine.

**Comment by master3395** [comment]
Just updated

Current Version :  2.3
Build :  2Current Commit :  6e28128f640a114af26731efb4bda53689b91d64
Latest Version :  2.3
Latest Build :  2Latest Commit :  6e28128f640a114af26731efb4bda53689b91d64

![image](https://user-images.githubusercontent.com/4199669/175825200-f74734ae-f260-4780-8d3f-09498393f632.png)

![image](https://user-images.githubusercontent.com/4199669/175828117-46f5ceec-b6f0-4f91-a2da-f0b2dd504a2f.png)

**Comment by usmannasir** [comment]
Is it centos 7 ? Man I think its time to  get rid of centos 7. You can try Almalinux.

Also show me 

```ls -la /usr/local/CyberCP/public```

**Comment by master3395** [comment]
> Is it centos 7 ? Man I think it's time to get rid of centos 7. You can try Almalinux.
> 
> Also show me
> 
> `ls -la /usr/local/CyberCP/public`

Been working my way over to AlmaLinux 9, but it takes time, when my Host broke down on OS change yesterday xD
Anyways, below is the location you wanted.

![bilde](https://user-images.githubusercontent.com/4199669/175881838-073b6e8e-7ead-49cd-9b9a-a4c8b5bd1712.png)

**Comment by lsthompson** [comment]
> Been working my way over to AlmaLinux 9

I'm not sure that'd work yet, I'd be deploying onto AlmaLinux 8.x for the time being. 9.x is VERY new.

**Comment by usmannasir** [comment]
I will test on cent7 and revert.

**Comment by master3395** [comment]
> I will test on cent7 and revert.

It works fine on a clean install of Cent7 and CyberPanel 2.3.2, so it's something with my install somehow.
This is why I did a full backup and waiting for my host to fix their OS reinstall issues.

I got CP on 2 different host's with Cent7, only the clean Cent7 works with upgrading to SnappyMail.

**Comment by usmannasir** [comment]
Can you check if something to do with this https://www.youtube.com/watch?v=MfdO_iE5MD4

**Comment by master3395** [comment]
> Can you check if something to do with this https://www.youtube.com/watch?v=MfdO_iE5MD4

The error-logs file has some SSL issues, and with 404.html, but other than that, nothing special.
[05.17.2022_03-00-02] invalid literal for int() with base 10: '/404.html' [calculateBandwidth]
/home/cyberpanel/error-logs.txt
[error-logs.txt](https://github.com/usmannasir/cyberpanel/files/8992161/error-logs.txt)

touch /usr/local/CyberCP/debug (Nothing)
touch /usr/local/CyberCP/emailDebug (Nothing)
![bilde](https://user-images.githubusercontent.com/4199669/175947876-c7e903c8-8ca8-42f7-bfc0-1261c35d4673.png)

This error.log has a few thousand lines of errors, but nothing that really sticks out.
/usr/local/lsws/logs/error.log
![bilde](https://user-images.githubusercontent.com/4199669/175947974-da91ffd6-b314-4064-ba4c-0c1fe0aa0e84.png)
[error.log](https://github.com/usmannasir/cyberpanel/files/8992222/error.log)

**Comment by master3395** [comment]
> > Been working my way over to AlmaLinux 9
> 
> I'm not sure that'd work yet, I'd be deploying onto AlmaLinux 8. x for the time being. 9. x is VERY new.

Didn't detect 9 at all :/
![image](https://user-images.githubusercontent.com/4199669/175991203-138b2516-3699-47cb-bb82-3368d13623d1.png)

**Comment by usmannasir** [comment]
Yes alma 9 is not supported as of yet, will work on it.

**Comment by master3395** [comment]
Alright, i got the URL changed on Almalinux 8, but sadly sieve does still not work D:
https://community.cyberpanel.net/t/problems-with-dovecot-in-latest-2-3-1-and-2-3-2-cp/35254
