### ISSUE TITLE
[BUG] SFTP incremental backup destination missing

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#906]
You can only add AWS to the destination.

CyberPanel
Current Version :  2.3
Build :  1Current Commit :  9c0f4927ae12589c9e64fd48f841a15ff7027360
Latest Version :  2.3
Latest Build :  2Latest Commit :  6e28128f640a114af26731efb4bda53689b91d64

![image](https://user-images.githubusercontent.com/4199669/175790022-e4d4341c-1b64-4e3c-bfbd-3fce4e3da96c.png)

**Comment by usmannasir** [comment]
There is already and issue related to this, sftp for incremental are stopped for now.
