### ISSUE TITLE
[BUG] Minor image missing

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#908]
This image is missing inside domains at the bottom.
Not sure if it has to do with the theme?

/static/images/icons/mautic.png

![image](https://user-images.githubusercontent.com/4199669/176047645-cae1e8f7-7cbf-4639-81a4-7a90341e608c.png)

**Comment by usmannasir** [comment]
Yes works fine in default and the themes I am using on. You can check dark theme by CyberPanel-VJ

**Comment by master3395** [comment]
Just tried.

![bilde](https://user-images.githubusercontent.com/4199669/176127179-db967353-7492-448d-aa7d-b8ec54904ab3.png)

Got the same problem.

![bilde](https://user-images.githubusercontent.com/4199669/176127239-49c8f172-2bae-404b-8ccc-b39a2f559838.png)

**Comment by master3395** [comment]
https://IP:2087/static/images/icons/mautic.png

![bilde](https://user-images.githubusercontent.com/4199669/176127450-ff0c616e-e678-4f10-acc6-3e891030753a.png)

**Comment by master3395** [comment]
OS: Almalinux 8 


Current Version :  
2.3
Build :  
2
Current Commit :  
6e28128f640a114af26731efb4bda53689b91d64
Latest Version :  
2.3
Latest Build :  
2
Latest Commit :  
6e28128f640a114af26731efb4bda53689b91d64

**Comment by usmannasir** [comment]
check now by upgrading

**Comment by master3395** [comment]
Fixed :)
![bilde](https://user-images.githubusercontent.com/4199669/176137304-a7513454-2e00-4542-afc7-a2cc9fe4cfae.png)
