### ISSUE TITLE
SSH Connection for each website

### ISSUE THREAD

**Issue by emresaracoglu** [litespeedtech/cyberpanel#91]
Hi,

Connecting with root only. Isn't it possible to connect to each website's user with a own SSH username?

Thank you.

**Comment by BurakBoz** [comment]
I support this.
Also I have an alternative to fix this issue.

Listing users on centos:
awk -F':' '{ print $1}' /etc/passwd

Usernames on cyberpanel are first 7 characters of domain name.
So 
consider my domain is abcdefgh.com so my username should be **abcdefg**

login ssh to root after that:
$ su abcdefg
$ cd ~/public_html

This will solve the problem but this is only temporary and idiotic solution to every day useage.

**Comment by emresaracoglu** [comment]
Yeah, that makes sense. But after I opened this topic, i changed the server software. Herewith; I've resolved to a server software that I've used before, and I've gone through all my problems right now. 

Cyberpanel had disappointed me in many points. but I like your thought. I want to try this on a new container.

Thank you for idea.

**Comment by usmannasir** [comment]
as @BurakBoz said, each website have its own user created. For security reasons login is disabled. You can log in from Command Line and enable shell access and set a password.
