### ISSUE TITLE
[BUG] upgrade fails 

### ISSUE THREAD

**Issue by devius** [litespeedtech/cyberpanel#912]
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g   -fstack-protector-strong -Wformat -Werror=format-security  -g -fwrapv -O2    -O0 -g3 -I. -I/usr/include/python3.8  -I. -I/usr/include/python3.8  -c -o main.o main.c
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g   -fstack-protector-strong -Wformat -Werror=format-security  -g -fwrapv -O2    -O0 -g3 -I. -I/usr/include/python3.8  -I. -I/usr/include/python3.8  -c -o wsgi.o wsgi.c
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g   -fstack-protector-strong -Wformat -Werror=format-security  -g -fwrapv -O2    -O0 -g3 -I. -I/usr/include/python3.8  -I. -I/usr/include/python3.8  -c -o wsgiinput.o wsgiinput.c
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g   -fstack-protector-strong -Wformat -Werror=format-security  -g -fwrapv -O2    -O0 -g3 -I. -I/usr/include/python3.8  -I. -I/usr/include/python3.8  -c -o wsgiwrapper.o wsgiwrapper.c
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g   -fstack-protector-strong -Wformat -Werror=format-security  -g -fwrapv -O2    -O0 -g3 -I. -I/usr/include/python3.8  -I. -I/usr/include/python3.8  -c -o lsapilib.o lsapilib.c
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g   -fstack-protector-strong -Wformat -Werror=format-security  -g -fwrapv -O2    -O0 -g3 -I. -I/usr/include/python3.8  -I. -I/usr/include/python3.8  -c -o lsapi-glue.o lsapi-glue.c
x86_64-linux-gnu-gcc -pthread -Wl,-Bsymbolic-functions  -Wl,-z,relro -g -fwrapv -O2    -L/usr/lib -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -o lswsgi main.o wsgi.o wsgiinput.o wsgiwrapper.o lsapilib.o lsapi-glue.o -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl  -lutil -lm -lm
chown: cannot access '/usr/local/CyberCP/lib64': No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

Seems something wrong with upgarde, please check...

**Comment by devius** [comment]
I also get this error while trying to access panel through SSL

`root@h:~# curl -I -XGET -k https://127.0.0.1:8090
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
root@h:~#`

**Comment by usmannasir** [comment]
Please check this video: https://www.youtube.com/watch?v=MfdO_iE5MD4&t=1s

It looks like your settings.py does not have correct MySQL passwords, I've explained in this video how you can correct it. I will close this issue if you want to further discuss it use our community forums. https://community.cyberpanel.net/

**Comment by devius** [comment]
You can close this report, but it is not fixing my situation.
All WordPress and hosted websites are working. I am unable to open Admin Panel with SSL, also upgrade process fails because same SSL issue, so video that you linked is not realted to this issue.
