### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by beQuietAndGit** [litespeedtech/cyberpanel#916]
**Describe the bug**
First time using cyberpanel. I cannot list a website. 

**To Reproduce**
1. Click on the "Websites" tab.
2. Click on "Create Website".
3. Website created
4. Click on "list Website".
5. Manage
6. install wordpress+Lite
7. Attempted to install WordPress and received an error.
I'm following jack Cao tutorial: https://www.youtube.com/watch?v=rWlq8e-6ujA

**Expected behaviour**
list a website

**Screenshots**
![2022-07-08_01-05](https://user-images.githubusercontent.com/102356922/177891371-f84cc7bf-dfc3-4b65-83a6-8e7b5649a6c0.png)

**Operating system:**
Ubuntu 20.04

**CyberPanel version:**
2.1.1

**Additional context**
The first time I tried to list I got the error that the folder of the website was not empty. I deleted the website, created it again and then I tried to list again, and the error message was new, the one in the screenshot.

**Comment by usmannasir** [comment]
what is the domain name?

**Comment by beQuietAndGit** [comment]
Now it is giving this error again: Installation failed. Error message: ["Directory is not empty. [404]"]

**Comment by beQuietAndGit** [comment]
I reinstalled ubuntu on the vps and the error is the same.
Now i installed in almalinux and the error is: Installation failed. Error message: [404]

**Comment by beQuietAndGit** [comment]
In another new almalinux instalation i tried to install wordpress. I didn't create a website, just tried to install wordpress.
Website - List Website - Manage (SRV03712488.ULTASRV.COM) - WP + LSCache - filled srv03712488.ultasrv.com Installation Details - [Stress Test](https://go.cyberpanel.net/StessTest)
In path, it doesn't matter if i put something in there or not, i get an error with an empty field or with a folder

**Comment by beQuietAndGit** [comment]
Installation failed. Error message: ["sh: 1: Syntax error: EOF in backquote substitution"," [404]"]

**Comment by beQuietAndGit** [comment]
I got it. The login password cannot have special characters and there must be a folder path.
