### ISSUE TITLE
PhpMyAdmin, snappy mail etc..  running on vulnerable PHP 7.3

### ISSUE THREAD

**Issue by Dreamer41** [litespeedtech/cyberpanel#919]
Any plans update cyberpanel apps and services to run on not deprecated PHP?
This might be serious security issue sooner or later.

![c8ac69549631fe0cf6c8ad132f40999ee3c490ca](https://user-images.githubusercontent.com/106725009/178101489-00c7cd3d-7b2f-4c9a-ab5d-f8133a8a52bd.jpeg)

![8508e510e0e6f37d8998d872b554774dc250242f](https://user-images.githubusercontent.com/106725009/178101470-da7c9926-ee0e-49c2-813f-d26468759b2f.jpeg)

**Comment by Dreamer41** [comment]
Anything on this? Is there some particular reason these need to run on 7.3?

**Comment by Dreamer41** [comment]
@usmannasir @qtwrk Solution made by[ tmoore](https://community.cyberpanel.net/t/how-update-php-version-for-phpmyadmin/36004/2?u=dreamer) on community forum.

 Solution:

The PHP 7.3 binary being used is duplicated at /usr/local/lscp/fcgi-bin/lsphp.

So to change your phpmyadmin version, you can do like I did:

Delete the current binary:
rm -f /usr/local/lscp/fcgi-bin/lsphp

Create symbolic link to the php81 binary where the duplicated binary resided:
ln -s /usr/local/lsws/lsphp81/bin/lsphp /usr/local/lscp/fcgi-bin/lsphp

To change to another version, for example PHP 7.4 instead of 8.1, but replace “lsphp81” with “lsphp74” on the command above.

**Comment by master3395** [comment]
You can change the default php version and test out the desired one you want using the code below :)

![image](https://user-images.githubusercontent.com/4199669/183227725-26aebb77-6fd1-4f61-8fd5-59f23df2e232.png)


Change default php version for CyberPanel apps:

`sh <(curl https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/phpmod.sh || wget -O - https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/phpmod.sh)`

**Comment by Dreamer41** [comment]
> You can change the default php version and test out the desired one you want using the code below :)
> 
> ![image](https://user-images.githubusercontent.com/4199669/183227725-26aebb77-6fd1-4f61-8fd5-59f23df2e232.png)
> 
> Change default php version for CyberPanel apps:
> 
> `sh <(curl https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/phpmod.sh || wget -O - https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/phpmod.sh)`

Problem with that fix you need to re-apply that every time you update cyberpanel.

**Comment by master3395** [comment]
> > You can change the default php version and test out the desired one you want using the code below :)
> > ![image](https://user-images.githubusercontent.com/4199669/183227725-26aebb77-6fd1-4f61-8fd5-59f23df2e232.png)
> > Change default php version for CyberPanel apps:
> > `sh <(curl https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/phpmod.sh || wget -O - https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/phpmod.sh)`
> 
> Problem with that fix you need to re-apply that every time you update cyberpanel.

True, I think the reason CyberPanel went with 7.3 is that it's passed as stable.
As you can see on the EOL, most PHP versions barely get 1 year of support, even so they might still be stable.

And yes latest PHP version might also be unstable and not be fully supported with everything within CyberPanel.

**Comment by Dreamer41** [comment]
@master3395  I have run everything with PHP 8.1 now month and haven't get any issues with it.

**Comment by usmannasir** [comment]
Replaced with php 7.4 until 8.0 or 8.1 is more stable overall.

**Comment by Dreamer41** [comment]
Still php 7.3 after last update. I have manually set 8.1 now from end of July and not noticed any issues.

**Comment by master3395** [comment]
> Still php 7.3 after the last update. I have manually set 8.1 now from the end of July and have not noticed any issues.

Change default php version for CyberPanel apps:
sh <(curl https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/phpmod.sh || wget -O - https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/phpmod.sh)

**Comment by master3395** [comment]
> Still php 7.3 after the last update. I have manually set 8.1 now from the end of July and have not noticed any issues.

I'm running 7.4 on CyberPanel by default, but since 7.4 is also quite old, then I will move to 8.0 on my installation.
Since 8.0 is now put as Stable.
While they work on 8.1 :)
Haven't had any issues with 7.4 either.

**Comment by Dreamer41** [comment]
> I'm running 7.4 on CyberPanel by default.

Check phpMyAdmin after cyberpanel update external apps run still on 7.3 by default. 
It's easy to change but not good for running production server with deprecated php by default and annoying that need fix after every update.
![image](https://user-images.githubusercontent.com/106725009/188809517-435a4854-c5b6-4305-8816-c3e1cd65e6fe.png)

**Comment by ShahniyalRajpoot** [comment]
how to open snappy PhpMyadmin ?
