### ISSUE TITLE
Remote Backup Storage Issue

### ISSUE THREAD

**Issue by BurakBoz** [litespeedtech/cyberpanel#92]
Remote Backup Transfers are all storaged on "/home/backup" directory
**BUT** 
All of this transfer-1234 folders are not used by default backup interface. (So you can't see, delete or restore by the default backup interface but files are exists there.)
I think many people doesn't know this issue.

So these files should be deleted after the transfer on new server to give a space to old server for next backup files will be created.
Also this system should be delete the backup files after restore process on new server to give a free space.
on CyberPanel Current version you can't backup a 50GB server (35GB of it full) because of the current backup system.
Files should be deleted after the transfer (on old server) and after the restore (on new server).

Storage issues should be solved by this way.

Please consider this is a bug. 
I'm having issues on remote backup system. 
You can try this on your self. 
Try to remote transfer 50GB server (35 - 40GB of FULL) to new 50GB server (clean one).
You will understand.

**Comment by BurakBoz** [comment]
Also SSL certificates on origin server are not transfered to new server I'm using cloudflare origin certificates and this is a nightmare to me. 
This should be consider as an optional feature

**Comment by usmannasir** [comment]
Understood your point, recently we released a package where backups are removed locally when they are sent to S3 storage. (https://cyberpanel.net/docs/installing-cyberpanel/)

However, we can not say it is bug since backup deletion is not implemented in your scenario. However, I will take this into consideration and will add it soon.

**Comment by usmannasir** [comment]
Fixed with this commit, will be pushed to new package soon https://github.com/usmannasir/cyberpanel/commit/0399a43830f0b52724ca43c17e0fa2e26d85d5d7
