### ISSUE TITLE
Fresh install/update Fails

### ISSUE THREAD

**Issue by vpsinghbaghel** [litespeedtech/cyberpanel#921]
OS: Ubuntu 20.04
CyberPanel: Latest version. Installed today 2 times.
![image](https://user-images.githubusercontent.com/55743857/178143223-bf4ff189-05e6-42b3-b9aa-d276a01dd4ad.png)

I was getting above error on server while doing update which was installed today itself.
I reinstalled Server OS and installed cyberpanel and run update again.
Received same error in update.
This is happening on a very fresh OS installed and very fresh Cyberpanel installed.

Has cyberpanel stopped supporting Ubuntu 20.04 ?
Such issues have started very recently. Just a few days. Before that everything worked correctly. Probably your new update has got lot of Bugs.

Please check.

Thank You.

**Comment by vpsinghbaghel** [comment]
![image](https://user-images.githubusercontent.com/55743857/178145919-035c158b-d349-447c-a650-806af21155a7.png)
Getting this on a fresh cyberpanel install now on Ubuntu 20.04. It's opening phpmyadmin when trying to open panel on port 8090.

**Comment by qtwrk** [comment]
what's the provider ?   
just tested on NetCup Ubuntu 20.04 , all good on me

**Comment by vpsinghbaghel** [comment]
Provider is Contabo.
This time installation has worked but update has still errors as shown in 1st screenshot above.

**Comment by qtwrk** [comment]
you mean installation works , but upgrade gives wrong page on :8090  ?

**Comment by vpsinghbaghel** [comment]
Please read them sir. 1st message was for update, 2nd was for install.

**Comment by vpsinghbaghel** [comment]
Then I said the installation has worked later but update still has errors.

**Comment by vpsinghbaghel** [comment]
On a freshly installed server, update is getting failed with errors on 1st screenshot.

**Comment by Dreamer41** [comment]
Are you using provider image or install script for installation?

**Comment by vpsinghbaghel** [comment]
I did install from your installation script.

**Comment by usmannasir** [comment]
@vpsinghbaghel there was an issue with missing table, I've resolved that yesterday. Can you try now?

Sorry for the trouble.

**Comment by vpsinghbaghel** [comment]
@usmannasir Thank you for responding and taking care of the issue.
However I tested with running update and received following error:

![image](https://user-images.githubusercontent.com/55743857/178283620-da753ffa-d1f5-4135-a6ff-9c65474dbb7a.png)

This seems to be exactly same error still.
Do I have to reinstall OS again and install fresh cyberpanel?
I hope I don't have to.
Please help.

**Comment by usmannasir** [comment]
Will check and revert tomorrow.

**Comment by usmannasir** [comment]
Do you have a ticket for this issue?

**Comment by vpsinghbaghel** [comment]
Creating ticket has no results sir.
I never got any solution by creating ticket.
So, I prefer raising issue in Github when I am facing any issue due to a bug or any feature related request.
If you say, I will create the ticket just now.

I was running update on another server today which is running CentOS 7 and received same error.
VPS provider was same on this server too.
Error is:
![image](https://user-images.githubusercontent.com/55743857/178919173-d9ed98ee-00c5-4efa-8a9d-fd6523638ea0.png)

**Comment by usmannasir** [comment]
Resolved this, please check

**Comment by vpsinghbaghel** [comment]
Thank you very much. :)
