### ISSUE TITLE
ServerAdmin value on SSL configuration is wrong

### ISSUE THREAD

**Issue by BurakBoz** [litespeedtech/cyberpanel#93]
I created a host and find out this issue.
On vHost configuration 443 settings are all ways is your email

**ServerAdmin usman@cyberpersons.com**

<VirtualHost *:80>

	ServerName myownsite.com
	ServerAlias www.myownsite.com
	ServerAdmin myownsite@myownemail.com
	SuexecUserGroup myown myown
	DocumentRoot /home/myownsite.com/public_html
	CustomLog /home/myownsite.com/logs/myownsite.com.access_log combined
	AddHandler application/x-httpd-php73 .php .php7 .phtml

</VirtualHost>

# Do not modify this file, this is auto-generated file.

<VirtualHost *:443>

	ServerName myownsite.com
	ServerAlias www.myownsite.com
	**ServerAdmin usman@cyberpersons.com**
	SuexecUserGroup myown myown
	DocumentRoot /home/myownsite.com/public_html
	CustomLog /home/myownsite.com/logs/myownsite.com.access_log combined
	SSLEngine on
	SSLVerifyClient none
	SSLCertificateFile /etc/letsencrypt/live/myownsite.com/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/myownsite.com/privkey.pem
	AddHandler application/x-httpd-php73 .php .php7 .phtml
</VirtualHost>

**Comment by usmannasir** [comment]
Did you update your account email? Probably take an email from currently logged in user.

**Comment by BurakBoz** [comment]
Yes I did. Port 80 configuration changed to myownsite@myownemail.com and 443 was still usman@cyberpersons.com

**Comment by usmannasir** [comment]
I will try to reproduce.

**Comment by usmannasir** [comment]
Can't reproduce on my end. It seems to pick up the right email. Try deleting the existing configurations within `<VirtualHost *:443>` and then re-issue SSL, make sure your account email is also updated.
