### ISSUE TITLE
[BUG] MailWatch unable to detect that MailScanner is running or tally the children processes; Latest script also causes scanned emails to not be listed

### ISSUE THREAD

**Issue by hifihedgehog** [litespeedtech/cyberpanel#930]
References https://github.com/mailwatch/MailWatch/issues/1254. Note ticket #ZY5NQ2DNI in the CyberPersons ticket system. The latest script also appears to have broken the viewing of the scanned email queue in MailWatch.

**Comment by hifihedgehog** [comment]
Found one issue. @usmannasir, Dovecot has deprecated and removed the autocreate plugin. Perhaps this is it?

**Comment by usmannasir** [comment]
I've added some comments here https://github.com/mailwatch/MailWatch/issues/1254

We can continue there as it contains more info.
