### ISSUE TITLE
Gdrive Backup

### ISSUE THREAD

**Issue by vpsinghbaghel** [litespeedtech/cyberpanel#931]
In Google Drive backup page:
If we set multiple sites for g drive backup and it fills more than 1 page. When we click to view 2nd page or click to view 1st page again, I see following error:
![image](https://user-images.githubusercontent.com/55743857/179816457-35dc055b-e9b3-4a5e-82b5-b27c734c84d3.png)
It shows invalid character. Probably for page number.
Please check.

Thank you.

**Comment by usmannasir** [comment]
There is dash in your drive name `-` remove that.

**Comment by vpsinghbaghel** [comment]
removed and created again. Now the name is as in pic below. But issue remains same.
![image](https://user-images.githubusercontent.com/55743857/180173765-50ffa177-659d-4c4d-a94f-df6742701285.png)

It's not because the - in name. Its something else. Please check.

**Comment by usmannasir** [comment]
Will try to reproduce and let you know.

**Comment by usmannasir** [comment]
resolved

**Comment by vpsinghbaghel** [comment]
Do I have to update cyberpanel for changes to take effect ?

**Comment by vpsinghbaghel** [comment]
I have updated the panel and problem is fixed. Thanks a lot for your prompt support. :)
