### ISSUE TITLE
[BUG]Postfix wont start automatically on server reboot

### ISSUE THREAD

**Issue by Dreamer41** [litespeedtech/cyberpanel#932]
**Describe the bug**
Postfix wont start automatically on server reboot and mail stop working, even on cyberpanel it show running when toggle off/on mail start working.

**To Reproduce**
What steps did you take when the issue occurred? 
1. SSH reboot
2. SSH: postfix status
3. result
postfix: Postfix is running with backwards-compatible default settings
postfix: See http://www.postfix.org/COMPATIBILITY_README.html for details
postfix: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
/usr/sbin/postconf: warning: /etc/postfix/master.cf: undefined parameter: mua_sender_restrictions
/usr/sbin/postconf: warning: /etc/postfix/master.cf: undefined parameter: mua_client_restrictions
/usr/sbin/postconf: warning: /etc/postfix/master.cf: undefined parameter: mua_helo_restrictions
/usr/sbin/postconf: warning: /etc/postfix/master.cf: undefined parameter: mua_sender_restrictions
/usr/sbin/postconf: warning: /etc/postfix/master.cf: undefined parameter: mua_client_restrictions
/usr/sbin/postconf: warning: /etc/postfix/master.cf: undefined parameter: mua_helo_restrictions
/usr/sbin/postconf: warning: /etc/postfix/main.cf: undefined parameter: virtual_mailbox_limit_maps
/usr/sbin/postconf: warning: /etc/postfix/main.cf: unused parameter: virtual_create_maildirsize=yes
/usr/sbin/postconf: warning: /etc/postfix/main.cf: unused parameter: virtual_maildir_extended=yes
postfix/postfix-script: the **Postfix mail system is not running**

**Operating system:**
Ubuntu 20.04

**CyberPanel version:**
Current Version:  2.3
Build:  2
Current Commit:  76b463acb21d2e148aad0ba240de0bd38c8eb72b

**Comment by usmannasir** [comment]
Can not reproduce this issue, seems fine on our end

```
postfix.service - Postfix Mail Transport Agent
     Loaded: loaded (/lib/systemd/system/postfix.service; enabled; vendor preset: enabled)
     Active: active (exited) since Thu 2022-07-21 10:03:41 UTC; 6min ago
    Process: 1127 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
   Main PID: 1127 (code=exited, status=0/SUCCESS)

Jul 21 10:03:41 ip-172-26-8-84 systemd[1]: Starting Postfix Mail Transpor
```
