### ISSUE TITLE
FileManager cannot download php files

### ISSUE THREAD

**Issue by BurakBoz** [litespeedtech/cyberpanel#94]
In file manager php files are showing parsed results and not downloadable php source code.
for example put a test.php in your public_html folder
test.php
`<?php echo "the parsed result"; ?>`
Try to download test.php file via file manager you will see only the "the parsed result" text.

**Comment by hifihedgehog** [comment]
Same here. I believe this issue may have been introduced when they switched over fully to Litespeed for the backend serving. As it is, the only way to download php files is to use an FTP client at the moment.

**Comment by jordanlambrecht** [comment]
@BurakBoz This is confirmed fixed as of v2.0.0 Stable: 

<img width="423" alt="Screen Shot 2021-02-05 at 6 38 54 PM" src="https://user-images.githubusercontent.com/54866853/107102926-8153fe00-67e1-11eb-9f8e-96a36f30d201.png">

Please close your issue to help keep the Issue backlog clean.

**Comment by istiak101** [comment]
This is resolved. Can you please close this @usmannasir @whattheserver ?
