### ISSUE TITLE
[BUG] Problems with failover on almalinux 8

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#941]
This happens if i install Docker on Almalinux 8
You get this error every time you use yum.
Yum was working fine before I installed CyberPanel.

`Invalid configuration value: failovermethod=priority in /etc/yum.repos.d/litespeed.repo; Configuration: OptionBinding with id "failovermethod" does not exist`

I had to use this tutorial to remove it.
https://communicode.io/how-to-fix-failovermethod-error-fedora/

![image](https://user-images.githubusercontent.com/4199669/182875946-b8216185-255d-40c5-8743-486e064c9daf.png)

**Comment by usmannasir** [comment]
You followed the correct tutorial to remove it.
