### ISSUE TITLE
[BUG] Missing php 8.1?

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#942]
I get this error when i try to switch default apps to PHP 8.1
I do have 8.1 folder with files in it, but it can only respond to 8.0 for some reason.

`ERROR! Missing php 8.1? Check if /usr/local/lsws/lsphp81 exists.`

![image](https://user-images.githubusercontent.com/4199669/183227841-ec4c2af9-5136-42c0-b6c5-2cac69ccfd3d.png)

![image](https://user-images.githubusercontent.com/4199669/183227868-f89afe7b-08fa-4725-b7ed-f947650e477c.png)

**Comment by usmannasir** [comment]
Is this alma or rocky?

**Comment by usmannasir** [comment]
I pushed a commit

**Comment by master3395** [comment]
> Is this alma or rocky?

It is Almalinux 8.6 :)
Just so you have it on record.

Just updated my test site to 2.3.3-dev

![image](https://user-images.githubusercontent.com/4199669/183302534-5e34dcd5-7b03-4edc-beb5-a93eb16f7f00.png)

```
Current Version:  2.3
Build:  2Current Commit:  148f9f055a122801ea8dc6dc7dd2a60d577863c7
Latest Version:  2.3
Latest Build:  2Latest Commit:  d617e48d37b9f7bb65ffa6a23547bd8a9a99853e
```

It does still say

```
Choose one of the following php versions [71-72-73-74-80-81]: 81
ERROR! Missing php 8.1? Check if /usr/local/lsws/lsphp81 exists.
```

**Comment by usmannasir** [comment]
I've installed AlmaLinux and PHP 8.1 seems fine

<img width="1440" alt="Screenshot 2022-08-09 at 9 42 26 AM" src="https://user-images.githubusercontent.com/17538454/183565915-de8c59cb-6c81-42e1-801e-1e97554e7e3e.png">

**Comment by master3395** [comment]
Changing it to 8.1 seems to fail.
It will stay at 8.0

List website > Manage > Php
![Skjermbilde 2022-08-09 090011](https://user-images.githubusercontent.com/4199669/183585085-b76284f6-61be-4004-a0ab-a09f6de7fde3.png)

Website manager: Php
![bilde](https://user-images.githubusercontent.com/4199669/183584967-9c5f9da6-12e4-4481-90f1-aa007207837b.png)

![bilde](https://user-images.githubusercontent.com/4199669/183585686-8548d995-276c-448e-af37-7b5b9b3ec421.png)

**Comment by usmannasir** [comment]
Let me check

**Comment by usmannasir** [comment]
It took few seconds, however, successfully changed to PHP 8.1 on my end.

**Comment by master3395** [comment]
> It took a few seconds, however, successfully changed to PHP 8.1 on my end.

How come it works on your end and not mine?

I changed the domain PHP to 8.1 and clicked restart PHP under PHP configuration, just to be sure.
Waited 5 minutes, and still 7.4
![bilde](https://user-images.githubusercontent.com/4199669/183833624-006fee86-5328-4055-82dc-421baf6ff6ce.png)

![bilde](https://user-images.githubusercontent.com/4199669/183833583-e0e2cce1-b267-4cbd-98b8-e615fb7df87d.png)

![bilde](https://user-images.githubusercontent.com/4199669/183833782-a6e199dd-e706-4045-bcf3-b37b8f95a72f.png)

**Comment by master3395** [comment]
I just checked the error log.

This is what it gave me when I changed it to 8.1
Not sure why it mentioned cmstest.newstargeted.com when I clearly tried it on newstargeted.com

`2022-08-10 08:58:22.422347 [INFO] [1820745] [newst12767778.655340]: locked pid file [/tmp/lshttpd/newst12767778.sock.pid].
2022-08-10 08:58:22.422460 [INFO] [1820745] [newst12767778.655340] remove unix socket for detached process: /tmp/lshttpd/newst12767778.sock
2022-08-10 08:58:22.422786 [NOTICE] [1820745] [LocalWorker::workerExec] VHost:cmstest.newstargeted.com suExec check uid 65534 gid 65534 setuidmode 0.
2022-08-10 08:58:22.422892 [NOTICE] [1820745] [LocalWorker::workerExec] Config[newst12767778.655340]: suExec uid 5005 gid 5005 cmd /usr/local/lsws/lsphp73/bin/lsphp, final uid 5005 gid 5005, flags: 0.
2022-08-10 08:58:22.426439 [NOTICE] [1820745] [newst12767778.655340] add child process pid: 2752612
2022-08-10 08:58:22.426564 [INFO] [1820745] [newst12767778.655340]: unlocked pid file [/tmp/lshttpd/newst12767778.sock.pid].`

**Comment by master3395** [comment]
I just tried on all my subdomains also.
Non of them change the PHP version.
Only the root domain does.

https://Ip:port/websites/newstargeted.com/cmstest.newstargeted.com - 7.3 (Created with 7.3) tried changing it first to 7.4 waited 10 min, then switched to 8.0 then waited 10 min, then switched to 8.1.

It does not change at all, it's stuck on 7.3
No matter if I try to change it from the master domain "sub-domain list" or from cyberpanel list websites.
No changes at all.

If I change the vhost file, it does change to the new PHP (But not 8.1, 8.1 makes the whole page just go white)

This is the full error log in cyberpanel
![image](https://user-images.githubusercontent.com/4199669/184164516-2cd29c06-3ef9-4dda-8d1d-a9bf3f4febc0.png)

CyberPanel Main log is just printed with let's encrypt 
![image](https://user-images.githubusercontent.com/4199669/184165055-c6101a63-7136-4912-8930-3dcc536bd738.png)

https://Ip:port/serverlogs/errorLogs
![image](https://user-images.githubusercontent.com/4199669/184164412-32909d63-6bb6-4b75-bbce-adb6b1b0b2dc.png)

**Comment by master3395** [comment]
On my main log files

Such as here:
/home/newstargeted.com/logs/newstargeted.com.error_log

I now get the error below.
If I manually switch the PHP version in vhost from 73 to 80

MIME type [application/x-httpd-php] for suffix '.php' does not allow serving as static file, access denied!

**Comment by master3395** [comment]
8.1 is missing from php extensions.

Below is the default installed extensions.
If I install lsphp81 from that page, then I can go into the host and manually change it to 81
![Skjermbilde 2022-08-11 220729](https://user-images.githubusercontent.com/4199669/184236468-5913a4f3-4fe0-48d0-8c59-5b4ab5302011.jpg)

Below is the cmsmstest.newstargeted.com with lsphp81 installed.
And changed manually in vhost because the change PHP buttons does not work for 81, even if I install the extension.
![image](https://user-images.githubusercontent.com/4199669/184236740-10b3ae51-354f-4855-9c4c-72b931a1865a.png)

**Comment by master3395** [comment]
You need to re-open this @usmannasir It's still an issue on all CyberPanel versions where 8.1 is present.
