### ISSUE TITLE
[BUG] Backups remove my VS Code settings, extensions etc... 

### ISSUE THREAD

**Issue by nickchomey** [litespeedtech/cyberpanel#943]
When you connect to your server with VS Code through SSH, it creates a folder called /home/[site]/.vscode which stores various things like settings and extensions. It appears that this directory is not backed up, so it does not get restored. 

Is it possible to either add this to the backup or allow us to manually configure which directories are backed up from the control panel?

**Comment by nickchomey** [comment]
Moreover, I have to reset my git settings (email and username) after restoring a backup...

**Comment by usmannasir** [comment]
Yes, CyberPanel stores `public_html` folder, and unfortunately this will not be going to change soon.

You can connect the vscode to public_html.

**Comment by nickchomey** [comment]
I am connecting to the `public_html` folder. The problem is that when you connect using the vhost username, it brings you to the root directory first and creates the .`vscode` folder there.

**Comment by usmannasir** [comment]
Oh, I see.

But unfortunately right now it is not possible to include folders outside `public_html`

**Comment by nickchomey** [comment]
No problem - i totally understand. Thanks for the response.
