### ISSUE TITLE
Rainloop/SnappyMail

### ISSUE THREAD

**Issue by vpsinghbaghel** [litespeedtech/cyberpanel#944]
![image](https://user-images.githubusercontent.com/55743857/184449357-83ff2f86-ca8e-426e-bc39-347538666598.png)

Getting this error when login to webmail after cyberpanel update.
OS: CentOS 7.
Cyberpanel: today updated to latest.
Everything was working perfect before update.

**Comment by usmannasir** [comment]
I would request that post something like this in our FB group or community.
