### ISSUE TITLE
[BUG] redis-server.service: Job redis-server.service/start failed with result 'dependency'.

### ISSUE THREAD

**Issue by namen3645** [litespeedtech/cyberpanel#948]
1. Go to control panel -> manageservices -> manageApplications
2. Install redis
3. Get error:
`
root@bob:~# sudo systemctl status redis-server
● redis-server.service - Advanced key-value store
     Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/redis-server.service.d
             └─override.conf
     Active: failed (Result: protocol) since Wed 2022-08-17 09:29:32 UTC; 8min ago
       Docs: http://redis.io/documentation,
             man:redis-server(1)
   Main PID: 82616 (code=exited, status=0/SUCCESS)
        CPU: 1ms

Aug 17 09:29:32 bob systemd[1]: Starting LSB: redis-server - Persistent key-value db...
Aug 17 09:29:32 bob systemd[1]: redis-server.service: Failed with result 'protocol'.
Aug 17 09:29:32 bob systemd[1]: Failed to start LSB: redis-server - Persistent key-value db.
Aug 17 09:30:51 bob systemd[1]: Dependency failed for Advanced key-value store.
Aug 17 09:30:51 bob systemd[1]: redis-server.service: Job redis-server.service/start failed with result 'dependency'.
Aug 17 09:36:22 bob systemd[1]: Dependency failed for Advanced key-value store.
Aug 17 09:36:22 bob systemd[1]: redis-server.service: Job redis-server.service/start failed with result 'dependency'.

For the second day I have been looking for what kind of redis dependencies in google and I can not find anything`

**Comment by qtwrk** [comment]
Ubuntu 20.04?

**Comment by namen3645** [comment]
yes

**Comment by fresent** [comment]
We had this issue when our disk got full.
It automatically started to work, once disk was cleaned up.
Might be worth to see you aren't running into disk issue.
