### ISSUE TITLE
Installation centos7 [BUG]

### ISSUE THREAD

**Issue by mr2aminul** [litespeedtech/cyberpanel#949]
**Describe the bug**

systemtap-devel.x86_64 0:4.0-13.el7       systemtap-runtime.x86_64 0:4.0-13.el7                trousers.x86_64 0:0.3.14-2.el7

Complete!
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting virtualenv==16.7.9
  Downloading https://files.pythonhosted.org/packages/05/f1/2e07e8ca50e047b9cc9ad56cf4291f4e041fa73207d000a095fe478abf84/virtualenv-16.7.9-py2.py3-none-any.whl (3.4MB)
    100% |████████████████████████████████| 3.4MB 273kB/s
Installing collected packages: virtualenv
Successfully installed virtualenv-16.7.9
--2022-08-20 13:22:25--  https://raw.githubusercontent.com/usmannasir/cyberpanel/v8.0.30/requirments.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-08-20 13:22:25 ERROR 404: Not Found.

 Requirement list has failed to download for 1 times...
Wait for 30 seconds and try again...

--2022-08-20 13:22:55--  https://raw.githubusercontent.com/usmannasir/cyberpanel/v8.0.30/requirments.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-08-20 13:22:56 ERROR 404: Not Found.

 Requirement list has failed to download for 2 times...
Wait for 30 seconds and try again...

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occurred? 
1. Ex.: Click on the "Websites" tab.
2. Ex.: Click on "Create Website".
3. Ex.: Attempted to create a website and received an error.

**Expected behavior**
I think githum file is missing.
I have visit the link. It says 404: Not Found
https://raw.githubusercontent.com/usmannasir/cyberpanel/v8.0.30/requirments.txt
--2022-08-20 13:46:18--  https://raw.githubusercontent.com/usmannasir/cyberpanel/v8.0.30/requirments.txt

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://prnt.sc/Fr7n6ioT2bBa)

**Operating system:**
Please enter your answer here (e.g. Centos 7.9)

**CyberPanel version:**
Please enter your answer here (e.g. 2.3.2).

**Comment by qtwrk** [comment]
this link , https://raw.githubusercontent.com/usmannasir/cyberpanel/v8.0.30/requirments.txt


it should be like `/cyberpanel/v2.3.2/requirments.txt`


 I wonder how it gets v8.0.30 

run `curl -4 https://cyberpanel.net/version.txt`   , what does it show ?

**Comment by mr2aminul** [comment]
{"version":"2.3","build":2}
[https://prnt.sc/swwy6zHmzCwK](url)

**Comment by qtwrk** [comment]
try a clean system 

then do  

`yum install curl wget` 

after that , do 

`curl -o cyberpanel.sh https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/cyberpanel.sh`

then run `script /root/debug.log` and finally run `bash -x cyberpanel.sh`  follow the prompt until it errors out.

**Comment by mr2aminul** [comment]
Thanks
