### ISSUE TITLE
Bug whmcs API ACCESS DISABLED for customers

### ISSUE THREAD

**Issue by patricknasci** [litespeedtech/cyberpanel#95]
**- Whmcs client central click "Login to Panel"** 

![Screenshot_20190602_234743](https://user-images.githubusercontent.com/11508790/58772916-833bd780-8591-11e9-90b8-cdae0c420f12.png)

**- Receive this error message:**

![image](https://i.imgur.com/8LpFrnJ.png)

**Clients can not access the API but need to automatically log in to the panel.**

**Comment by usmannasir** [comment]
Going to release a default option for API access soon.

**Comment by neoricalex** [comment]
Thanks @usmannasir !
+1 Here waiting this update
