### ISSUE TITLE
Official Support for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by sherlock7402** [litespeedtech/cyberpanel#952]
Hi, 

as far as I noticed, Cyberpanel could not support Ubuntu 22.04 LTS yet, because Litespeed did not offer support yet. Good news: This is now no longer the case :smile:

https://docs.litespeedtech.com/lsws/extapp/php/getting_started/

Please add an official support, thank you!

**Comment by usmannasir** [comment]
We will be definitely supporting this now.

**Comment by Dreamer41** [comment]
Any update on this?

**Comment by usmannasir** [comment]
Check branch v2.3.3-dev, already working on this. There are some issues I am addressing

**Comment by CyberFlameGO** [comment]
Sweet, am hyped for this!!

**Comment by militaryk** [comment]
I'm rooting it on!! cant wait.

**Comment by shyton** [comment]
I am impatiently waiting for it 😍

**Comment by TopSecretGamingsWINS** [comment]
I am also impatiently waiting for it 😍😍😍

**Comment by CyberFlameGO** [comment]
Seems to've been merged recently :)

**Comment by shyton** [comment]
When will the stable and final v2.3.3 version be released?

**Comment by usmannasir** [comment]
@shyton very soon. Can't tell exact ETA as few things which are currently out of our hands, but soon.

**Comment by CyberFlameGO** [comment]
Is there a ballpark of some sort you can give? e.g. a week, month, or year?

**Comment by Dreamer41** [comment]
@CyberFlameGO 
> Is there a ballpark of some sort you can give? e.g. a week, month, or year?

Probably month definitely not year.. I installed already cyberpanel on 22.04 at test server and my short testing it installed and was running. Just wont dare to launch new servers on 22.04 before official support confirmed.

**Comment by usmannasir** [comment]
There is some problem in LSCPD, LSCPD is developed by LiteSpeed core team, once that issue is resolved I can tell you guys the ETA.

Right now installation is going through.

**Comment by CyberFlameGO** [comment]
Ah yup okay, thanks!

**Comment by usmannasir** [comment]
**Update:** As of today CyberPanel install/upgrade is now working fine on Ubuntu 22, will continue to test other functions.

**Comment by mshastchi** [comment]
How to upgrade?

**Comment by usmannasir** [comment]
Don't its not production ready yet. Only for testing purposes, check our docs for installing development versions.

Also don't make the mistake of upgrading Ubuntu 20 to 22

**Comment by mshastchi** [comment]
I have done the second mistake already! but OK I would not do the first one

**Comment by therealgilles** [comment]
The script already says 22.04 is supported:

```
CyberPanel is supported on x86_64 based Ubuntu 18.04, Ubuntu 20.04, Ubuntu 20.10, Ubuntu 22.04, CentOS 7, CentOS 8, AlmaLinux 8, RockyLinux 8, CloudLinux 7, CloudLinux 8, openEuler 20.03, openEuler 22.03
```

but the code itself does not have 22.04 so the install script errors out – which I guess is better for now.

**Comment by usmannasir** [comment]
@therealgilles it is already supported on Ubuntu 22.04 on `v2.3.3-dev` branch

**Comment by Vladdov** [comment]
Hello.
What is at least approximately the timing of the release of the official release with support for Ubuntu 22.04? I want to start making a website so that I don't have to reinstall the server later. I'm looking forward to it. Thank you.

**Comment by usmannasir** [comment]
I've merged the Ubuntu 22 code to current stable branch. 

If anyone still face issues they can reach out to us.

**Comment by mshastchi** [comment]
@usmannasir 
I had a working CyberPanel in Ubuntu 20 now I have updated to Ubuntu 22 I should upgrade the CyberPanel or install?
