### ISSUE TITLE
Email Forwarding to Pipe not working due Permission denied

### ISSUE THREAD

**Issue by TuxADN** [litespeedtech/cyberpanel#954]
Hello friends,
I need some help getting email piping to work please.
I've configured an email address to forward incoming emails to a pipe program.
The email is received and processed by Postfix, gets a Permission denied error, and it finally gets to the queue for later retry.

Email Log:

```
Aug 25 21:07:52 mail postfix/qmgr[754997]: 6D6DB401362: from=<external.user@gmail.com>, size=5458, nrcpt=1 (queue active)
Aug 25 21:07:52 mail postfix/pipe[791543]: 6D6DB401362: to=<my_email@domain.com>, relay=my_emailpipe, delay=1044, delays=1044/0/0/0.01, dsn=4.3.0, status=deferred (temporary failure. Command output: pipe: fatal: pipe_command: execvp /home/domain.com/public_html/pipe.php: Permission denied )
```

Pipe program is chmod 755 executable:

```
# ls -la /home/domain.com/public_html/pipe.php
-rwxr-xr-x 1 domai1234 domai1234 468 Mar  9  2021 /home/domain.com/public_html/pipe.php
```

This CyberPanel instance is running on Ubuntu 20.04
Your help is appreciated.

**Comment by usmannasir** [comment]
I think it is not working because the parent directory does not have executable permissions.

**Comment by TuxADN** [comment]
Solved it.
Acatually what needs to be done is to modify postfix master.cf

Ensure what user and group the script is owned by:

`ls -la /home/domain.name/path_to_script_folder`

Modify master.cf

`nano /etc/postfix/master.cf`


Modify the pipe line with the command to execute:

```
change:
user=adminuser
to:
user=scriptuser:scriptgroup
```

Restart postfix

`service postfix restart`

Wonder if this (specify the script userowner:group or to use the current folder userowner:group where the script is located) is some selection that can be added in the Create new Forwarding to Pipe form in CyberPanel.
(Feature request?)

Hope it helps anyone else, let me know.

**Comment by usmannasir** [comment]
Can you show your whole master.cf file?

**Comment by TuxADN** [comment]
At the very end it's located the line added by CyberPanel when creating the Forward to Pipe:

namepipe unix - n n - - pipe flags=Rq user=user6493:user6493  argv=/home/domain.name/public_html/pipe.php -f  $(send>

**Comment by usmannasir** [comment]
OK. I will check and close this.
