### ISSUE TITLE
[BUG] System users don't get deleted when you delete a website

### ISSUE THREAD

**Issue by nickchomey** [litespeedtech/cyberpanel#955]
If you delete a website, its /home/ directory gets removed but the user doesn't. 

You can see this by running ` cat /etc/passwd` which will show all the users

Or you could enter `su - [first 5 characters of username]` and press tab twice - it will show all the users that have that prefix 

e.g.
```
root@vps:~# su - nickc
nickc1281  nickc8768  nickc9697  nickc9700
```

All of these exist because I've recreated a website for the same domain many times - each time it generates a new user with a unique 4 digits at the end.

**Comment by nickchomey** [comment]
Now that I look closer, I see that systemusers for most domains/websites have been deleted - these are just orphans. I don't know what would have caused it, but it is worth investigating

**Comment by usmannasir** [comment]
Let me check

**Comment by usmannasir** [comment]
```
[root@ip-172-31-15-45 home]# ls -la
total 0
drwx--x--x.  8 root       root       125 Sep  5 11:45 .
dr-xr-xr-x. 18 root       root       281 Sep  5 11:32 ..
drwx------.  2 cyberpanel cyberpanel 215 Sep  5 11:46 cyberpanel
drwx------.  2 docker     docker      62 Sep  5 11:31 docker
drwx------.  3 ec2-user   ec2-user    74 Sep  1 11:13 ec2-user
drwx--x--x.  5 stagi7610  stagi7610   52 Sep  5 11:44 staging.cyberpanel.net
drwx--x--x.  5 usman1716  usman1716   52 Sep  5 11:45 usman.cyberpanel.net
drwx------.  2 vmail      vmail       62 Sep  5 11:36 vmail```

Now after deleting `usman.cyberpanel.net`

```
[root@ip-172-31-15-45 home]# ls -la
total 0
drwx--x--x.  7 root       root        97 Sep  5 11:48 .
dr-xr-xr-x. 18 root       root       281 Sep  5 11:32 ..
drwx------.  2 cyberpanel cyberpanel 215 Sep  5 11:46 cyberpanel
drwx------.  2 docker     docker      62 Sep  5 11:31 docker
drwx------.  3 ec2-user   ec2-user    74 Sep  1 11:13 ec2-user
drwx--x--x.  5 stagi7610  stagi7610   52 Sep  5 11:44 staging.cyberpanel.net
drwx------.  2 vmail      vmail       62 Sep  5 11:36 vmail
[root@ip-172-31-15-45 home]# cat /etc/passwd | grep usman
[root@ip-172-31-15-45 home]#
```

User is properly deleted.
