### ISSUE TITLE
DNS server not working

### ISSUE THREAD

**Issue by RitZz48** [litespeedtech/cyberpanel#957]
Current Version:  2.3
Build:  2Current Commit:  d617e48d37b9f7bb65ffa6a23547bd8a9a99853e

Cyberpanel DNS is not running. 
![image](https://user-images.githubusercontent.com/102799834/187474338-2d3cdb0b-2a34-453c-9355-da0f7b32bbd5.png)

The server above is running a different panel. 
I tried restarting the server with no luck.

**Comment by RitZz48** [comment]
Bump

**Comment by usmannasir** [comment]
kindly open configuration related issues on our Facebook group or community.

There seems to be a configuration issue on your server.
