### ISSUE TITLE
Git not working for private repo

### ISSUE THREAD

**Issue by yodyyyy** [litespeedtech/cyberpanel#96]
I already setup the webhooks and adding the ssh keys, but not pulled. Also check in settings, seems the key indicator not changed to green while pulling.
![image](https://user-images.githubusercontent.com/8794792/59158996-31dd9c00-8aed-11e9-8f82-f5012bb09edd.png)

**Comment by usmannasir** [comment]
Did you add the keys at an account level, such as here `https://github.com/settings/keys`.

**Comment by yodyyyy** [comment]
Yes i add the keys, same as the picture above

**Comment by yodyyyy** [comment]
![image](https://user-images.githubusercontent.com/8794792/59187198-19c65500-8b9f-11e9-9d38-45d12d20d6a4.png)

**Comment by usmannasir** [comment]
The directory you are attaching to is completely empty? There must not be a single file there.

**Comment by yodyyyy** [comment]
Still not working
![image](https://user-images.githubusercontent.com/8794792/59187377-86d9ea80-8b9f-11e9-9668-408f4cae8945.png)
![image](https://user-images.githubusercontent.com/8794792/59187421-9d804180-8b9f-11e9-8aec-e6b432f5cce0.png)
![image](https://user-images.githubusercontent.com/8794792/59187438-a709a980-8b9f-11e9-9946-f9f783594f64.png)

![image](https://user-images.githubusercontent.com/8794792/59187485-c1dc1e00-8b9f-11e9-8d60-00ad4a803b09.png)

**Comment by usmannasir** [comment]
What is your OS? On my end it seems to work, maybe your git version is too old, or git not able to install. You can try creating a ticket.

**Comment by yodyyyy** [comment]
Centos 7

I logged in to domain ssh, and doing clone, key seems not work too.
![image](https://user-images.githubusercontent.com/8794792/59188793-b1797280-8ba2-11e9-9b75-4951b830335d.png)

**Comment by usmannasir** [comment]
Kindly submit your ticket to -> https://platform.cyberpanel.net/

**Comment by jovaniedelacruz** [comment]
I'm having this same issue as the screenshot above. in ssh can't clone and right after succesfully linking the git repo it deletes the public_html folder. I went in and remade it and then tried the ssh clone command again but that shows me the same "permission denied (public key)" error. Maybe it's something with how the keys are generated? The key keeps saying it's never been used to maybe it's being generated but not saved/associated to the right website in cyberpanel.

**Comment by jovaniedelacruz** [comment]
got it to finally clone but I had to ssh into root@panel.x and do "ssh-keygen" and use the .pub key generated. This does not solve the issue. Just shows that it's possible for git clone to work but not currently on 1.9 on CentOS 7.6 through the cyberpanel web ui. However, because this was done as root, I do not think the webhooks to auto pull after a push work at all. Did some test pushs of my repo and they are delivered according to GitHub but I don't see any of the changes in CyberPanel.

**Comment by daheadcracker** [comment]
I'm having the same issue. Working with a private gitlab repo. Tried setting the ssh key on repo and profile level. Deleting everything inside the websites folder (although the .ssh folder is beeing created again after refreshing the "setupGit" page in cyberpanel - but this belongs there I guess). Cloned the repo by myself via ssh (this worked btw only when adding `.git` to the repo url - but pushes to the repo are still not getting pulled although the webhook is properly integrated in gitlabs "settings/integrations"). Then tried adding the `.git` extension to the repo name on the "setupGit" page, but this also didn't work.

Cyberpanel is just not pulling/cloning anything although it says so in the loading animation while setting up.

**Comment by jovaniedelacruz** [comment]
@daheadcracker have you reinstalled/updated your cyberpanel? They fixed this issue recently. They fixed it the same night I sent a bug report via cyberpanel which was fast.

**Comment by daheadcracker** [comment]
> 
> 
> @daheadcracker have you reinstalled/updated your cyberpanel? They fixed this issue recently. They fixed it the same night I sent a bug report via cyberpanel which was fast.

Reinstalling seems like using sledgehammer to crack a nut. But yes, I've updated to the latest version already before I tried all the above.

**Comment by daheadcracker** [comment]
Ok, now that I waited long enough for a release to fix this issue, I wrote my own script to execute the pull command. And one thing i noticed. When I setup git via the cyberpanel UI, the /.shh/config file gets always generated with github.com as Hostanme, no matter what you click in the assistant (gitlab). Appart from that, I find it pretty annoying that cyberpanel always deletes everything inside the "public_html" folder when reconfiguring the git integration. The UI should at least ask for that. So better put the cloned repo inside websites root folder and change the vhost config accordingly.

Preperation for my script included:
1. check php username on the server to set permissions: `<?php echo `whoami`; ?>`
2. For the sake of simplicity - set permission to the whole repo folder: `sudo chown -R above_user Repo_Folder` (Better: include the php user to a group which has write access for the repo folder)
3. get/generate(without passphrase) ssh keys as the above user: `ssh-keygen`
4. Gitlab: Settings - CI/CD - Deploy Keys use above public ssh key
5. change the ssh config to (IdentityFile should be the path to the above ssh private key):

```
Host custom_string.gitlab.com
    Hostname gitlab.com
    IdentityFile /home/path_to_website_root/.ssh/gitlab
	StrictHostKeyChecking no
```
	
6. Change git config url to `git@custom_string.gitlab.com:gitlab_user_name/repo.git`
7. Start the ssh agent: `eval `ssh-agent -s``
8. Add the private key to the agent: `ssh-add /.ssh/gitlab`
9. execute to check if the ssh login is works: `ssh -T git@custom_string.gitlab.com`
10. gitlab: Settings - Webhooks / Generate a webhook - paste URL to the php script (including password parameter as php script password) and gitlab.pub public key
11. test the push event and check if your repo is up to date with eg. `git log -1` to see the latest pulled commit

(to also have access via the root user account: repeat step 5 in the "/root/.ssh" folder)

**Comment by usmannasir** [comment]
I'm adding a dedicated git manager with more features on the v1.9.5 version. This feature will be removed then.

**Comment by daheadcracker** [comment]
Hi,
so I've updated cyberpanel to 2.0 Build 1E. Unfortunately I'm not able to see the "Manage Git" Button which is described ([here](https://cyberpanel.net/docs/how-to-use-git-manager-in-cyberpanel/)) on any website. I tried setting up git like it was described in earlier versions under "APPLICATION INSTALLER - Git" again and also created a new website. But no "Manage Git" Button appears. What could I be doing wrong?

**Comment by hennaboy** [comment]
Websites > list websites > manage website > scroll down to the bottom click on the GIT logo

**Comment by daheadcracker** [comment]
> Websites > list websites > manage website > scroll down to the bottom click on the GIT logo

Nope, this the wasn't the issue. I ran the update again [described here](https://cyberpanel.net/docs/upgrading-cyberpanel/) and now I'm on version 2.0 Build 1 (no E). I can see the Button and the correct git Manager now (only with minor ui bugs, like never ending and missplaced loading indicators). But it works.

**Comment by hennaboy** [comment]
Well your post was asking for where the manage git was located which is in the location as per my reply.

UI bugs. Nope don't see those either. Perhaps try clearing your cache.
