### ISSUE TITLE
[BUG] Update get stuck on ubuntu 20.04

### ISSUE THREAD

**Issue by Dreamer41** [litespeedtech/cyberpanel#968]
**Describe the bug**
Update get stuck on ubuntu 20.04

> [09.15.2022_07-44-49] #########################################################################
> 
> [09.15.2022_07-44-49] /root/.acme.sh/acme.sh --upgrade --auto-upgrade successful.
> 
> [09.15.2022_07-44-49] #########################################################################
> 
> [Thu 15 Sep 2022 07:44:49 AM UTC] Changed default CA to: https://acme-v02.api.letsencrypt.org/directory
> 
> 
> 
> [09.15.2022_07-44-49] #########################################################################
> 
> [09.15.2022_07-44-49] /root/.acme.sh/acme.sh --set-default-ca  --server  letsencrypt successful.
> 
> [09.15.2022_07-44-49] #########################################################################
> 
> 
> 
> 
> [09.15.2022_07-44-49] #########################################################################
> 
> [09.15.2022_07-44-49] sed -i '/CyberCP/d' /etc/crontab successful.
> 
> [09.15.2022_07-44-49] #########################################################################
> 
> sed: -e expression #1, char 89: unterminated `s' command
> sed: -e expression #1, char 89: unterminated `s' command
> sed: -e expression #1, char 89: unterminated `s' command
> sed: -e expression #1, char 89: unterminated `s' command
> sed: -e expression #1, char 89: unterminated `s' command
> sed: -e expression #1, char 89: unterminated `s' command
> 
> 
> 
> [09.15.2022_07-44-49] #########################################################################
> 
> [09.15.2022_07-44-49] find /usr/local/lsws/conf/vhosts/ -type f -name 'vhost.conf' -exec sed -i "s/.*CustomLog.*/    LogFormat '%h %l %u %t "%r" %>s %b "%{Referer}i" "%{User-Agent}i"' combined
> &/g" {} \; successful.
> 
> [09.15.2022_07-44-49] #########################################################################

**Operating system:**
Ubuntu 20.04

**CyberPanel version:**
Latest

**Comment by usmannasir** [comment]
Do you have imunify360 or imunifyav installed?

**Comment by Dreamer41** [comment]
I have imunifyav

**Comment by usmannasir** [comment]
run this `rm /etc/sysconfig/imunify360/integration.conf` and then do upgrade, something wrong with imunify upgrade which is called during CP installation.
