### ISSUE TITLE
[BUG] CYBER PANEL AUTHENTICATOR LOGIN PROBLEM

### ISSUE THREAD

**Issue by teboy** [litespeedtech/cyberpanel#969]
Hello sir,

I just created a new server on vultr with cyberpanel installed, after successful installation I tried access the login page at port 8090 but the login page in requesting for google authenticator code. I did not set up google authenticator at all so now I cant even login to my server at all.
Pease this is very urgent issue

Thanks and regards

**Comment by usmannasir** [comment]
Clear your browser cache and visit again, there is no such bug.
