### ISSUE TITLE
[BUG] SMTP certificate verify failing.

### ISSUE THREAD

**Issue by Dreamer41** [litespeedtech/cyberpanel#971]
I cant connect SMTP I get message below

certificate Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

I have  issued successfully new SSL for mailserver and mail domains, restart postfix.
I can send and receive thru snappy mail. Test with [mail-tester.com](http://mail-tester.com/) dont show any problems either.

Below log from mail.

Sep 22 09:47:38 sgserver1 postfix/submission/smtpd[772857]: connect from [mail.website.com](http://mail.website.com/)[66.22.88.99]
Sep 22 09:47:38 sgserver1 postfix/submission/smtpd[772857]: SSL_accept error from [mail.website.com](http://mail.website.com/)[66.22.88.99]: -1
Sep 22 09:47:38 sgserver1 postfix/submission/smtpd[772857]: warning: TLS library problem: error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:…/ssl/record/rec_layer_s3.c:1543:SSL alert number 45:
Sep 22 09:47:38 sgserver1 postfix/submission/smtpd[772857]: lost connection after STARTTLS from [mail.website.com](http://mail.website.com/)[66.22.88.99]
Sep 22 09:47:38 sgserver1 postfix/submission/smtpd[772857]: disconnect from [mail.website.com](http://mail.website.com/)[66.22.88.99] ehlo=1 starttls=0/1 commands=1/2

**Operating system:**
Ubuntu 20.04

**CyberPanel version:**
Latest

**Comment by usmannasir** [comment]
This is not a bug.

**Comment by Dreamer41** [comment]
Pretty sure there is some bug.. when mail renew SSL it won't update new
keys somewhere so SMTP SSL fails.

**Comment by usmannasir** [comment]
You can't connect to smtp from third party client?

**Comment by Dreamer41** [comment]
Third party client get SSL error. Can send and receive from snappymail fine.

**Comment by usmannasir** [comment]
https://platform.cyberpersons.com/

Send ticket here with server login details, I will have to check if it is actually a bug.

**Comment by Dreamer41** [comment]
Got this error again exactly 3 month later.. Have to every time buy email debugger to fix issue.
SSL gets issued fine but SMTP with any client fail. When analyze with debugger it show everything is ok, after apply force fix on debugger problem is gone.

Pretty sure somewhere postfix settings SSL stuff wont get updated.

**Comment by Dreamer41** [comment]
@usmannasir see this community [Post](https://community.cyberpanel.net/t/cannot-send-emails-as-via-gmail-ssl-certificate-mismatch/39446/6?u=dreamer) there is clearly bug for SSL update for mail domains acme.sh keys.
