### ISSUE TITLE
Git manager webhook address gives 500 error

### ISSUE THREAD

**Issue by ofyalcin** [litespeedtech/cyberpanel#979]
CyberPanel 2.3.1 on Ubuntu 20.04

I installed GIT with git manager. There is no problem when I do git pull manually. However, when I try to use the webhook, I get a 500 error. I followed all the official documentation but couldn't find a solution.

`https://<HOSTNAME>:8090/websites/<WEBSITE>/webhook` OR `https://<IP>:8090/websites/<WEBSITE>/webhook` 

![500](https://user-images.githubusercontent.com/21265333/196215677-048d7981-a14d-4e77-abd1-a67f4d4150bc.jpg)

**Comment by usmannasir** [comment]
You can not visit this page in web browser as it requires `POST` data.

It works fine with Git payload.

![git](https://user-images.githubusercontent.com/17538454/196872241-e2fab9c4-a82b-4e4b-8e22-93000da5a293.png)

**Comment by ofyalcin** [comment]
> 

This is not an answer or a solution. I know how this works, don't worry. Same thing happens with git webhook integration.

![git](https://user-images.githubusercontent.com/21265333/196873166-b560ae75-11d0-46d9-9f14-bdd2c0caf777.jpg)

**Comment by usmannasir** [comment]
Show me settings tab and don't hide any info as I need full picture.

**Comment by ofyalcin** [comment]
> 

![git1](https://user-images.githubusercontent.com/21265333/196936973-7d34a534-9877-4afc-97eb-5ba3f5660558.jpg)

**Comment by ofyalcin** [comment]
> Show me settings tab and don't hide any info as I need full picture.

I found where the problem is. The "Content type" option in the webhook settings needs to be selected as "application/json". Thanks Usman.

**Comment by usmannasir** [comment]
yes, good luck.
