### ISSUE TITLE
Containerization / Create Limits redirects to expired license page

### ISSUE THREAD

**Issue by lotkao** [litespeedtech/cyberpanel#98]
I have a fresh installed cyberpanel on CentOS 7.
Current Version 1.8
Build 4
I am using the free (non-Enterprise) version.

When I click on "Containerization" and then under it on "Create Limits" (/container/), I get redirected to https://cyberpanel.net/license-expired/. Is this a bug, or wanted?

**Comment by usmannasir** [comment]
That is Enterprise only feature.
