### ISSUE TITLE
File Manager Path Changing

### ISSUE THREAD

**Issue by ksaltik** [litespeedtech/cyberpanel#980]
I want to change the path of file manager path when it is clicked in website management screen.

Why I want this? Because I have customized folder structure for wordpress. And I don't want to reach the configuration files when they click file manager icon link in website manament page in panel.

Is there any way to change it even with code editing

**Comment by usmannasir** [comment]
In query string you can give the path like this `?path=/home/staging.cyberpanel.net/public_html/`

Now if you can edit basic html, you can edit the page and add the path in query string.
