### ISSUE TITLE
[BUG] Adding .sh domain doesn't resolve site

### ISSUE THREAD

**Issue by ryansechrest** [litespeedtech/cyberpanel#982]
**Describe the bug**
I recently registered a .sh domain and tried to add it as a domain alias to an existing website, but I kept seeing the default Ubuntu page. I then removed the domain alias and tried to add the .sh domain as a website, just to see if I would get the default CyberPanel landing page, but that also didn't work. Adding a domain with a different TLD, like .com, still works as expected.

**To Reproduce**
What steps did you take when the issue occurred? 
1. Add new site with a .sh domain

**Expected behavior**
I should see the site or the default CyberPanel landing page. 

**Operating system:**
Ubuntu 20.04 LTS

**CyberPanel version:**
2.3.2

**Additional context**
I added several .com domains as a domain alias to a site, and they all worked as expected, but whenever I add a .sh domain, it doesn't load the corresponding website-- it simply shows the Ubuntu landing page. I checked the web server configuration file and I see the .sh domain listed in the map directive, just like the other domain aliases. I also manually restarted the web server to ensure the configuration file as applied. Last, I know the DNS is pointing to the right server, because when I ping the .sh domain, I get the server's IP address.

**Comment by ryansechrest** [comment]
I visited my .sh domain again today and the CyberPanel landing page is now displaying. I'll leave this issue open just in case this is a problem that somehow self-corrected, but if you find that it isn't a CyberPanel issue, feel free to close.

**Comment by usmannasir** [comment]
I think that was only due to DNS propagation, I will close this issue now.

PS: DNS propagation can take more time in some cases, which is something beyond CyberPanel
