### ISSUE TITLE
[Feature]  Pure-FTPd Support 1.0.50

### ISSUE THREAD

**Issue by trevorrobinson** [litespeedtech/cyberpanel#987]
Pure-FTPd 1.0.50 has removed support for MD5 from version 1.0.50. See https://www.pureftpd.org/project/pure-ftpd/news/#version-1050-released

Cyberpanel will need to support crypt, argon2 or crypt(3) to work with the latest versions.

Confirmed to be broken on the latest cyberpanel release 2.3 (Commit 7427667c14c2ddbc2fcb7bfa35870155d4a343dc).

**Comment by igmarketing** [comment]
Can't believe this issue has been reported in October and still not fixed 5 months later.. FTP server is broken on probably thousands of servers and Cyberpanel team doesn't seem to care. Sad.

**Comment by cagivacode** [comment]
I just ran into this on Ubuntu 22.04. Pure-ftpd is on 1.0.51 for most of the big RH 9/ rocky 9 /alma 9 distributions.

You can run 1.0.49 from ubuntu 20.04 on 22.04 by manually installing the packages.

Using Scrypt in python seems trivial....but I don't know.

**Comment by SaJeTek-Developer** [comment]
Hi @usmannasir, can we have this looked into as CentOS 7 is at end of life and the default version in Almalinux 9 is pure-ftpd 1.0.51.
This breaks ftp totally in Cyberpanel

**Comment by usmannasir** [comment]
yes i am checking this now

**Comment by usmannasir** [comment]
fixed.
