### ISSUE TITLE
[BUG] Cat: /home/cyberpanel: No such file or directory

### ISSUE THREAD

**Issue by richardevcom** [litespeedtech/cyberpanel#988]
**Describe the bug**
I was trying to create e-mail list for website by uploading .txt and .csv file containing multiple e-mail addresses to my websites base directory. So the path I used was `/home/domain.com/public_html/emails-list.txt`.

However when visiting *"Create Email List"* page in **CyberPanel** dashboard via `https://domain.com:8443/emailMarketing/domain.com/emailLists` and providing this path I get this error:
```
cat: /home/cyberpanel: No such file or directory
```

I triple checked that file exists, has correct permissions and is writable. There are no error logs, so it is really hard to pin-point where exactly **CyberPanel** crashes regarding this task.

[Read more in this CyberPanel community topic I started.](https://community.cyberpanel.net/t/cat-home-cyberpanel-no-such-file-or-directory/37933?u=richardevcom)

**To Reproduce**
What steps did you take when the issue occurred? 
1. Click on Websites and select "Create domain" and create `domain.com`
2. Click on Websites and select "List domains". Find newly created domain and transform it to website.
3. Open up `domain.com` management page and select "Create list"
4. Enter name and path to email list file, for ex., `/home/domain.com/public_html/email-list.txt`
5. Hit Creat list and you'll see the error.

**Expected behavior**
Email list is created without an error.

**Screenshots**
![screenshot](https://community.cyberpanel.net/uploads/default/original/2X/4/40d9f8a291fad41e20f67d2c898b45bcaf451cae.jpeg)

**Operating system:**
Ubuntu 20.04 (latest - updated & upgraded)

**CyberPanel version:**
2.3 (latest)

**Additional context**
As mentioned [in this community topic](https://community.cyberpanel.net/t/cat-home-cyberpanel-no-such-file-or-directory/37933?u=richardevcom) I suspect that the issue is not within `/usr/local/CyberCP/emailMarketing/emailMarketing.py` buth rather in something, that tries to read/create `/home/cyberpanel/*` numbered files containing loglike content.

**Comment by usmannasir** [comment]
We've discontinued this feature because of mautic integration.

**Comment by richardevcom** [comment]
Appreciate the answer @usmannasir
Any other features you're discontinuing? I noticed this error on couple other places as well.

**Comment by Zorglub25** [comment]
Hello,
I encounter the same error.
I don't understand the last post of Usmannasir "because of mautic integration"...
Has someone fixed this problem ?
Many thanks.

**Comment by richardevcom** [comment]
> Hello, I encounter the same error. I don't understand the last post of Usmannasir "because of mautic integration"... Has someone fixed this problem ? Many thanks.

Feature is discontinued. https://github.com/usmannasir/cyberpanel/issues/988#issuecomment-1312458800
Upgrade to latest build.
