### ISSUE TITLE
Unable to Delete

### ISSUE THREAD

**Issue by mehdiakram** [litespeedtech/cyberpanel#989]
Unable to Delete files. After delete showing delete successfully but not deleted

**Screenshots**
![1](https://user-images.githubusercontent.com/56603254/199746922-4e4f0917-f3f0-462c-94f3-f30cd5e68aa1.png)
![2](https://user-images.githubusercontent.com/56603254/199746937-64c4b4fc-4ccc-4b34-ab1a-6e9948eae509.png)
![3](https://user-images.githubusercontent.com/56603254/199746941-4ad397bf-be87-4f51-8bb9-7bf31b674c54.png)

**Operating system:**
Cent OS 7

**CyberPanel version:**
2.3

**Comment by usmannasir** [comment]
Just click fix permissions and then delete again.

**Comment by mehdiakram** [comment]
Some times fix permissions not work
