### ISSUE TITLE
Can't modify "default" ACLs

### ISSUE THREAD

**Issue by lotkao** [litespeedtech/cyberpanel#99]
I have a fresh installed cyberpanel on CentOS 7.
Current Version 1.8
Build 4
I am using the free (non-Enterprise) version.

When I want to create a user, I have to choose an ACL, it offers me 3 options "admin", "reseller", and "user".

![Selection_0271](https://user-images.githubusercontent.com/12074418/59961001-55481400-94fb-11e9-9018-1006e22b85d9.jpg)

When I click on "Modify ACL" in the "users" section:

![Selection_0274](https://user-images.githubusercontent.com/12074418/59960995-44979e00-94fb-11e9-900d-af77888a65da.jpg)

I can't choose to modify any ACL:

![Selection_0272](https://user-images.githubusercontent.com/12074418/59960997-4bbeac00-94fb-11e9-8dca-4402e9d02b7b.jpg)

When I checked the database, I can found the 3 default ACLs:

![Selection_0278](https://user-images.githubusercontent.com/12074418/59961132-537f5000-94fd-11e9-8160-9c9be213e80e.jpg)

then I found this file: https://github.com/gitforwebwork/cyberpanel/blob/1.8.0/plogical/acl.py

and in it the coding that hides the 3 ACLs:

![Selection_0279](https://user-images.githubusercontent.com/12074418/59961560-a22fe880-9503-11e9-9aca-888cc9b5880b.jpg)

What is the reason for not allowing to view or edit these 3 ACLs?

If the settings have to stay the way they are, I think you should still make it possible for Admins to view the 3 default ACLs in order to know what access rights each ACL has been given, and then simply don't allow to modify them.

Also, I think that an Admin should at least be able to modify the "user" ACL. For example, a user has the permission to create a backup, but not the permission to restore a backup. In my case, I would want users to be able to to restore their own backups.

**Comment by usmannasir** [comment]
Right now if you delete default ACLs it may cripple the system, that is why it is not allowed to delete default ACLs. However, ACLs that you have created can be deleted.
