### ISSUE TITLE
[BUG] SnappyMail

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#990]
When SnappyMail now gets updates.
Default PHP is 7.4 and up. (It will refuse if it uses 7.3 or below).
CyberPanel still has 7.3 or something as standard.
It should either be bumped to 7.4 or 8.0 since 8.1 isn't that ready with CyberPanel yet.

**Comment by Dreamer41** [comment]
I have tried to ask too that default cyberpanel apps PHP should be updated something else than deprecated 7.3 for months.. 
There is manual solution change PHP to run `sh <(curl https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/phpmod.sh || wget -O - https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/phpmod.sh)` but that need to run everytime you update your cyberpanel.

**Comment by usmannasir** [comment]
I think you guys are on old installation, for me the default PHP for new installation is 

```
[root@ip-172-31-15-45 fcgi-bin]# ./lsphp -v
PHP 7.4.33 (litespeed) (built: Oct 31 2022 10:36:05)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.4, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies
    with Xdebug v2.9.0, Copyright (c) 2002-2019, by Derick Rethans
[root@ip-172-31-15-45 fcgi-bin]# 
```

You can also achieve this by using

```
cp /usr/local/lsws/lsphp74/bin/lsphp /usr/local/lscp/fcgi-bin/lsphp
systemctl restart lscpd
```
