### ISSUE TITLE
[BUG] Ubuntu 22.04.5 LTS install fail

### ISSUE THREAD

**Issue by milossh** [litespeedtech/cyberpanel#991]
Trying to install cyberpanel as per official documentation, on Ubuntu 22.04 LTS, fails with following error:

```
The following packages have unmet dependencies:
 libmariadbclient-dev : Depends: libmariadb-dev (= 1:10.3.34-0ubuntu0.20.04.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
above command failed...
```

I can only assume this is due to requirement being Ubuntu 22.04.1 package libmariadb-dev

**Comment by usmannasir** [comment]
Resolved

**Comment by milossh** [comment]
Can you please point to the original issue? I tried searching beforehand but with no luck
