### ISSUE TITLE
[FEATURE] downgrade from LiteSpeed ​​ENTERPRISE to OpenLiteSpeed ​​makes "all sites disappear".

### ISSUE THREAD

**Issue by willph** [litespeedtech/cyberpanel#993]
**Describe the bug**

if you take the 15 day trial it breaks the CyberPanel.

downgrade from LiteSpeed ​​ENTERPRISE to OpenLiteSpeed ​​makes "all sites disappear".

It's like stopping CyberPanel.

There is no possibility to downgrade to OpenLiteSpeed ​​through the CyberPanel dashboard.

**To Reproduce**
What steps did you take when the issue occurred? 
1. Click on the "Switch"  15 Day trial version liteSpeed.
2. Downgrade to OpenLiteSpeed via terminal
3. apt-cache policy openlitespeed
4. apt install openlitespeed
5. breaks CyberPanel, sites registered in it to work

**Screenshots**
![image](https://user-images.githubusercontent.com/17226802/201496170-4f12591a-b4c8-429c-9e48-186285fdc67a.png)

**Operating system:**
 Ubuntu 20.04 LTS

**CyberPanel version:**
Latest Version
![image](https://user-images.githubusercontent.com/17226802/201496344-51719b1d-e2fa-4632-8493-070c01ff2beb.png)

**Comment by qtwrk** [comment]
it shows a message that downgrade is impossible if you go to LSWS

**Comment by usmannasir** [comment]
CyberPanel does not have this feature yet, so can't consider this a bug.

Also message clearly says you can't reverse for now.

We will add this in future.

**Comment by willph** [comment]
thank you very much for the reply, @usmannasir @qtwrk 

I know you won't believe it, but worse than bad luck I clicked that button by accident with the mouse(touch) of the notebook.

**Comment by qtwrk** [comment]
well , as sad as it is ,  only viable option you have right now is to reinstall server and redeloy sites, or create a new server and migrate sites to new server

**Comment by willph** [comment]
> CyberPanel does not have this feature yet, so can't consider this a bug.
> 
> Also message clearly says you can't reverse for now.
> 
> We will add this in future.

sorry for putting it as a bug.
Should have put it as a "feature"
