### ISSUE TITLE
Package change not effect immediately

### ISSUE THREAD

**Issue by mehdiakram** [litespeedtech/cyberpanel#998]
After change package still show 100% used. 

![Screenshot_2022-11-19-12-44-49-735_com android chrome](https://user-images.githubusercontent.com/56603254/202838462-fad16118-7724-46ef-960f-3c52d9830d3e.jpg)

**Comment by mehdiakram** [comment]
Disk space showing 100%,
Unable to delete any file,
Site showing error 403 Forbidden.

**Comment by usmannasir** [comment]
I've resolved this issue.

**Comment by mehdiakram** [comment]
> I've resolved this issue.

How?

**Comment by usmannasir** [comment]
Please see two commits above, also just upgrade CyberPanel using official upgrade guide.

Then either modify package or change package for website and this should immediately resolve your issue.
